### ISSUE TITLE
Bug in generate

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#100]
When we are generating the config, we assume that the app name is the same as it was written on the disk https://github.com/cloudflare/wrangler/blob/8ebd03e8e864e1f68975ae82985695005639f55f/src/user/settings.rs#L57.

However an app with name `myApp` generates a directory called `my-app`, and our logic fails.

**Comment by ashleygwilliams** [comment]
cargo-generate thinks it's cute and updates your name to match rust conventions. that doesn't make sense here tho so i'll be sure to call cargo-generate --force which skips the renaming.
