### ISSUE TITLE
tests broken on master

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1012]
for real this time

see build logs for pr #1011 that just adds two newlines to the readme and should not cause new failures: https://dev.azure.com/ashleygwilliams/wrangler/_build/results?buildId=2859&view=logs&j=f6e08d29-a39e-537c-cc8e-5799972a34ac

two tests are timing out in our windows ci pipeline for some reason. have not been able to reproduce on our local windows machine.

**Comment by ispivey** [comment]
@EverlastingBugstopper I can't access the build log anymore. Was this the same as https://github.com/cloudflare/wrangler/runs/762295513?check_suite_focus=true , or something different?

If the same, I'll update to point to the latest instance, and attach some logs more permanently.

If not the same and this is lost to the ether, figure we can close it.

**Comment by EverlastingBugstopper** [comment]
Oh this is from back when we were using azure pipelines. I still need to make a new issue about the GitHub actions failures.
