### ISSUE TITLE
One file missing in Workers after Wrangler publish

### ISSUE THREAD

**Issue by johntunnel** [cloudflare/wrangler#1013]
#### Environment

* operating system: Windows 10
* output of `rustc -V`:
* output of `node -v`: 12.14.1
* output of `wrangler -V`: 1.6.0

#### Steps to reproduce
After "wrangler publish" the file style.min.css is not reachable and chrome displays error 500.

The file is located at:
./wp-includes/css/dist/blocklibrary/style.min.css
Same happens if the file is moved 1 directory lower to:
./wp-includes/css/dist/style.min.css
But if file (same file) is moved 2 directories lower (or even lower) it works OK:
./wp-includes/css/style.min.css
or
./wp-includes/style.min.css

Actual webpage with the problem: 
www.hotel-azul.net
http://www.hotel-azul.net/wp-includes/css/style.min.css   OK
http://www.hotel-azul.net/wp-includes/css/dist/blocklibrary/style.min.css  NOT OK

#### What did you expect to see?
The file should be available on cloudflare worker sites domain

#### What did you see instead?
error 500 on Chrome devtools and message: 
"could not find wp-includes/css/dist/blocklibrary/style.min.css in your content namespace"

**Comment by EverlastingBugstopper** [comment]
I believe this is related to #40 which should have a fix landing in the next release

**Comment by johntunnel** [comment]
It was .gitignore's fault, where "dist" was written by default.
