### ISSUE TITLE
compile error .. cargo install wrangler 

### ISSUE THREAD

**Issue by neuhausler** [cloudflare/wrangler#1015]
#### Environment

* operating system: OSX 10.14.6
* output of `rustc -V`: rustc 1.35.0-nightly
* output of `node -v`: v13.6.0
* output of `wrangler -V`: 

#### Steps to reproduce

_$ cargo install wrangler --force_

#### What did you expect to see?
successful build of wrangler

#### What did you see instead?
_Compiling binary-install v0.0.3-alpha
error[E0412]: cannot find type `NonZeroI8` in module `num`
    --> /Users/local/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.101/src/de/impls.rs:2416:5
     |
2416 |     NonZeroI8,
     |     ^^^^^^^^^ help: a struct with a similar name exists: `NonZeroU8`_

**Comment by ashleymichal** [comment]
hey @neuhausler , my first guess is that your rust version might be out of date; we develop and test Wrangler against the latest version, which is currently 1.4.0, and you've got 1.35.0-nightly  coming up as your version. I  suggest running `rustup update`  and trying again with the newer version.

**Comment by neuhausler** [comment]
yes .. was able to successfully compile it with newest stable rust version 1.40.0.

**Comment by ashleymichal** [comment]
@neuhausler glad to hear it!
