### ISSUE TITLE
Can't Deploy with workers_dev = false

### ISSUE THREAD

**Issue by wpmaps** [cloudflare/wrangler#1017]
### 🐛 Bug Report
I'm trying to deploy to my cloudflare workers but when workers_dev = false, it gives me this error.

command: wrangler publish

` Using namespace for Workers Site "__resources-workers_sites_assets"
 Success
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
 Built successfully, built project size is 11 KiB.
Error:  There was an error fetching your project's routes.
 Status Code: 403 Forbidden
 Msg: {"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
`

The API access token has all the rights, still get this error in deployment.

Here is my wrangler.toml file

`name = "resources"
type = "webpack"
account_id = "xxx"
zone_id = "xxx"
workers_dev = false
route = "mydomain.com/*"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.staging]
name = "worker-dev"
route = "dev.mydomain.com/*"

[env.production]
name = "worker"
route = "prod.mydomain.com/*"`

* operating system:
* output of `node -v`:10.16.3
* output of `wrangler -V`:1.6

When workers_dev = true, it deploy fine but URLs other than index.html shows this error:

`could not find login/index.html in your content namespace`

Thanks

**Comment by gabbifish** [comment]
Hi there! Sorry you're running into this problem. So, it looks like you're trying to deploy to `mydomain.com/*` (that is, you aren't passing an environment). It seems you may be having a permissions issue; what are you using to authenticate to Cloudflare? If you are using an API token, you must make sure you have the Workers routes API permission to access and upload routes.

Let me know if you'd like help walking through token issuance to make sure you can get these permissions :)

**Comment by EverlastingBugstopper** [comment]
I'd also double check to see if you have an environment variable that is overriding your `wrangler.toml`. `CF_ACCOUNT_ID`, `CF_ZONE_ID`, `CF_API_KEY`, `CF_API_TOKEN`, and `CF_EMAIL` will all override your various configuration settings. 

If you still can't figure out what's happening here, you can run `RUSTLOG=info wrangler publish`, paste the output here, and we will take a look.

**Comment by janzheng** [comment]
> I'd also double check to see if you have an environment variable that is overriding your `wrangler.toml`. `CF_ACCOUNT_ID`, `CF_ZONE_ID`, `CF_API_KEY`, `CF_API_TOKEN`, and `CF_EMAIL` will all override your various configuration settings.
> 
> If you still can't figure out what's happening here, you can run `RUSTLOG=info wrangler publish`, paste the output here, and we will take a look.

I'm just following the tutorial (https://developers.cloudflare.com/pages/tutorials/build-an-api-with-workers) and it doesn't specify how to change these values, so I'm running into this error at the "Publishing the API" stage, FYI.
