### ISSUE TITLE
Add autocompletions for Wrangler commands

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1025]
For instance, typing `wrangler p` and then pressing `tab` should give a list like

```
publish      -- 🆙  Publish your worker to the orange cloud
preview      -- 🔬  Preview your code temporarily on cloudflareworkers.com
```

This could be done by providing a script to include in `.bashrc` or `.zshrc`, but it would be awesome if we could distribute the autocompletion along with the tool itself. That might be something to upstream into clap-rs.

EDIT: Looks like `clap` [supports](https://docs.rs/clap/2.33.0/clap/struct.App.html#method.gen_completions) this

**Comment by jspspike** [comment]
I'll take a look at this issue

**Comment by jspspike** [comment]
I am having issues with creating `App` at build time and I think it would be best if this is held off until we upgrade to [clap_v3](https://docs.rs/clap-v3/3.0.0-beta.1/clap_v3/).
