### ISSUE TITLE
Can't Deploy with workers_dev = false

### ISSUE THREAD

**Issue by kaihendry** [cloudflare/wrangler#1033]
```
[hendry@t480s ~]$ wrangler -V
 wrangler 1.7.0
[hendry@t480s ~]$ node -v
v13.7.0
```

Just bought Cloudflare Workers Unlimited. I'm not sure if this is right forum for support for paying customers. I googled the error message and it appears to be very similar to https://github.com/cloudflare/wrangler/issues/1017
```

[hendry@t480s foobar]$ RUSTLOG=info wrangler publish
 The route in your wrangler.toml should have a trailing * to apply the Worker on every path, otherwise your site will not behave as expected.
route = foobar.webconverger.org*
 Using namespace for Workers Site "__foobar-workers_sites_assets"
 Success
⬇ Installing wranglerjs...
⬇ Installing wasm-pack...
 Built successfully, built project size is 11 KiB.
Error:  There was an error fetching your project's routes.
 Status Code: 403 Forbidden
 Msg: {"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
```

I suspect the token might not have permissions to setup the route on my zone, but I am not sure. I am not sure where to update the token permissions either. Is it safe to share the wrangler.toml with account id and zone id?

My goal is to deploy a static site upon https://foobar.webconverger.org using Workers.

**Comment by EverlastingBugstopper** [comment]
Hi @kaihendry - it is safe to share the `wrangler.toml`, just make sure not to share your api token. 

This looks like an API authentication error, meaning there is something wrong with your configuration. You'll need to double check that your account id and zone id are correct, in addition to having a valid `wrangler config` api token. I'd also double check that environment variables `CF_ACCOUNT_ID` and `CF_ZONE_ID` are not overriding what you have in your `wrangler.toml`

**Comment by kaihendry** [comment]
I think it's something with the token, but couldn't figure it out so I cancelled my subscription.

**Comment by EverlastingBugstopper** [comment]
Sorry to see you go - happy trails 😄
