### ISSUE TITLE
Publish to multiple environments using wrangler publish --env

### ISSUE THREAD

**Issue by llernestal** [cloudflare/wrangler#1036]
#### Overview and problem statement

The help text for `wrangler publish` states:

```
OPTIONS:
    -e, --env <env>    environments to publish to
```
But it doesn't seem possible to publish to multiple environments in one go. Wouldn't it be convenient to add support for that? So one could, for example, deploy a worker to multiple Zones/Routes.

If there already is this kind of support, I apologize, but I coludn't find it anywhere in the documentation :blush: 

#### Basic example

`wrangler publish --env env1 env2`

**Comment by EverlastingBugstopper** [comment]
Hey @llernestal - this seems like a really cool feature! This probably isn't something we can prioritize as a team but if you'd like to tackle this I'd be happy to review a PR.

https://github.com/clap-rs/clap has built-in support for parsing arguments like this, we would likely just need to change each function that takes an environment to instead take a list of environments and then loop over each top-level function, running it once for each environment.
