### ISSUE TITLE
Add `wrangler kv:namespace delete --yes` to skip prompt

### ISSUE THREAD

**Issue by x46085** [cloudflare/wrangler#1042]
### 💡 Feature request

Add `wrangler kv:namespace delete --yes` to skip prompt

#### Overview and problem statement

I would like to automate the create of my kv:namespace, including deleting them. I was able to use use jq & sed with `wrangler kv:namespace list` in order to find a previous namespace (this would be improved to save me the query parsing backflips if the API had a "GET" request query-able by the  namespace name, but for another ticket). But I am now stuck because I can't call `wrangler kv:namespace delete --namespace-id={id}` without avoiding the prompt for "yes/no". I intended to fork the repo and implement this tweak in the meantime.

#### Basic example

This is my current working script:
```
name=somename
binding=somebinding

namespace_id=$(wrangler kv:namespace list | jq ".[]  | select(.title == \"${name}-${binding}\") | .id" | sed -e 's/"//g')
if [ ! -z "$namespace_id" ]; then
    wrangler kv:namespace delete --namespace-id=${namespace_id}; 
fi
```

**Comment by ashleymichal** [comment]
hey! we actually support piping the command `yes` to any delete operations in wrangler, so your `if` statement would  look like the following:

```
yes | wrangler kv:namespace delete --namespace-id=${namespace_id};
```

**Comment by ashleymichal** [comment]
> this would be improved to save me the query parsing backflips if the API had a "GET" request query-able by the namespace name, but for another ticket

we can pass this on; i too would love this but the wrangler team does not own the kv api.

**Comment by x46085** [comment]
Oh hey that will work! Thanks very much for the quick reply!
