### ISSUE TITLE
"self.webpackChunk is not a function" when publishing to development env 

### ISSUE THREAD

**Issue by calderonth** [cloudflare/wrangler#1044]
### 🐛 Bug Report

I am trying to have `production` endpoint and a `development` endpoint for my Worker. It is using webpack and the worker is quite basic. I am just trying to use a different route to differentiate the two workers but when publishing the dev worker, I have the following error:

```
 wrangler publish --env development
 Using namespace for Workers Site "__worker-development-workers_sites_assets"
 Success
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
 Built successfully, built project size is 252 KiB.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught TypeError: self.webpackChunk is not a function\n  at line 1\n"
    }
  ],
  "messages": []
}
```

#### Environment

* operating system:
* output of `rustc -V`: rustc 1.41.0 (5e1a79984 2020-01-27)
* output of `wrangler -V`: wrangler 1.7.0

#### Steps to reproduce

Extract of wrangler.toml:
```
name = "jwt-gateway"
type = "webpack"
workers_dev = true

[env.development]
...
webpack_config = "webpack.config.test.js"
route = "worker-test.example.com/*"

[env.production]
...
webpack_config = "webpack.config.prod.js"
route = "worker.example.com/*"
```
#### What did you expect to see?
Publishing the 2 workers should work.
#### What did you see instead?
The development worker fails to be published.

**Comment by EverlastingBugstopper** [comment]
Hi @calderonth - my guess is that this is an issue with your webpack file. Would you mind providing us with the contents of `webpack.config.prod.js` and `webpack.config.test.js` (or better yet, a link to a repo so that we can reproduce this issue?)

**Comment by EverlastingBugstopper** [comment]
you should be able to `npm install -g @cloudflare/wrangler@beta` and read up on the new "Secret/Text Environment variables" feature in the release notes: https://github.com/cloudflare/wrangler/releases/tag/v1.8.0-rc.0

**Comment by xtuc** [comment]
Using dynamic import `import("k.js")` isn't support in wrangler or cloudflare worker
