### ISSUE TITLE
Use console::Emoji for emojis

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1051]
https://docs.rs/console/0.9.2/console/struct.Emoji.html

this allows us to be consistent with how we display emojis on terminals that don't support them/want them

**Comment by ashleymichal** [comment]
we do this: https://github.com/cloudflare/wrangler/blob/master/src/terminal/emoji.rs#L14 but maybe there's a few places where emoji are being abused?

**Comment by EverlastingBugstopper** [comment]
oohh i didn't even know! silly me - i just saw the api while browsing docs and was like - we should do that
