### ISSUE TITLE
add wrangler.toml for existing project

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/wrangler#106]
If I have an existing project and I want to deploy it using wrangler, there should be a command for generating _just_ a `wrangler.toml` file, instead of using generate for a whole new directory. 

note that i accidentally did this a hacky way by running `wrangler generate .`, which created a `wrangler.toml` locally and then bailed out:

```
cloudflare-workers-todos $ wrangler generate .
⬇️ Installing cargo-generate...
🐑 Generating a new js worker project with name '.'...
⚠️   Renaming project called `.` to ``...
🔧   Creating project called ``...
⛔   Target directory already exists, aborting!
```

maybe `wrangler init` or something similar should exist?

**Comment by ashleygwilliams** [comment]
this is a great idea and not too hard to implement!!
