### ISSUE TITLE
wrangler reports incorrect size

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#1076]
#### Environment

* operating system:
* output of `rustc -V`:
* output of `node -v`:
* output of `wrangler -V`:

#### Steps to reproduce

Worker will an inline source map report an incorrect size, see:
```
$ wrangler build
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
 Built successfully, built project size is 480 KiB.
$ du -sh worker/script.js
1.7M    worker/script.js
```

webpack config:
```
module.exports = {
//...
  devtool: "inline-sourcemap"
}
```

#### What did you expect to see?

Correct size and our warning

**Comment by tmikaeld** [comment]
Seeing the same thing, reported size is 231kb, actual size is 955kb.

**Comment by xtuc** [comment]
I just remembered that wrangler should report the size after compression, so that's expected.

**Comment by tmikaeld** [comment]
@xtuc So script size is based on Gzipped size?
