### ISSUE TITLE
[dev] Worker updates not seen in terminal until restarting dev

### ISSUE THREAD

**Issue by yet-another-dev** [cloudflare/wrangler#1082]
_Mentioned initially in https://github.com/cloudflare/wrangler/issues/1078#issuecomment-587695836._

@EverlastingBugstopper 

#### Environment

* operating system: MacOS (Catalina, 10.15.1)
* output of `rustc -V`: n/a
* output of `node -v`: v10.17.0
* output of `wrangler -V`: 1.8.0-rc.1

#### Steps to reproduce

With dev running, add a console log statement inside the worker. Save. The console log does not show up. Restart dev, the console log is there.

#### What did you expect to see?

The new console log should show up in the terminal without dev needing to be restarted.

#### What did you see instead?

The new console log does not show up in the terminal.

**Comment by EverlastingBugstopper** [comment]
@yet-another-dev - the reload itself can take a bit since it needs to re-build and upload the worker to the cloudflare api (`wrangler dev` is not offline). Does it work if you wait a bit until you see a `Built successfully` message?

**Comment by yet-another-dev** [comment]
> Does it work if you wait a bit until you see a `Built successfully` message?

No, I'm afraid not.

**Comment by cpauwels** [comment]
I'm having the same issue here, also with the console.logs.

**Comment by EverlastingBugstopper** [comment]
Ok - I'm able to reproduce with a Workers Site project, but not with a regular worker. Going to investigate this.

**Comment by EverlastingBugstopper** [comment]
It seems like this has to do with how `make_service_fn` works - I need to force it to update quicker than it is. Waiting on a response from some Rust experts 😄
