### ISSUE TITLE
switch from failure to anyhow

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1091]
it is better https://crates.io/crates/anyhow

**Comment by gabbifish** [comment]
How specifically is it better? I think we need an RFC for this :)

**Comment by EverlastingBugstopper** [comment]
here's an interesting state of error handling in rust blog post: https://blog.yoshuawuyts.com/error-handling-survey/

1. `anyhow` is based on `std::Error` and does not have a custom `Fail` trait 
1. `anyhow` has 0 dependencies
1. Should be able to remove the ugly `format_err` calls we're required to include with the `failure` crate

Overall - it seems to be a cleaner approach that better takes advantages of the standard library and takes what's worked in other error handling crates and creates a more streamlined API.

**Comment by caass** [comment]
Hello commenting to add failure has [been deprecated :)](https://github.com/rust-lang-nursery/failure/pull/347)
