### ISSUE TITLE
Question: dev kv support

### ISSUE THREAD

**Issue by donifer** [cloudflare/wrangler#1095]
#### Overview and problem statement

Now that `wrangler dev` is in beta, are there any plans to add local `kv` support? 

It would be pretty useful to spin up locally the "full ecosystem" and develop against it, ideally with offline support. Unless I'm missing something, right now it kinda feels like coding in the dark unless you deploy/preview with the real kv which is not ideal specially in a team.

**Comment by EverlastingBugstopper** [comment]
Hey @donifer - This is already (sort of) implemented.

`wrangler dev` is not offline (see #1093) and we are planning on creating a new preview KV namespace for you that you can use to test and it will not interfere with your production KV namespace (see #1032)
