### ISSUE TITLE
Clarity on the respective purposes of build and publish

### ISSUE THREAD

**Issue by JamesHenry** [cloudflare/wrangler#1102]
#### Overview and problem statement

I guess this would likely fall into a request for documentation updates...

I just went to set up a CI/CD pipeline for an experimental Cloudflare Worker I am working on and wrangler did not behave how I intuitively expected it to.

I set up a Build stage to my pipeline in which I ran `wrangler build`, then published the built artifact for consumption in my Deploy stage. Pretty standard stuff I think.

In my Deploy stage I set up `wrangler publish` and expected it to be responsible for taking the result of `wrangler build` (a nice lightweight artifact) and publishing it to my Cloudflare account.

Instead it seems like `publish` essentially needs the full repo source and npm installation all over again, which suggests it is not intended to be combined with `build` at all, which has left me confused as to the design/intended use-cases of the commands.

Would love to hear your thoughts on this setup and intuition, maybe I have just messed up my approach.

Thanks!

**Comment by victoriabernard92** [comment]
I agree with this report. It is unclear and frustrating to have to build every time on publish. JS developers often know what steps to get a project built and prefer to have control of that.  I think rather than documenting this we should consider solving the problem at the design of the CLI level. 

Possible solutions:
- `publish --skip-build`. Which would simply publish to CF but do no building. Radical, but if this flag gets popular consider sunsetting the old `publish` to skip builds by default
- In`wrangler.toml`, have `type='javascript'` not install wasm-pack or build anything it simply talks to CF's API

**Comment by JamesHenry** [comment]
@victoriabernard92 thanks for acknowledging - do you help run the project? Would you be willing to accept PRs to implement these proposed solutions?

**Comment by victoriabernard92** [comment]
@JamesHenry while we do accept PRs this proposal needs design from and buy in from our team. I am looking forward to hearing their suggestions and getting back to you.

**Comment by JamesHenry** [comment]
@victoriabernard92 Are there individuals we can ping to make this a little more concrete?

Again, I am happy to do all the work here, I just need the go ahead

**Comment by JamesHenry** [comment]
This should remain open please

**Comment by JamesHenry** [comment]
This should remain open please.

@ashleymichal - is there a way I can avoid this now being my job to keep this open? 😅 

This seems to have been acknowledged by the team as something that could be improved and will be addressed?

**Comment by ashleymichal** [comment]
it is indeed; it also needs some attention alongside the [other wrangler build issues](https://github.com/cloudflare/wrangler/milestone/35). i think a `wrangler publish --skip-build` flag could be a good approach to solving the immediate problem; I think it would also benefit from a top-level `build_dir` setting in wrangler.toml that defaults to the existing build_dir settings.

**Comment by xortive** [comment]
closing since this is addressed by #1677, which will be going out as part of an RC in the near future.
