### ISSUE TITLE
[dev] On change, cloudflared tunnel breaks

### ISSUE THREAD

**Issue by yet-another-dev** [cloudflare/wrangler#1107]
@EverlastingBugstopper

> If you would like to try something that hasn't been tested yet, you could try to put a worker in front of something you're running on localhost.
>
> Let's say you have a react app that you're developing locally and it's running on localhost:4000 and you want to also develop a worker at the same time (maybe play around with the new HTMLRewriter API a bit). Unfortunately, you cannot call $ wrangler dev --host localhost:4000 because Cloudflare's preview service needs the back end to be a public URL.
>
> What you can do instead is spin up a TryCloudflare endpoint and pass that url to the --host argument of wrangler dev and then develop them in tandem.
>
> This is a completely unpaved path that has not been tested at all so your mileage may vary. If you get it to work, we'd love to hear about it!

I've tested this out and it _kinda_ works. The first issue I've run into is getting changes to update. The steps of what I'm seeing: 
1. save a change (say, a simple change in my worker site's HTML)
2. refresh the page 
3. the change is not there...
4. if I restart `wrangler dev` the change is there
5. if i _do not_ restart `wrangler dev` but instead refresh my browser every few seconds I eventually see a 500 for the HTML page with an error code along the lines of `could not find index.cc2f4dbd9f20219bea74e17400a95478e40941f0f0a4c17e2ec83eac27a2e0e8.html in your content namespace`.
6. Wait maybe 2 minutes or so (seriously!), refreshing every few seconds, and the 500 is gone and the update is live (without having restarted `wrangler dev`).

So it seems like there's some type of conflict between the way `wrangler dev` is updating on changes and the way the tunnel is serving them.

**Comment by tomByrer** [comment]
> * save a change (say, a simple change in my worker site's HTML)
> * refresh the page
> * the change is not there...
> * if I restart `wrangler dev` the change is there

I came here to report this bug also.  Discovered during public beta, but since I am still learning Workers I thought it could had been my error.  Now I'm using wrangler v1.8.0 (Win10, VSCode Bash), I get the same non-updating error even when I [CTRL-Z, CTRL-S] to a previously known working version.
