### ISSUE TITLE
Published secrets have unexpected carriage return appended to value

### ISSUE THREAD

**Issue by Cherry** [cloudflare/wrangler#1109]
### 🐛 Bug Report

When publishing secrets using `wrangler secret put API_KEY` for example, secrets are appended with an unnecessary carriage return such as `\r` when accessed in a script.

#### Environment

* operating system: Windows 10
* output of `rustc -V`: n/a
* output of `node -v`: v12.16.1
* output of `wrangler -V`: 1.8.0

#### Steps to reproduce

`wrangler put secret API_KEY` - enter `TEST`

Worker script:
```js
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})
/**
 * Respond with hello worker text
 * @param {Request} request
 */
async function handleRequest(request) {
  return new Response(JSON.stringify(API_KEY), {
    headers: { 'content-type': 'text/plain' },
  })
}
```

#### What did you expect to see?
`TEST` was expected to be printed back.

#### What did you see instead?
`TEST\r` was printed back. This can cause problems when API keys are appended to URLs for example, because it results in an encoded `%0d` in the URL.

Can be seen at https://secrets-test.nodecraft.workers.dev/.

**Comment by gabbifish** [comment]
HI @Cherry! I'm really sorry you're running into this issue. This definitely looks like a bug. I'll investigate this today. My first hunch is that the interactive input form for `wrangler secret put` must accidentally append the `\r` character to the secret input.

**Comment by Cherry** [comment]
Thanks @gabbifish. The work-around I'm using right now is to just wrap the secret in `String(API_KEY).trimEnd()`. It's not pretty and obviously has limitations, but works for our immediate use-case.

Let me know if I can provide any more info to help the resolution here.

**Comment by gabbifish** [comment]
We think this may be a windows input quirk--I wasn't able to reproduce this extra `\r` behavior on my linux machine, nor was he able to reproduce it on his Mac OSX machine. This must be why we didn't catch this in our testing phase, and we're sorry about that. We're working on a fix right now.
