### ISSUE TITLE
Can't Install on Ubuntu with Cargo

### ISSUE THREAD

**Issue by justinh00k** [cloudflare/wrangler#1113]
#### Environment

* operating system:
* output of `rustc -V`: 1.39.0

#### Steps to reproduce

`cargo install wrangler --features vendored-openssl`

#### What did you expect to see?

Installation of Wrangler.

#### What did you see instead?

> Compiling chrome-devtools-rs v0.0.0-alpha.0
> error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
>   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/chrome-devtools-rs-0                              .0.0-alpha.0/src/domain/runtime/event/mod.rs:12:1
>    |
> 12 | #[non_exhaustive]
>    | ^^^^^^^^^^^^^^^^^
>    |
>    = note: for more information, see https://github.com/rust-lang/rust/issues/44                              109
> 
> error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
>   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/chrome-devtools-rs-0                              .0.0-alpha.0/src/domain/runtime/method/mod.rs:15:1
>    |
> 15 | #[non_exhaustive]
>    | ^^^^^^^^^^^^^^^^^
>    |
>    = note: for more information, see https://github.com/rust-lang/rust/issues/44                              109
> 
> error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
>   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/chrome-devtools-rs-0                              .0.0-alpha.0/src/domain/runtime/method/mod.rs:33:1
>    |
> 33 | #[non_exhaustive]
>    | ^^^^^^^^^^^^^^^^^
>    |
>    = note: for more information, see https://github.com/rust-lang/rust/issues/44                              109
> 
> error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
>   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/chrome-devtools-rs-0                              .0.0-alpha.0/src/domain/mod.rs:15:1
>    |
> 15 | #[non_exhaustive]
>    | ^^^^^^^^^^^^^^^^^
>    |
>    = note: for more information, see https://github.com/rust-lang/rust/issues/44                              109
> 
> error: aborting due to 4 previous errors
> 
> For more information about this error, try `rustc --explain E0658`.
> error: failed to compile `wrangler v1.8.0`, intermediate artifacts can be found                               at `/tmp/cargo-installZ5X1eK`
> 
> Caused by:
>   could not compile `chrome-devtools-rs`.

**Comment by EverlastingBugstopper** [comment]
Hey @justinh00k - `#[non_exhaustive]` was introduced in rust 1.40.0 - you will need to run `rustup update` in order for installation to work.
