### ISSUE TITLE
Timeout error when trying to install 1.8.1 via NPM

### ISSUE THREAD

**Issue by PierBover** [cloudflare/wrangler#1123]
When trying to install I get this error:

```
Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.8.1/x86_64-apple-darwin
Error fetching release Request failed with status code 522
(node:10945) UnhandledPromiseRejectionWarning: Error: Request failed with status code 522
```

**Comment by EverlastingBugstopper** [comment]
This is related to a current incident which we are addressing. You can follow along [here](https://www.cloudflarestatus.com/) and we will also update this issue when it is resolved.

**Comment by EverlastingBugstopper** [comment]
This has been resolved. Please re-open this issue if you see any more 522 errors.
