### ISSUE TITLE
Error installing wrangler v1.8.1 Mac OS

### ISSUE THREAD

**Issue by kalch** [cloudflare/wrangler#1124]
#### Environment

* operating system: Mac OS 10.13.6
* output of `rustc -V`: rustc 1.41.1
* output of `node -v`: v13.8.0
* output of `wrangler -V`: -bash: wrangler: command not found

#### Steps to reproduce

cargo install wrangler

#### What did you expect to see?

wrangler has been installed

#### What did you see instead?

error[E0433]: failed to resolve: could not find `__rt` in `quote`
   --> /Users/mfk/.cargo/registry/src/github.com-1ecc6299db9ec823/failure_derive-0.1.6/src/lib.rs:107:70
    |
107 | fn display_body(s: &synstructure::Structure) -> Result<Option<quote::__rt::TokenStream>, Error> {
    |                                                                      ^^^^ could not find `__rt` in `quote`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `failure_derive`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wrangler v1.8.1`, intermediate artifacts can be found at `/var/folders/yq/6ylm9wk93p784v53q8w4pgph0000gn/T/cargo-installk5qILZ`

Caused by:
  build failed

**Comment by nbari** [comment]
Same here with maOS `10.15.3`

**Comment by bradyjoslin** [comment]
Notice a discussion going on [in the Rust user forum](https://users.rust-lang.org/t/failure-derive-compilation-error/39062) mentioning this error related to other projects.  Seems a number of crates are affected due to some dependency collisions.

**Comment by EverlastingBugstopper** [comment]
Is this still happening? I can't reproduce on my Mac

**Comment by EverlastingBugstopper** [comment]
Ah - looks like it's fixed: https://github.com/rust-lang-nursery/failure/issues/342#issuecomment-595317113
