### ISSUE TITLE
Wrangler publish error: You must set workers_dev = true

### ISSUE THREAD

**Issue by atismeiers** [cloudflare/wrangler#1133]
#### Environment

* operating system: Windows 10 Pro
* output of `rustc -V`: rustc 1.41.1 (f3e1a954d 2020-02-24)
* output of `node -v`: v12.16.1
* output of `wrangler -V`: wrangler 1.8.1

#### Steps to reproduce

https://github.com/atismeiers/cloudflare-wrangler/blob/master/description%20of%20issue

#### What did you expect to see?
wrangler publish
 JavaScript project found. Skipping unnecessary build!
 Deployed to the following routes:
my-worker.com/* => created

#### What did you see instead?
wrangler publish
Error: you must set workers_dev = true OR provide a zone_id and route/routes.

**Comment by EverlastingBugstopper** [comment]
The `workers_dev` field definition tells Wrangler that you would like to deploy to your workers.dev subdomain, and the `route` field definition tells Wrangler that you would like to deploy to a route. It doesn't know which one you want, so you have to remove one, hence the error message:

`you must set workers_dev = true OR provide a zone_id and route/routes`

If you remove the `workers_dev` field completely it should behave as expected.
