### ISSUE TITLE
npm package doesn't have a binary

### ISSUE THREAD

**Issue by steveklabnik** [cloudflare/wrangler#1139]
### 💡 Feature request

It would be nice if the npm package registered a binary, rather than relying on a post-install hook to do the right thing.

#### Overview and problem statement

https://github.com/volta-cli/volta is an `nvm`-like tool. 

```console
> npm i -g wrangler
Volta error: Global package installs are not supported.

Use `volta install wrangler` to add a package to your toolchain (see `volta help install` for more info).
```

This makes sense, and I think is good overall. But:

```
> volta install wrangler
error: Package has no executables to install.

Please verify the requested package name.
```

I don't think this tool is *super* popular, but given that wrangler distributes a binary, indicating that in the `package.json` seems like the right thing to do.

**Comment by EverlastingBugstopper** [comment]
```console
$ volta install @cloudflare/wrangler
success: installed @cloudflare/wrangler@1.8.1 with executables: wrangler
```

This seems to work

**Comment by steveklabnik** [comment]
![image](https://user-images.githubusercontent.com/27786/76569484-3a4e7300-6481-11ea-90dd-88536948d584.png)

**Comment by EverlastingBugstopper** [comment]
<3
