### ISSUE TITLE
Periods should not be allowed in environment variable names

### ISSUE THREAD

**Issue by GregBrimble** [cloudflare/wrangler#1142]
#### Environment

* operating system: MacOS 10.15.3
* output of `rustc -V`: `rustc 1.39.0`
* output of `node -v`: `v13.7.0`
* output of `wrangler -V`: `👷 ✨  wrangler 1.8.1`

#### Steps to reproduce

1. Create an environment variable with a period in the name e.g. `MYSECRET.NAME`:

    1. `wrangler secret put MYSECRET.NAME`, or
    1.  Or using the dashboard:
        ![image](https://user-images.githubusercontent.com/8484333/76682073-be733880-65f0-11ea-9cf4-396f058e25cb.png)

1. The variable is now inaccessible in a worker:

    ```js
    console.log(MYSECRET.NAME)
    ```

    > `worker.js:X Uncaught (in promise) ReferenceError: MYSECRET is not defined`

#### What did you expect to see?

1. An error should be thrown when trying to set an environment variable with a period in the name, in both wrangler, and in the dashboard UI.

**Comment by EverlastingBugstopper** [comment]
Hey @GregBrimble I've filed an issue internally to disallow these on the API side of things.
