### ISSUE TITLE
Cache the asset manifest

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1151]
Building the asset manifest takes _forever_. We should use some sort of database (sqlite?) or some formatted representation of the asset manifest so that we can do some sort of "incremental compilation" kind of like the rust compiler does. This is probably a decent undertaking and I have no idea how it would work but it would be cool!

**Comment by ashleymichal** [comment]
i would love to cache the asset  manifest PER INVOCATION; however, i'm not sure how to effectively cache or optimize BETWEEN INVOCATIONS without doing some kind of version control integration (which would be cool but like... a huge thing that would potentially touch everything).

**Comment by EverlastingBugstopper** [comment]
my thinking is that it would be in a .gitignored file so it would only be in the devs machine, kinda like target is for rust

**Comment by EverlastingBugstopper** [comment]
ehhhh - closing this as wont do since we merged #1221 and hashing is much faster now
