### ISSUE TITLE
`Error: you must set workers_dev = true OR provide a zone_id and route/routes.` is confusingly worded

### ISSUE THREAD

**Issue by ndarilek** [cloudflare/wrangler#1152]
This error message is confusing, as it seems to imply that these options aren't mutually exclusive. I'd suggest the following:

"Error: you can either set workers_dev = true, OR provide a zone_id and route/routes."

Maybe that wording can be improved further, but that at least implies mutual exclusivity. :)

**Comment by EverlastingBugstopper** [comment]
Hi @ndarilek - I agree that it can be a little confusing to have these mutually exclusive options in your configuration, I'll add the word either to the error message! Thanks :)
