### ISSUE TITLE
give better error message when environment variable config is invalid

### ISSUE THREAD

**Issue by Ichabond** [cloudflare/wrangler#1155]
#### Environment

* operating system: Macos X Catalina 10.15.3
* output of `rustc -V`: `rustc 1.41.0`
* output of `node -v`: `v13.11.0`
* output of `wrangler -V`: `👷 ✨  wrangler 1.8.2`

#### Steps to reproduce

Have the `CF_API_EMAIL` or `CF_API_KEY` environment variables set
`wrangler whoami` fails with:
```
Error: ⚠️  Your authentication details are improperly configured.
Please run `wrangler config` or visit
https://developers.cloudflare.com/workers/tooling/wrangler/configuration/#using-environment-variables
for info on configuring with environment variables
```
Even though `wrangler config` was executed, and a token is set.

#### What did you expect to see?
```
👋  You are logged in with an API Token.

Your token is missing the 'Account Settings: Read' permission.

Please generate and auth with a new token that has these perms to be able to list your accounts.

+--------------+------------+
| Account Name | Account ID |
+--------------+------------+
```
#### What did you see instead?
```
Error: ⚠️  Your authentication details are improperly configured.
Please run `wrangler config` or visit
https://developers.cloudflare.com/workers/tooling/wrangler/configuration/#using-environment-variables
for info on configuring with environment variables
```

#### Summary
Having the `CF_API_EMAIL` or `CF_API_KEY` environment variables set breaks the wrangler authentication flow apparently. Unsetting both fixed it.

**Comment by ashleymichal** [comment]
subtle difference but note in the docs: change `CF_API_EMAIL` to `CF_EMAIL` and try again?

**Comment by Ichabond** [comment]
Hey @ashleygwilliams I had those ENV vars set for another project. It could be useful to give this information as feedback in the error message, as right now the user is left wondering what exactly is wrong.

**Comment by jeremyschlatter** [comment]
I just encountered this as well, and only figured out what was wrong because of this GitHub issue.

In my case, I had CF_API_KEY and CF_API_EMAIL set from another project that I had forgotten about. I logged in with `wrangler login`, and everything seemed fine until I got this message on `wrangler publish`.

The problem was resolved when I cleared those env vars. It would have been helpful for me if the error message had told me that I was trying to authenticate with both the wrangler config file and with the env vars.

**Comment by jaap** [comment]
Had the same behaviour here. Probably used Cloudflare's CLI at some point and forget about the env settings I did.
A fast way to debug was to run `printenv | grep CF_API`

![CleanShot 2021-11-03 at 11 31 34](https://user-images.githubusercontent.com/724492/140045456-bf024bcd-f81f-4578-aab8-3e5eff8ce029.png)

**Comment by dsundquist** [comment]
Had the same problem, this is a direct conflict with flarectl.  If you've recently used flarectl you'll probably run into this.
