### ISSUE TITLE
Custom KV namespace bindings not created when publishing a Workers Site

### ISSUE THREAD

**Issue by rfreebern** [cloudflare/wrangler#1156]
### 🐛 Bug Report

I have a Workers Site with an additional custom KV namespace binding in its `wrangler.toml`:

```
name = "site-with-custom-kv-binding"
type = "webpack"
account_id = "<my account id>"
workers_dev = true

kv_namespaces = [
  { binding = "KV", id = "<id of a KV namespace I created>" }
]

[site]
bucket = "frontend/"
entry-point = "./"
```

After I `wrangler publish`, the site content is deployed properly and loads as expected. However, if I use e.g. `KV.get('foo');` in the worker script, it fails with the message `KV is not defined`. Additionally, the binding doesn't appear to have been created:

```
curl -s -XGET "https://api.cloudflare.com/client/v4/accounts/<my account id>/workers/scripts/site-with-custom-kv-binding/bindings" -H "Authorization: Bearer "$CF_API_TOKEN -H "Content-Type: application/json" | jq .
{
  "result": [
    {
      "name": "__STATIC_CONTENT",
      "namespace_id": "...",
      "type": "kv_namespace"
    },
    {
      "name": "__STATIC_CONTENT_MANIFEST",
      "type": "text_blob"
    }
  ],
  "success": true,
  "errors": [],
  "messages": []
}
```

#### Environment

* operating system:
* output of `rustc -V`: rustc 1.39.0
* output of `node -v`: v10.19.0
* output of `wrangler -V`: wrangler 1.8.2

#### Steps to reproduce

See above.

#### What did you expect to see?

The `KV` binding created and accessible to my worker.

#### What did you see instead?

No binding.

**Comment by rfreebern** [comment]
On further testing, the binding isn't created for a non-Sites worker either. Am I misunderstanding how KV namespace bindings are supposed to be established? [The docs](https://developers.cloudflare.com/workers/tooling/wrangler/kv_commands/) imply it will be created automatically, but I can't see where in the code that would theoretically happen.

**Comment by EverlastingBugstopper** [comment]
Hey @rfreebern, I _believe_ this should work if you change `kv_namespaces` to `kv-namespaces` but I'm not entirely sure. Let me know if that works!

**Comment by rfreebern** [comment]
Thank you! You're :100: correct. I was confused because the other entries in `wrangler.toml` use underscores. Also now I see what [this](https://github.com/cloudflare/wrangler/blob/master/src/settings/toml/manifest.rs#L41) is for. Thanks for the help!

**Comment by aamnah** [comment]
> Hey @rfreebern, I _believe_ this should work if you change `kv_namespaces` to `kv-namespaces` but I'm not entirely sure. Let me know if that works!

This was tripping up my code as well with the error 

```
Error: unknown field `kv_namespaces`, there are no fields
```

I had it with an `_` because [that's how the docs have it](https://developers.cloudflare.com/workers/cli-wrangler/commands#kv) and i copy/pasted from there, and that's how the `wrangler kv:namespace create "FOO"` command adds it

```                                                                        
🌀  Creating namespace with title "awesome-api-FOO"
✨  Success!
Add the following to your configuration file:
kv_namespaces = [
         { binding = "FOO", id = "b6e12fb0b8d49888e5fb0b8d4985a0" }
]
---
```
