### ISSUE TITLE
Webpack: build in-memory

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#116]
Will relying on an in-memory [filesystem for for webpack ](https://webpack.js.org/api/node/#custom-file-systems) allow us not having a `dist_to_clean`?

_Originally posted by @nickbalestra in https://github.com/cloudflare/wrangler/diffs_

**Comment by ashleygwilliams** [comment]
can you elaborate on what `dist_to_clean` is and what the implications of not having one are?

**Comment by xtuc** [comment]
The `dist_to_clean` (`./dist`) folder contains the assets Webpack build, we concatenate them and send the bundle to `wrangler`. This manipulation doesn't require actual files on disk.

**Comment by ashleygwilliams** [comment]
cool. i'm trying to figure out what the concern is?

**Comment by xtuc** [comment]
Just an improvement, no particular concern I think.

**Comment by nickbalestra** [comment]
Yes, as Sven said, no particular concerns here, mainly a question around wrangler architecture . 
As we are using `webpack as backend` I think we might want to consider handling all side effects likes writing to disk, logging to the console, etc in wrangler and not elsewhere (i.e. `webpack`, or `wrangler-js`). 
`dist_to_clean` [is where currently](https://github.com/cloudflare/wrangler/blob/dc7473811c6be3f96501a42c76fceaceec0297fd/wrangler-js/index.js#L67) Webpack write to disk. This currently require some[ cleanup logic](https://github.com/cloudflare/wrangler/blob/456e9acb140941ca2f5ee5abbb0567bda57ba263/src/wranglerjs/mod.rs#L59) in wrangler. As webpack support swapping the output file system for the compiler, relying on an in-memory file system could improve/simplify this

**Comment by xtuc** [comment]
This is required by webpack 5, emitted assets logic was changed.

**Comment by EverlastingBugstopper** [comment]
dist_to_clean has been gone forever aaannnnddd i think this issue is better tracked by #640.
