### ISSUE TITLE
Setup documentation for API usage is confusing

### ISSUE THREAD

**Issue by gaahrdner** [cloudflare/wrangler#1167]
Quick start says to "paste in your API key":

<img width="765" alt="Screen Shot 2020-03-26 at 5 51 03 PM" src="https://user-images.githubusercontent.com/739932/77704220-98ec1480-6f8a-11ea-88d9-e7a0c3887b7f.png">

However running `wrangler config` asks for an API Token, which is at odds with the large documentation block saying `(Not Recommended)`:

<img width="879" alt="Screen Shot 2020-03-26 at 5 50 40 PM" src="https://user-images.githubusercontent.com/739932/77704328-d18bee00-6f8a-11ea-927a-74b274559fd5.png">

**Comment by EverlastingBugstopper** [comment]
Hey this is a formatting issue we fixed in #1164 and released today with Wrangler 1.8.3. Thanks for the report!
