### ISSUE TITLE
wrangler fails to generate project after first setup

### ISSUE THREAD

**Issue by gaahrdner** [cloudflare/wrangler#1168]
### 🐛 Bug Report

Followed the quickstart [here](https://developers.cloudflare.com/workers/quickstart#configure).

#### Environment

* operating system: Mac OS X 10.15.3 19D76
* output of `rustc -V`: rustc 1.41.1
* output of `node -v`: v13.11.0
* output of `wrangler -V`: 👷 ✨  wrangler 1.8.2

#### Steps to reproduce

```
❯ wrangler generate my-worker
⬇️ Installing cargo-generate...
🔧   Creating project called `my-worker`...
Error: ⛔   Git Error: failed to clone into: /Users/gaahrdner/Code/my-worker38LGcL
Error: tried running command:
/Users/gaahrdner/Library/Caches/.wrangler/cargo-generate-ab5c5dc97dff785b/cargo-generate generate --git https://github.com/cloudflare/worker-template --name my-worker --force
exited with exit code: 1
```

#### What did you expect to see?

Successful "Done! New project created" message.

#### What did you see instead?

An error message.

**Comment by gaahrdner** [comment]
I should note I can clone the repo just fine outside of wrangler:

```
❯ git clone https://github.com/cloudflare/worker-template my-worker
Cloning into 'my-worker'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 109 (delta 11), reused 19 (delta 8), pack-reused 80
Receiving objects: 100% (109/109), 30.99 KiB | 10.33 MiB/s, done.
Resolving deltas: 100% (41/41), done.
```

**Comment by ashleymichal** [comment]
is the repo in question private? if so, do you mind trying again with a public repo? at the moment i don't believe wrangler uses the local gitconfig; if the public repo works, then that is likely the issue and i'll rename this ticket.

**Comment by EverlastingBugstopper** [comment]
Hey @gaahrdner, this is a known issue in [cargo-generate](https://github.com/ashleygwilliams/cargo-generate/issues/168) but I think there's a reasonable [workaround](https://github.com/ashleygwilliams/cargo-generate/issues/168#issuecomment-537093190). Hope this helps 😄

**Comment by gaahrdner** [comment]
It does seem to be an upstream issue, thanks @EverlastingBugstopper !

**Comment by ashleymichal** [comment]
closing as upstream issue in cargo generate.
