### ISSUE TITLE
wrangler publish returns exit code 0 despite route deployments failing

### ISSUE THREAD

**Issue by nchlswhttkr** [cloudflare/wrangler#1172]
### 🐛 Bug Report

If you run `wrangler publish` and the script/assets are successfully uploaded but it fails to deploy the worker to the specified routes, the command does not exit with nonzero status.

#### Environment

* operating system:
  `macOS 10.14.6`
* output of `rustc -V`:
  `1.41.0 (5e1a79984 2020-01-27)`
* output of `node -v`:
  `12.16.1`
* output of `wrangler -V`:
  `1.8.2`

#### Steps to reproduce

Deploy a worker with a `route` that does not match its `zone_id`.

```sh
wrangler generate my-app https://github.com/cloudflare/worker-template && cd my-app

# Update wrangler.toml
# workers_dev = false
# route = "https://nicholas.cloud/hello-worker"

CF_ACCOUNT_ID="X" CF_API_TOKEN="X" CF_ZONE_ID="<matching-zone-id>" wrangler publish
# 💁  JavaScript project found. Skipping unnecessary build!
# ✨  Deployed to the following routes:
# https://nicholas.cloud/hello-worker => created
echo $?
# 0

CF_ACCOUNT_ID="X" CF_API_TOKEN="X" CF_ZONE_ID="<bad-zone-id>" wrangler publish
# 💁  JavaScript project found. Skipping unnecessary build!
# ✨  Deployed to the following routes:
# https://nicholas.cloud/hello-worker => creation failed: ⚠️  Code 10022: Route pattern must include zone name: https://nicholas.cloud/hello-worker
# 🕵️

echo $?
# 0
```

#### What did you expect to see?

`wrangler publish` should exit with a nonzero status code, since route creation failed.

#### What did you see instead?

`wrangler publish` exited with a status of `0`.

**Comment by nchlswhttkr** [comment]
I've taken [a stab at fixing this](https://github.com/nchlswhttkr/wrangler/commit/e463d479ca98e42035926a5ee267afc2879d5a75), happy to PR if need be. I haven't written Rust before, so there might be a more convenient way to write this.

It seems that the code to handle the results of multiple route deployments doesn't immediately bail, so that it can print these results/error messages. I added a check after this to see whether any deployment failed, and bailed from there.

```sh
CF_ACCOUNT_ID="X" CF_API_TOKEN="X" CF_ZONE_ID="<matching-zone-id>" ~/Documents/wrangler/target/debug/wrangler publish
# 💁  JavaScript project found. Skipping unnecessary build!
# ✨  Deployed to the following routes:
# https://nicholas.cloud/hello-worker => stayed the same

echo $?
# 0

CF_ACCOUNT_ID="X" CF_API_TOKEN="X" CF_ZONE_ID="<bad-zone-id>" ~/Documents/wrangler/target/debug/wrangler publish
# 💁  JavaScript project found. Skipping unnecessary build!
# ✨  Deployed to the following routes:
# https://nicholas.cloud/hello-worker => creation failed: ⚠️  Code 10022: Route pattern must include zone name: https://nicholas.cloud/hello-worker
# 🕵️
# Error: Something went wrong while publishing routes

echo $?
# 1
```

**Comment by BlueyNeilo** [comment]
Have you tried turning it off and on again?
