### ISSUE TITLE
Encounter error msg when execute "wrangler preview --watch"

### ISSUE THREAD

**Issue by zhangdongasia** [cloudflare/wrangler#1173]
#### Steps to reproduce
1.
I used the following command to "successfully" install wrangler on aws EC2 with standard linux 2 AMI
# npm install -g  @cloudflare/wrangler --unsafe-perm=true --allow-root

2. 
create project with default wrangler template, say "hello wrangler", and complete wrangler.toml editting, and leave index.js file as default.
# wrangler generate project-name

here, both the account_id and zone_id are correct and confirmed.
# cat wrangler.toml
name = "my-worker"
type = "webpack"
account_id = "9ffa348……"
workers_dev = true
[env.production]
# The ID of your domain you're deploying to
zone_id = "600a410……"
# The route pattern your Workers application will be served at
route = "mydomainname.com/*"

but when perform preview, facing the error:
# wrangler preview --watch
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
/root/.cache/.wrangler/wranglerjs-049……/index.js:22
(async function() {
       ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
Error: failed to execute `"/bin/node" "/root/.cache/.wrangler/wranglerjs-04929fc326d5fa5a" "--output-file=/tmp/.wranglerjs_outputmLkWr" "--wasm-binding=wasm" "--no-webpack-config=1" "--use-entry=/root/steve-worker/index.js"`: exited with exit code: 1

#### What did you expect to see?
Is the wrangler installed incorrectly, or other setting wrong, I searched all issues and google, but no clear solution. please provide any ideas.

**Comment by zhangdongasia** [comment]
A problem with the editing and font sizes. Hope that would not impact reading..

**Comment by ashleymichal** [comment]
@zhangdongasia which version of node are you running? wranglerjs assumes LTS.

**Comment by EverlastingBugstopper** [comment]
@zhangdongasia - This is a JavaScript error, not a Rust error. This makes me think that this is an issue with the Workers script you are attempting to preview. Could you try running `wrangler build` and see if the same issue occurs?

**Comment by zhangdongasia** [comment]
reply laer, issue had been resolved, it's because node version not meet wrangler, install latest version will work.
