### ISSUE TITLE
wrangler publish does not pick changes to main.css file

### ISSUE THREAD

**Issue by danbars** [cloudflare/wrangler#1187]
#### Environment

* operating system: Mac 10.14.6
* output of `rustc -V`: `command not found`
* output of `node -v`: `v11.10.1`
* output of `wrangler -V`: `wrangler 1.8.1`

#### Steps to reproduce
My folder structure is:
```
mysite
  public
    assets
      css
        main.css
        some-other.css
      js
        main.js
        jquery.js
        some-more.js
      more-folders
    index.html
    more-files-and-folders-here
```
When I make changes to main.css wrangler does not pick the changes and the file remains with it's old version on the server after running `wrangler publish`.
I'm not changing all files here, so this might be happening with other files but I haven't noticed it
The publish finish successfully without any error messages.

#### What did you expect to see?
main.css being updated in live site too

#### What did you see instead?
All changed files are updated, except for main.css

#### Workaround
I've found the following workaround -
If I run `wrangler dev` and only after that `wrangler publish` - the updated main.css is uploaded to the server.

Might be related - my folder is not yet tracked in git (local or remote). I remember seeing somewhere else that wrangler looks into .gitignore so I thought that there might be some connection to that fact

**Comment by danbars** [comment]
Adding some more data - under `/public` I also have `images` folder with a file named `charttt_screenshot.png` which is also ignored by wrangler.
Other images like logo.svg from the same folder are uploaded correctly.

Is there some log file that I can check to see what was done by wrangler?

Right now I'm pretty stuck because the workaround I mentioned before does not work for this case.

**Comment by EverlastingBugstopper** [comment]
Hey @danbars - thanks for the report. It would be helpful to know if you can reproduce this on a `workers.dev` subdomain (set `worker_dev = true` in your `wrangler.toml`).

It would also be helpful if you could point me towards a repository where I could mess around with this myself and try to reproduce - it's hard to pin down the issue w/o knowing more details about how everything is set up.

One thing you might try is updating Wrangler to the latest version and watching the output when you run `wrangler publish` and see if it's including the main.css file you expect it to - there should be a little spinner that tells you what file it's preparing to upload.

**Comment by danbars** [comment]
Hi @EverlastingBugstopper I will try to make a small reproduceable repo.
