### ISSUE TITLE
Built file size is confusing

### ISSUE THREAD

**Issue by mpint** [cloudflare/wrangler#1188]
#### Overview and problem statement

The built file size language is a little confusing. 

```
 Uploading...
 Uploading...
 Success
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
 Built successfully, built project size is 11 KiB.
```

"Built project size" can be interpreted as the size of your built `bundle.js` in webpack terms, which can be confusing when the user notices that `bundle.js` is significantly larger than than the reported built project size.

The reported value appears to be the gzipped project size.  Adding this would clarify the difference:
```
 Built successfully, compressed project size is 11 KiB.
```

**Comment by EverlastingBugstopper** [comment]
for anyone stumbling across this issue, the built size is computed after gzip compression

**Comment by EverlastingBugstopper** [comment]
related issue #1227

**Comment by jorgelbg** [comment]
Has something changed on how the worker size is calculated in wrangler 1.9? I have a worker that with wrangler 1.8.4 builds into a file of ~635KiB. But when built with wrangler 1.9 I get the warning of the over 1Mb file and of course cannot be published:

```
❯❯❯ wrangler --version                                                                           16:12:54
👷 ✨  wrangler 1.8.4

~/C/worker master*
❯❯❯ wrangler build                                                                               16:12:58
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
Warning: webpack's output filename is being renamed to worker.js because of requirements from the Workers runtime
✨  Built successfully, built project size is 635 KiB.

~/C/worker master*
❯❯❯ npm install -g @cloudflare/wrangler@1.9                                                      16:13:05
/usr/local/bin/wrangler -> /usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js

> @cloudflare/wrangler@1.9.0 postinstall /usr/local/lib/node_modules/@cloudflare/wrangler
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.9.0/x86_64-apple-darwin
wrangler has been installed!
+ @cloudflare/wrangler@1.9.0
updated 3 packages in 2.534s

~/C/worker master*
❯❯❯ wrangler build                                                                               16:13:15
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
Warning: webpack's output filename is being renamed to worker.js because of requirements from the Workers runtime
✨  Built successfully, built project size is 1 MiB. ⚠️  Your built project has grown past the 1MiB size limit and may fail to deploy. ⚠️
```

**Comment by ashleymichal** [comment]
@jorgelbg nothing should have changed, and we haven't been able to reproduce. is this still happening for you? if so, it needs its own issue, i don't want to lose it under this one.

**Comment by jorgelbg** [comment]
@ashleymichal Thanks for the reply! 

I tested with the latest release (v1.9.2) and I see the same thing happening. I will open a new issue and put the details there.

**Comment by petebacondarwin** [comment]
We just landed bundle size reporting in Wrangler 2. See https://github.com/cloudflare/wrangler2/pull/1272
Please upgrade to that version of Wrangler if this is still a problem for you.
