### ISSUE TITLE
restrict posts to localhost

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#1201]
should probably limit LogServer to only print things posted to it from the trace worker (or wherever logs come from). Can imagine a scenario where tails are long running and someone has another process that posts here and futzes with their log ingestion.

_Originally posted by @EverlastingBugstopper in https://github.com/cloudflare/wrangler/pull/1195_

**Comment by EverlastingBugstopper** [comment]
is this blocked externally on the API?

**Comment by ashleymichal** [comment]
@EverlastingBugstopper the trace-worker will need to send the tail id as a header with each post request yes. this is blocked then on work in both the API and the trace worker, but I don't think it's a blocker for release.
