### ISSUE TITLE
[dev] HTTPS support

### ISSUE THREAD

**Issue by phanect** [cloudflare/wrangler#1204]
#### Overview and problem statement

It would be very nice if `wrangler dev` server allows HTTPS access. I think the self-signed certificate is enough.

I maintain Cloudflare Workers to redirect to HTTPS URL on HTTP access on specific pages.
(The website I'm involved is a bit large and I cannot configure that with Page Rules since you can create only 100 Page Rules available.)

I tried to test HTTPS redirection with `wrangler dev`, but as expected, I opened "http://localhost:8787", then the Worker redirected to "https://localhost:8787" and the error page is shown.

@EverlastingBugstopper #1047

**Comment by EverlastingBugstopper** [comment]
for wrangler dev, we need a way for users to test http vs https. right now localhost server we spin up is always http, and will send https requests upstream to the worker, but that can be confusing behavior ofc. ideally, i'd send the request w/the same protocol that was sent to localhost, but there's the issue of certificates for https localhost. 

i found this tool that might be helpful for us to use https://crates.io/crates/certainly

it also looks like webpack-dev-server defaults to http, but will use http with a self-signed cert it provides if you want. https://webpack.js.org/configuration/dev-server/#devserverhttps

**Comment by lexavey** [comment]
wrangler dev  --local-protocol https

**Comment by bangank36** [comment]
> wrangler dev --local-protocol https

Works great! Thanks for sharing!
