### ISSUE TITLE
[dev] Needs more granular error handling

### ISSUE THREAD

**Issue by mpint** [cloudflare/wrangler#1206]
#### Environment

OSX 10.14.6
Node v12.15.0
Wrangler 1.8.4

#### Steps to reproduce

Using Workers sites, if you accidentally run `wrangler dev` before building your project (i.e. the `bucket` directory doesn't exist), Wrangler returns an unhelpful error message.  Downgrading Wrangler to 1.8.0 returned a helpful error message about the missing `./public` bucket that allowed me to fix the problem.  It appears the new `Could not upload your script` error is clobbering more actionable errors from previous versions.

#### What did you expect to see?

An error message about the missing bucket.

#### What did you see instead?

```
✨  Built successfully, built project size is 491 KiB.
🌀  Using namespace for Workers Site "__blog-workers_sites_assets_preview"
Error: Could not upload your script. Check your internet connection or https://www.cloudflarestatus.com/ for rare incidents impacting the Cloudflare Workers API.
```

**Comment by EverlastingBugstopper** [comment]
this is closed by #1251, thanks @mpint
