### ISSUE TITLE
Wrangler Tail Alpha testing feedback

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#1207]
If you've installed any of the 1.9.0 release candidates, we'd love to hear from you! Please comment on this issue with any feedback you have, big or small.

**Comment by arunesh90** [comment]
Hey!

Liking the idea of having the tail command a lot 😄
Currently trying to get it to work with my in-production worker, but I seem to be getting `Error: Could not extract tunnel url from cloudflared`. Any idea why that might be?

**Comment by ashleymichal** [comment]
@arunesh90 no problem! that was going to be my first question, but this does highlight that missing cloudflared does not give a helpful error message so thank you!

**Comment by johnspurlock** [comment]
Interesting! Is the ability to tail worker logs documented as part of the public API somewhere?  (without using wrangler)

**Comment by ashleymichal** [comment]
@johnspurlock no it isn't, at the moment wrangler is the blessed implementation. that being said there is more work to be done around worker logs.

**Comment by victoriabernard92** [comment]
When a client's internet is messed up nice to have a better error message:

```
 wrangler tail --env dev | jq .
Setting up log streaming from Worker script "delete-gateway-dev" to Wrangler. This may take a few seconds...
Closing tail session...
Error: ⚠️  Error: error sending request for url (https://api.cloudflare.com/client/v4/accounts/95e065d2e3f97a1e50bae58aea71df6d/workers/scripts/delete-gateway-dev/tails): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```

One idea `❗️DNS resolution error when connecting to api.cloudflare.com. Try checking your internet connection and run again`

**Comment by chasers** [comment]
This looks nice! Will work on a Logflare integration soon. `outcome` looks especially useful. Only thing I can see is that people will want more than 10 events/second pretty quickly. Having that configurable would be useful I'm sure.

**Comment by ashleymichal** [comment]
@chasers for sure the limitations are not practical for a production logging solution; wrangler tail is best suited for in the moment troubleshooting. additional work is required on the platform (where the limits are set) for more comprehensive solutions.

**Comment by ashleymichal** [comment]
thanks everyone for your feedback! we've addressed some of it, and created issues for the rest to address in later releases.
