### ISSUE TITLE
webpack.BannerPlugin does not work with wrangler

### ISSUE THREAD

**Issue by wraithgar** [cloudflare/wrangler#1214]
#### Environment

* operating system:
Ubuntu bionic
* output of `rustc -V`:
not installed
* output of `node -v`:
v10.17.0
* output of `wrangler -V`:
wrangler 1.8.4

#### Steps to reproduce

When adding `webpack.BannerPlugin` to our `plugins` array in `webpack.config.js` we get the following traceback when trying to run `webpack build`

```sh
/home/gar/.cache/.wrangler/wranglerjs-14712ec6e7f3d5bb/index.js:124
      throw err;
      ^

TypeError: compilation.updateAsset is not a function
    at /home/gar/[redacted]/node_modules/webpack/lib/BannerPlugin.js:111:19
```

To reproduce this add the following to your `webpack.config.js` file:

```javascript
module.exports = async function setup () {
  return {
     // existing webpack config
    plugins: [ new webpack.BannerPlugin('hello world') ]
  }
}
```

#### What did you expect to see?
A successful build

#### What did you see instead?
The traceback provided.

Please note that running webpack-cli manually results in a successful build asset.

**Comment by xtuc** [comment]
could you please share your `package.json`? It would like to check the webpack version because wrangler runs `4.33.0`

**Comment by wraithgar** [comment]
Here are the dependencies and devDependencies from the package.json.

```
 "dependencies": {
    "@cloudflare/wrangler": "^1.8.4",
    "cookie": "^0.4.0",
    "webpack": "^4.42.1"
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "cheerio": "^1.0.0-rc.3",
    "faker": "^4.1.0",
    "git-validate": "^2.2.4",
    "mocha": "^7.1.1",
    "nock": "^12.0.3",
    "node-fetch": "^2.6.0",
    "nyc": "^15.0.1",
    "standard": "^14.3.3"
  },
```

Wrangler will not run if webpack isn't in package.json itself, it complains with:
```sh
(node:17342) UnhandledPromiseRejectionWarning: Error: Cannot find module 'webpack'
```

If I pin webpack back to the older version of 4.33.0 it works, I can see the banner in my built file.

Is there a better way of keeping wrangler's needed version of webpack in sync w/ my package.json?

**Comment by xtuc** [comment]
Maybe we should use a peer dependency?
