### ISSUE TITLE
`wrangler route list` knows nothing about `--env`

### ISSUE THREAD

**Issue by thochra** [cloudflare/wrangler#1216]
### 🐛 Bug Report

Looks like the `route` command is unable to load config according to a specified environement:
```
$ wrangler route list --env production
Error: You must specify a zone_id in `wrangler.toml` to use `wrangler route` commands.
```

#### Environment

* operating system: linux/ubuntu
* output of `rustc -V`: N/A
* output of `node -v`: v12.16.1
* output of `wrangler -V`: wrangler 1.8.2

#### Steps to reproduce

Put configuration of zones/accounts/routes in an env section and try to list the routes.

#### What did you expect to see?

Routes associated to an env.

#### What did you see instead?

missing configuration message or default config routes instead of the env's ones.

**Comment by EverlastingBugstopper** [comment]
The error message here indicates that you need to set a `zone_id` in the `[env.production]` section of your `wrangler.toml` in order for that command to work.

**Comment by thochra** [comment]
Of course the zone_id and account_id have been filled for these envs because I can publish the worker.

here is a sample to reproduce it:
```
cd /tmp
wrangler generate -t webpack test-route
cd test-route
```

`wrangler.toml`
```
name = "test-route"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
account_id = "1516XXXX"
zone_id = "9c08XXXXX"
```

**Comment by tagspace** [comment]
I can also confirm that this is an issue.

If I create an environment, then I can no longer use 
wrangler route list

**Comment by EverlastingBugstopper** [comment]
I'm still unable to reproduce this error - @ashleymichal maybe you can try?

**Comment by thochra** [comment]
@EverlastingBugstopper In the example I gave I voluntarily let empty the account and zone id to demonstrate it doesn't take into consideration the values in the prod env.

If you have an account and zone id in the default section, then if you try to switch to another zone in the prod env you'll see you'll query the default zone, not the prod one.

Hopping it will help to reproduce...

**Comment by ashleymichal** [comment]
we've repro'd this and  i've started on a solution.  should be able to work on it more later this week.

**Comment by Berndinox** [comment]
Same Problem here, is there a fix?

**Comment by jspspike** [comment]
I'll take a look at this issue
