### ISSUE TITLE
[dev] Support for local configuration

### ISSUE THREAD

**Issue by dmcgowan** [cloudflare/wrangler#1229]
#### Overview and problem statement

Add support for setting up a local development configuration outside of the `wrangler.toml` when using `wrangler dev`. The issue today is that the `wrangler.toml` is normally committed to the repository, but should exclude any developer specific configuration. [Some templates refer to a `./.env` file](https://github.com/ConzorKingKong/cloud-storage/blob/95183305108cf961f33b14597e7a2d5fa24ed06a/README.md#cloud-storage) which seems to match a solution to this problem, however, I could not find a way to have `wrangler dev`
use this.

#### Basic example

Maybe it looks like
```
$ cat ./.env
[env.dev]
account_id = 123456
workers_dev = true
vars = { "somevar" = "devvalue", "creds" = "mycreds"}
```

**Comment by ashleymichal** [comment]
i think this is related to #1064 ? and/or some consideration of "composable" wrangler.toml files.

**Comment by dmcgowan** [comment]
@ashleymichal yeah, I think #1064 would also solve my use case

**Comment by ashleymichal** [comment]
closing as solvable by #1064
