### ISSUE TITLE
wrangler publish says it succeeds (false positive) 

### ISSUE THREAD

**Issue by nodebotanist** [cloudflare/wrangler#124]
If you pass no Zone ID with `wrangler publish` it correctly errors, but if there is any value, even a garbage Zone ID, you get a success message even if the publish fails because of a bad Zone ID.

**Comment by ashleygwilliams** [comment]
looks like this was from a very old version of wrangler! im going to close but reopen if you can repro with the latest master (i have tried and cannot)
