### ISSUE TITLE
only check for updating installed tools once every 24 hours

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1240]
in #1003, we stopped reinstalling wasm-pack and wranglerjs on every change

in #1190 we added messages if wrangler needs updating and stored when we last checked in `~/.wrangler/version.toml` so we only hit the crates.io api once every 24 hours

we should add when we last checked for the latest version of wasm-pack to `version.toml` in the same way we do for updating wrangler

**Comment by EverlastingBugstopper** [comment]
blocked on #1190 and #1003

**Comment by xtuc** [comment]
could we also make it optional? when working offline we shouldnt block the user because of not being able to check or update the version

**Comment by EverlastingBugstopper** [comment]
yeah that's probably not a bad idea
