### ISSUE TITLE
No documentation about the `type` field now required in wrangler.toml

### ISSUE THREAD

**Issue by steveklabnik** [cloudflare/wrangler#125]
I updated wrangler, and got this:

```console
> wrangler build
Error: ErrorMessage { msg: "⚠\u{fe0f} Your project config has an error, check your `wrangler.toml`: missing field `type`" }
```

I did some source diving, and fixed it, but this should be explained somewhere :smile:

**Comment by xtuc** [comment]
Was the key previsouly not required? What was the default?

**Comment by signalnerve** [comment]
for whoever picks this up: I think the supported types right now are `Rust`, `Webpack`, and `JavaScript`, and it _is_ required in your config. `wrangler generate` does fill in `type` when generating new projects, but if you have an old `wrangler`-based project, you'll need to add it manually. 

a notable thing I learned today – the type in `wrangler.toml` is case-insensitive, too

<img width="564" alt="Screen Shot 2019-05-24 at 12 19 51 PM" src="https://user-images.githubusercontent.com/922353/58345553-40099800-7e1e-11e9-8d56-b26670e7eec0.png">

**Comment by steveklabnik** [comment]
@xtuc it was previously not a thing that existed, because wrangler only did rust projects

**Comment by xtuc** [comment]
Yes, that's right. I believe we can close this because #144 sets the default.

**Comment by steveklabnik** [comment]
Just because a default gets set doesn't mean that it should be hard to figure out what it does.

**Comment by ashleygwilliams** [comment]
we are def gonna doc this- when i write the wrangler docs... 'm gonna open a generic issue for that. all the current docs are gonna go away.
