### ISSUE TITLE
improve cloudflared error reporting

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#1255]
# Reported during RC:

> I was getting the `"Error: Could not extract tunnel url from cloudflared"` message because something else was already bound to 8081. Cloudflared does give a proper message for that one, so surfacing the error up from `cloudflared` would be a helpful addition to debugging issues.

_Originally posted by @cthos in https://github.com/cloudflare/wrangler/issues/1207#issuecomment-617270207_

# Solution

cloudflared puts a lot of messaging out to stderr; some of it is info, some is error. we need  to figure out how to pull errors out of this, or work with that team to figure out exit codes when it fails, to give better error messages on failure.

**Comment by EverlastingBugstopper** [comment]
would be extra nice if cloudflared had some sort of error endpoint you could query (even better if it was a websocket)

**Comment by Electroid** [comment]
Won't fix: we're moving away from `cloudflared` and using Durable Object / WebSockets for `wrangler tail` in the future.
