### ISSUE TITLE
warn when non-string values are defined in vars

### ISSUE THREAD

**Issue by PierBover** [cloudflare/wrangler#1259]
### 💡 Feature request

When passing a boolean environment variable from `wrangler.toml` it should be a `Boolean` in the worker context and not a string.

If this is not feasible at least a warning would be great when running wrangler if it finds a boolean in the env vars.

#### Overview and problem statement

TOML files accept string and booleans but when the environment variables in `wrangler.toml` are "injected" into the worker these are all passed as strings. This can cause confusion as demonstrated in the below example.

I imagine the behavior is similar when passing env vars from the CF dashboard although I haven't verified it.

#### Basic example

In the `wrangler.toml`:
```
vars = {DEBUG = false}
```
Then doing in the worker:
```
if (DEBUG) {
  // this will execute because DEBUG is now a string and any string returns true
}
```
The solution is to do this which is tedious and prone to errors:
```
if (DEBUG === 'true') {
  // this will not exceute
}
```

**Comment by EverlastingBugstopper** [comment]
those variables do indeed get stringified if you upload them from the UI. looking into this

**Comment by EverlastingBugstopper** [comment]
we're not going to allow anything other than strings to be uploaded via the cloudflare API.

unfortunately completely disallowing non-string variables to be defined in `wrangler.toml` isn't really an option because of backwards compatibility issues, so i think we should detect if someone has not put quotes around the value of a `var` and then issue a warning, letting them know that the variable they uploaded will be represented as a string.

**Comment by ashleymichal** [comment]
> completely disallowing non-string variables to be defined in wrangler.toml isn't really an option because of backwards compatibility issues

do non-string variables work today?

**Comment by EverlastingBugstopper** [comment]
yeah - you can definitely specify a boolean value in `wrangler.toml`. it will always be uploaded as a string, but that's kinda confusing since we allow folks to specify `true` or `false` instead of making them do `"true"` or `"false"`

**Comment by PierBover** [comment]
Is this only for booleans?

I haven't tested it, but I imagine it's the same for numbers.

**Comment by EverlastingBugstopper** [comment]
it's the same for everything. it seems as if the `toml` library we're using actually _does_ error if you try to deserialize a non-string into a string field. this makes me think that our old friend `Config` is doing something wonky that converts those values to strings.

**Comment by ashleymichal** [comment]
hopefully #867 will correct this.
