### ISSUE TITLE
`secret put` fails if worker hasn't been built

### ISSUE THREAD

**Issue by ObsidianMinor** [cloudflare/wrangler#1266]
### 🐛 Bug Report

`secret put` fails if worker hasn't been built successfully once. This is different from if the worker hasn't been published, which is a separate issue (#1129).

#### Environment

* operating system: Linux
* output of `rustc -V`: rustc 1.43.0 (4fb7144ed 2020-04-20)
* output of `node -v`: v12.16.3
* output of `wrangler -V`: wrangler 1.9.0

#### Steps to reproduce

1. Create a new worker (don't build)
2. Call `wrangler secret put SECRET`
3. Fill in with a value.

#### What did you expect to see?

Success! A draft worker is created to insert the secret in the API.

#### What did you see instead?

`Error: No such file or directory (os error 2)`

**Comment by ashleymichal** [comment]
best guess is that this is a workers site where as part of publish wrangler is looking for the bucket directory and finding nothing. we should update draft to really just publish a hello world worker.
