### ISSUE TITLE
Custom hostname support for Cloudflare API

### ISSUE THREAD

**Issue by manatarms** [cloudflare/wrangler#1270]
#### Overview and problem statement

Currently, the Cloudflare api hostname `api.cloudflare.com` is hard coded in wrangler. It would be nice to support more than one hostname for resiliency purposes. Maybe something like  `--api-hostname` param or a config variable.

**Comment by xtuc** [comment]
as discussed internally, coudl we consider an environment variable instead of a CLI argument.

**Comment by EverlastingBugstopper** [comment]
I say we check for the `CF_API_HOST` backend. We will need to pass this host to `cloudflare-rs` and also use it in our own `http` module. I don't think we should add a flag as this is a very niche use case and not something we should bog users down with unless they go looking for it.

**Comment by manatarms** [comment]
`CF_API_HOST` in env sounds like a good plan to me 👍

**Comment by ispivey** [comment]
Sounds good to me too 👍

**Comment by manatarms** [comment]
Comment to reopen issue. Been busy, I'll make a PR to fix
