### ISSUE TITLE
Using Parcel 2 

### ISSUE THREAD

**Issue by vladinator1000** [cloudflare/wrangler#1274]
### 💡 Feature request
I'm making a starter kit with Parcel 2 🎉 I'm trying to figure out how to get `wrangler dev` to support hot loading so I don't have to cancel and re-build my project every time I make a change.

#### Overview and problem statement
Wrangler is coupled to Webpack and this means the dev experience with bundlers other than webpack is lacking because of the lack of hot reloading. Not sure if that's a problem, it would be great to have some flexibility but I can convert back to webpack if needed.

#### Basic example

Check out [this repo](https://github.com/vladinator1000/ts-cloudflare/)✨

**Comment by xtuc** [comment]
webpack's integration offers a better UX but doens't allow using other bundlers.
I'm convienced that we can make wrangler with any bundler. Wrangler's JavaScript type allows to deploy a single js file, which could be emited by TypeScript or Parcel. However, there's no plan to do so at the moment

**Comment by vladinator1000** [comment]
Sounds good, I'll tweak my project to use webpack instead.
