### ISSUE TITLE
Request: Set JavaScript path by wrangler.toml or CLI

### ISSUE THREAD

**Issue by jahredhope** [cloudflare/wrangler#1275]
### 💡 Feature request

Wrangler has been awesome to get to work with so thanks for all the hard work. I'd like to please raise a feature request that would help with my use-case.

#### Overview and problem statement

I'm attempting to incrementally adopt wrangler for uploading a worker and related KV storage.
I've already got a (perhaps over-complicated) build process so for now I just want wrangler to upload the file. (After doing a bunch of KV stuff)
I'm able to do this using type="javascript" which is great, but this requires me to modify the package.json main attribute.
Unfortunatly modifying this attribute breaks other things in my project.

#### Basic example

I'd like to be able to specify the path to find the single JavaScript file by either wrangler.toml

```toml
type = "javascript"
main = "dist/worker.js"
```

or via the CLI

```bash
$ wrangler publish --main "dist/worker.js"
```

My preference would be via wrangler.toml

**Comment by EverlastingBugstopper** [comment]
this makes sense to me - i always thought it was strange that we grabbed it from package.json

for webpack type projects, we allow a `webpack_config` field to point to a custom configuration.

i think for this one we should add a field in the toml `javascript_config` to match that convention.

**Comment by ashleymichal** [comment]
for my money i like `main`, or `entry-point` or similar; there's not really a config here like with webpack, just an entry point file, so naming it config might be confusing. but semantics aside, i like this idea.
