### ISSUE TITLE
[tail] assert port type is Option<u16>

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#1284]
oh snap i need to do this for tail...

_Originally posted by @ashleymichal in https://github.com/cloudflare/wrangler/pull/1272_

**Comment by luanraithz** [comment]
This validation seems to be [here](https://github.com/cloudflare/wrangler/blob/master/src/main.rs#L1061). Is there any other place it should be?

**Comment by EverlastingBugstopper** [comment]
that seems correct @luanraithz.

@ashleymichal something else we should be doing?

**Comment by ashleymichal** [comment]
nope. probably just didn't get closed when it should have.
