### ISSUE TITLE
Install Wrangler in local node_modules by default

### ISSUE THREAD

**Issue by thomkrupa** [cloudflare/wrangler#1286]
#### Overview and problem statement

Current install directory is `join(os.homedir(), ".wrangler");`.

`homedir()` is blocked by many CI/CD tools (I tried on Vercel and Gatsby Cloud) which means you can't install anything there. Usually, if you run `npm i <package>` it installs in local `node_modules` - you can use different versions of packages safely in different projects. A package should install globally if you run `npm i -g <package>` command.

**Comment by osdiab** [comment]
Would it at least be possible to make the install path configurable? I’m resorting to just checking the binary into my project because of this issue.

**Comment by ispivey** [comment]
@osdiab that stinks 😕  we know we're overdue to revisit how the installer works. We'll talk it through soon and see if there's a simple way to unblock per-project installation and configuration.

**Comment by bpofficial** [comment]
Could we simply set an environment variable? then that pretty much changes 
```typescript
const installDirectory = join(process.cwd(), ".wrangler");
```
to
```typescript
const installDirectory = join(process.env.WRANGLER_INSTALL_PATH || process.cwd(), ".wrangler");
```
or
```typescript
const installDirectory = join(process.env.WRANGLER_USE_CWD || process.cwd(), ".wrangler");
``` 
to install in the root of the project.

Which would allow pretty much all CI/CD's to have an env var set that allows us to manage the whereabouts of wrangler's binary.
