### ISSUE TITLE
Rollup Support

### ISSUE THREAD

**Issue by wtcross** [cloudflare/wrangler#1287]
#### Overview and problem statement

It would be great for Wrangler to support [Rollup](https://github.com/rollup) for module bundling in addition to Webpack. The [wasm](https://github.com/rollup/plugins/tree/master/packages/wasm) module for Rollup enables importing and bundling wasm modules. With my limited understanding of Wrangler internals I think this would enable supporting Rollup as well.

#### Basic example

The [svelte-ssr-worker](https://github.com/lukeed/svelte-ssr-worker) project by @lukeed is a great example of a project that could benefit from this.

**Comment by xtuc** [comment]
Similar report https://github.com/cloudflare/wrangler/issues/1274. To echo what I said, I think it's certainly possible to support mutliple bundlers, it's just not on our TODO list at the moment.

**Comment by wtcross** [comment]
Thanks for the quick response. Webpack accomplishes all the same things so I would also categorize this as low priority. This would be more of a refinement down the road I suppose.

**Comment by wtcross** [comment]
I created an example similar to the [`svelte-ssr-worker`](https://github.com/lukeed/svelte-ssr-worker) project I previously linked to that uses Webpack instead of Rollup to accomplish the same goal.

https://github.com/wtcross/svelte-ssr-cloudflare-worker-site

Note the need to wrap `wrangler` with NPM scripts since it's a multi-phased build (client → ssr → worker).

**Comment by PierBover** [comment]
Is it not possible to bundle a Worker project to a single `.js` file with Rollup and then in `wrangler.toml` just use `type = "javascript"`?

Am I missing something?

**Comment by wtcross** [comment]
@PierBover as far as I can tell it forces a webpack build even if `type = "javascript"` is used. That's probably a separate issue.

**Comment by EverlastingBugstopper** [comment]
mmmmm - definitely should not be running webpack at all if you set `type = "javascript"`. if it is, that's a bug.

**Comment by PierBover** [comment]
I haven't seen that either. And I even used Rollup to bundle a worker (or at least I tested it).
