### ISSUE TITLE
wrangler panic: panicked at 'called `Result::unwrap()` on an `Err` value: Protocol("Connection reset without closing handshake")'

### ISSUE THREAD

**Issue by danbars** [cloudflare/wrangler#1295]
#### Environment

* operating system:
* output of `rustc -V`:
`bash: rustc: command not found`
* output of `node -v`:
`v11.10.1`
* output of `wrangler -V`:
`wrangler 1.9.0`
* contents of `wrangler.toml`
```
name = "get"
type = "webpack"
account_id = "c3232a9885fb9cc84a59deeda19da388"
workers_dev = false
route = "https://get.charttt.com/*"
zone_id = "8aec397bce26382b7dc72f5e2ae126f9"
```
#### Steps to reproduce
On a project that used to work properly, wrangler panics when I run `wrangler dev`
You can see [screenshot here](https://imgur.com/a/ZMxG3IB)

I've upgraded wrangler from 1.8.1 to 1.9.0 but still same error:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Protocol("Connection reset without closing handshake")', src/commands/dev/socket.rs:46:27
```

**Comment by EverlastingBugstopper** [comment]
Hey thanks for the report! I actually _just_ fixed this one up and it should be going in the next release. Hang tight!

**Comment by danbars** [comment]
Super! when is the next release expected?

**Comment by EverlastingBugstopper** [comment]
probably tomorrow :)
