### ISSUE TITLE
[dev] console.log() messages stop being printed

### ISSUE THREAD

**Issue by PierBover** [cloudflare/wrangler#1320]
### 🐛 Bug Report

So once I get this message from `dev` I get no more `console.log` messages:

> Script modified; context reset.

I still get the usual `dev` messages. Eg:
```
Script modified; context reset.
-----------------------
[2020-05-24 22:59:42] OPTIONS example.com/v1/channels/pier/stories HTTP/1.1 204 No Content
[2020-05-24 22:59:42] GET example.com/v1/channels/pier HTTP/1.1 200 OK
[2020-05-24 22:59:42] GET example.com/v1/channels/pier/stories HTTP/1.1 200 OK
[2020-05-24 22:59:45] OPTIONS example.com/v1/channels/pier HTTP/1.1 204 No Content
[2020-05-24 22:59:45] GET example.com/v1/channels/pier HTTP/1.1 200 OK
[2020-05-24 22:59:57] OPTIONS example.com/v1/stories HTTP/1.1 204 No Content
[2020-05-24 22:59:57] POST example.com/v1/stories HTTP/1.1 500 Internal Server Error
🌀  Detected changes...
```

This has happened to me two or three time since I updated to `1.9.1`. I think this never happened before updating but I'm not 100% certain.

**Comment by EverlastingBugstopper** [comment]
🤔  hmmm - this is a rough one. definitely don't like to see it but I'm not entirely sure what's happening here as I can't seem to reproduce the issue!

are you logging something a bit strange? it's possible that the devtools protocol parser is just dropping some messages. if you could get it to reproduce with `RUST_LOG=debug` and paste the logs that would be _super_ helpful

**Comment by PierBover** [comment]
Ok, I'll see if I can reproduce it and give you all the info I can.

**Comment by vladinator1000** [comment]
When I tried it I had to wait a minute after running dev until I start seeing actual console logs.

**Comment by RaeesBhatti** [comment]
I think I'm facing the same issue. `wrangler dev` keeps telling on ` 500 Internal Server Error` on every request but never really shows an error.

**Comment by RaeesBhatti** [comment]
Nevermind, there was an error being thrown above the stack where I had `try {}  catch {}`

**Comment by AsathalMannan** [comment]
same issue here,.. `wrangler dev` not printing `console.log(data)`
anyone resolved this?

using:
- Wrangler 1.19.2
- Node 16.8.0

**Comment by agrippanux** [comment]
I am also getting the same behavior as @AsathalMannan

**Comment by agrippanux** [comment]
in further testing, it seems like console.log() will print out if it’s in the index file but not in an included file.  Is there a workaround for this?

**Comment by allisongs** [comment]
When my index.js file has an import statement at the top ie "import { blah } from 'templates'". I get no console logs. when I do nothing but comment out the import statement, I get console logs. There are no errors in the code.

**Comment by petebacondarwin** [comment]
This sounds like a failure to bundle the code correctly?
Either way, I don't believe this should be a problem with the latest version of Wrangler (https://github.com/cloudflare/wrangler2).
Please upgrade to that version and if there is still a problem, create an issue at https://github.com/cloudflare/wrangler/issues/new/choose.

**Comment by fresheneesz** [comment]
This also happened to me randomly today. Console logs just don't appear in the wrangler output. I know the console log is getting hit because its returning responses correctly. No idea what might have caused it. I was adding a `.dev.vars` file at the time. But removing it doesn't seem to help. I did add a secret for a `dev` environment and when I try to turn off dev mode it says I need to register a `workder.dev` subdomain. Doubt that's related, but that's the only thing I can think of

**Comment by fresheneesz** [comment]
This happened to me when I ran two instance of wrangler. I would have expected the second run to simply fail, but instead it looks like it works, but its actually just another instance on a different port. I would suggest simply erroring if the expected port isn't available.
