### ISSUE TITLE
Webpack: avoid install wrangler-js in the user's project

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#133]
We could install wrangler-js in wrangler cache instead to hde it to the user.

**Comment by ashleygwilliams** [comment]
this is the same as #154

**Comment by xtuc** [comment]
https://github.com/cloudflare/wrangler/issues/154 is to move it in our source, this issue is the global installation.

**Comment by ashleygwilliams** [comment]
oh whoops. sorry about that.
