### ISSUE TITLE
exited with exit code: 0xc0000135

### ISSUE THREAD

**Issue by eng-dibo** [cloudflare/wrangler#1333]
just installed wranger and trying to generate my first app
```
wrangler generate repo-hunt https://github.com/cloudflare/worker-template-router
```
but got an error
```
Error: tried running command:
cmd /C C:\\Users\\eldeeb\\AppData\\Local\\.wrangler\\cargo-generate-0.5.0\\cargo-generate.exe generate --git https://github.com/cloudflare/worker-template-router --name r
epo-hunt --force
exited with exit code: 0xc0000135
```

**Comment by eng-dibo** [comment]
I just installed wrangler (on windows) and trying to generate a project, no anything else

```
> npm i @cloudflare/wrangler -g
> wrangler help
> wrangler generate my-worker
```

**Comment by jahands** [comment]
I just set up a fresh nodejs Windows env with latest Node LTS and Cargo and installed wrangler with npm and it worked fine.

Can you post more info about your environment?
Output of:
`wrangler -V`
`node -v`
`npm -v`

What Windows version are you on?

**Comment by Natnael123** [comment]
> What Windows version are you on?

wrangler : 1.9.2
node : v12.17.0
npm : 6.14.4
