### ISSUE TITLE
Add subdomain registration call

### ISSUE THREAD

**Issue by rita3ko** [cloudflare/wrangler#135]
Per discussion, this could be configured with
`wrangler config --subdomain banana`
which would set it up as banana.workers.dev

This might take ~30 seconds, so we should let the user know. 

The API call is:
`PUT /accounts/<account id>/subdomain`

Upon success, the API responds with:
```
{
  "success": true,
  "errors": [],
  "messages": [],
  "result": {
    "subdomain": "myname"
  }
}
```

If it's taken (or blacklisted), it will respond with a 409 --> we should handle this with a message like "pls pick something different".

**Comment by ashleygwilliams** [comment]
this reintroduces account id... i guess it was inevitable :P 

how many people have multiple accounts? i'm not sure i can come up with a good strategy pre launch but i imagine it's a thing?
