### ISSUE TITLE
Instructions for finding account_id only work if you have a zone

### ISSUE THREAD

**Issue by kentonv** [cloudflare/wrangler#1364]
When you generate a new project, Wrangler writes:

    You can find your account_id and zone_id in the right sidebar of the zone overview tab at https://dash.cloudflare.com

This only works if you have a zone, but if you're using workers.dev exclusively, then you don't have any zone pages and so the mentioned sidebar doesn't show up anywhere.

I couldn't find anywhere in the UI that showed my account ID in this case. However, the account ID does appear in the URL.

**Comment by EverlastingBugstopper** [comment]
mm - we should update to point them to the account-level workers page. i believe it's on the right panel in that case

**Comment by ashleymichal** [comment]
correct. but also more than likely this belongs in docs.

**Comment by kentonv** [comment]
Huh somehow I missed that the account ID shows up on the Workers page. I thought I looked there.

> but also more than likely this belongs in docs.

Docs are great, but they wouldn't be a replacement for this message.

**Comment by ashleymichal** [comment]
i'm a dingus and thought you were talking about the readme. saying "account home"  is probably  ideal.

**Comment by kentonv** [comment]
Problem is that the account home doesn't actually have your account ID on it. :(

It looks like we can't directly link to the worker page either, unless we already know the user's account ID... ugh.

This will all be solved when we support an OAuth flow for configuration, of course...

**Comment by EverlastingBugstopper** [comment]
mm - i dont think it'll be solved with oauth since you'll still need to specify account + zone id.

also - don't we have deeplinks or something? cc @neynah

**Comment by kentonv** [comment]
With OAuth, presumably you'd type `wrangler login` or whatever and then it would open a tab in your browser where you select which account you want, etc. No need to tell people to hunt for an ID to copy/paste...

**Comment by EverlastingBugstopper** [comment]
hmm. yeah - we dont store account_id or zone_id globally since folks often have more than one of each, so they are per-project configuration instead of global configuration like your api key. would probably be nice to spit out list of available account ids when you would run `wrangler login` like we do now with `wrangler whoami`

**Comment by kentonv** [comment]
Ohhh, I didn't know about `wrangler whoami`. Maybe this message here should really direct people to run that. It's much easier than digging around in the dashboard for an account ID...

I guess it's a little weird that our config file mixes deployment information with source code... seems like that makes it hard to, say, have an open source worker on github that anyone can deploy to their own account. Wonder if it makes sense to put account ID and script name in a separate file that could optionally not be checked in, or something.

**Comment by ashleymichal** [comment]
> wrangler whoami

yas

> I guess it's a little weird that our config file mixes deployment information with source code... seems like that makes it hard to, say, have an open source worker on github that anyone can deploy to their own account. Wonder if it makes sense to put account ID and script name in a separate file that could optionally not be checked in, or something

this has definitely introduced issues. i think wrangler login and whoami could be instrumental in fixing this problem

**Comment by EverlastingBugstopper** [comment]
agreed @kentonv - i think we should definitely think about ways to better support per-developer settings that dont get checked in to version control.
