### ISSUE TITLE
Running wrangler build outputs "Installing wasm-pack" on non-WASM projects

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/wrangler#137]
The current version of wrangler on `master` outputs "⬇️ Installing wasm-pack..." when running `wrangler build`, even on non-WASM projects (e.g. `webpack` project type):

```
simple-slack-bot $ wrangler publish
⬇️ Installing wasm-pack...
audited 4178 packages in 1.637s
found 0 vulnerabilities
```

**Comment by ashleygwilliams** [comment]
i can't repro this! i made https://github.com/cloudflare/wrangler/pull/141 to remove wasm specific comments from the --help

**Comment by ashleygwilliams** [comment]
closing this. @signalnerve please reopen if you can repro with master

**Comment by signalnerve** [comment]
oh weird! ok, will re-open if i run into it again, but thanks for checking!
