### ISSUE TITLE
wrangler tail command is not working

### ISSUE THREAD

**Issue by simplenotezy** [cloudflare/wrangler#1378]
### 🐛 Bug Report

When I run `wrangler tail` I get:

    error: Found argument 'tail' which wasn't expected, or isn't valid in this context

Found info about the tail command here https://developers.cloudflare.com/workers/about/tips/debugging/

**Comment by ispivey** [comment]
@simplenotezy can you please edit your issue to include the requested info in the bug report template? Also, make sure you're using the latest release, following the instructions in the bug report template.



#### Environment

* operating system:
* output of `rustc -V`:
* output of `node -v`:
* output of `wrangler -V`:
* contents of `wrangler.toml`

#### Steps to reproduce

**Comment by simplenotezy** [comment]
I realized I was running some versions behind recent. Fixed. Thanks.
