### ISSUE TITLE
Allow project type specification in template repos (or generate command)

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/wrangler#138]
Generating a project based on a template defaults to the `JavaScript` project type, but it would be useful for either the `generate` command to accept a project `type` flag, or for the command to be able to infer the template type from the repository itself. 

For context: we have the [`worker-template-router`](https://github.com/cloudflare/worker-template-router) which is a JS template for wrangler projects with a built-in `Router` class, all defined in `index.js`. I think this should probably be refactored to be a `webpack` project, so we can pull the `Router` class out of `index.js` into `router.js`. 

Because we don't have any way of indicating to wrangler _what_ the incoming template is, making this change would effectively make the template a non-functional `webpack` template (it wouldn't know that it needs to build, before even getting to any issues with `require` etc) without any mechanism to reflect that in the `wrangler.toml`.

A side note: the quick way around this (for now) might be to key based on the template string to detect `webpack`, we have an exception in `generate` for templates with `rust` in the template URL right now, which sets the project `type` as `rust`.

**Comment by nodebotanist** [comment]
+1
