### ISSUE TITLE
Error sending request for url (...): operation timed out

### ISSUE THREAD

**Issue by SirJosh3917** [cloudflare/wrangler#1386]
The issue lies [here](https://github.com/cloudflare/wrangler/blob/master/src/http/legacy.rs#L40).

I'm writing some web workers on a slow internet speed. When I want to preview my web worker (`wrangler preview --watch`), my internet speed requires a full second to upload 50KiB, and I have 2.3MiB of uncompressed JavaScript to upload. This is 46 seconds, and surpasses the 30 second timeout limit.

A simple fix would be to utilize the user's configuration (located at <user's home directory>\.wrangler\config\default.toml) and allow them to specify an `http_timeout` in seconds.

Current workaround is to compile from source with a longer timeout.

**Comment by GregBrimble** [comment]
Think this is worsened by [the new release, `1.10.0`](https://github.com/cloudflare/wrangler/releases/tag/v1.10.0) since the asset uploads are done in bulk rather than individually. I'm on a flaking connection myself and 1.10.0 was unusable—I had to downgrade to 1.9.2.

**Comment by EverlastingBugstopper** [comment]
Hmmm.. I don't think the bulk upload change should have impacted this as it just increased the limit of the amount of files you can upload at once by batching the API calls to be run subsequently. However, we did shorten the HTTP timeout for kv commands that are not bulk uploads in a refactor by @ashleymichal... 

@GregBrimble if you run the command with RUST_LOG=debug, are you able to pin down the API call that is timing out?

**Comment by EverlastingBugstopper** [comment]
we just released 1.10.1 that should address this issue @SirJosh3917 and @GregBrimble 😄  sorry for the inconvenience!!

**Comment by GregBrimble** [comment]
It did indeed! Thanks @EverlastingBugstopper :)

**Comment by AlexRMU** [comment]
Same error:
```
$ npx wrangler dev
Error: error sending request for url (https://f2672430decd48489585e9f4c494fdf9.alex-swim.workers.dev/cdn-cgi/workers/preview/?s0=ATrR8bTK6g5NbvmdHaHkTj7Sdysu_P_F6YtsL7HN0r630h-8p8aZ7KN_zWcrjFqWMEuMsXT0NAIbN8K5UvRaNobbkI0R94ADoHPi90eY4dIxmhHoguOnyyOKwJ9WM_N_QbWlgc1WWQXY7DpC8gTmMexhxdD8RSV0Q1X-to8TyCmbk3Q3BXJlL9mPic6G--m9hBnBRnVa3seWzsJ65ybgZrC7ZnxWWwCcs5Pnsd7WUk-UfBG0NalGhf_hw8vygc2nd_VzHW0-cN5NTLDfRKDuFqcw_pZKNAa3jhu6_BaBmc3jzjKyoR7x0Jati5v09L6j0uAPR69tzhLMXAG3rggnt8A): error trying to connect: operation timed out

or

Error: error sending request for url (https://api.cloudflare.com/client/v4/accounts/15ca03de9af46e35326a3bdd0cd20bf9/workers/subdomain/edge-preview): error trying to connect: operation timed out
```
The link displays this:
```
{
inspector_websocket: "wss://f2672430decd48489585e9f4c494fdf9.alex-swim.workers.dev/cdn-cgi/workers/preview/inspector",
token: "ATJ30CNmoMYlhKNbddtmtKkeiADRDN_6P7eoEZ-eGX9EHjKpQ82yFxotUordcH7fw0CLkyfc7GTlrPnIsxtOJHo3ghnVULmc7EhAU08hqUnpB48ecbus_5_Y60X3mUBLBiiHXvp2IeHf1JTw6CvwBgxHzUodhjtN3WsB9BlTkrW6BVp9481eMnvpGdoifuBL6ntHVLSudIcDqTQiwKPUwLFG9GaDoMWZ25iQwclpfL9G6aYcQ47ULWe4PCzja04L2X_oYJFcC_yO6pyjBHxuK8BNmi7u1A9rlFiCKmqtT2uI1KATfyUNv3-Z79BY5IGqS5nDUUb3RqZJHnCVsWOwaFF41myx3YR7b9aAzw2jcF5ZPjyHUNzI2eOECM3SI9VM16Cjok5Ng-EQ8RwPZRst1v8B1TPVgEy-TUugzDrKWHMBMhqzcGL3O21xmcrdO39OjFAMl-2vMla80nMcCyHdxio"
}

or

{
success: false,
errors: [
    {
    code: 9106,
    message: "Missing X-Auth-Key, X-Auth-Email or Authorization headers"
    }
  ]
}
```

**Comment by AlexRMU** [comment]
wrangler 1.13.0

**Comment by LumpKim** [comment]
I am experiencing the same issue while using 1.15.0 version in WSL2. When I run the `wrangler login` command, the API key is issued from the browser, but it stops at `Validating credentials...` and a timeout error occurs.

**Comment by johanwestling** [comment]
> I am experiencing the same issue while using 1.15.0 version in WSL2. When I run the `wrangler login` command, the API key is issued from the browser, but it stops at `Validating credentials...` and a timeout error occurs.
> 
> ```
> Error: error sending request for url (https://api.cloudflare.com/client/v4/workers/token): operation timed out
> ```

I've seen the same things with `wrangler dev` on 1.15.1 on WSL2 when using on specific wifi network. And it's not like the wifi itself is specifically slow/bad (measured 180/76 Mbits from https://speed.cloudflare.com/ on the same network) and all other sites works fine. Only wrangler having issues connecting.

**Comment by yerol** [comment]
Same issue trying to deploy 718Kb script on Windows 10 (not bash). Wrangler version 1.16.1.

`Built successfully, built project size is 729 KiB.
Error: error sending request for url (https://api.cloudflare.com/client/v4/accounts/6fc7e....e23/workers/scripts/fidsy): operation timed out`

On the same wifi, same wrangler version, same code deploys almost instantly when I use my mac.

**Comment by johanwestling** [comment]
Seems like this is related to Windows network adapters but for some reason shows up an issue mainly in wrangler... I did the following and got things to work again with wrangler:

1. Run powershell/cmd as administrator.
1. Run: `wsl --shutdown`.
1. Run: `netsh winsock reset`.
1. Run: `netsh int ip reset all`.
1. Run: `netsh winhttp reset proxy`.
1. Run: `ipconfig /flushdns`.
1. Hit <kbd>WIN<kbd> + <kbd>Q<kbd>.
1. Enter `Network Reset`.
1. Restart.
