### ISSUE TITLE
Critical: Error: Number of keys to delete (16010) exceeds max of 10000

### ISSUE THREAD

**Issue by simplenotezy** [cloudflare/wrangler#1398]
#### Environment

* operating system:
* output of `rustc -V`: rustc 1.41.0
* output of `node -v`: v10.20.1
* output of `wrangler -V`: wrangler 1.9.2
* contents of `wrangler.toml`:

```
name = "jwr-nuxt"
type = "webpack"
account_id = "0de41866465843875a6d452ca5bd6e1f"
workers_dev = false
route = "thejewelleryroom.com/*"
zone_id = "5323273892234c0ce2ebcd182644e8fb"
kv-namespaces = [
	{ binding = "REDIRECTS", id = "a79e38aac1fe464f99a8e8fc75d2b16f" }
]
[site]
bucket = "dist"
entry-point = "workers-site"

[env.beta]
name = "jwr-nuxt-beta"
entry-point = "workers-site-beta"
bucket = "dist"
route = "beta.thejewelleryroom.com/*"
kv-namespaces = [
	{ binding = "REDIRECTS", id = "a79e38aac1fe464f99a8e8fc75d2b16f" }
]
```

#### Steps to reproduce

Running wrangler publish

#### What did you expect to see?

Should publish

#### What did you see instead?

    Error: Number of keys to delete (16010) exceeds max of 10000

This is pretty critical. Our site is currently down because I by mistake published our beta site to production, and now I cannot publish our production site anymore.

**Comment by simplenotezy** [comment]
I had to manually delete the whole namespace then reupload to get site up and running

**Comment by EverlastingBugstopper** [comment]
hey @simplenotezy - sorry for the inconvenience here. does this still happen with the latest version of wrangler? 1.10.1 is out and has some changes around this behavior

**Comment by simplenotezy** [comment]
Yeah I am unfortuantely. And it happens every re-deploy now.

```
 Deployed to the following routes:
thejewelleryroom.com/* => stayed the same
Error:  Code 10012: bulk remove keys: 'received 31905 keys, but max allowed per request is: 10000'
 Run `wrangler kv:namespace list` to see your existing namespaces with IDs
```

**Comment by ashleymichal** [comment]
i see  where the bug lies. will correct asap.

**Comment by simplenotezy** [comment]
Great news!
