### ISSUE TITLE
wrangler tail verbosity level is Too High

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1420]
seems to be printing out all cloudflared logs that are usually hidden behind `-v`. not sure what's going on, dont think it's a regression on our side since 1.9.2 is also behaving that way. pretty sure cloudflared release changed something with their output streams. currently investigating

**Comment by bradyjoslin** [comment]
This must be why `wrangler tail | jq` hasn't been working for me - realize it started after I recently updated `cloudflared`.  I'm also not sure how to download a previous version of `cloudflared`.

**Comment by ashleymichal** [comment]
hey! this bit us too, so we asked cloudflared to revert their logging. i think we should still send their stdout stream to /dev/null the way we do with  their stderr stream, but in the meantime this should be solved for users by updating to the latest version of cloudflared.

**Comment by ashleymichal** [comment]
> i think we should still send their stdout stream to /dev/null the way we do with their stderr stream
