### ISSUE TITLE
[dev] apollo-cloudflare-server having issue with wrangler dev/publish depending on local schema size

### ISSUE THREAD

**Issue by ecerroni** [cloudflare/wrangler#1435]
Originally mentioned [here](https://github.com/cloudflare/wrangler/issues/1047#issuecomment-651682704)

Requiring a local json file and passing it to makeRemoteExecutableSchema works differently depending on the json file size:

small => wrangler dev works | wrangler publish works
medium => wrangler dev does not work | wrangler publish works (it might not deploy at first, but you have to retry)
big => wrangler dev does not work | wrangler publish does not work (script always times out)

In all the above cases the built project size is always < 1MB

This has been difficult to debug. The root cause of the issue could be anything, even not related to wrangler. Any help would be appreciated.

Reproducing [repo](https://github.com/ecerroni/issue-wrangler). Instructions are in the README.md

**Comment by signalnerve** [comment]
hey @ecerroni - just so i can understand, can you drop the file sizes of each schema in this issue? my first instinct here is that something related to adding a big file into the workers bundle, and maybe not specifically related to the workers graphql project. let me know and we can continue to debug. thanks!
