### ISSUE TITLE
Incorrect error line numbers in wrangler dev

### ISSUE THREAD

**Issue by kentonv** [cloudflare/wrangler#1459]
#### Environment

* operating system: Linux
* output of `rustc -V`: rustc 1.43.1 (8d69840ab 2020-05-04)
* output of `node -v`: v12.18.2
* output of `wrangler -V`: wrangler 1.10.3
* contents of `wrangler.toml`

#### Steps to reproduce

1. Write a script containing a syntax error.
2. Run `wrangler dev`.
3. Send a request to the local server.

#### What did you expect to see?

```
SyntaxError: missing ) after argument list
    at worker.js:135:54
```

#### What did you see instead?

(in red)

```
Uncaught
SyntaxError: missing ) after argument list
```

No line number is reported.

#### More details

The inspector protocol produces a message like this:

```
{
  "method": "Runtime.exceptionThrown",
  "params": {
    "timestamp": 0,
    "exceptionDetails": {
      "exceptionId": 1,
      "text": "Uncaught SyntaxError: missing ) after argument list",
      "lineNumber": 134,
      "columnNumber": 54,
      "url": "worker.js"
    }
  }
}
```

Looks like it's a matter of pulling the line number out and reporting it?

**Comment by jspspike** [comment]
Should be fixed [here](https://github.com/EverlastingBugstopper/chrome-devtools-rs/pull/46). Will put up a PR to update dependency once this gets merged.

**Comment by jspspike** [comment]
Seems like the line and column numbers provided in that devtools message are incorrect. Probably need to use sourcemap to solve this issue.

**Comment by EverlastingBugstopper** [comment]
they seem to even be incorrect for vanilla javascript uploads w/o webpack.... not sure whats going on there

**Comment by johnomeara1** [comment]
2022 Update: Doesn't work for imported modules

Here's an example:
![image](https://user-images.githubusercontent.com/80555253/210293880-d9e9894a-998f-40fa-b830-79989e28faab.png)

My imported file doesn't even have more than 100 lines...
