### ISSUE TITLE
"Fatal: error in validating input" with rustwasm-worker-template

### ISSUE THREAD

**Issue by CoolOppo** [cloudflare/wrangler#1474]
#### Environment

* operating system: Windows
* output of `rustc -V`: rustc 1.45.1 (c367798cf 2020-07-26)
* output of `node -v`: v14.1.0
* output of `wrangler -V`: wrangler 1.10.3
* contents of `wrangler.toml`: Default contents after running `wrangler generate my-app https://github.com/cloudflare/rustwasm-worker-template`

#### Steps to reproduce

1. Run `wrangler generate my-app https://github.com/cloudflare/rustwasm-worker-template`
2. (Optional to reproduce bug) Fill in `account_id` in `wrangler.toml`
3. Run `wrangler preview`

#### What did you expect to see?
I expected to be able to preview the Hello World.

#### What did you see instead?
Massive error output too large to paste from wasm compilation, followed by:

```
Fatal: error in validating input
Error: failed to execute `wasm-opt`: exited with exit code: 1
  full command: "C:\\Users\\me\\AppData\\Local\\.wasm-pack\\wasm-opt-171374efd61df962\\wasm-opt.exe" "C:\\Users\\me\\OneDrive\\Desktop\\my-app\\pkg\\my_app_bg.wasm" "-o" "C:\\Users\\me\\OneDrive\\Desktop\\my-app\\pkg\\my_app_bg.wasm-opt.wasm" "-O"
To disable `wasm-opt`, add `wasm-opt = false` to your package metadata in your `Cargo.toml`.
Error: tried running command:
cmd /C C:\\Users\\me\\AppData\\Local\\.wrangler\\wasm-pack-0.9.1\\wasm-pack.exe build --target no-modules
exited with exit code: 1
```

Note that even if I put `wasm-opt = false` under my `[package]` section in `Cargo.toml`, `wasm-opt` is still run.

**Comment by ispivey** [comment]
I ran in to this today as well. It looks like this is caused by https://github.com/rustwasm/wasm-pack/issues/886 , which is explored more in https://github.com/WebAssembly/binaryen/issues/3006 . 

If you're just getting started, you can add this to your `Cargo.toml`:

```toml
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```

That disables running the `wasm-opt` optimization step, which will at least get you unblocked. Should be more news or an upstream change to unblock you by Monday.

**Comment by CoolOppo** [comment]
Thanks for the response @ispivey, much appreciated. You're definitely right as I just installed Ubuntu in a VM and it happens there as well.

**Comment by CoolOppo** [comment]
Just thought of something: It would be helpful if the error output said specifically to put `wasm-opt = false` under `[package.metadata.wasm-pack.profile.release]` in case an upstream error occurs in the future.
