### ISSUE TITLE
"Maximum call stack size exceeded" when installing wrangler (install-wrangler.js)

### ISSUE THREAD

**Issue by SukkaW** [cloudflare/wrangler#1481]
#### Environment

* operating system: `ubuntu-latest` from GitHub Action
* output of `rustc -V`:
* output of `node -v`: `12.8.1`
* output of `wrangler -V`: 1.10.3
* contents of `wrangler.toml`

It doesn't matter.

#### Steps to reproduce

Using [wrangler-action](https://github.com/cloudflare/wrangler-action) provided by Cloudflare, Inc.

#### What did you see instead?

![image](https://user-images.githubusercontent.com/40715044/89522173-5a594700-d813-11ea-9f56-124eee0b2338.png)

#### Other Information

I want to open a new issue at [wrangler-action](https://github.com/cloudflare/wrangler-action), but since it is `install-wrangler.js` goes wrong I believe the issue should be opened here directly.

**Comment by EverlastingBugstopper** [comment]
does this happen on newer versions of node?

**Comment by SukkaW** [comment]
@EverlastingBugstopper 

I configured my GitHub Action with `node-12.x`. And as I mentioned, when I open the issue the latest Node.js 12 is `12.8.1`.

Since `12.8.3` is out and GitHub Action back to normal, I believe the issue has been solved.
