### ISSUE TITLE
Cloudflare is too painful to be used on privacy respecting system

### ISSUE THREAD

**Issue by Kreyren** [cloudflare/wrangler#1484]
Maintainers: Please transfer this issue to an appropriate tracker.

---

## Issue

Currently it's painful to use any Cloudflare website on a system that respects privacy, because Cloudflare requires:
1. Javascript
![image](https://user-images.githubusercontent.com/11302521/89572530-81bb0e80-d829-11ea-92d5-48b44f28953c.png)
2. Cookies
![image](https://user-images.githubusercontent.com/11302521/89572687-c34bb980-d829-11ea-9c18-e50cf474529a.png)
3. hCaptcha (which needs to be passed on every cloudflare website multiple times a day)
![image](https://user-images.githubusercontent.com/11302521/89572728-d1013f00-d829-11ea-80aa-d9dc8a3fb105.png)

## Expected solution

Make it less painful to use Cloudflare services for privacy-concious people.

**Comment by EverlastingBugstopper** [comment]
we do not field general cloudflare requests in this repository, please contact customer support. thanks
