### ISSUE TITLE
wrangler kv:namespace create "MyKV" hangs on free accounts

### ISSUE THREAD

**Issue by jbeeko** [cloudflare/wrangler#1489]
#### Environment

* operating system: MacOS
* output of `rustc -V`: N/A
* output of `node -v`: v12.18.1
* output of `wrangler -V`: wrangler 1.10.3
* contents of `wrangler.toml`

```
#https://developers.cloudflare.com/workers/tooling/wrangler/configuration/

name = "cfworker"
type = "webpack"
#route = "<only needed if deploying to your domain>"
#zone_id = "<only needed if deploying to your domain>"
workers_dev = true

webpack_config = "webpack.config.js"
```

#### Steps to reproduce

* create a free account
* configure `wrangler` authentication
* execute `wrangler v:namespace create "MyKV"`

#### What did you expect to see?
Command complete with a notice that KV is not available on free accounts

#### What did you see instead?
Command hangs, no response for over 30 seconds. The same command on a paid account returns quickly.

**Comment by nataliescottdavidson** [comment]
Hey @jbeeko, I wasn't able to reproduce this. This is my output:
```
nat@C02DD4J1MD6R jsworkerkvfree % wrangler kv:namespace create "mykv"
🌀  Creating namespace with title "jsworker-mykv"
⚠️  Code 10026: your account is not entitled to use this method
🕵️  Workers KV is a paid feature, please upgrade your account (https://www.cloudflare.com/products/workers-kv/)
```
