### ISSUE TITLE
Some access to KV Store on free accounts when deploying to preview using wrangler dev

### ISSUE THREAD

**Issue by jbeeko** [cloudflare/wrangler#1490]
#### Overview and problem statement

I am writing a blog post on how to get started with workers using F# and Fable the JS transpiler. Part of the post discusses KV. Because KV is not available for free accounts is no way for readers to follow along without a paid account. If there was access to KV, even if only on a preview deploy, it would be more likely users will try things out.

**Comment by koeninger** [comment]
We're definitely aware that some form of access to free KV is a desired feature.

Thanks for working on an F# / Fable post, feel free to ping me if I can be of assistance.

**Comment by jbeeko** [comment]
@koeninger Thanks for your offer. That post is up here https://github.com/jbeeko/cfworker-web-api. 

On a related note, I read your blog post on Worker language support and noticed you are taking PRs for language support templates. If I submit a PR for FSharp will it be considered?

**Comment by koeninger** [comment]
Nice, I shared that blog post internally.

A template for F# would be great.

**Comment by jbeeko** [comment]
@koeninger Bit of a pushy ask here and feel free to ignore it. The FSharp community will be hosting another Applied F# Challenge. I'd like to do something with Durable Objects but have not heard back on my Beta application. Do you know who I can follow up with?
