### ISSUE TITLE
Make `--host` in `wrangler dev` use unauthenticated instead of ignoring argument

### ISSUE THREAD

**Issue by jspspike** [cloudflare/wrangler#1494]
### 💡 Feature request

Currently if you pass `--host` to `wrangler dev` while authenticated it will just ignore it since it makes sense to use the host provided in the `wrangler.toml`. Instead it should run unauthenticated dev using the provided host.

**Comment by SupremeTechnopriest** [comment]
Why is this desirable?  It breaks testing with KV stores because you cant use them in unauthenticated mode.

**Comment by sordina** [comment]
I'd also like to know how to test against an arbitrary upstream (specified by --host or some other way) with wrangler dev and still be authenticated so I can use KV like @SupremeTechnopriest .
