### ISSUE TITLE
wrangler tail - no logs

### ISSUE THREAD

**Issue by oligirling** [cloudflare/wrangler#1503]
#### Environment

* operating system: **macOs**
* output of `rustc -V`: n/a
* output of `node -v`: **v13.6.0**
* output of `wrangler -V`: **1.10.3**
* contents of `wrangler.toml`:
```
name = "cloudflare-worker-staging"
type = "webpack"
account_id = "..."
workers_dev = true
route = ""
zone_id = "..."
kv-namespaces = [
    ....
]

[env.production]
name = "cloudflare-worker"
kv-namespaces = [
    ...
]
```

#### Steps to reproduce
Running `wrangler tail` doesn't seem to do anything for me. I have tested this for an endpoint that is working, and an endpoint that is throwing an exception, nothing gets printed to my console.
I have also tried logging my production env but again the same, no logs. I have tried another terminal and still nothing.
I am in the correct directory when running the command 
I have installed cloudflared and wrangler to the latest version this morning, so i don't believe its that.

#### What did you expect to see?
Logs

#### What did you see instead?
Nada
<img width="734" alt="Screenshot 2020-08-15 at 12 37 06" src="https://user-images.githubusercontent.com/42932986/90311588-42a94f00-def4-11ea-8dfe-0a189d6e84a3.png">
<img width="617" alt="Screenshot 2020-08-15 at 12 45 43" src="https://user-images.githubusercontent.com/42932986/90311657-45f10a80-def5-11ea-924d-085e4a769312.png">

**Comment by mdjx** [comment]
Ensure that you don't already have something running on localhost on ports 8080 or 8081. I had the same issue with `wrangler tail` and it was due to another service using port 8081. 

You can specify a custom port with `wranger tail --port xxxx`

**Comment by oligirling** [comment]
> Ensure that you don't already have something running on localhost on ports 8080 or 8081. I had the same issue with `wrangler tail` and it was due to another service using port 8081.
> 
> You can specify a custom port with `wranger tail --port xxxx`

Looks like this was it! Thanks!
