### ISSUE TITLE
[dev] rewrite redirect responses to local server

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1508]
if wrangler dev gets a redirect response AND the redirect is to the same zone the worker is running on, make the request go to wrangler dev again (i think)... might be a little weird, we want to make sure we dont allow something that we dont allow in production

**Comment by kokarn** [comment]
This seems to still be an issue I believe. 

After wrangler publish, I can no longer test my worker on localhost. It instead redirects to another worker in prod

**Comment by Rizary** [comment]
Hi, I'm using `wrangler 1.15.0` and I have the same issue with @kokarn 

is there any way to quick fix to this? or should I target the `*.dev` url?
