### ISSUE TITLE
Support publish with a large amount of assets

### ISSUE THREAD

**Issue by simplenotezy** [cloudflare/wrangler#1511]
When deploying large sites it takes quite a while to publish a site. It would be really cool if there was a way to split out on multiple threads so upload could run faster. Is this possible, or perhaps already on the backlog?

E.g. the publish time is the same when running on a 2 core server vs a 8 core server, and it would be nice to be able to take advantage of available server resources

**Comment by lumebug** [comment]
I believe the way static site hosts like Netlify handle this is by hashing the files first and only uploading the ones that have changed
