### ISSUE TITLE
🌊    I'm leaving Cloudflare

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#1515]
Hey y'all.

It is with a heavy heart that I'm announcing my departure from Cloudflare - today is my last day. I've absolutely loved working with the Workers community and I'm really excited to see what everyone builds with the platform we've created together. 

Before I leave, I'm cutting a release of one last version of Wrangler which brings a bunch of new features to `wrangler dev` and should really provide a good experience for any developer on our platform. Wrangler's not going anywhere and I'm fully confident that the project is in good hands, so please keep watching this space! 

You can follow me on [GitHub](https://github.com/EverlastingBugstopper) or [Twitter](https://twitter.com/SmoothAsSkippy) if you'd like to keep up with what I'm working on. 

So long and thanks for all the fish
Avery

**Comment by ispivey** [comment]
Closed with status "changelog - BREAKING MY HEART"
