### ISSUE TITLE
npm install -g @cloudflare/wrangler Error: EACCES: permission denied, mkdir

### ISSUE THREAD

**Issue by JasonCoombs** [cloudflare/wrangler#1517]
### 🐛 Bug Report

NOTE:
  Please fill out each section below before submitting your 🐛 bug report.

  Before opening a new issue, please:
  * search for existing issues: https://github.com/cloudflare/wrangler/issues
  * make sure you are using the latest release: https://workers.cloudflare.com/docs/quickstart/updating-the-cli/

BUG REPORT TEMPLATE PROBLEM:

404 NOT FOUND on https://workers.cloudflare.com/docs/quickstart/updating-the-cli/

#### Environment

* operating system: macOS 10.15.5 (output of sw_vers -productVersion)
* output of `rustc -V`: rustc 1.45.2
* output of `node -v`: v14.8.0
* output of `wrangler -V`: 👷 ✨  wrangler 1.11.0 (after successful installation)
* contents of `wrangler.toml`

#### Steps to reproduce

1. install nodejs using binary package installer, e.g. `https://nodejs.org/en/download/`
2. `$ sudo npm install -g @cloudflare/wrangler`
3. fake success message:

```
Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.11.0/x86_64-apple-darwin
wrangler has been installed!
+ @cloudflare/wrangler@1.11.0
updated 1 package in 5.075s
```

4. attempt to verify successful installation: `$ wrangler -V`

```
Error: spawnSync /Users/jasoncoombs/.wrangler/bin/wrangler ENOENT
    at Object.spawnSync (internal/child_process.js:1070:20)
    at spawnSync (child_process.js:602:24)
    at Binary.run (/usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/binary-install/src/binary.js:131:20)
    at run (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:39:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /Users/jasoncoombs/.wrangler/bin/wrangler',
  path: '/Users/jasoncoombs/.wrangler/bin/wrangler',
  spawnargs: [ '-V' ]
}
```

5. google "Error: spawnSync wrangler"
6. read [https://github.com/cloudflare/wrangler/issues/803](https://github.com/cloudflare/wrangler/issues/803)
7. down the rabbit hole to #803 

[https://github.com/cloudflare/wrangler/issues/803#issuecomment-678593003](https://github.com/cloudflare/wrangler/issues/803#issuecomment-678593003)

8. install nvm
9. ```
$ nvm ls
->      v14.8.0
         system
default -> node (-> v14.8.0)
node -> stable (-> v14.8.0) (default)
stable -> 14.8 (-> v14.8.0) (default)
```

10. `$ nvm install node`

```
Downloading and installing node v14.8.0...
Downloading https://nodejs.org/dist/v14.8.0/node-v14.8.0-darwin-x64.tar.xz...
############################################################################################################### 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v14.8.0 (npm v6.14.7)
Creating default alias: default -> node (-> v14.8.0)
```

11. verify nvm version of npm instead of system-install:

```
$ which npm
/Users/jasoncoombs/.nvm/versions/node/v14.8.0/bin/npm
```

12. try again to npm install -g (note: no longer requires sudo but [probably?] nvm doesn't truly install wrangler globally):

```
$ npm install -g @cloudflare/wrangler
/Users/jasoncoombs/.nvm/versions/node/v14.8.0/bin/wrangler -> /Users/jasoncoombs/.nvm/versions/node/v14.8.0/lib/node_modules/@cloudflare/wrangler/run-wrangler.js

> @cloudflare/wrangler@1.11.0 postinstall /Users/jasoncoombs/.nvm/versions/node/v14.8.0/lib/node_modules/@cloudflare/wrangler
> node ./install-wrangler.js

Downloading release https://workers.cloudflare.com/get-npm-wrangler-binary/1.11.0/x86_64-apple-darwin
wrangler has been installed!
+ @cloudflare/wrangler@1.11.0
added 34 packages from 21 contributors in 3.732s
$ wrangler -V
👷 ✨  wrangler 1.11.0
```

13. SUCCESS

#### What did you expect to see?

wrangler global installation successful using system nodejs installation from global binary package installer

#### What did you see instead?

wrangler installation failed with `npm ERR! code ELIFECYCLE`

mandatory requirement for nvm (not explained in the documentation, not found in searching known Issues)

**Comment by MHuiG** [comment]
sh: 1: node: Permission denied

解决这个问题的方法如下

npm config set user 0
npm config set unsafe-perm true

**Comment by ScottSmith95** [comment]
As a new user to Cloudflare Workers, this really threw me for a loop. It's only in this thread that I've found nvm is a requirement. I use n to manage node versions so it's a bit of a pain too.

**Comment by iandelahorne** [comment]
This bit us really hard for our CI containers, which just install nodejs and don't use nvm. We had to resort to installing wrangler via cargo which was a bit of a pain.

**Comment by xortive** [comment]
closing since it looks like the docs PR has been merged to recommend nvm as part of onboarding on the docs site.

@iandelahorne I think #1780 may be of interest to you, which allows you to configure exactly where you want to install wrangler which should be useful for CI.
