### ISSUE TITLE
Cannot proxy from react dev server to workers

### ISSUE THREAD

**Issue by dgitq** [cloudflare/wrangler#1521]
Hello! I use react when developing locally and the connection is refused when proxying from local react dev server to localhost:8787 instance started with 'wrangler dev'?

package.json in my react app has: "proxy": "http://localhost:8787"

Proxy error: Could not proxy request /api/test from localhost:3000 to http://localhost:8787.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

I am running "wrangler 1.10.2"

Here is a link to react documentation that describes this process: https://create-react-app.dev/docs/proxying-api-requests-in-development

Thanks

**Comment by dgitq** [comment]
Is anyone @Cloudflare reading the issues anymore, now that EverlastingBugstopper has left?

**Comment by rita3ko** [comment]
hey @dgitq — we still read and triage the issues, but haven't had as much bandwidth to look into them. from a quick glance this does seem like a CORS issue, though the CRA docs say the "proxy" feature is intended specifically to avoid them, so would need to spend some looking into it.

**Comment by dgitq** [comment]
Good to hear @rita3ko, that you are still reading the issues that is. :) Yes it's definitely a CORS issue, thats why the proxy feature exists so that we don't have to explicitly deal with CORS in a dev environment since this will not occur in production if everything is served from the same host and port.

**Comment by dgitq** [comment]
Just realised that "CORS issue" might be a tad ambiguous. The "proxy" feature is used to avoid having CORS issues when developing. And if I add explicit CORS handling in the code I can develop locally. I am guessing that here is something in your backend preventing the proxy feature from connecting.

Here is another thread of others having the same issue and needing to bypass this by explicitly handling CORS just to be able to develop locally: https://github.com/cloudflare/wrangler/issues/1262

Thanks

**Comment by dgitq** [comment]
Any updates?

**Comment by nataliescottdavidson** [comment]
Closing as duplicate, update on #1262
