### ISSUE TITLE
When `wrangler dev` throws an error, it would memory leak after been killed

### ISSUE THREAD

**Issue by alsotang** [cloudflare/wrangler#1542]
#### Environment

* operating system: macos 10.15.6 (19G2021)
* output of `rustc -V`:
* output of `node -v`: v14.8.0
* output of `wrangler -V`: 1.11.0
* contents of `wrangler.toml` 

```
name = "wall"
type = "webpack"
account_id = "xxxxx"
workers_dev = true
route = ""
zone_id = ""
```

#### Steps to reproduce

1. Run `wrangler dev` in my worker project
2. Change some files and rust would throw some error said like `senderror`. Files watch would not work.
3. Then I `ctrl+c` the process, but the node process is still running.

#### What did you expect to see?

Last night I restart many times when I use `wrangler dev`. It didn't work continually. Most of the problem is wrangle can not watch my file changes then I should manually restart it. And there is a certain rust error showed in the console.

```
thread '<unnamed>' panicked at '--watch change message failed to send: "SendError(..)"', src/wranglerjs/mod.rs:110:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When I `ctrl+c` the node process, I think it is truly **exit** 

#### What did you see instead?

This morning, 3 nodejs process are still running. `ps xua` show they are just like `wrangler dev`

**Comment by nataliescottdavidson** [comment]
@xtuc Could we be spawning multiple node processes?

**Comment by nelsonjchen** [comment]
I have a similar issue on WSL2 too as well.
