### ISSUE TITLE
Confusing/incorrect documentation for `--host` CLI argument

### ISSUE THREAD

**Issue by TehShrike** [cloudflare/wrangler#1545]
### 🐛 Bug Report

This sentence doesn't make sense to me: https://github.com/cloudflare/wrangler/blob/7798fb04242fc58e8e58c98087bd40b04a126134/src/main.rs#L514

> Host to forward or requests to

What is that `or` supposed to be?

This is important to me because I feel like I don't have a good mental model for when `wrangler dev` calls my local code versus proxies request straight through to the production workers deployed to the server, and I was hoping that digging into the `host` options might clear that up.

The grammatical typo is reproduced in the published documentation at https://developers.cloudflare.com/workers/cli-wrangler/commands#dev

#### Steps to reproduce

```sh
wrangler help dev
```

#### What did you expect to see?

A sensical sentence

#### What did you see instead?

> Host to forward or requests to

**Comment by ashleymichal** [comment]
this is a typo for sure! will queue it up as an easy fix
