### ISSUE TITLE
NaCl helper process running without a sandbox!

### ISSUE THREAD

**Issue by kcantrel** [cloudflare/wrangler#1549]
#### Environment
* operating system: Ubuntu 20.04.1
* output of `rustc -V`: Command 'rustc' not found,
* output of `node -v`: v10.19.0
* output of `wrangler -V`: wrangler 1.11.0
* contents of `wrangler.toml`

name = "cache_in_kv"
type = "javascript"
account_id = "553a8af51bbbbf2bec5832e148064499"
workers_dev = false
route = "*api.lonestar.org/api/pricecheck/*"
zone_id = "21d8970ff158935f37066da894b7f094"

kv_namespaces = [ 
	{ binding = "cache", id = "020223dd80e640dba5c2cd0098bb8d60", preview_id = "020223dd80e640dba5c2cd0098bb8d60" }
]

#### Steps to reproduce
Just upgrade to wrangler 1.11.0

#### What did you expect to see?
$ wrangler preview
⚠️  Specifying the same KV namespace ID for both preview and production sessions may cause bugs in your production worker! Proceed with caution.
💁  JavaScript project found. Skipping unnecessary build!

#### What did you see instead?
$ wrangler preview
⚠️  Specifying the same KV namespace ID for both preview and production sessions may cause bugs in your production worker! Proceed with caution.
💁  JavaScript project found. Skipping unnecessary build!
[0908/122712.424494:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly

#### Notes:
I had issues installing the latest version. If I tried to install it as a normal user (using: npm install -g @cloudflare/wrangler), it would complain that I didn't have write access to various directories in /usr/local/lib. If I "sudo -i" first, it would, oddly enough, complain that I didn't have write access to '/root/.wrangler'. I would have to set the mode of 'root' home directory to 7777 to get past that. However, even after that finished, since wrangler looks for the executable in ~/.wrangler/bin, going back to the normal user it wasn't executing the appropriate version of wrangler. So, to get it where I could do the upgrade for the normal user, I had to modify the permissions to all the directories and files in /usr/local/lib that wrangler wanted to updated to 775, and change the group to 'sudo' since I knew I had that group as well. Once I did that, I got a clean install, but I'm getting the above error.

**Comment by kentonv** [comment]
Hi @kcantrel,

This message is printed by Chrome. I see it whenever I run Chrome from the command line on Linux:

```
$ google-chrome-beta 
Opening in existing browser session.
[0908/152303.061170:ERROR:nacl_helper_linux.cc(308)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
```

So this isn't really a Wrangler issue. Arguably Wrangler could redirect Chrome's output to `/dev/null`, though that might hide real errors. Not sure what's the best answer here.

> I had issues installing the latest version. If I tried to install it as a normal user (using: npm install -g @cloudflare/wrangler), it would complain that I didn't have write access to various directories in /usr/local/lib. If I "sudo -i" first, it would, oddly enough, complain that I didn't have write access to '/root/.wrangler'.

I suspect this has to do with passing the `-i` flag to sudo. That tells sudo that you not only want root privileges, but that you want to "log in as root", which among other things changes your home directory to `/root`, leading wrangler to try to install there. I think `sudo npm install -g @cloudflare/wrangler` should have done the right thing. Sorry about the confusion.

**Comment by kcantrel** [comment]
HI @kentonv,

Thanks for the info. Any idea why the earlier version of wrangler (1.10) did not cause this error message to appear? Also, do you know that I can safely ignore this "error"? It does appear as though the "preview" still works as expected.

Thanks!
