### ISSUE TITLE
Option to continue serving old resources

### ISSUE THREAD

**Issue by AngusMorton** [cloudflare/wrangler#1553]
Currently, it seems like when you deploy a Worker Site, if users are still on the 'previous version' and they request a resource they may not get it. For example, `UserScreen.abcd.js` becomes `UserScreen.efgh.js`, in a release, users who haven't loaded the new index.html will continue to reference the old JS files and so might request them after the new version has been released.

When deploying a Cloudflare Worker Site, we want to continue to serve older files (that aren't overwritten) for some configurable period of time.

How I imagine this working:
* New Unique files (e.g. with a content hash built-in like the ones built by create-react-app) would get added.
* Non-unique files (e.g index.html) would replace the existing resource.
* Files were 'removed' would be given an expiration date of some configurable time in the future.

We're seeing this issue in practice where users are requesting resources that no longer exist even though our index.html is served with a browserTTL of 0.

**Comment by ashleymichal** [comment]
off the cuff, i'd say this requires that kv-asset-handler falls back to just requesting things by path if they are not in the asset manifest; that said we'd need some way to key old things in kv  to the path. i think we can use kv expiration ttls to keep things from sticking around longer than desired.

**Comment by AngusMorton** [comment]
> this requires that kv-asset-handler falls back to just requesting things by path if they are not in the asset manifest

Would it be possible to merge the old and new asset manifests? That way kv-asset-handler behaviour remains the same except that it might request a resource that has expired so it would 404 at that point (I imagine?).

Would you consider an RFC for this? and if the RFC is approved an implementation?

**Comment by ashleymichal** [comment]
@AngusMorton i would love an RFC for this; one constraint to keep in mind is that the asset manifest size is part of the 1MB total size limit on the worker bundle; i've alternatively toyed around with an idea for storing a massive merged asset manifest in kv as a "backup". would love any ideas you have!

**Comment by dmitryyankowski** [comment]
Bumping this up as well! I'd love to see this implemented soon (if possible). The only issue i'm having is what the OP explained. I use Workers Sites, however sometimes there's an issue where users will refresh and get a newer `index.html` file, however for some reason the assets within this file don't exist (for whatever reason). I'd like to be able to keep the older files around for say `x` amount of days until they are deleted (the files older than x date will be deleted on the next deploy).

**Comment by dlucian** [comment]
I vote for this too, any PWA runs into ChunkLoadError issues because older chunks are not available when a new release is done. We have this situation as well and the only workaround that I see is forcing an app reload whenever a ChunkLoadError occurs, which is not ideal.

**Comment by dmitryyankowski** [comment]
With the announcement of Cloudflare "Pages" https://pages.cloudflare.com, look's like i'll be switching that that once my invite is approved :) Each deployment get's it's unique URL, and it's own unique set of static assets, so this is great news! 😃

**Comment by WesCossick** [comment]
We'd be very interested in this functionality at our company (commenting to prevent this issue from going stale).

**Comment by bompus** [comment]
I believe for this to be implemented well, the KV API would need to support updating an existing KV pair with an expiration.

Then, instead of wrangler's sync function bulk deleting the old (stale) assets, it could bulk update all those that didn't already have an expiration to add an expiration of 7 days (configurable?) from the current date.

**Comment by threepointone** [comment]
This was fixed in the latest wrangler; it now doesn't delete older resources _at all_. We'll make the situation better soon so you don't overflow kv, but this is a good solution for now imo.
