### ISSUE TITLE
Running `wrangler publish` does not publish anything

### ISSUE THREAD

**Issue by simplenotezy** [cloudflare/wrangler#1565]
#### Environment

* operating system:
* output of `rustc -V`: rustc 1.43.0
* output of `node -v`: v10.20.1
* output of `wrangler -V`: 👷 ✨  wrangler 1.11.0

#### Wrangler.toml

	name = "my-site-default"
	type = "webpack"
	account_id = "some_id"
	workers_dev = false
	route = "somedomain.com/*"
	zone_id = "some_zone"
	kv-namespaces = [
		{ binding = "REDIRECTS", id = "some_id", preview_id = "some_id" }
	]
	[site]
	bucket = "build"
	entry-point = "workers-site"

	[env.beta]
	name = "my-site-beta"
	entry-point = "workers-site-beta"
	bucket = "build"
	route = "beta.somedomain.com/*"
	kv-namespaces = [
		{ binding = "REDIRECTS", id = "some_id", preview_id = "some_id" }
	]

	[env.production]
	name = "my-site"
	entry-point = "workers-site"
	bucket = "build"
	route = "somedomain.com/*"
	kv-namespaces = [
		{ binding = "REDIRECTS", id = "some_id", preview_id = "some_id" }
	]

#### Steps to reproduce

1) I run `wrangler publish` inside my `build` folder.
2) Then I use `rsync -auv someIncrementalBuildFolder/ build/` to merge changes inside build/ folder (`someIncrementalBuildFolder` contains some new pages that needs to be added / replaced on worker site)
3) Then I run `wrangler publish` again. It finishes 43 seconds - but when I request the route that was added, I get a 404.
4) I verified that the route I am requesting does exist inside `build/` folder.

#### What did you expect to see?
I would expect a 200 status code along with the contents.

#### What did you see instead?
I got a 404.

**Comment by simplenotezy** [comment]
Not sure how this bug actually happend.

I notice that inside my /build/ folder there is no `worker.js` file as there is in `/dist/` (dist was usually my go to, but I have just changed to `/build/` and changed `bucket` to `build`).

Maybe it is related to changing the `bucket` configuration in wrangler?

**Comment by simplenotezy** [comment]
Upon debugging further, I wanted to test to clear the whole KV namespace and then rerun wrangler publish. So I deleted the namespace, and ran wrangler publish again. It then said: `🌀  Created namespace for Workers Site "__jwr-nuxt-beta-workers_sites_assets"` and I see the namespace in the dashboard. However, nothing happens after that. Rerunning it again it says `🌀  Using namespace for Workers Site "__jwr-nuxt-beta-workers_sites_assets"` no keys are in. But site is still being served.

What am I missing here?

**Comment by simplenotezy** [comment]
Maybe related? https://community.cloudflare.com/t/wrangler-claims-to-successfully-publish-but-doesnt-actually-update-workers/128316/4

**Comment by simplenotezy** [comment]
Hoping it could help to rename the KV name (name = "something-unique"), but it didn't

**Comment by simplenotezy** [comment]
I tried running with `--verbose`, but it seems as though that argument has been removed. It's funny, because the publish command use to output, e.g. "Routes stayed the same", but it sems to never get that far, and instead halt at `🌀  Using namespace for Workers Site "__jwr-nuxt-beta-workers_sites_assets"`

**Comment by simplenotezy** [comment]
Sorry, I don't want to stress this / you @ispivey, but I am eager to find a solution so I can continue deploying with my otherwise beloved Wrangler <3

Any temporary solutions / workarounds I can try would be greatly appreciated.

**Comment by simplenotezy** [comment]
This is how it looks:
![wrangler publish failing](https://user-images.githubusercontent.com/3786627/93929364-0a2f3900-fd1c-11ea-917a-2ac04af2b6f9.gif)

**Comment by simplenotezy** [comment]
Ok, so I have just tested locally, and there it works fine. It's only on our deployment server it silently fails.

**Comment by simplenotezy** [comment]
I have tried uninstalling wrangler completely, then re-install, but that did not help either

**Comment by simplenotezy** [comment]
Not sure what went wrong, but I decided to start from scratch:

1) Created new user
2) Installed nvm as is the recommended way to use wrangler
3) Installed everything
4) Ran wrangler publish
5) Everything works fine.

Still curious what went wrong though.

**Comment by ashleymichal** [comment]
i'm really glad you got this working @simplenotezy ! i'm going to close this for now, but if you end up reproducing the bug, we'll be happy to look into it 😄 !

**Comment by erzr** [comment]
Sorry to dig this back up but I'm having issues with files + KV as well.

I set up a new site `wrangler generate --site my-site` and tried publishing it:

```
C:\Code\my-site>wrangler publish --verbose
 Built successfully, built project size is 13 KiB.
 Using namespace for Workers Site "__my-site-workers_sites_assets"
 Success
 Uploading site files
 Successfully published your script to
 https://my-site.aelamarre.workers.dev
```

Nothing seems to get deployed though: https://my-site.aelamarre.workers.dev
