### ISSUE TITLE
Improving the Rust debugging experience

### ISSUE THREAD

**Issue by vladinator1000** [cloudflare/wrangler#1575]
### 💡 Feature request

I got super excited to try Workers with Rust, but the development experience could use some love. If you try to do something real, like parsing the request body for example:
```rs
#[wasm_bindgen]
pub fn graphql(val: &JsValue) -> String {
    let serde_result = val.into_serde::<GraphQLRequest<DefaultScalarValue>>();

    "hello".to_string()
}
```

If something panics, you'll see something like this:
```
Uncaught (in promise)
RuntimeError: unreachable
    at <anonymous>:wasm-function[611]:0x58f23
    at <anonymous>:wasm-function[1146]:0x69762
    at <anonymous>:wasm-function[1228]:0x6a65c
    at <anonymous>:wasm-function[884]:0x63a72
    at <anonymous>:wasm-function[106]:0x2abd3
    at graphql (<anonymous>:wasm-function[855]:0x62bfc)
    at __exports.graphql (worker.js:104:14)
    at handleRequest (worker.js:199:20)
Uncaught (in response)
Error: internal error
```

The only way to debug this for me was to rewrite my code and match on the result and return the error as a string.

```rs

#[wasm_bindgen]
pub fn graphql(val: &JsValue) -> String {
    let serde_result = val.into_serde::<juniper::GraphQLRequest<juniper::DefaultScalarValue>>();

    match serde_result {
        Ok(value) => "hello".to_string(),
        Err(error) => error.to_string(),
    }
}
```
Now we get
```
invalid type: string "{\"query\":\"{\\n  currentUser {\\n    name\\n  }\\n}\\n\"}", expected struct GraphQLRequest at line 1 column 61
```

While I see there is no magic in the wasm stuff I feel like this is very frustrating to debug, because the worker is in JS and you're bound to send stuff from it to Rust. :( Essentially you have to test your program totally separately with wildcard strings as input before you attempt to run it in a worker. Is it possible to somehow return the nice error stack trace in the wasm error logs?

**Comment by ashleymichal** [comment]
@vladinator1000 this is definitely a good issue; unfortunately it is a cross-platform one that, iiuc, wrangler alone cannot address. i am linking this issue in internal runtime development circles, but i'll have to close it as something this team cannot give. if we see something go on the roadmap about this, we'll update this thread. if i have misunderstood your ask, feel free to comment further.

**Comment by vladinator1000** [comment]
Sounds great Ashley <3, also I wouldn't be mad if I could entirely skip the JS bit and upload workers entirely in Rust
