### ISSUE TITLE
Download your Project

### ISSUE THREAD

**Issue by evanspy1** [cloudflare/wrangler#1576]
#### Overview and problem statement

Sometimes I will not put my project on GitHub or some other version control scheme and then I need to access and work on it from another computer, so I wish there was a "wrangler download" command that would grab and download the latest version of your project and put it in a folder.

**Comment by nataliescottdavidson** [comment]
Hey @evanspy1 - version control isn't part of wrangler or workers. I'd recommend using a git based version control scheme locally, and a trusted remote server on github or other provider. We are currently building around github workflows.
