### ISSUE TITLE
Mini-RFC: 'wrangler dash'

### ISSUE THREAD

**Issue by ObsidianMinor** [cloudflare/wrangler#1577]
A real pain point I've found with using wrangler and the dash is that there isn't a clean and easy way to get from the CLI to the dash quickly. This is sometimes necessary if you want to see analytics or past events with cron triggers (or if a new feature has come out that doesn't have support in wrangler yet).

For that I propose `wrangler dash`, a command that simply navigates directly to the dash page for your uploaded worker.

### Example usage
```
$> wrangler dash
```
This would open your default browser and navigate to the worker dash page.

You may also pass a `--url` parameter to print the URL we would navigate to instead.
```
$> wrangler dash --url
https://dash.cloudflare.com/{{account ID}}/workers/view/{{worker name}}
```

If the worker hasn't been published, we could navigate to where the worker would be or just display an error after making a check to see if it actually exists.
```
$> wrangler dash
🛑 This worker hasn't been uploaded yet and doesn't have an associated dash page!
```

If we're not in a project directory we would simply state that we need to be in one.
```
$> wrangler dash
🛑 'wrangler dash' must be called in a project directory!
```

**Comment by ashleymichal** [comment]
i think this is cool and a nice quality of life improvement! i do think we may need to go straight to the workers list, or include a flag for the one you want / env you want.
