### ISSUE TITLE
Wrangler Installation Issues with MacOS

### ISSUE THREAD

**Issue by Dextario** [cloudflare/wrangler#1590]
### 🐛 Bug Report

I am trying to install Cloudflare's Wrangler to my VS Code.

When I go into my VS Code and use` npm i @cloudflare/wrangler -g` all goes well with the installation.  However, when I attempt to do wrangler as a command it tells me `zsh: command not found: wrangler` . I am not sure how I can fix this. I've tried a lot of different things online and scoured Cloudflare's resources for an answer, but to no avail.  

#### Environment

* operating system: MacOS
* output of `rustc -V`: zsh: command not found: rustc
* output of `node -v`: v12.19.0
* output of `wrangler -V`: zsh: command not found: wrangler - This is my issue
* contents of `wrangler.toml` zsh: command not found: wrangler.toml

#### Steps to reproduce 

Anytime I attempt to use wrangler my zsh will write back command not found wrangler.

**Comment by 0xbkt** [comment]
It seems like your `$PATH` does not include the path to globally installed Node.js executables.

See `npm help folders`.

**Comment by Electroid** [comment]
(You can follow that issue thread, we're working on a fix!)
