### ISSUE TITLE
Retry API requests

### ISSUE THREAD

**Issue by matthew-plusprogramming** [cloudflare/wrangler#1591]
#### Environment

* operating system: Windows (Ubuntu WSL 2)
* output of `rustc -V`: command not found
* output of `node -v`: v12.18.3
* output of `wrangler -V`: 👷 ✨  wrangler 1.11.0

#### Steps to reproduce

There are no steps I took to produce this error. The difference in the environment between when this was working as wasn't is my internet speed is slightly slower (still at a very good speed) and my computer has been restarted since the last time I used wrangler.

Just yesterday, `wrangler dev` (and all commands that queried the cloudflare api) were working. Today I'm getting this error:

```
wrangler dev 
💁  JavaScript project found. Skipping unnecessary build!
Error: error sending request for url (https://api.cloudflare.com/client/v4/accounts/ACCOUNT_ID_IS_HERE/workers/subdomain/edge-preview): error trying to connect: operation timed out
```
I have tested querying this API with postman & curl and the API is responding normally. I have attempted to uninstall and reinstall both node and wrangler. I have even attempted to downgrade both versions to no avail. I have no idea why every wrangler command keeps timing out. My current network speed from speedtest-cli is 30.59Mbit/s download & 15.53Mbit/s upload

**Comment by matthew-plusprogramming** [comment]
Any and all troubleshooting help would be appreciated. I'm currently working on my cloudflare internship interview take-home assignment which I hopefully can finish up sooner rather than later. I'll keep posting any updates as they come

**Comment by matthew-plusprogramming** [comment]
I seem to have found the issue. I guess that it was timing out due to my network being too slow. Upon switching back to my old network with a download speed of 61.82 Mbit/s and upload speed of 20.30 Mbit/s as opposed to 30.59 Mbit/s and 15.53 Mbit/s respectively wrangler commands started working again. I still would consider this some sort of issue as in both cases I had a fairly fast internet connection.

**Comment by Electroid** [comment]
Sometimes there are network errors, it seems though, that `wrangler` is not currently retrying. It probably should, so updated this issue to reflect that.

**Comment by jackmawer** [comment]
I'm receiving the same error, but I'm not certain if my issue is related. I'm running Wrangler 1.12.2 under WSL.

**Comment by RuslanZavacky** [comment]
Same error under WSL as @jackmawer

**Comment by Adamlb** [comment]
I also don't seem to be able to use wrangler from wsl2. I can from windows fine, and can curl the cloudflare api from wsl2 fine, but am having the same connection timeout issues.
