### ISSUE TITLE
Error: could not download `wasm-pack` Access is denied. (os error 5)

### ISSUE THREAD

**Issue by jerryc05** [cloudflare/wrangler#1593]
#### Environment

* operating system: Win 10 (not WSL)
* output of `rustc -V`: `rustc 1.49.0-nightly (3525087ad 2020-10-08)`
* output of `node -v`: `v14.13.1`
* output of `wrangler -V`: `wrangler 1.11.0`
* contents of `wrangler.toml`
```
name = *omitted*
type = "rust"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

```

#### Steps to reproduce

Run `wrangler preview --watch` in `cmd`.

#### What did you expect to see?
No err

#### What did you see instead?
```
  Installing wasm-pack v0.9.1...
Error: could not download `wasm-pack`
Access is denied. (os error 5)
```

Also, I have this problem #1504 as well. I got over it by `wrangler init` and then clone the repo manually.

### Edit:
I installed Node.js later, but wasm still does not work well under Win10.

**Comment by sarsamurmu** [comment]
Maybe this - https://github.com/rustwasm/wasm-pack/issues/727#issuecomment-752938070

**Comment by xtuc** [comment]
Could you please run the command with `RUST_LOG=debug command...` and paste the output?

**Comment by jerryc05** [comment]
@xtuc Sorry I uninstalled wrangler on Windows and installed it on WSL. Maybe we can leave this open and see if anyone faced the same issue
