### ISSUE TITLE
Use regex to validate account_id or zone_id are valid hex

### ISSUE THREAD

**Issue by realandrewyang** [cloudflare/wrangler#1598]
#### Environment

* operating system: WSL (Linux) on Windows 10
* output of `rustc -V`:
```
Command 'rustc' not found, but can be installed with:

sudo apt install rustc
```
* output of `node -v`: v14.13.1
* output of `wrangler -V`: 👷 ✨  wrangler 1.11.0
* contents of `wrangler.toml`
```
name = "andrew-app"
type = "webpack"
account_id = "<REDACTED-EMAIL>"
workers_dev = true
```

#### Steps to reproduce

1. Obtain global API key
2. Run `wrangler config`
Output of 2:
```
💁  Validating credentials...
✨  Successfully configured. You can find your configuration file at: /home/andrew/.wrangler/config/default.toml
```
3. Run `wrangler publish`

#### What did you expect to see?
Successful build, go to andrew-yang.workers.dev and see a static site I loaded through workers

#### What did you see instead?
After running 3, I see
```
✨  Built successfully, built project size is 1004 bytes.
Error: Something went wrong! Status: 400 Bad Request, Details {"success":false,"errors":[{"code":7003,"message":"Could not route to \/accounts\/<REDACTED-EMAIL>\/workers\/scripts\/andrew-app, perhaps your object identifier is invalid?"},{"code":7000,"message":"No route for that URI"}],"messages":[],"result":null}
```

**Comment by Electroid** [comment]
I've updated this issue to reflect the problem, `wrangler` should probably validate that your `account_id` is in a valid form (and not an email)

**Comment by realandrewyang** [comment]
Thanks for the support, I've used the correct `account_id` now
