### ISSUE TITLE
cargo install wrangler fails on Windows 10 when building openssl-sys

### ISSUE THREAD

**Issue by rfilmyer** [cloudflare/wrangler#1601]
### 🐛 Bug Report

When attempting to install `wrangler` via `cargo`, the build fails trying to install `openssl-sys` with the error:

    error: failed to run custom build command for `openssl-sys v0.9.58`

This is after attempting several tricks recommended for this issue, including:

* Building, [`vcpkg`](https://github.com/microsoft/vcpkg), installing `openssl-windows:x64-windows` and `openssl:x64-windows-static`, and running `vcpkg integrate install` as mentioned in this [StackOverflow Answer](https://stackoverflow.com/a/61921362/2856889)
* Setting the `$env:OPENSSL_DIR` and `$env:OPENSSL_STATIC` environment variables as noted in [this issue](https://github.com/sfackler/rust-openssl/issues/1086)
* Creating a trivial crate to attempt to see if `openssl` would build at all (it does, after setting the `OPENSSL_DIR` variable)

The fact that my trivial crate worked, but `cargo install wrangler` did not, leads me to believe this is more complicated than an issue simply building openssl.

#### Environment

* operating system: Windows 10 Home v2004, build 19041.546
* output of `rustc -V`: rustc 1.47.0 (18bf6b4f0 2020-10-07)
* output of `node -v`: N/A
* output of `wrangler -V`: N/A
* contents of `wrangler.toml`: N/A

#### Steps to reproduce

* run `cargo install wrangler`

(see above for attempts to resolve dependencies)

#### What did you expect to see?

wrangler being installed successfully

#### What did you see instead?

The following error and backtrace:

```
error: failed to run custom build command for `openssl-sys v0.9.58`
Caused by:
  process didn't exit successfully: `C:\Users\rdoge\AppData\Local\Temp\cargo-installGkbRYg\release\build\openssl-sys-1f3c263b0b6ff8c9\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\Users\\rdoge\\AppData\\Local\\Temp\\cargo-installGkbRYg\\release\\build\\openssl-sys-ce609b8cb30f92bf\\out\\openssl-build\\install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\rdoge\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.12.0+1.1.1h\src\lib.rs:411:39
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
     1: core::panicking::panic_fmt
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\panicking.rs:85
     2: core::option::expect_none_failed
               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\option.rs:1221
     3: core::result::Result<T,E>::unwrap
     4: openssl_src::Build::build
     5: openssl_src::Build::build
     6: build_script_main::find_vendored::get_openssl
     7: build_script_main::env::{{closure}}
     8: build_script_main::find_openssl::{{closure}}
     9: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wrangler v1.11.0`, intermediate artifacts can be found at `C:\Users\rdoge\AppData\Local\Temp\cargo-installGkbRYg`

Caused by:
  build failed
```

**Comment by luanraithz** [comment]
I'm also facing this issue, any workaround @rfilmyer ?

**Comment by rfilmyer** [comment]
Not really. I was able to install via NVM with no issues, but the Rust/Cargo install never worked for me.

**Comment by nataliescottdavidson** [comment]
@rfilmyer do you have perl installed on your machine? That error formatting is kind of crappy, but it's saying that it couldn't find perl.

**Comment by rfilmyer** [comment]
Apologies. I have been away from my computer for a week and will confirm tonight whether perl is installed. My instinct is no, so I will attempt to install perl and will follow up on the results.

Perl is often not installed on Windows computers so it may be good to note that as a dependency on Windows for the Rust version of the tool
