### ISSUE TITLE
Linux (wrangler publish) slows to a halt when 38000+ html files in their own folder.

### ISSUE THREAD

**Issue by Phara0h** [cloudflare/wrangler#1602]
#### Environment

* operating system:ubuntu 20.04lts
* output of `rustc -V`: none
* output of `node -v`: v14.5.0
* output of `wrangler -V`:  1.11.0
* contents of `wrangler.toml`
```
name = "XXX"
type = "webpack"
account_id = "XXX"
workers_dev = true
route = ""
zone_id = "XXX"
```
[site]
bucket = "./public"

#### Steps to reproduce

1. generate 38000+ html files that live in their own folder under public.  
2. spin up a linux instance ubuntu 20.04 (used t3a and a t5a simular results)
3. wrangler publish
4.  watch it slowly crawl to a halt 
5. process randomly stops with no error.

#### What did you expect to see?
my static webpage uploaded in a timely fashion. 
#### What did you see instead?
process randomly stops with no error.

**Comment by Electroid** [comment]
Same issue as #1511, we should find a way to speed up KV uploads.
