### ISSUE TITLE
As a Workers Sites user I'd like to upload PDF files larger than 10 MB

### ISSUE THREAD

**Issue by IlariExove** [cloudflare/wrangler#1608]
#### Overview and problem statement

Working with Workers Sites with a Bundled plan allows me to publish static web sites using Wrangler tool. One problem I've encountered with Workers Sites is that it doesn't support objects larger than 10 MB in the KV storage. Uploading PDF files larger than 10 MB fails with an error from Wrangler. If it's technically possible to implement chunked objects in the KV storage I'd be delighted to see support for objects larger than 10 MB in Workers Sites.

**Comment by GregBrimble** [comment]
Think this can probably be closed with the recent announcement that [25MB values are now supported by KV](https://blog.cloudflare.com/workers-kv-free-tier/).

**Comment by IlariExove** [comment]
Agreed.
