### ISSUE TITLE
Add element under element in htmlRewriter

### ISSUE THREAD

**Issue by yifan97** [cloudflare/wrangler#1612]
So the below handler allows us to do things with `element`. I am wondering how can we append a nested/child element to `element`?

```
class ElementHandler {
  element(element) {
    // An incoming element, such as `div`
    console.log(`Incoming element: ${element.tagName}`)
  }
}
```

**Comment by ObsidianMinor** [comment]
A child element can be appended to the end of the set of children of an element by using `append` on the element with your content. For more info, [see the docs](https://developers.cloudflare.com/workers/runtime-apis/html-rewriter#element). In the future, you can ask questions like this in the [Cloudflare Community](https://community.cloudflare.com/) under the [Workers topic](https://community.cloudflare.com/c/developers/workers/40).
