### ISSUE TITLE
Wrangler 1.12 publish destroys Worker site

### ISSUE THREAD

**Issue by HKochniss** [cloudflare/wrangler#1625]
### 🐛 Bug Report
New wrangler 1.12 destroyed our worker site in Ubuntu CI/CD Agent (and locally reproducible on Windows 10).

"destroyed" means the KV namespace is completely empty after publish, resulting in a simple "could not find index.html in your content namespace" error message when invoking the website

Switching back to wrangler 1.11 (fixing version in CI/CD pipeline) did fix the problem. So surprise, much blame!

**UPDATE** see below comment, the [env] stuff is a red herring, it also doesn't work with basically the simplest Worker site toml without any usage of `--env`.

#### Environment
* operating system(s): Windows 10 (locally)/Ubuntu Linux (Azure DevOps CI/CD)
* output of `rustc -V`: - not installed locally
* output of `node -v`: v12.16.1
* output of `wrangler -V`: wrangler 1.12.0
* contents of `wrangler.toml`

**Old toml**
```
# to be set via environment
name = "dev" 
type = "webpack"
account_id = "[some account id]"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./dist"
entry-point = "workers-site"

# environment configuration
[env.local]
name = "local"

[env.dev]
name = "dev"

[env.prod]
name = "prod"
```

**New simplified toml that stil exhibits the behavior:**
```
# to be set via environment
name = "dev" 
type = "webpack"
account_id = "[some account id]"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./dist"
entry-point = "workers-site"
```

#### Steps to reproduce
**Old toml** 
`wrangler build --env dev`
`wrangler publish --env dev`

**Newer simple toml** 
`wrangler build`
`wrangler publish`

with a built vue SPA site (or any site) that gets built to /dist directory. I suppose the content of the website nor the bucket does really matter here..

#### What did you expect to see?
Worker site not being destroyed 10 minute before customer review..

#### What did you see instead?
"could not find index.html in your content namespace"
![image](https://user-images.githubusercontent.com/1243055/97643567-5de22000-1a48-11eb-9d7f-1d55b4767ec4.png)

![image](https://user-images.githubusercontent.com/1243055/97643981-62f39f00-1a49-11eb-89c4-65a1d33321de.png)

**Comment by rita3ko** [comment]
Hey @HKochniss! Thanks for reporting this. 

We just reverted back the change we think is the culprit — please try wrangler 1.12.1 and let us know if you're still experiencing an issue — we haven't been able to repro so far.

**Comment by HKochniss** [comment]
Hrm this deeply confusing on my end.. when I run
`npm uninstall -g @cloudflare/wrangler && npm install -g @cloudflare/wrangler`

it clearly says 
```
wrangler has been installed!
+ @cloudflare/wrangler@1.12.1
added 34 packages from 21 contributors in 1.39s
```

but `wrangler -V` still returns 
 wrangler 1.12.0

SO with this "new"(?) version it still doesn't work, published assets are empty. Rolled back to 1.11 to verify it still works on that version.

**Comment by HKochniss** [comment]
Ok there might be a red herring with the --env variable

If I remove `--env` param and  I change the original name at top from "" to "wrongdeploy" and then do a simple `wrangler build` and `wrangler publish` it creates that worker, but **still with an empty KV namespace**.

So there might be something special about my payload. 

I should note that this is the customer's account and I'm an invited admin. Maybe there is some rights issue? I don't know..
I'll try the same on my personal CF account and try to get a minimal repro that I can share once I find the time today.

**Comment by nataliescottdavidson** [comment]
Hey @HKochniss, sorry that this happened. Since we weren't able to reproduce the issue, we reverted a change that seemed to be the most likely culprit. Unfortunately looks like that wasn't it. Can you send your account id to wrangler@cloudflare.com so that I can have a look at the logs to determine where this failure is coming from?

**Comment by HKochniss** [comment]
just did with subject "regarding issue 1625"

Had a busy day, will try a repro until tomorrow.

**Comment by lostpebble** [comment]
Yep, upgrading to 1.12 caused our site to stop working and return an error as well.

Downgraded to 1.11 and its working now. Also noticed the with the version not changing to 1.12.1 when doing `wrangler -V` - it still displayed `1.12.0`.

**Comment by nataliescottdavidson** [comment]
@HKochniss @lostpebble still trying to reproduce this, any chance you can share your project structure or private repo?

**Comment by erzr** [comment]
@nataliescottdavidson I'll chime in here as well. I could reproduce this with 1.12. Downgrading to 1.11 resolved the issue for me. I added some steps in what I thought could be related issue yesterday: https://github.com/cloudflare/wrangler/issues/1565#issuecomment-719057506

**Comment by ObsidianMinor** [comment]
I could reproduce this with a new generated default `site` template as well.

**Comment by HKochniss** [comment]
ok so I tried a few things:

- installed wrangler on Windows 10 via cargo, there it gives **correct 1.12.1** via `wrangler -V`, still **doesn't work**, publishs no assets
- switched to private CF Account, still **doesn't work**
- used from-scratch template via `wrangler generate --site my-site` in a worker called "dev" still **doesn't work**
- used from-scratch template via `wrangler generate --site my-site` in a worker called "test" still **doesn't work**

switching back to wrangler 1.11 does work. I really don't know what better repro steps to provide when the **standard template** approach from https://developers.cloudflare.com/workers/platform/sites/start-from-scratch doesn't work..

I would caution using the npm version right now, there really seems to be a software delivery chain problem when my npm version is not equal the rust version. Might be CF people from America fetch a wrong/old version.. 

Sorry,

**Comment by chocolatkey** [comment]
Can confirm, I was very confused. Luckily, decided to go to GitHub issues after exhausting all other options, and found this. Downgrading to 1.11 fixed it

**Comment by nataliescottdavidson** [comment]
@ all who were affected by this, sincere apologies. 1.12.1 does not have the correct fix, 1.12.2 does.

**Comment by HKochniss** [comment]
just to confirm: works now and `wrangler -V` is correctly showing 1.12.2

**Comment by revelt** [comment]
It's happening to me on Wrangler `1.19.0`, it's flakey and sometimes website ends up with "could not find index.html in your content namespace" sometimes does not. I tried downgrading to `1.11`, didn't help. But somehow, after 5th `wrangler publish` attempt, it did publish fine, I managed to delete the worker assets on Account GUI page manually, maybe that had influenced it. Website's repo in question is public, https://github.com/codsen/codsen.com

**Comment by zwily** [comment]
I just had this happen to me on `1.19.0` as well.

**Comment by revelt** [comment]
@nataliescottdavidson should we create a new issue or would you rather reopen this?

**Comment by nkostic** [comment]
This happens to me with 1.19.11 if you visit my page https://nenadkostic.com you will see that each blog entry if reloaded returns that could not find index.html page. I tried 1.11, 1.18 multiple time build publish and same result. I can not share my links to anyone right now and all links that lead to my blog posts directly not accessible. Any workaround suggestions ?

**Comment by cookmscott** [comment]
I'm having this issue in `wrangler 1.19.12` .. sad to see the flakiness of these deploys
