### ISSUE TITLE
Method to clear the worker cache via wrangler

### ISSUE THREAD

**Issue by lynchem** [cloudflare/wrangler#1628]
#### Overview and problem statement

We're using our worker as a reverse proxy but when the origin html or css changes the worker is still serving the cached version. 

#### Basic example

Our blog exists at blog.domain.com/blog but is accessed via www.domain.com/blog. When we detect any request to assets in the blog folder we make a request to the blog machine. 

```
addEventListener("fetch", event => {
    event.respondWith(handleEvent(event));
});
async function handleEvent(event) {
    ... 
    let proxyUrl = `https://${myBlog.hostname}/${targetPath}`;
    let newHeaders = new Headers(event.request.headers);
    newHeaders.set("cache-control", "no-cache");
    return fetch(proxyUrl, {headers: newHeaders});
}
```
We tried adding no-cache to the headers to stop it (doesn't work) but ideally we'd like to be able to use the cache and simply clear the cache when we make changes to the blog itself.

Is this something we should add to the wrangler CLI or there's an existing way to handle this?

**Comment by Electroid** [comment]
You can clear cache from the Cloudflare dashboard: https://support.cloudflare.com/hc/en-us/articles/200169246-Purging-cached-resources-from-Cloudflare

**Comment by lynchem** [comment]
Ok, I've since discovered my problem was with the reverse proxy and the origin apache server. Apologies for the noise.
