### ISSUE TITLE
`.ignore` files causes `wrangler publish` to skip files

### ISSUE THREAD

**Issue by winstonwolff** [cloudflare/wrangler#1652]
#### Environment

* operating system: MacOS 10.15.7
* output of `rustc -V`: rustc 1.21.0
* output of `node -v`: v12.14.1
* output of `wrangler -V`: 👷 ✨  wrangler 1.10.1
* contents of `wrangler.toml`: 
```
# See https://developers.cloudflare.com/workers/quickstart

type = "webpack"
account_id = "..."
zone_id = "..."
workers_dev = false
name = "abfinder-staging"
routes = [
    "staging.abortionfinder.org/*",
]

[site]
bucket = "build"
entry-point = "workers-site"

[env.production]
name = "abfinder-production"
routes = [
    "www.abortionfinder.org/*",
]
```

#### Steps to reproduce

- I have a `.ignore` file I use to configure `ag` (https://github.com/ggreer/the_silver_searcher) and it contains:
```
*.svg
...(more lines)...
```

- I run `wrangler publish`. I see that wrangler is publishing files, and they are mostly up on CloudFlare. However my SVG files are missing. E.g. if I go to this URL: `https://www.abortionfinder.org/static/media/icon_clock.eb8011c0.svg` I get my root index file instead.

- If I remove or comment out the `# *.svg` line, and publish again, the SVG file is now up CloudFlare.

It seems like there is an undocumented feature where `.ignore` files are read by `wrangler.` ?

#### What did you expect to see?

I would expect one of these:
- The documentation would mentioned that '.ignore' files are read.
- OR don't read them unless specified?
- OR change the name of the file so it doesn't conflict with Silver Searcher?

**Comment by ObsidianMinor** [comment]
This doesn't happen with wrangler 1.12.2, as the fix for a previous issue in the release also made the directory walker ignore `.ignore` files.
