### ISSUE TITLE
Wrangler generate running on .github directory

### ISSUE THREAD

**Issue by Scotsoo** [cloudflare/wrangler#1659]
#### Environment

* operating system: Windows, WSL2 Ubuntu
* output of `rustc -V`: -
* output of `node -v`: v14.15.0
* output of `wrangler -V`: � ✨  wrangler 1.12.2
* contents of `wrangler.toml` -

We've included a github workflow in our template, so CI is setup automatically. Looks like wrangler generate is trying to apply on the `.github/workflows/build.yml` file. Should these be omitted?
#### Steps to reproduce
Run: `wrangler generate netacea-cloudflare-worker https://github.com/netacea/cloudflare-worker-template-typescript`

#### What did you expect to see?
A successful generate
#### What did you see instead?
```
 Creating project called `netacea-cloudflare-worker`...
Error:  Error replacing placeholders `/c/Users/xx/repos/cloudflare-testing-1/netacea-cloudflare-worker/.github/workflows/build.yml`
Info: caused by liquid: Unknown variable
  with:
    requested variable=matrix
    available variables=authors, crate_name, project-name

Error: tried running command:
/home/xxx/.cache/.wrangler/cargo-generate-0.5.0/cargo-generate generate --git https://github.com/netacea/cloudflare-worker-template-typescript --name netacea-cloudflare-worker --force
exited with exit code: 1
```

**Comment by xortive** [comment]
wrangler generate is built on top of [cargo-generate](https://github.com/cargo-generate/cargo-generate), 

you can add a `cargo-generate.toml` with an include / exclude section to exclude `.github` https://github.com/cargo-generate/cargo-generate#include--exclude
