### ISSUE TITLE
wrangler secret fails with inconsistent error messages for list, put and delete

### ISSUE THREAD

**Issue by mgajda** [cloudflare/wrangler#1662]
### 🐛 Bug Report

Listing returns no secrets:
```
$ wrangler secret list
[]
```

Trying to assign secret tells the secret is already assigned:
```
$ wrangler secret put SUPERSECRET_APIKEY 
Enter the secret text you'd like assigned to the variable SUPERSECRET_APIKEY on the script named myscript-verify:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
🌀  Creating the secret for script name myscript-verify
Error: ⚠️  Code 10053: global variable SUPERSECRET_APIKEY already set
🕵️  There is already another binding with a different type by this name. Check your configuration file or your Cloudflare dashboard for conflicting bindings
```

Trying to delete secret tells there is no such thing:
```
$ wrangler secret delete SUPERSECRET_APIKEY
Are you sure you want to permanently delete the variable SUPERSECRET_APIKEY on the script named myscript-verify? [y/n]
y
🌀  Deleting the secret SUPERSECRET_APIKEY on script myscript-verify.
Error: ⚠️  Code 10056: workers.api.error.binding_not_found
🕵️
```
This is `wrangler` version:
```
👷 ✨  wrangler 1.12.2
```
#### Environment

* operating system:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

* output of `rustc -V`: this is NodeJS script only.
* output of `node -v`: `v10.19.0`
* output of `wrangler -V`: `👷 ✨  wrangler 1.12.2`
* contents of `wrangler.toml`:
```
name = "myscript"
type = "webpack"
workers_dev = true
routes = ["DOMAIN_REDACTED/subscription/form", "DOMAIN_REDACTED/subscription/add-request", "DOMAIN_REDACTED/subscription/verify*"]
account_id = "REDACTED"
zone_id = "REDACTED"

vars.SUPERSECRET = "abcdef"

vars.JWT_EXPIRATION_TTL = 1209600 # 14 Days the expiration of JWT
vars.JWT_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
vars.CSS_TEMPLATE = "/assets/style.css"
```

Same thing happens if I published a script with `vars.SUPERSECRET` and then deleted the variable from `.toml` file.

#### Steps to reproduce

Replace relevant parts of `wrangler.toml` with your key and try to repeat the steps above.

#### What did you expect to see?

That secret is absent after `wrangler secret delete`, present after `wrangler secret put` and `wrangler list` shows it when I get the error that it exists.

#### What did you see instead?

Incomprehensible errors.

**Comment by Claker** [comment]
Have the same issue. It there a solution for this?

**Comment by julien51** [comment]
same issue for us!
