### ISSUE TITLE
Code debugging with vscode using breakpoint

### ISSUE THREAD

**Issue by gilm123** [cloudflare/wrangler#1670]
### 💡 Feature request
A way to locally debug the code

#### Overview and problem statement
In every reference to the word "debug" in the documentation, i can only see ways to debug with logs.
i find myself adding a log after a log, while i just need a breakpoint.

we are developing using wrangler dev with a result of a typescript build with webpack.

**Comment by rfgamaral** [comment]
This is needed for proper development, logging to the console is the poor man's debugger, we need something better. As anyone managed to get this working, possibly with VS Code? Or this just not possible for now? 🤔
