### ISSUE TITLE
Automatically populate account/zone IDs after wrangler login

### ISSUE THREAD

**Issue by ConzorKingKong** [cloudflare/wrangler#1671]
#### Overview and problem statement

Currently, even after logging in with wrangler, you have to manually add your `account_id` to your `wrangler.toml` when generating a new project. It would be really nice to instead store the `account_id`s associated with an account when someone logs in, allow for setting a default when generating a project to put in the project's `wrangler.toml`, and then passing a flag to choose an `account_id` different than the default if the user needs to use a different stored `account_id`.

**Comment by threepointone** [comment]
In wrangler 2 you don't need to add account_id, and zone_id is inferred from routes. More info here https://github.com/cloudflare/wrangler2 Hope to get this to GA soon!
