### ISSUE TITLE
When using DefinePlugin with wrangler and webpack 5.x, Wrangler build breaks with TypeError: parser.isAsiPosition is not a function

### ISSUE THREAD

**Issue by oweikopf** [cloudflare/wrangler#1678]
### 🐛 Bug Report

After updating from webpack 4 to webpack 5, the wrangler build breaks when DefinePlugin is used and its declared variable is actually used in the js file to transform.

#### Environment

* operating system: macOS
* output of `rustc -V`: (not installed)
* output of `node -v`: v12.16.2
* output of `wrangler -V`: 👷 ✨  wrangler 1.12.2
* contents of `wrangler.toml`
name = "my-website"
type = "webpack"
account_id = "1234567890"
workers_dev = true
webpack_config = "webpack.config.js"

[env.dev]
zone_id = "xxx"
account_id = "xxx"

#### Steps to reproduce
- Clone repository: https://github.com/oweikopf/bug_wrangler_webpack_define_plugin
- execute `npm install`
- exectue `wrangler build --env dev`

#### What did you expect to see?
Wrangler executes, using the VERSION variable defined in the DefinePlugin in webpack.config.js to substitute the value in index.js

#### What did you see instead?

```wrangler build --env dev
👀  ./src/index.js
Module parse failed: parser.isAsiPosition is not a function
You may need an appropriate loader to handle this file type.
TypeError: parser.isAsiPosition is not a function
    at /Users/oweikopf/Documents/Code/Mule/test/bug_wrangler_webpack_define_plugin/node_modules/webpack/lib/DefinePlugin.js:233:18
    at SyncBailHook.eval [as call] (eval at create (/Users/oweikopf/Library/Caches/.wrangler/wranglerjs-1.12.2/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:16)
    at SyncBailHook.lazyCompileHook (/Users/oweikopf/Library/Caches/.wrangler/wranglerjs-1.12.2/node_modules/tapable/lib/Hook.js:154:20)
    at Parser.walkIdentifier (/Users/oweikopf/Library/Caches/.wrangler/wranglerjs-1.12.2/node_modules/webpack/lib/Parser.js:1893:25)
    at Parser.walkExpression (/Users/oweikopf/Library/Caches/.wrangler/wranglerjs-1.12.2/node_modules/webpack/lib/Parser.js:1512:10)
    at Parser.walkLeftRightExpression (/Users/oweikopf/Library/Caches/.wrangler/wranglerjs-1.12.2/node_modules/webpack/lib/Parser.js:1657:8)
    at Parser.walkBinaryExpression (/Users/oweikopf/Library/Caches/.wrangler/wranglerjs-1.12.2/node_modules/webpack/lib/Parser.js:1661:8)
    at Parser.walkExpression (/Users/oweikopf/Library/Caches/.wrangler/wranglerjs-1.12.2/node_modules/webpack/lib/Parser.js:1497:10)
    at Parser.walkExpressions (/Users/oweikopf/Library/Caches/.wrangler/wranglerjs-1.12.2/node_modules/webpack/lib/Parser.js:1477:10)
    at Parser.walkNewExpression (/Users/oweikopf/Library/Caches/.wrangler/wranglerjs-1.12.2/node_modules/webpack/lib/Parser.js:1739:9)
Error: webpack returned an error. Try configuring `entry` in your webpack config relative to the current working directory, or setting `context = __dirname` in your webpack config.
```

#### Additional information:
This demonstrates the issue with minimal demo setup to rule out actual project code as the culprit.
The same configuration worked without issue on webpack 4.44.2, the issue occurs after an update to webpack 5.10.1 and breaks after.
The issue does not occur with an npm build outside of wrangler, DefinePlugin substitution occurs there as expected.
Similarly, it does not occur when the variable created in DefinePlugin is not used in index.js.

**Comment by Grunet** [comment]
Not related to this project, but I ran into the same error with the same DefinePlugin substitution use case just now with [webpack-stream](https://www.npmjs.com/package/webpack-stream) and found this while searching for more info on it. 

What I eventually realized is that I was directly pulling in a v5 version of webpack and using that one's DefinePlugin option, but webpack-stream itself actually had its own v4 webpack dependency rather than using mine as a peer. Switching to use its instead solved my problem. 

So if this project has its own v4 webpack dependency ([which it seems like it might?](https://github.com/cloudflare/wrangler/blob/master/wranglerjs/package.json)) that may explain it.

**Comment by xtuc** [comment]
Thanks for the report and the repro. Wrangler isn't compatible with webpack 5 at the moment

**Comment by oweikopf** [comment]
> Thanks for the report and the repro. Wrangler isn't compatible with webpack 5 at the moment

Thanks for the information @xtuc!
Is there a plan to fix this anytime soon?
Background: My company's security policy requires us to move to webpack 5 by end of Feb due to a security issue in webpack 4.

**Comment by oweikopf** [comment]
@xtuc Sorry to nag, but can you offer any insight into if and when webpack 5 compatibility might be ensured (or whether that's even in the pipeline?)

**Comment by xtuc** [comment]
https://github.com/cloudflare/wrangler/pull/1677 will allow to specify a custom build commands and any bundlers/versions would be supported

**Comment by Electroid** [comment]
To use webpack v5, you will need to use custom [builds](https://developers.cloudflare.com/workers/cli-wrangler/configuration#build), which release in 1.16.
