### ISSUE TITLE
JS & CSS static contents not minified after deployment

### ISSUE THREAD

**Issue by symisc** [cloudflare/wrangler#1679]
Hi,

After successful deployment via wrangler of static assets to **workers KV sites**. CSS and JS assets are served as is without minification, unlike contents served from standard proxied Cloudflare. Below, the `webpack.config.js` for the deployment

`module.exports = {
context: __dirname,
  target: "webworker",
  entry: "./index.js",
  mode: "production",
  optimization: {
        minimize: true
   }
}`

Is there any plugin, commands to add for the minification process to take effect for the served static contents?

**Comment by xortive** [comment]
https://github.com/cloudflare/wrangler/pull/1833 might help with this, as you could setup a build step for your static assets.
