### ISSUE TITLE
Wrangler doesn't see local wasm-pack binaries 

### ISSUE THREAD

**Issue by theashguy** [cloudflare/wrangler#1686]
### 🐛 Bug Report

Pre-built wasm-pack binaries are not available on M1 Darwin/Arm64. You can however build them quickly using cargo and everything works fine. Unfortunately, Wrangler obstinately wants to only use pre-built binaries for some reason. A better approach would be to run with the locally available binaries, perhaps with a version check?

#### Environment

* operating system: OSX Big Surr / Apple M1 Mac
* output of `rustc -V`: rustc 1.50.0-nightly (5be3f9f10 2020-12-03)
* output of `node -v`: v15.3.0
* output of `wrangler -V`: 👷 ✨  wrangler 1.12.2
* contents of `wrangler.toml`
```
name = "rust"
type = "rust"

account_id = "KEYISHERE"
workers_dev = true
route = ""
zone_id = ""
```

#### Steps to reproduce

Install wrangler on an M1 machine using Cargo. Attempt to do any `preview` / `build` / `dev` etc and you'll be gated by wranglers internal dependency on pre-built wasm-pack binaries. It will not attempt to use locally installed binaries or try to build these itself (both of which work fine). 

#### What did you expect to see?

The command runs to completion.

#### What did you see instead?

```
⬇️   Installing wasm-pack v0.9.1...
Error: could not download `wasm-pack`
no prebuilt wasm-pack binaries are available for this platform
```

**Comment by theashguy** [comment]
Trying to work through a workaround where I manually symlink the binaries into the cache directory but I'm not sure what the expected directory format is. Wrangler uses a package called install-binaries to handle this, which generates a folder called `.wrangler` in the home directory, and then inside there a folder is created each time you download a new binary based on the name and version number of the binary. I'm just not 100% sure what this format is...

...will report back once I figure it out.

**Comment by xtuc** [comment]
have you tried with `type= "webpack"` and https://github.com/wasm-tool/wasm-pack-plugin?

**Comment by theashguy** [comment]
I have not. Will give that a go and report back.

**Comment by xtuc** [comment]
Sounds like the issue is solved. Feel free to continue to comment if we need to re-open the issue again

**Comment by nilslice** [comment]
This should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:

`npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`
