### ISSUE TITLE
Unclear errors from `wrangler dev`

### ISSUE THREAD

**Issue by viraptor** [cloudflare/wrangler#1694]
#### Environment

* operating system: macos
* output of `rustc -V`: `rustc 1.46.0 (04488afe3 2020-08-24)`
* output of `node -v`: `v14.15.1`
* output of `wrangler -V`: `wrangler 1.12.2`
* contents of `wrangler.toml`:
```
type = "webpack"
name = "service_id"
```

#### Steps to reproduce

Run `yarn wrangler dev`

#### What did you expect to see?

App starting, or a clear error.

#### What did you see instead?

> Error: No deployments specified!
> error Command failed with exit code 1.

With no link / explanation. There doesn't seem to be any mention about deployment configuration in https://developers.cloudflare.com/workers/cli-wrangler/commands#dev

**Comment by ObsidianMinor** [comment]
You need to specify either `workers_dev` or a `zone_id` with a `route` or `routes` to do a dev deployment with `wrangler dev`.

See [Configuration -> Keys](https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys).

**Comment by yet-another-dev** [comment]
I'm seeing the same error (`Error: No deployments specified!`) when trying to run `wrangler dev`. I _can_ successfully run `wrangler preview` and `wrangler publish`. This error message is super not helpful. I'm trying to run a "development" related command, why am I seeing an error mentioning "deployment"!?

**Comment by jbampton** [comment]
Not sure if this will help you.

When you run wrangler dev the code actually runs on the Cloudflare network and not on your local machine.

cloudflare/cloudflare-docs#10

https://blog.cloudflare.com/announcing-wrangler-dev-the-edge-on-localhost/

**Comment by toastal** [comment]
I agree. `No deployments specified` is not an error that gave me any useful information about needing a `zone_id` for environments.
