### ISSUE TITLE
[Low Priority] Wrangler update message has a broken documentation link

### ISSUE THREAD

**Issue by lkhrs** [cloudflare/wrangler#1695]
#### Environment

* operating system: macOS Big Sur
* output of `rustc -V`:
* output of `node -v`:
* output of `wrangler -V`:
* contents of `wrangler.toml`

#### Steps to reproduce

Run any Wrangler action while on an out of date version of Wrangler

#### What did you see instead?
<img width="604" alt="Screenshot 2020-12-22 at 19 07 53@2x" src="https://user-images.githubusercontent.com/1342461/102947653-6a538980-4489-11eb-8a6b-aff62875473a.png">

The docs link in the update message is no longer current for updating the CLI:
https://developers.cloudflare.com/workers/quickstart#updating-the-cli

The current documentation is here:
https://developers.cloudflare.com/workers/cli-wrangler/install-update#update

**Comment by xtuc** [comment]
thanks for the report. Would you mind sending a PR to fix that?

**Comment by lkhrs** [comment]
As far as I can tell from the source code, this has already been updated.
