### ISSUE TITLE
Validate non empty zone ID when doing `wrangler publish --release`

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/wrangler#170]
If a user tries to run `wrangler publish --release` without a zone ID, they get a fairly opaque message back – we should validate that the zone ID is set before hitting the API at all

```
Error: ErrorMessage { msg: "⛔ There was an error featching your project\'s routes.\n Status Code: 400 Bad Request\n Msg: {"success\":false,\"errors\":[{\"code\":7003,\"message\":\"Could not route to \\/zones\\/workers\\/routes, perhaps your object identifier is invalid?\"},{\"code\":7000,\"message\":\"No route for that URI\"}],\"messages\":[],\"result\":null}" }
```

**Comment by xtuc** [comment]
the `zone_id` is optional in the config. Not sure what the logic there, cc'ing @ashleygwilliams

**Comment by xtuc** [comment]
Can you still reproduce it on master?

**Comment by ashleygwilliams** [comment]
@xtuc if you don't do `--release` wrangler defaults to deploying to a workers.dev subdomain- which does not need a zone_id. the bug here is that wrangler does check if zone_id exists.. but zone_id is an empty string which is Some(). we need to check is_empty() not is some().

**Comment by ethereal001** [comment]
> If a user tries to run `wrangler publish --release` without a zone ID, they get a fairly opaque message back – we should validate that the zone ID is set before hitting the API at all
> 
> ```
> Error: ErrorMessage { msg: "⛔ There was an error featching your project\'s routes.\n Status Code: 400 Bad Request\n Msg: {"success\":false,\"errors\":[{\"code\":7003,\"message\":\"Could not route to \\/zones\\/workers\\/routes, perhaps your object identifier is invalid?\"},{\"code\":7000,\"message\":\"No route for that URI\"}],\"messages\":[],\"result\":null}" }
> ```

https://keyport.tv/about
