### ISSUE TITLE
console.log logs ConsoleAPICalled instead in 1.12.3

### ISSUE THREAD

**Issue by gahabeen** [cloudflare/wrangler#1707]
### 🐛 Bug Report
`console.log` doesn't log the right content but instead the ConsoleAPICalled

#### Environment
* operating system: Windows 10
* output of `node -v`: v12.16.3
* output of `wrangler -V`: wrangler 1.12.3

#### Steps to reproduce
- Update from wrangler 1.12.2 to 1.12.3
- Use Webpack type in wrangler.toml
- Write a console.log("A beautiful log") in your script
- Run it

#### Steps to fix
Downgrade from wrangler 1.12.3 to 1.12.2

#### What did you expect to see?
I expected to see the log "A beautiful log" in the console.

#### What did you see instead?
I saw "`ConsoleAPICalled(Event { type: "log", args: [RemoteObject { type: String, subtype: None, description: None, class_name: None, value: Some(String("My beautiful log")), preview: None }] })`" instead.

**Comment by evilandfox** [comment]
Any suggestions?.. wrangler is great tool, thanks to authors, but after last version upgrade it is not possible to debug using `console.log`. And a `thread 'tokio-runtime-worker' panicked` problem still appeares...

**Comment by advaith1** [comment]
I can also reproduce this with 1.13.0, downgrading to 1.12.2 fixed it

**Comment by ParadauxIO** [comment]
I'm experiencing the above, downgrading also appears to have fixed it.

**Comment by xtuc** [comment]
It looks like one of the recent versions broke the console formatting. Would you mind sending a PR? It's probably just changing how we print the log messages to the console

**Comment by nascode** [comment]
I confirmed this. Downgrading to 1.12.2 for now

**Comment by calendee** [comment]
Thanks so much @mdycz. The associated PR is #1749

**Comment by lsrugo770** [comment]
Also, the v1.12.3 or v1.13 do not show exceptions from the worker in the terminal. Downgrading to v1.12.2 fixes it
