### ISSUE TITLE
Upgrade message URL is incorrect (out of date?)

### ISSUE THREAD

**Issue by alankemp** [cloudflare/wrangler#1712]
When I ran wrangler today I got this message about upgrading:

A new version of Wrangler (1.12.3) is available!
You can learn more about updating here:
https://developers.cloudflare.com/workers/quickstart#updating-the-cli

But that link doesn't have any useful information.   I guess it should probably go to:
https://developers.cloudflare.com/workers/cli-wrangler/install-update

**Comment by thmsdnnr** [comment]
I think this link was updated to the URL you suggest in the v1.12.3 release: https://github.com/cloudflare/wrangler/commit/07e359af27282c3fe3176a9c77cd9a41345a5404

https://github.com/cloudflare/wrangler/blob/v.1.12.3/src/main.rs#L50

**Comment by Electroid** [comment]
Yes, this was fixed in https://github.com/cloudflare/wrangler/commit/07e359af27282c3fe3176a9c77cd9a41345a5404
