### ISSUE TITLE
JavaScript project fails without package.json

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler#1715]
### 🐛 Bug Report

Wrangler errors without a package.json for JavaScript projects, yet there is no reason to require it.

#### Environment

* output of `wrangler -V`: wrangler 1.12.3
* contents of `wrangler.toml`: type=javascript

#### Steps to reproduce

1. Create a hello world script with `type=javascript`
2. Run `wrangler dev` or `wrangler publish`
3. See the error `Error: Your JavaScript project is missing a package.json file`

#### What did you expect to see?

Wrangler should be able to publish a plain JavaScript project without a package.json.

**Comment by rbrishabh** [comment]
Hi @Electroid, I would like to work on this! Could you please help me get started?

**Comment by squaresmile** [comment]
For others, you need to follow [the required file layout](https://developers.cloudflare.com/workers/platform/sites/configuration/) of the `entry-point` option for worker sites.

For [my project](https://github.com/atlasacademy/apps/blob/master/packages/db-og-worker/wrangler.toml), I copy `package.json` and `package-lock.json` to the `dist` folder and change `main` in `package.json` from `dist/worker.js` to `worker.js`.
