### ISSUE TITLE
Possible bad state concerning API token

### ISSUE THREAD

**Issue by iwikal** [cloudflare/wrangler#1720]
### 🐛 Bug Report

  I installed wrangler with `cargo add wrangler`, and logged in using `wrangler login`. Then, while I was trying to troubleshoot a different issue, I also installed wrangler with `yarn global add @cloudflare/wrangler`, to see if it was any different. But when I tried to log in with this new installation of wrangler, this happened.
   - `wrangler login`
   - Browser window opens with a request for access
   - I press the confirmation button and wait for a bit
   - Browser window says it is done and can now be closed
   - I close the window
   - wrangler is still running in my terminal and just waits indefinitely for a new API token

I figure it has something to do with my two conflicting installations, so I run `yarn global remove @cloudflare/wrangler` and try the cargo version again:
```
❯ wrangler whoami
Error: ⚠️  Code 9109: Invalid access token
```
I tried running `wrangler login` again, but the same weird infinite waiting occurred. I finally resolved the problem by visiting https://dash.cloudflare.com/profile/api-tokens and re-rolling the token, and manually pasting the new token into `~/.wrangler/config/default.toml`. While typing out this issue, I tried to reproduce the behavior again from a fresh start, so I deleted my token using the web interface, deleted all of `~/.wrangler`, uninstalled wrangler, and reinstalled it. But still, the same problem occurs. `wrangler login` is now broken for me forever, it seems.

#### Environment

* operating system: Linux 5.9.14-arch1-1 x86_64
* output of `rustc -V`: rustc 1.50.0-nightly (11c94a197 2020-12-21)
* output of `node -v`: v10.23.0
* output of `wrangler -V`: 👷 ✨  wrangler 1.12.3
* contents of `wrangler.toml`: N/A

#### Steps to reproduce

Not sure. I can't get back to the original state.

#### What did you expect to see?
Either two parallel wrangler installations successfully using the same config and token, or some kind of warning.

#### What did you see instead?
See description.

**Comment by xtuc** [comment]
what are the token's permissions? you can see it on https://dash.cloudflare.com/profile/api-tokens

**Comment by iwikal** [comment]
The token was created during `wrangler login` and has the following permissions:
 - All accounts
   - Workers KV Storage: Edit
   - Workers Scripts:Edit
   - Account Settings:Read
 - All zones
   - Workers Routes:Edit
 - All users
   - User Details:Read

**Comment by PradeepSinghMakwana** [comment]
I am also seeing the wrangler not able to continue after asking for api key, even after approving the request through browser. I am running in ubuntu 20.04 livecd. I actually run npx wrangler login, because I installed it with:

npm i @cloudflare/wrangler -D
 
I do not want wrangler to be installed globally since changes in livecd global environment are not preserved. Is anything that I can try.

npx wrangler --version // wrangler 1.13.0
npm --version // 7.5.4
node --version // v14.15.1

**Comment by Electroid** [comment]
The infinite waiting during `wrangler login` is certainly an issue, and based on previous reports, I don't think multiple installations has an affect. Going to link to the original issue so we can better track and prioritize a fix: https://github.com/cloudflare/wrangler/issues/1703
