### ISSUE TITLE
Allow longer secrets

### ISSUE THREAD

**Issue by danbars** [cloudflare/wrangler#1723]
#### Overview and problem statement
wrangler secret is limited in length. Trying to store firebase private key (as an example) I have to split it into multiple parts and concatenate before using it.

Allowing longer secrets, so that common private-key (RSA/DER) can be stored, would be useful.
I believe that 2k is usually enough, but don't take my word on it.

**Comment by sarveshpro** [comment]
same issue here. I am trying to store GCP private key.

**Comment by xtuc** [comment]
I ran into that issue as well and ended up splitting the key into multiple keys, works if you use JWK

**Comment by MariusK-DV** [comment]
I ran into this as well.

**Comment by MariusK-DV** [comment]
@xtuc No and it's not a solution I necessarily want to implement

**Comment by Electroid** [comment]
Update: our intention is to increase the secret limit to 5Kib. We should have an update in the next 2ish weeks.

**Comment by rita3ko** [comment]
Hi folks! We've updated our limit to 5K now. 🎉
