### ISSUE TITLE
Installation with cargo fails on Fedora

### ISSUE THREAD

**Issue by Siilwyn** [cloudflare/wrangler#1724]
#### Environment
* operating system: Fedora 33 (Workstation)
* output of `rustc -V`: rustc 1.48.0 (7eac88abb 2020-11-16)

#### Steps to reproduce
0. Install Fedora (or use a live usb)
0. `curl -sSf https://sh.rustup.rs | sh`
0. `cargo install wrangler`

#### What did you expect to see?
Successful compilation.

#### What did you see instead?
The following error:
```
error: failed to run custom build command for `openssl-sys v0.9.60`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installApI70e/release/build/openssl-sys-60ccebb9043ad269/build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running "perl" "./Configure" "--prefix=/tmp/cargo-installApI70e/release/build/openssl-sys-8295b9fc332cbbde/out/openssl-build/install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-shared" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"

  --- stderr
  Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /usr/local/lib64/perl5/5.32 /usr/local/share/perl5/5.32 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ./Configure line 15.
  BEGIN failed--compilation aborted at ./Configure line 15.
  thread 'main' panicked at '


  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=/tmp/cargo-installApI70e/release/build/openssl-sys-8295b9fc332cbbde/out/openssl-build/install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-shared" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
      Exit status: exit code: 2


      ', /home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.13.0+1.1.1i/src/lib.rs:415:13

```

#### Workaround
Installing Perl seems to fix this issue for some reason... `sudo dnf install perl`. Would be nice if there isn't an external dependency on Perl though, maybe a dependency is using it?

##### Additional error
After running Perl and installing Wrangler running `wrangler help` does print the help message but followed with:
```
fish: “wrangler” terminated by signal SIGSEGV (Address boundary error)
thread '<unnamed>' panicked at 'Client::new(): reqwest::Error { kind: Builder, source: Normal(ErrorStack([])) }', /home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/blocking/client.rs:618:38
stack backtrace:
```

Even when running with `RUST_BACKTRACE=1` it does not print a backtrace, not sure how related this issue is, might need a new seperate ticket?

**Comment by xtuc** [comment]
wrangler doesn't depend directly on perl, however `openssl-sys` seems to require it. Since it's caused by a dependecy, would you mind opening a issue there instead?

**Comment by Siilwyn** [comment]
@xtuc Ah I see, we are talking about [this project](https://github.com/sfackler/rust-openssl) right?
What would you propose to them to change? Don't think they can 'include' perl as a dependency...

A silly question perhaps too but I see `rustls` being used why does `wrangler` also need `openssl-sys`, don't they achieve the same goal?

**Comment by xtuc** [comment]
Isn't `openssl-sys` a dependecy of `rustls`?

**Comment by Siilwyn** [comment]
As far as I know not, the whole point of `rustls` is that it's 100% written in Rust and so doesn't need system libs.
Looking at the dependencies on the crate page also does not list `openssl-sys`: https://crates.io/crates/rustls

**Comment by xtuc** [comment]
I just noticed wrangler itself depends on openssl: https://github.com/cloudflare/wrangler/blob/master/src/commands/dev/tls/certs.rs#L1-L10

**Comment by Siilwyn** [comment]
Ah okay!
