### ISSUE TITLE
RFC: KV put with metadata

### ISSUE THREAD

**Issue by ags799** [cloudflare/wrangler#1734]
### 💡 Feature request

Perform a [KV put with metadata](https://developers.cloudflare.com/workers/runtime-apis/kv#metadata) from Wrangler:
```
wrangler kv:key put my-key my-value --metadata '{"some": "json"}'
```
Any kind of JSON works:
* boolean
* number
* object
* array
* strings

**Comment by xtuc** [comment]
> accept almost any kind of JSON [...] not strings though

does it mean
```
wrangler kv:key put my-key my-value --metadata '1'
```
is supported but not
```
wrangler kv:key put my-key my-value --metadata '"json"'
```

**Comment by ags799** [comment]
Yes.

**Comment by koeninger** [comment]
Why?  Doing e.g. the following from a worker is fine:

        await NS.put(key, value, {metadata: "some_string"})

**Comment by xtuc** [comment]
I was asking if we disallow a string insisde an object or a string instead an object, so we would disallow:
```sh
    await NS.put(key, value, "some_string")
```

but not
```js
    await NS.put(key, value, 1)
```
?

**Comment by koeninger** [comment]
the third argument isn't metadata, it's an options object that may contain a metadata key.  See   https://developers.cloudflare.com/workers/runtime-apis/kv#metadata  and https://github.com/cloudflare/workers-types/blob/master/index.d.ts#L610

  My example above would result in 

        const { value, metadata } = await NS.getWithMetadata(key);

binding metadata to "some_string", not {metadata: "some_string"}

**Comment by xtuc** [comment]
Indeed, thanks for clarify. I hidden my comment since it's not relevant

**Comment by ags799** [comment]
> Why? Doing e.g. the following from a worker is fine:
> 
> ```
>     await NS.put(key, value, {metadata: "some_string"})
> ```

Never mind, I wasn't escaping quotes correctly in my curl command. The API will accept strings just fine.
