### ISSUE TITLE
Failure to parse wrangler.toml gives confusing error

### ISSUE THREAD

**Issue by chrislange** [cloudflare/wrangler#1737]
### 🐛 Bug Report

This bug appears to be related to the action itself within GitHub when it's trying to deploy. I cannot get it to complete successfully and it fails every time at the below (line 16).

![image](https://user-images.githubusercontent.com/4365169/104826983-3e8dae80-5851-11eb-8871-7b5061ec95f8.png)

This is my `main.yml` file for the action.

![image](https://user-images.githubusercontent.com/4365169/104827000-5c5b1380-5851-11eb-8f14-1af0fba84d1a.png)

**Comment by xtuc** [comment]
I suspect the error comes from your wrangler.toml that doesn't parse. Could you please post your wrangler config here (remove the secret things)?

**Comment by xortive** [comment]
while this is likely a user configuration problem, we should do better about surfacing toml parse errors in a way that the user can figure out what the problem is and fix it themselves
