### ISSUE TITLE
Wrangler Serves Incomplete / Corrupted PDF Files 

### ISSUE THREAD

**Issue by willbicks** [cloudflare/wrangler#1746]
### 🐛 Bug Report

I started a discussion on the CF community forum about an issue I'm having with PDF files served by Wrangler being corrupted when accessed from a Chrome browser. Here is a link to that thread, which unfortunately didn't go far: https://community.cloudflare.com/t/pdfs-downloaded-from-cfworkers-wrangler-corrupted/238857/3

To summarize, I’m in the process of finishing up a site that it hosted by Wrangler on Cloudflare Workers, and I’m having an issue with PDFs that are embedded on the site. For whatever reason, the PDF file becomes corrupt after you refresh the page a few times. This is only an issue that occurs when the PDF is served by CF, and doesn’t happen when hosted locally or by a server running Apache.

The full pdf is only about 400kb, which I would think is well within the acceptable size range for workers to deliver. In addition, the issue also occurs with a smaller PDF that is only 200kb. It seems to be more reliable on desktop browsers, but on both Chrome for Windows and Chrome for Android after enough refreshes the worker stops delivering the full file and instead delivers a corrupted file that is only 25kb, and the contents when viewed with a hex editor are only the last bits of the actual file. My most recent two tests on both Windows and Android have seen this issue arise after only one refresh, but in the past it has taken many more. This has been replicated on multiple environments, and the steps to do so are below.

In the workers dashboard there have been zero errors in the last 24 hours.

#### Environment

* using cloudflare/wrangler-action@1.2.0 on GitHub Actions
* contents of `wrangler.toml`
```
name = "willbicks-hugo"
type = "webpack"
account_id = "XXXXXXXXXXXXXXXXXXXXXX"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.staging]
zone_id = "XXXXXXXXXXXXXXXXXXXXXX"
routes = ["www-twenty.willbicks.com/*", "twenty.willbicks.com/*"]
vars = {ENFORCE_BASEURL = "https://www-twenty.willbicks.com", ENFORCE_CODE = 301}
```

#### Steps to reproduce

To replicate the issue you can try visiting this page, which has the embeds on it, on Chrome for Windows or Android. https://www-twenty.willbicks.com/projects/crow-research/ You should notice it work perfectly the first time, but if you refresh enough times it will stop working and give a red corrupted file warning. Once it’s stopped working, you can copy the direct url to the PDF (https://www-twenty.willbicks.com/projects/crow-research/2021-01-22_Methods_for_Counting_Roosting_Birds.pdf) and paste it in a new browser tab, and you’ll get the corrupted partial file from the cloudflare worker. I tried this on my phone, and also had a friend with separate internet connection and separate phone try it, and he encountered the exact same issue, and the corrupted 25kb file he was served had the exact same hash.

To further try and determine the source of this issue, I pushed the exact same website to a server running Apache and proxied through Cloudflare. The site running Apache works perfectly every time, but the site running on Wrangler / CF Workers serves corrupt PDFs after enough refreshes, as described above.

Here are the links to both sites:
Apache, works perfectly: https://www-twenty-apache.willbicks.com/projects/crow-research/
Wrangler / CF Worker, breaks after a few refreshes: https://www-twenty.willbicks.com/projects/crow-research/

When you clear the browser cache the issue disappears initially, but again after enough refreshes it returns.

#### What did you expect to see?

The embedded viewer should correctly show the PDF file, and when accessed via the direct URL the complete PDF should be downloaded.

#### What did you see instead?

After enough refreshes, the PDF viewer gets a corrupted copy of the PDF file with only the last ~25kb, and displays [a red warning message](https://drive.google.com/file/d/1z4_tZe6MoF6SLjXJLFgFpyPSfFDGv_5d/view?usp=sharing). In addition, when accessed by the [direct URL to the PDF](https://www-twenty.willbicks.com/projects/crow-research/2021-01-22_Methods_for_Counting_Roosting_Birds.pdf), the [downloaded file is corrupted](https://drive.google.com/file/d/1QdARyEyAKjkSutTY2P7YlGBWp-PqF1cr/view?usp=sharing) and contains only the last 25kb of the full file.

**Comment by harrishancock** [comment]
This seems like a kv-asset-handler issue, filed a bug report here: https://github.com/cloudflare/kv-asset-handler/issues/165

I'm going to close this one, because there's not much wrangler devs can do about this.
