### ISSUE TITLE
Wrangler publish outputs to stderr instead of stdout

### ISSUE THREAD

**Issue by jamestgot** [cloudflare/wrangler#1747]
#### Environment

* operating system: Linux mint
* output of `rustc -V`: None
* output of `node -v`: 10.16.3
* output of `wrangler -V`: 1.13.6

* contents of `wrangler.toml` 

name = "[redacted]"
type = "webpack"
account_id = [redacted]
workers_dev = true
route = [redacted]
zone_id = [redacted]

[site]
bucket = "./www"
entry-point = "workers-site"

#### Steps to reproduce

wrangler publish outputs to stderr instead of stdout.

command --> wrangler publish 2>stderr.txt
 

#### What did you expect to see?

if publish outputs to stdout, stderr.txt would be empty.

#### What did you see instead?

instead, output is in stderr.txt

**Comment by xortive** [comment]
This is intended behavior, we reserve stdout for structured output (ex. for CI), while stderr is for diagnostic output, progress reports/logging, and similar
