### ISSUE TITLE
README - Windows installation via cargo is missing external openssl dependency

### ISSUE THREAD

**Issue by Kage-Yami** [cloudflare/wrangler#1765]
### 🐛 Bug Report

For installing `wrangler` on Windows via `cargo`, the README fails to mention that `openssl` is a runtime external dependency; only `perl` is mentioned as a compile-time external dependency. 

#### Environment

* operating system: Windows 10 19042
* output of `rustc -V`: `rustc 1.50.0 (cb75ad5db 2021-02-10)`
* output of `node -v`: _Not installed_
* output of `wrangler -V`: _Reported error shows_ / `wrangler 1.13.0` after fixing
* contents of `wrangler.toml` _N/A_

#### Steps to reproduce

1. Install `rustup` - https://rustup.rs/
2. Install `scoop` - https://scoop.sh/
2. Install `perl` external dependency: `scoop install perl`
3. Install `wrangler`: `cargo install wrangler` (which succeeds)
4. Attempt to login: `wrangler login` (error appears)

The issue can be fixed by installing `openssl` external dependency: `scoop install openssl`

#### What did you expect to see?

The usual login message on the CLI:

> Allow Wrangler to open a page in your browser? [y/n]

#### What did you see instead?

This error in a popup window (screenshot attached):

> The code execution cannot proceed because libssl-1_1-x64.dll was not found. Reinstalling the program may fix this problem.

![image](https://user-images.githubusercontent.com/2202488/107842350-50da1880-6e0e-11eb-9376-3296954fe6ae.png)

**Comment by koeninger** [comment]
Starting from a fresh windows install, installing the VS C++ tools, rustup, and Strawberry Perl as recommended by https://www.perl.org/get.html works for me without having to explicitly install openssl.  Perhaps there's something about the way scoop installs perl that it doesn't include openssl?

Assuming I'm reading correctly that `scoop install openssl` worked for you, I'll add a note to the readme.

**Comment by Kage-Yami** [comment]
Yup, additionally running `scoop install openssl` did the trick for me, so that update sounds good to me. 🙂
