### ISSUE TITLE
allow custom wrangler config to wrangler dev

### ISSUE THREAD

**Issue by gilm123** [cloudflare/wrangler#1766]
### 💡 Feature request
please allow giving wrangler dev a specific wrangler toml config file, same as with publish

#### Overview and problem statement
allow giving wrangler config path to wrangler dev command.

#### Basic example
`wrangler dev -c some-folder/wranger.toml`

**Comment by Electroid** [comment]
Hey, thanks for submitting this request. Could you elaborate on why you have a seperate `toml` file just for `dev`?

**Comment by gilm123** [comment]
Hey :) yea, so we just want to be able to arrange these files in a different folder structure instead of having them at the root,
to be more specific, we got a `wrangler` folder with 
dev.toml
prod.toml
where prod.toml file is divided into 2 environment - staging/production
and dev.toml are settings to run locally

**Comment by threepointone** [comment]
I believe this works with the `--config <path>` flag now, I tried it myself and it works. I'll close this issue for now, but let me know if it doesn't work as expected.
