### ISSUE TITLE
Allow custom path to javascript file

### ISSUE THREAD

**Issue by hansottowirtz** [cloudflare/wrangler#1767]
#### Overview and problem statement

When using `target = "javascript"`, the worker file is taken from `package.json`'s `main` field. This doesn't really make sense in my case. I'm building separate worker files for each environment with Rollup (so they can be tree-shaken individually), and I'd like to put the used file path in `wrangler.toml` instead of in `package.json`.

#### Basic example

```
path = "dist/worker.js"
```

**Comment by xtuc** [comment]
Will be possible once https://github.com/cloudflare/wrangler/pull/1677 is merged

**Comment by Electroid** [comment]
Done in release 1.16, see the [build](https://developers.cloudflare.com/workers/cli-wrangler/configuration#build) section of the Workers documentation!

**Comment by hansottowirtz** [comment]
Not sure if this can be closed, it only seems to work for `build.upload.format = "modules"`. Is it possible to also enable this for the service worker format?

**Comment by threepointone** [comment]
This is a lot better in the next major version of wrangler, we have a top level `main` field in `wrangler.toml` you can point to your entry point, whether it's service worker or modules format
