### ISSUE TITLE
Having too many routes mapped causes wrangler dev to return HTTP 431

### ISSUE THREAD

**Issue by d-gagne** [cloudflare/wrangler#1768]
#### Environment

* operating system: Mac OS 10.15.7
* output of `rustc -V`: rustc 1.49.0
* output of `node -v`: v10.14.0
* output of `wrangler -V`: wrangler 1.12.2
* contents of `wrangler.toml`

name = "app"
type = "webpack"
account_id = "<redacted>"
workers_dev = true
routes = [
  "www-test.example.com/en-US/p/*", 
  "www-test.example.com/es-AR/p/*",
  "www-test.example.com/en-AU/p/*",
  "www-test.example.com/de-AT/p/*",
  "www-test.example.com/fr-BE/p/*",
  "www-test.example.com/nl-BE/p/*",
  "www-test.example.com/pt-BR/p/*",
  "www-test.example.com/en-CA/p/*",
  "www-test.example.com/fr-CA/p/*",
  "www-test.example.com/es-CL/p/*",
  "www-test.example.com/hr-HR/p/*",
  "www-test.example.com/da-DK/p/*",
  "www-test.example.com/fi-FI/p/*",
  "www-test.example.com/fr-FR/p/*",
  "www-test.example.com/de-DE/p/*",
  "www-test.example.com/en-IE/p/*",
  "www-test.example.com/it-IT/p/*",
  "www-test.example.com/es-MX/p/*",
  "www-test.example.com/nl-NL/p/*",
  "www-test.example.com/en-NZ/p/*",
  "www-test.example.com/nb-NO/p/*",
  "www-test.example.com/pl-PL/p/*",
  "www-test.example.com/pt-PT/p/*",
  "www-test.example.com/ro-RO/p/*",
  "www-test.example.com/sl-SI/p/*",
  "www-test.example.com/sv-SE/p/*",
  "www-test.example.com/en-GB/p/*",
  "www-test.example.com/en-ZA/p/*",
  "www-test.example.com/es-ES/p/*",
  "www-test.example.com/fr-CH/p/*",
  "www-test.example.com/de-CH/p/*"
]
zone_id = "<redacted>"
webpack_config = "webpack.config.js"

#### Steps to reproduce

1. wrangler dev (this works fine)
2. curl / open browser to http://127.0.0.1:8787/en-US/p/<some path here>

#### What did you expect to see?

Good response (fetch from origin)

#### What did you see instead?

HTTP/1.1 431 Request Header Fields Too Large

If you reduce the number of routes in the wrangler toml (somewhere around 15 of these), it will work.

**Comment by xtuc** [comment]
Could you instead run the worker on `www-test.example.com/*` and do the routing in the worker as a workaround?

**Comment by d-gagne** [comment]
There are many workarounds, such has having an environment just for dev with that wildcard route.

I think the proper solution would be either

- support a larger number of routes like this somehow, or
- support regex routes.

regex routes would be highly preferable in these scenarios, as the long list of routes is mostly due to locale paths.

**Comment by rita3ko** [comment]
Hey @d-gagne! We generally discourage users from having too many routes (due to how they scale currently), and would advise, as @xtuc suggested to handle the routing in the Worker (could even store them in KV). I anticipate this would have impact not just on `wrangler dev` but could impact Workers performance in general as the routing table within the zone grows. 

Going to close this ticket as the routes improvements we'd need to make to support this are not specific to wrangler, and tracked elsewhere, but this is good feedback!
