### ISSUE TITLE
Memory issue fails "silently"

### ISSUE THREAD

**Issue by simplenotezy** [cloudflare/wrangler#1769]
### 🐛 Bug Report

When `wrangler publish` runs out of memory, no error message is shown + no exit code.

#### Environment

* operating system:
* output of `rustc -V`: rustc 1.47.0
* output of `node -v`: v10.20.1
* output of `wrangler -V`: wrangler 1.13.0

#### Steps to reproduce

Have thousands of files to publish

#### What did you expect to see?
Script should fail with an exitcode + an error message should appear.

#### What did you see instead?
The gist of it is this:

	⠂   Preparing build/anpe-atelier-cph-gold-ring-in-diamonds-and-gold-sarah-lil-pink-ring-gold-white-diamonds-pi
	⠁   Preparing build/ro-copenhagen-white-earring-in-diamonds-and-whitegold-rock-square-diamond-stud-earring-m-w
	⠋   Preparing build/marie-mas-necklace-in-rosegold-long-swinging-chain-necklace-rosegold-green-malachite-and-w
	⠁   Preparing build/sif-jakobs-jewellery-earring-in-gold-plated-vulcanello-chain-earrings-gold-plated-white-zi
	root@deployer:/workspace/jwr-nuxt-production#

Our CI then thinks deploy went smooth - instead of taking ~20 minutes, it takes 2 minutes, but fails silently.

**Comment by xtuc** [comment]
How do you know it's due to a memory issue? Since wrangler invokes node/webpack we could try to increase their allowed memory.

**Comment by simplenotezy** [comment]
@xtuc I kept ranning `free -m` in a seperate terminal window. Once free memory reached close to 0, the `wrangler publish` command terminated itself. @xtuc

**Comment by xtuc** [comment]
I see, so adding more memory to node/webpack won't be helpful. I think it's unlikely to be fixed soon, any chance you can use a bigger machine for your CI?

**Comment by rita3ko** [comment]
@simplenotezy are you using Workers Sites? We've made some optimizations for how we handle this in our new product, [Cloudflare Pages](https://pages.cloudflare.com/), which is currently in beta. Happy to give you access if you email me at rita at cloudflare.com.

**Comment by simplenotezy** [comment]
@xtuc i simply added some more swap memory which solved it for now.

@rita3ko would be happy to test it out. Currently running a 10GB e-commerce store built in nuxt.js with WordPress acting as headless CMS. Build currently takes around 1 hour. So curious if it's a fit, nevertheless, I'd be happy to test out with other projects.
