### ISSUE TITLE
Incorrect Version Number

### ISSUE THREAD

**Issue by Kynson** [cloudflare/wrangler#1772]
#### Environment

* operating system: macOS Big Sur V. 12.2.1
* output of `rustc -V`: rustc 1.49.0 (e1884a8e3 2020-12-29)
* output of `node -v`: v14.15.1
* output of `wrangler -V`: wrangler 1.12.2 (This is incorrect) [Should be 1.13.0]
* contents of `wrangler.toml` N/A

#### Steps to reproduce

1. Run `npm uninstall -g @cloudflare/wrangler && sudo npm install -g @cloudflare/wrangler@latest`
2. Run `wrangler -V`

#### What did you expect to see?
Output the correct version number (1.13.0 as of 18 Feb, 2021)

#### What did you see instead?
An old version number (1.12.2)

<img width="565" alt="Screenshot 2021-02-18 at 13 26 42" src="https://user-images.githubusercontent.com/46522440/108309888-632ccb80-71ed-11eb-8e78-cd94792f13da.png">

Thank you.

**Comment by rita3ko** [comment]
Hey! Thanks for reporting this. Seems like something weird going on with our latest NPM release. Going to look into it.

**Comment by Kynson** [comment]
Hello, may I know if the issue is fixed? The issue still persist in version 1.15.0. Or it is my problem?
<img width="564" alt="Screenshot 2021-03-14 at 16 32 07" src="https://user-images.githubusercontent.com/46522440/111062413-88a6af80-84e3-11eb-8175-a8b64a10f188.png">
