### ISSUE TITLE
webpack-based worker cannot parse native bigints

### ISSUE THREAD

**Issue by armfazh** [cloudflare/wrangler#1774]
#### Environment

* operating system: ubuntu 18.04
* output of `rustc -V`: rustc 1.50.0 (cb75ad5db 2021-02-10)
* output of `node -v`: v14.15.5
* output of `wrangler -V`: 👷 ✨  wrangler 1.13.0
* contents of `wrangler.toml` 

```toml
name = "my-app"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
```

#### Steps to reproduce

```sh
 $ wrangler generate my-app https://github.com/cloudflare/worker-template-router
 $ cd my-app
 $ echo "const x = 1234567890n;" >> index.js
 $ wrangler build
```

#### What did you expect to see?

```sh
✨  Built successfully, built project size is 1 KiB.
```

#### What did you see instead?

```sh
👀  ./index.js 31:11
Module parse failed: Identifier directly after number (31:11)
You may need an appropriate loader to handle this file type.
|     return resp
| }
> const x = 1234567890n;
| 
Error: webpack returned an error. You may be able to resolve this issue by running npm install.
```

#### Workaround

You can change `1234567890n` by `Bigint("1234567890")`. However, this is suboptimal.

**Comment by Electroid** [comment]
I suspect this is because our version of webpack is still `4.x`, and the default configuration may not include the newest ECMAScript features like `BigInt` literals. 

In https://github.com/cloudflare/wrangler/pull/1677, we are adding support for custom bundlers, which should allow you to use a newer version of webpack or another bundler.

**Comment by xortive** [comment]
closing since #1677 will be going out as part of a RC in the near future (unfortunately github's neat close feature didn't work when merging into a release branch :/)
