### ISSUE TITLE
wrangler login got stuck

### ISSUE THREAD

**Issue by jimshtepa** [cloudflare/wrangler#1775]
#### Environment

* operating system:Ubuntu 20.04
* output of `rustc -V`:
* output of `node -v`: v14.15.1
* output of `wrangler -V`: 1.13.0
* contents of `wrangler.toml`:

name = "my-project"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

#### Steps to reproduce

Upon installation of wrangler and an attempt to obtain token 'wrangler login' command gets stuck with a message 'waiting for API token'

'wrangler whoami' results in following message => `Error: config path does not exist /home/ubuntu/.wrangler/config/default.toml. Try running `wrangler login` or `wrangler config``

#### What did you expect to see?
I expected to get authenticated

#### What did you see instead?
wrangler login gets stuck waiting for an API TOKEN

**Comment by Electroid** [comment]
Thanks for reporting this! Going to link to another issue, which seems to report the same issue you're having: https://github.com/cloudflare/wrangler/issues/1703
