### ISSUE TITLE
Adding new dependency cause compilation fail

### ISSUE THREAD

**Issue by ycd** [cloudflare/wrangler#1777]
#### Environment

* operating system: Arch Linux
* output of `rustc -V`: rustc 1.52.0-nightly (9b471a3f5 2021-02-19) - rustc 1.50.0 (cb75ad5db 2021-02-10)  [tested both]
* output of `node -v`: v15.9.0
* output of `wrangler -V` 1.13.0
* contents of `wrangler.toml`

```
account_id = "myaccid"
name = "somename"
route = ""
type = "rust"
workers_dev = true
zone_id = ""
```

#### Steps to reproduce

 1. Generated new project with `wrangler generate myprojectname  https://github.com/cloudflare/rustwasm-worker-template/`
 1. Added new dependency to cargo.toml `isahc = "1.1.0"`
 1. Ran `wrangler preview --watch`

Got the following output: 

```

error: aborting due to 50 previous errors

Some errors have detailed explanations: E0061, E0283, E0412, E0422, E0425, E0432, E0433, E0435, E0573.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `socket2`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Compiling your crate to WebAssembly failed
Caused by: failed to execute `cargo build`: exited with exit code: 101
  full command: "cargo" "build" "--lib" "--release" "--target" "wasm32-unknown-unknown"
Error: tried running command:
/home/ycd/.cache/.wrangler/wasm-pack-0.9.1/wasm-pack build --target no-modules
exited with exit code: 1
```

<details><summary>Previous 50 errors</summary><br><pre>

rror[E0432]: unresolved import `crate::sys`
  --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/socket.rs:25:5
   |
25 | use crate::sys;
   |     ^^^^^^^^^^ no `sys` in the root

error[E0432]: unresolved import `sys`
  --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:88:5
   |
88 | use sys::c_int;
   |     ^^^ use of undeclared crate or module `sys`

error[E0435]: attempt to use a non-constant value in a constant
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:236:33
    |
236 |             len: mem::size_of::<sockaddr_in>() as socklen_t,
    |                                 ^^^^^^^^^^^ non-constant value

error[E0435]: attempt to use a non-constant value in a constant
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:287:33
    |
287 |             len: mem::size_of::<sockaddr_in6>() as socklen_t,
    |                                 ^^^^^^^^^^^^ non-constant value

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:108:16
    |
108 |         Domain(sys::AF_INET)
    |                ^^^ use of undeclared crate or module `sys`

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:113:16
    |
113 |         Domain(sys::AF_INET6)
    |                ^^^ use of undeclared crate or module `sys`

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:146:14
    |
146 |         Type(sys::SOCK_STREAM)
    |              ^^^ use of undeclared crate or module `sys`

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:153:14
    |
153 |         Type(sys::SOCK_DGRAM)
    |              ^^^ use of undeclared crate or module `sys`

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:158:14
    |
158 |         Type(sys::SOCK_SEQPACKET)
    |              ^^^ use of undeclared crate or module `sys`

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:164:14
    |
164 |         Type(sys::SOCK_RAW)
    |              ^^^ use of undeclared crate or module `sys`

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:193:18
    |
193 |         Protocol(sys::IPPROTO_ICMP)
    |                  ^^^ use of undeclared crate or module `sys`

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:198:18
    |
198 |         Protocol(sys::IPPROTO_ICMPV6)
    |                  ^^^ use of undeclared crate or module `sys`

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:203:18
    |
203 |         Protocol(sys::IPPROTO_TCP)
    |                  ^^^ use of undeclared crate or module `sys`

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/lib.rs:208:18
    |
208 |         Protocol(sys::IPPROTO_UDP)
    |                  ^^^ use of undeclared crate or module `sys`

error[E0412]: cannot find type `sockaddr_storage` in this scope
  --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:30:14
   |
30 |     storage: sockaddr_storage,
   |              ^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `socklen_t` in this scope
  --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:31:10
   |
31 |     len: socklen_t,
   |          ^^^^^^^^^ not found in this scope
   |
help: consider importing this type alias
   |
1  | use crate::socket::net::udp::net_imp::netc::socklen_t;
   |

error[E0412]: cannot find type `sockaddr` in this scope
  --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:49:47
   |
29 | pub struct SockAddr {
   | ------------------- similarly named struct `SockAddr` defined here
...
49 |     pub unsafe fn from_raw_parts(addr: *const sockaddr, len: socklen_t) -> SockAddr {
   |                                               ^^^^^^^^
   |
help: a struct with a similar name exists
   |
49 |     pub unsafe fn from_raw_parts(addr: *const SockAddr, len: socklen_t) -> SockAddr {
   |                                               ^^^^^^^^
help: consider importing this struct
   |
1  | use crate::socket::net::udp::net_imp::netc::sockaddr;
   |

error[E0412]: cannot find type `socklen_t` in this scope
  --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:49:62
   |
49 |     pub unsafe fn from_raw_parts(addr: *const sockaddr, len: socklen_t) -> SockAddr {
   |                                                              ^^^^^^^^^ not found in this scope
   |
help: consider importing this type alias
   |
1  | use crate::socket::net::udp::net_imp::netc::socklen_t;
   |

error[E0412]: cannot find type `sockaddr_storage` in this scope
  --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:50:41
   |
47 | impl SockAddr {
   |     - help: you might be missing a type parameter: `<sockaddr_storage>`
...
50 |         let mut storage = MaybeUninit::<sockaddr_storage>::zeroed();
   |                                         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `AF_INET` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:148:38
    |
148 |         if self.storage.ss_family == AF_INET as sa_family_t {
    |                                      ^^^^^^^ not found in this scope
    |
help: consider importing this constant
    |
1   | use crate::socket::net::udp::net_imp::netc::AF_INET;
    |

error[E0412]: cannot find type `sa_family_t` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:148:49
    |
148 |         if self.storage.ss_family == AF_INET as sa_family_t {
    |                                                 ^^^^^^^^^^^ not found in this scope
    |
help: consider importing this type alias
    |
1   | use crate::socket::net::udp::net_imp::netc::sa_family_t;
    |

error[E0412]: cannot find type `sockaddr_in` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:150:72
    |
150 |             let addr = unsafe { &*(&self.storage as *const _ as *const sockaddr_in) };
    |                                                                        ^^^^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
1   | use crate::socket::net::udp::net_imp::netc::sockaddr_in;
    |

error[E0425]: cannot find value `ip` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:160:51
    |
160 |             Some(SocketAddr::V4(SocketAddrV4::new(ip, port)))
    |                                                   ^^ not found in this scope

error[E0425]: cannot find value `AF_INET6` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:161:45
    |
161 |         } else if self.storage.ss_family == AF_INET6 as sa_family_t {
    |                                             ^^^^^^^^ not found in this scope
    |
help: consider importing this constant
    |
1   | use crate::socket::net::udp::net_imp::netc::AF_INET6;
    |

error[E0412]: cannot find type `sa_family_t` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:161:57
    |
161 |         } else if self.storage.ss_family == AF_INET6 as sa_family_t {
    |                                                         ^^^^^^^^^^^ not found in this scope
    |
help: consider importing this type alias
    |
1   | use crate::socket::net::udp::net_imp::netc::sa_family_t;
    |

error[E0412]: cannot find type `sockaddr_in6` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:163:72
    |
163 |             let addr = unsafe { &*(&self.storage as *const _ as *const sockaddr_in6) };
    |                                                                        ^^^^^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
1   | use crate::socket::net::udp::net_imp::netc::sockaddr_in6;
    |

error[E0425]: cannot find value `ip` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:171:17
    |
171 |                 ip,
    |                 ^^ not found in this scope

error[E0412]: cannot find type `sa_family_t` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:187:29
    |
187 |     pub fn family(&self) -> sa_family_t {
    |                             ^^^^^^^^^^^ not found in this scope
    |
help: consider importing this type alias
    |
1   | use crate::socket::net::udp::net_imp::netc::sa_family_t;
    |

error[E0412]: cannot find type `socklen_t` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:192:26
    |
192 |     pub fn len(&self) -> socklen_t {
    |                          ^^^^^^^^^ not found in this scope
    |
help: consider importing this type alias
    |
1   | use crate::socket::net::udp::net_imp::netc::socklen_t;
    |

error[E0412]: cannot find type `sockaddr` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:197:36
    |
29  | pub struct SockAddr {
    | ------------------- similarly named struct `SockAddr` defined here
...
197 |     pub fn as_ptr(&self) -> *const sockaddr {
    |                                    ^^^^^^^^
    |
help: a struct with a similar name exists
    |
197 |     pub fn as_ptr(&self) -> *const SockAddr {
    |                                    ^^^^^^^^
help: consider importing this struct
    |
1   | use crate::socket::net::udp::net_imp::netc::sockaddr;
    |

error[E0422]: cannot find struct, variant or union type `sockaddr_in` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:215:27
    |
215 |         let sockaddr_in = sockaddr_in {
    |                           ^^^^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
1   | use crate::socket::net::udp::net_imp::netc::sockaddr_in;
    |

error[E0425]: cannot find value `AF_INET` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:216:25
    |
216 |             sin_family: AF_INET as sa_family_t,
    |                         ^^^^^^^ not found in this scope
    |
help: consider importing this constant
    |
1   | use crate::socket::net::udp::net_imp::netc::AF_INET;
    |

error[E0412]: cannot find type `sa_family_t` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:216:36
    |
216 |             sin_family: AF_INET as sa_family_t,
    |                                    ^^^^^^^^^^^ not found in this scope
    |
help: consider importing this type alias
    |
1   | use crate::socket::net::udp::net_imp::netc::sa_family_t;
    |

error[E0425]: cannot find value `sin_addr` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:218:13
    |
218 |             sin_addr,
    |             ^^^^^^^^ not found in this scope

error[E0412]: cannot find type `sockaddr_storage` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:231:41
    |
202 | impl From<SocketAddrV4> for SockAddr {
    |     - help: you might be missing a type parameter: `<sockaddr_storage>`
...
231 |         let mut storage = MaybeUninit::<sockaddr_storage>::zeroed();
    |                                         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0573]: expected type, found local variable `sockaddr_in`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:233:48
    |
233 |         unsafe { (storage.as_mut_ptr() as *mut sockaddr_in).write(sockaddr_in) };
    |                                                ^^^^^^^^^^^ not a type
    |
help: consider importing this struct instead
    |
1   | use crate::socket::net::udp::net_imp::netc::sockaddr_in;
    |

error[E0412]: cannot find type `socklen_t` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:236:51
    |
236 |             len: mem::size_of::<sockaddr_in>() as socklen_t,
    |                                                   ^^^^^^^^^ not found in this scope
    |
help: consider importing this type alias
    |
1   | use crate::socket::net::udp::net_imp::netc::socklen_t;
    |

error[E0422]: cannot find struct, variant or union type `sockaddr_in6` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:260:28
    |
260 |         let sockaddr_in6 = sockaddr_in6 {
    |                            ^^^^^^^^^^^^ not found in this scope
    |
help: consider importing this struct
    |
1   | use crate::socket::net::udp::net_imp::netc::sockaddr_in6;
    |

error[E0425]: cannot find value `AF_INET6` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:261:26
    |
261 |             sin6_family: AF_INET6 as sa_family_t,
    |                          ^^^^^^^^ not found in this scope
    |
help: consider importing this constant
    |
1   | use crate::socket::net::udp::net_imp::netc::AF_INET6;
    |

error[E0412]: cannot find type `sa_family_t` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:261:38
    |
261 |             sin6_family: AF_INET6 as sa_family_t,
    |                                      ^^^^^^^^^^^ not found in this scope
    |
help: consider importing this type alias
    |
1   | use crate::socket::net::udp::net_imp::netc::sa_family_t;
    |

error[E0425]: cannot find value `sin6_addr` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:263:13
    |
263 |             sin6_addr,
    |             ^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `sockaddr_storage` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:282:41
    |
241 | impl From<SocketAddrV6> for SockAddr {
    |     - help: you might be missing a type parameter: `<sockaddr_storage>`
...
282 |         let mut storage = MaybeUninit::<sockaddr_storage>::zeroed();
    |                                         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0573]: expected type, found local variable `sockaddr_in6`
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:284:48
    |
284 |         unsafe { (storage.as_mut_ptr() as *mut sockaddr_in6).write(sockaddr_in6) };
    |                                                ^^^^^^^^^^^^ not a type
    |
help: consider importing this struct instead
    |
1   | use crate::socket::net::udp::net_imp::netc::sockaddr_in6;
    |

error[E0412]: cannot find type `socklen_t` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:287:52
    |
287 |             len: mem::size_of::<sockaddr_in6>() as socklen_t,
    |                                                    ^^^^^^^^^ not found in this scope
    |
help: consider importing this type alias
    |
1   | use crate::socket::net::udp::net_imp::netc::socklen_t;
    |

error[E0425]: cannot find value `MSG_OOB` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/socket.rs:267:30
    |
267 |         self.inner.recv(buf, MSG_OOB)
    |                              ^^^^^^^ not found in this scope

error[E0425]: cannot find value `MSG_OOB` in this scope
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/socket.rs:335:30
    |
335 |         self.inner.send(buf, MSG_OOB)
    |                              ^^^^^^^ not found in this scope

error[E0061]: this function takes 4 arguments but 3 arguments were supplied
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/sockaddr.rs:170:33
    |
170 |             Some(SocketAddr::V6(SocketAddrV6::new(
    |                                 ^^^^^^^^^^^^^^^^^ expected 4 arguments
171 |                 ip,
    |                 --
172 |                 port,
    |                 ----
173 |                 addr.sin6_flowinfo,
    |                 ------------------ supplied 3 arguments

error[E0283]: type annotations needed
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/socket.rs:878:27
    |
878 |             inner: socket.into(),
    |                    -------^^^^--
    |                    |      |
    |                    |      cannot infer type for type parameter `U`
    |                    this method call resolves to `T`
    |
    = note: cannot satisfy `_: From<TcpStream>`
    = note: required because of the requirements on the impl of `Into<_>` for `TcpStream`

error[E0283]: type annotations needed
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/socket.rs:886:27
    |
886 |             inner: socket.into(),
    |                    -------^^^^--
    |                    |      |
    |                    |      cannot infer type for type parameter `U`
    |                    this method call resolves to `T`
    |
    = note: cannot satisfy `_: From<TcpListener>`
    = note: required because of the requirements on the impl of `Into<_>` for `TcpListener`

error[E0283]: type annotations needed
   --> /home/ycd/.cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.3.19/src/socket.rs:894:27
    |
894 |             inner: socket.into(),
    |                    -------^^^^--
    |                    |      |
    |                    |      cannot infer type for type parameter `U`
    |                    this method call resolves to `T`
    |
    = note: cannot satisfy `_: From<UdpSocket>`
    = note: required because of the requirements on the impl of `Into<_>` for `UdpSocket`
</pre></details>

#### What did you expect to see?

No error.

#### What did you see instead?

Error.

**Comment by xortive** [comment]
Hey there! Closing as this issue is not in scope for the wrangler issue tracker, but I'll try and point you in the right direction:

`isahc` (which looks to be a HTTP client library) will not work with WASM in the workers environment. WASM programs cannot directly access system resources like sockets to communicate with the outside world, they must go through Javascript. In-progress standards like (https://wasi.dev/)[WASI] hope to resolve this limitation, but unfortunately this is not possible today.

If you want to make HTTP requests from your Rust code in a Worker, you'll need to wrap the JS `fetch()` API such that you can call it from Rust.

**Comment by ycd** [comment]
Awesome, that's very nice of you, thanks @xortive!
