### ISSUE TITLE
We should have an issue template for install problems

### ISSUE THREAD

**Issue by xortive** [cloudflare/wrangler#1782]
Folks often run into #240 and end up filing an issue here. Even though we document it on the onboarding phase and in the wrangler readme, we should have a note in the bug report template, or an installer-specific template that ensures users have checked that their node/npm environment is correct before filing an installer issue

**Comment by jasikpark** [comment]
Perhaps with that adding min node/npm to the package.json would help with that? https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines
