### ISSUE TITLE
Feature request: Allow site config per environment

### ISSUE THREAD

**Issue by steverandy** [cloudflare/wrangler#1795]
#### Describe the feature

Allow [configuring site](https://developers.cloudflare.com/workers/cli-wrangler/configuration#site) for an environment.
Currently we can only configure at the top level.
I have a use case for example in development, I would like to turn off `site` and enable it only for production environment.

#### Describe the alternatives

Are there any alternatives to solving this problem? If so, what was your experience with them?
_No alternatives found._

**Comment by xortive** [comment]
I think we implemented this in https://github.com/cloudflare/wrangler/pull/1573, can you give it a try?

**Comment by steverandy** [comment]
@xortive do you know if it's possible to turn off site for `wrangler dev` and let other environments still use it.

**Comment by xortive** [comment]
I haven't tried this, but if you have a dedicated environment for `wrangler dev`, try doing `site = {}` in the environment config. If that doesn't work, then I think this would require feature work to do what you're asking for.

**Comment by steverandy** [comment]
@xortive I'm not using dedicated env for dev.
I kinda need a config like this:

```
[site]
bucket = "./public"
entry-point = "."

[dev]
site = {}
```

Is this a valid config?
