### ISSUE TITLE
Cannot find module '@cloudflare/binary-install'

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler#1811]
#### Describe the bug

When attempting to update wrangler using `npm`, it fails.

```bash
$ npm install -g @cloudflare/wrangler
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@cloudflare/wrangler
npm ERR! command failed
npm ERR! command sh -c node ./install-wrangler.js
npm ERR! internal/modules/cjs/loader.js:1083
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '@cloudflare/binary-install'
npm ERR! Require stack:
npm ERR! - /usr/local/lib/node_modules/@cloudflare/wrangler/binary.js
npm ERR! - /usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1080:15)
```

:warning: **Temporary Fix**
```bash
rm -rf /usr/local/lib/node_modules/@cloudflare/wrangler
npm install -g @cloudflare/wrangler
```

#### Reproduce the bug

1. Run `npm install -g @cloudflare/wrangler` (twice, if you haven't installed wrangler already)
2. See error

#### Environment and versions

* operating system: `macOS Mojave 10.14.6`
* output of `wrangler -V`: `1.15.0`
* output of `node -v`: `v14.8.0`
* output of `npm -v`: `7.6.1`

**Comment by xortive** [comment]
This bug perplexes me, I can trigger it updating between old versions of wrangler too... It might be a problem with npm?

**Comment by Electroid** [comment]
I tried the newest patch of `npm (7.6.4)` and it's still a problem. Here's what the directory looks like, not sure if it helps.
```bash
$ ls /usr/local/lib/node_modules/@cloudflare
wrangler
$ ls /usr/local/lib/node_modules/@cloudflare/wrangler
README.md		install-wrangler.js	npm-shrinkwrap.json	run-wrangler.js
binary.js		node_modules		package.json		uninstall-wrangler.js
$ ls /usr/local/lib/node_modules/@cloudflare/wrangler/node_modules
@cloudflare		concat-map		inflight		mkdirp			wrappy
axios			follow-redirects	inherits		once			yallist
balanced-match		fs-minipass		minimatch		path-is-absolute
brace-expansion		fs.realpath		minipass		rimraf
chownr			glob			minizlib		tar
$ ls /usr/local/lib/node_modules/@cloudflare/wrangler/node_modules/@cloudflare
binary-install
```

**Comment by bofeiw** [comment]
It also occurs in Gitlab CI in the step to install this dependency.

I found that manually specify the previous version would be a workaround while this issue is being resolved.
`- npm i @cloudflare/wrangler@1.13.0 -D`

**Comment by pavelbinar** [comment]
`rm -rf /usr/local/lib/node_modules/@cloudflare/wrangler`
did not work for me, I had to uninstall and install again:

```
npm remove -g @cloudflare/wrangler
npm install -g @cloudflare/wrangler
```

**Comment by Electroid** [comment]
Unfortunately, we found this error can still occur. It now can error with `Cannot find module 'axios'`. So it appears the error is not what we thought it to be

**Comment by nilslice** [comment]
@Electroid - we should probably move this out of the Apple Silicon  milestone, since it isn't isolated to only those devices. That way we can close up that milestone, and lump this into some general bugfix group?
