### ISSUE TITLE
No cargo-generate binary for aarch64-apple-darwin.tar.gz

### ISSUE THREAD

**Issue by mrbm** [cloudflare/wrangler#1813]
### 🐛 Bug report

https://workers.cloudflare.com/get-binary/ashleygwilliams/cargo-generate/v0.5.0/aarch64-apple-darwin.tar.gz is being referenced by the wrangler create project...but It doesn't exist.

Installed everything from scratch 4 hours ago using cargo.

#### Describe the bug

error message:
% wrangler generate --site demo-project
⬇️   Installing cargo-generate v0.5.0...
Error: could not download `cargo-generate`
failed to download from https://workers.cloudflare.com/get-binary/ashleygwilliams/cargo-generate/v0.5.0/aarch64-apple-darwin.tar.gz

#### Reproduce the bug

A list of steps to reproduce the bug.
running on: m1 MacBook Air
curl https://sh.rustup.rs -sSf | sh
source ~/.cargo/env
cargo install wrangler
(install command line tools)
cargo install wrangler
wrangler generate --site demo-site
get error:
⬇️   Installing cargo-generate v0.5.0...
Error: could not download `cargo-generate`
failed to download from https://workers.cloudflare.com/get-binary/ashleygwilliams/cargo-generate/v0.5.0/aarch64-apple-darwin.tar.gz

#### Expected behavior
 normal creation of project
#### Environment and versions
BigSur 11.2.3
wrangle 1.15.0
MacBook Air M1

**Comment by mrbm** [comment]
using home-brew:
brew install openssl@1.1

then:
echo 'export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc
export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
cargo install cargo-generate
(that installed cargo-generate 0.6)

Then reattempting to create a project gives the following errors still:
⬇️   Installing cargo-generate v0.5.0...
Error: could not download `cargo-generate`
failed to download from https://workers.cloudflare.com/get-binary/ashleygwilliams/cargo-generate/v0.5.0/aarch64-apple-darwin.tar.gz

So...I'm stuck here. Is everybody not seeing this? Did Ashley recently remove https://workers.cloudflare.com/get-binary/ashleygwilliams/cargo-generate/v0.5.0/aarch64-apple-darwin.tar.gz 
why is there reference to an old version? Is this a wrangler or a rust issue?

Thanks guys!

**Comment by Electroid** [comment]
Thanks for flagging this. This might be because https://github.com/ashleygwilliams/cargo-generate is redirecting to https://github.com/cargo-generate/cargo-generate.

**Comment by mrbm** [comment]
I spent 6hrs banging my head on this (I am new to wrangler)...while that might be part of the issue, also review this:
https://github.com/cloudflare/wrangler/blob/9f63cd067c3fd7327278538910e1e6dd5ee65e4e/src/install/mod.rs#L25

```
pub fn install_cargo_generate() -> Result<PathBuf, failure::Error> {
    let tool_name = "cargo-generate";
    let tool_author = "ashleygwilliams";
    let is_binary = true;
    let version = Version::parse(dependencies::GENERATE_VERSION)?;
    install(tool_name, tool_author, is_binary, version)?.binary(tool_name)
}
```

Is this responsible for generating the path:
https://workers.cloudflare.com/get-binary/ashleygwilliams/cargo-generate/v0.5.0/aarch64-apple-darwin.tar.gz

too_author is in your code base and then generating the install path...I am not super close to your codebase(I just thought I would be able to quickly create the Auth0 before being sucked down this rabbit hole last night)...but I am guessing this bit of code is going to be a problem.

**Comment by Electroid** [comment]
Ah.. yes, M1 support. We're still working on it, and you highlighted the issue correctly. We haven't built/uploaded the `cargo-generate` binary for M1 support yet. But it's something we're working on! #1763

**Comment by mrbm** [comment]
@Electroid indeed...

OpenSSL 1.1.1j has the M1 support and homebrew has everything ready for m1.

Could you simply make the path https://workers.cloudflare.com/get-binary/ashleygwilliams/cargo-generate/v0.5.0/aarch64-apple-darwin.tar.gz serve the file and things would be up and running? That would be a 10 minute fix till you sort out the rest. Or is there more to it?

M1 MacBooks are kinda a big thing right now, so let's get this rolling....would rather not be forced to fire up my other computer.

**Comment by mrbm** [comment]
@Electroid Hey there just checking in to see if there are any updates on this...would like to be using my new Mac! Thanks

**Comment by mrbm** [comment]
@Electroid remember the original issue was https://workers.cloudflare.com/get-binary/ashleygwilliams/cargo-generate/v0.5.0/aarch64-apple-darwin.tar.gz not existing...could you guys make that exist again?

**Comment by xortive** [comment]
@mrbm thanks for keeping up with this issue. The problem here is that cargo-generate's CI doesn't build binaries for aarch64-apple-darwin -- we had experimented with manually building these and adding them to the release after the fact (which is why 1.15.0 had one on the releases page), but I believe we ran into problems with that approach.

You can use wrangler without `cargo-generate` -- just `git clone` the template repo directly

**Comment by mrbm** [comment]
@xortive

I want to use generate and do all the cool demos to help me get started in the Cloudflare Worker world (VERY exciting stuff you guys are doing that can help the the little guy compete against the big guys).

That said spent a good amount of time picking around:

Here's one solution 
https://github.com/cloudflare/wrangler/issues/1685 they seem to have a work around by running it via the emulator.


But reviewing it more, I don't want rosetta... I have the need for unnecessary speed (and efficiency)

Reviewing your code, your RC 2 is still pointing to Ashley (which doesn't make sense if the file isn't there)


SO this seems to have worked: I uncompressed https://github.com/cloudflare/wrangler/releases/download/v1.15.0/cargo-generate-v0.5.0-aarch64-apple-darwin.1.tar.gz and put the binary in my cargo binary folder: 

ie /Users/username/.cargo/bin/

I then went into source file: src/commands/generate.rs
and went to line 50 and replaced:
`let binary_path = install::install_cargo_generate()?;`
with:
`let binary_path = PathBuf::from("/Users/username/.cargo/bin/cargo-generate");`

And now the generate command works!

Hopefully this little tweak sheds light on what to clean up in your next build. I haven't tested beyond generate, but will very soon. Let me know what you think.

Thanks guys.

**Comment by yonnic** [comment]
oh I have the exact same problem with the mac mini M1
I hope this missing binaries will be uploaded soon, so far I have to use git clone

**Comment by nilslice** [comment]
This should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:

`npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`

**Comment by facklambda** [comment]
I believe this issue has resurfaced in wrangler 1.17.0.

**Comment by nilslice** [comment]
@facklambda - I believe you should be able to install wrangler using `cargo` for your system. 

If you don't have `cargo`, install it via: https://rustup.rs/ and run `cargo install wrangler`.
