### ISSUE TITLE
issue with secrets not allowed to be added before publishing

### ISSUE THREAD

**Issue by mrbm** [cloudflare/wrangler#1814]
#### Describe the bug

Attempting to do the Auth0 tutorial from scratch on an Intel Mac Mojave box, attempting to add a secret, via the command:
wrangler secret put SOMENAME

I am then prompted to enter a value. After entering value it gives the message: 

Creating the secret for script name XXXX
Worker XXXX doesn't exist in the API yet. Creating a draft Worker so we can create a new secret.
Error: No such file or directory (os error 2)

In the notes it says this issue occurs in version 1.9 and that it is necessary to pre-publish then come back and add secrets...but looks like the issue is still an issue in version 1.15 on an intel Mac.

**Comment by Electroid** [comment]
Hey, thanks for reporting this issue. Just to confirm, you were following this tutorial? https://developers.cloudflare.com/workers/tutorials/authorize-users-with-auth0

Also, does the error tell you which file or directory it is trying to find, but doesn't exist?

**Comment by mrbm** [comment]
@Electroid I was using that tutorial, but I think the issue is irrelevant of that tutorial.
