### ISSUE TITLE
No asset manifest generated for Worker Site

### ISSUE THREAD

**Issue by yafanasiev** [cloudflare/wrangler#1815]
#### Describe the bug

There is no asset manifest generated on `wrangler publish` for worker site.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Run `wrangler init --site mysite`
2. Add prebuilt static site to `./dist` folder
3. Run `wrangler publish`
4. There is no asset manifest for created worker

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS 11.2
* output of `wrangler -V`:  wrangler 1.15.0
* output of `node -v`: v12.18.3
* content of `wrangler.toml`:

```
name = "mysite"
type = "webpack"
account_id = "<redacted>"
workers_dev = false
zone_id = "<redacted>"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.staging]
name = "mysite-staging"
route = "mysite-staging.<redacted>/*"
```

Maybe this is just me being dumb, but I can't find asset manifest anywhere. I see a KV namespace created, a worker being created, a binding from worker to assets KV namespace as well, but no binding for asset manifest (it is not in worler code either). Am I missing something or is this really a bug?

**Comment by rita3ko** [comment]
@yafanasiev could you clarify one small thing for us: is the Worker Site itself not working (are you able to see it / get it deployed)? If so, I suspect what you're running into is the fact that the asset manifest is a text blob type binding that we don't expose anywhere in the UI currently, and just works behind the scenes.

**Comment by yafanasiev** [comment]
The Worker Site works okay, I am more interested in inner workings of wrangler and asset manifest. I want to build kind of custom solution for Worker Sites and wanted to check the manifest format for reference. So it was strange that I could not find it anywhere, but it being hidden away from UI makes sense. Is there and API for this or maybe you could provide such manifest for reference?
