### ISSUE TITLE
Allow routes to be excluded

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler#1817]
I am wondering how to exclude certain routes in the wrangler.toml.

Given the example here in the docs to exclude cat.png -> https://developers.cloudflare.com/workers/platform/routes#matching-behavior

```
*example.com/images/cat.png -> <no script>
*example.com/images/*       -> worker-script
```
Doesn't appear as though this is supported in the wrangler.toml

_Originally posted by @initplatform in https://github.com/cloudflare/wrangler/issues/866#issuecomment-712389372_

**Comment by alexandrukis** [comment]
Are there any plans for implementing this?
