### ISSUE TITLE
Static files on wrangler dev

### ISSUE THREAD

**Issue by RaeesBhatti** [cloudflare/wrangler#1819]
#### Describe the feature

The static files should be served from the `bucket` directory when running `wrangler dev`.

#### Describe the alternatives

Not sure what's going on now but it seems like when a static resource is requested, `wrangler` just throws a 500 Internal Server Error.

Here is my `[site]` config:
```
[site]
bucket = "./__sapper__/build"
entry-point = "./handler"
```

**Comment by lukeburns** [comment]
You have to use https://github.com/cloudflare/kv-asset-handler to serve static assets manually, e.g. https://github.com/lukeburns/kit-worker/blob/main/workers-site/index.js#L62

**Comment by RaeesBhatti** [comment]
Thank you!
