### ISSUE TITLE
generate: project name mismatch

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#182]
Here the output:
```
wrangler generate myApp https://github.com/xtuc/img-color-worker
⬇️ Installing cargo-generate...
 Generating a new webpack worker project with name 'myApp'...
 Renaming project called `myApp` to `my-app`...
 Creating project called `my-app`...
 Done! New project created /myApp
```

There is no occurence of `my-app` in the `myApp` directory, however `myApp` does.

**Comment by xtuc** [comment]
Also it would be cool to captialize Webpack.

**Comment by ashleygwilliams** [comment]
def feel free to file PRs for these- they should be pretty small changes to println statements contents and position

**Comment by granjef3** [comment]
we will need to roll up the version for `cargo-generate` in wrangler.toml once the fix for this is merged in upstream.

**Comment by granjef3** [comment]
Added this to 1.1.0 as the work is done, just needs upstream to be merged and for us to update the dependency.
