### ISSUE TITLE
Run wrangler dev locally

### ISSUE THREAD

**Issue by RaeesBhatti** [cloudflare/wrangler#1820]
#### Describe the feature

It seems like my requests to `wrangler dev` are being routed to Cloudflare servers. This is causing unnecessary latency in when I make the changes and when they're realized in the server (~4-5 seconds). `wrangler dev` should run locally on local assets.

#### Describe the alternatives

Right now I'm stuck on a 500 Internal Server Error on all static resources. I'm not sure if I'm supposed to use `https://github.com/cloudflare/kv-asset-handler` locally or not or how to set it up in a `wrangler dev` setup. Do I have to upload the static files to KV before running `wrangler dev`?

**Comment by dgitq** [comment]
I agree fully! There should be a way to **develop** and run **tests** locally without the requests being routed to the Cloudfare edge..
Never really understood why Cloudflare neglected this and usually points to 'wrangler preview/dev' as a replacement for a proper local environment. Back in the day there was support by the community but it is not maintained any more: https://github.com/dollarshaveclub/cloudworker

Other cloud providers such as Azure have support for local development environments. There should be an official support maintained by Cloudflare @rita3ko :) 

In the mean time you can look into jdanyow's packages collection:
https://github.com/cloudflare/wrangler/issues/1321
https://github.com/cfworker/cfworker

Thanks!

**Comment by RaeesBhatti** [comment]
I've since published https://github.com/RaeesBhatti/cloudflare-kv-isomorphic which emulates Cloudflare KV API's when running locally on NodeJS. This allows me to develop the site without `wrangler dev`. It might be useful to some people.

**Comment by RaeesBhatti** [comment]
I guess this is no longer relevant with the new miniflare release
