### ISSUE TITLE
Bundler Build Hook

### ISSUE THREAD

**Issue by coreybutler** [cloudflare/wrangler#1825]
### 💡 Feature request

Wrangler (dev) should have an option to delegate the build step to a user-defined process... i.e. more like a git hook. 

#### Describe the feature

Developers should be able to specify their own build process. There are many ways this could be implemented. One of the simplest would be accepting a script/command in the `wrangler.toml` file, such as `type = "custom"` and `rebuild = "npm run build"` or a wrangler argument such as `wrangler dev --onchange "npm run build"`. Wrangler would execute this script instead of running webpack.

I go out of my way to avoid webpack, because it doesn't fit in with any of my other development tools. It's painfully slow for larger apps. Personally, I've even been transitioning away from Rollup to esbuild for performance purposes. Tomorrow there may be another build tool, or perhaps there's a revival of grunt/gulp interest. Tooling continues to evolve and developers shouldn't be restricted in such choices. Clearly, I'm not alone, as is evident by issue #1089.

Bottom line: my personal tooling opinions don't matter, but developers shouldn't be force-fed tooling. They should have control of their own build processes. Providing and honoring a configuration option solves this. Perhaps webpack could be a default instead of the "only choice".

#### Describe the alternatives

I have continually been frustrated with the developer experience of `wrangler dev`. I went so far as to rebuild the [dollarshaveclub emulator](https://github.com/dollarshaveclub/cloudworker/network/members), mostly so I could have a livereload hook for my own build process\*. Their utility is not maintained, the work was non-trivial, and I don't particularly want to maintain what I've created either (I'm not in this business). There are 65 other forks of this alternative project, and I don't think any of them are maintained either. Plus, it's not a Cloudflare solution.

**cc** @ashleygwilliams @xtuc since I believe they're on this team?

_\*I can also run the environment locally (refreshes take 3-10ms compared to wrangler taking 4-5 seconds)_

**Comment by xortive** [comment]
This exists already and is out in a release candidate!

https://github.com/cloudflare/wrangler/releases/tag/v1.15.0-custom-builds-rc.1
