### ISSUE TITLE
wrangler dev should display unhandled exceptions

### ISSUE THREAD

**Issue by vivaladan** [cloudflare/wrangler#1826]
#### Describe the bug

wrangler tail displays unhandled exceptions.
wrangler dev does not. the docs imply that both do.

#### Reproduce the bug

wrangler dev
code throws an error
you get a single log line ending in '500 Internal Server Error'

#### Expected behavior

as above, but an additional log line containing the exception

#### Environment and versions

Fill out the following information about your environment.

* operating system: Windows 10
* output of `wrangler -V`: 1.15.0
* output of `node -v`: 14.15.4

**Comment by mikestreety** [comment]
I have just experienced this same issue which was quite frustrating at the time.

I had the following code:

```js
addEventListener('fetch', event => {
	event.respondWith(handleRequest(event))
});

/**
 * Respond to the request
 * @param {Request} request
 */
async function handleRequest(event) {
	const data = {
		hello: "world2"
	}

	const json = JSON.stringify(data, null, 2)

	return event.respondWith(
		new Response(json, {
			headers: {
				"content-type": "application/json;charset=UTF-8"
			}
		})
	)
}
```

In hindsight, you can see the function responds with `event.respondWith` into a second `event.respondWith`. 

However, when running `wrangler dev`, my terminal was filled with 

```bash
[2021-04-03 19:42:01] GET rsstojson.mikestreety.workers.dev/ HTTP/1.1 500 Internal Server Error
[2021-04-03 19:42:01] GET rsstojson.mikestreety.workers.dev/favicon.ico HTTP/1.1 500 Internal Server Error
```

and the browser returned a generic `1101` error - the kind I would expect in production, but not development.

A few things that would be amazing/flagged up for me:

- A verbose error to be thrown in the browser
- A verbose error to be thrown in the command line
- An explanation as to why, when I refresh the `http://127.0.0.1:8787/` URL, requests to `rsstojson.mikestreety.workers.dev` are made

Thanks for all the great work 👍
