### ISSUE TITLE
[build] Custom building isn't triggered when using workers-sites

### ISSUE THREAD

**Issue by potatopotaro** [cloudflare/wrangler#1827]
#### Describe the bug

When using both Workers Sites and the new Custom Builds functionality from v1.15.0-custom-builds-rc.1, only the Workers Sites build behavior executes. Any Custom Builds behavior fails to start or run in any manner, silently.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Generate a Workers Sites project using Wrangler and test the development env to ensure it works.
2. Integrate a very simple build script of your choice and make sure the wrangler.toml has its type set to "javascript". Additionally, make sure to comply with the custom build requirements, as specified [here](https://github.com/cloudflare/wrangler/releases/tag/v1.15.0-custom-builds-rc.1).
3. Run the build script alone to ensure it works correctly.
4. Deploy the wrangler dev env again and notice that the build logs are the same as they were from the start.
5. Comment out the `[sites]` or `sites = ...` config in the `wrangler.toml` and execute the wrangler dev env again. This will break the site but that is more or less arbitrary for this repro. Notice how the build logs are now the same as the logs from step (3).

#### Expected behavior

I'd expect one of the two: (1) the custom build step executes, whether along with the Workers Sites build step or not, (2) the Wrangler CLI, or the RC docs, warn us that our Custom Build is incompatible with Workers Sites; which would be a shame :(

#### Environment and versions

Fill out the following information about your environment.

* operating system: macOS Big Sur V11.1
* output of `wrangler -V`: 1.15.0-custom-builds-rc.1
* output of `node -v`: v14.2.0
* content of `wrangler.toml`:
```
account_id = "a8fd033530d1accd19cb64882e138305"
name = "custom-sites-builder"
type = "javascript"
workers_dev = true
site = { bucket = "./public", entry-point = "./" }

[build]
upload_format = "service-worker"
command = "pnpm run build"
```

**Comment by GregBrimble** [comment]
Fixed by #1833
