### ISSUE TITLE
Webpack mismatch when using ts-loader and webpack 5

### ISSUE THREAD

**Issue by TriangularCube** [cloudflare/wrangler#1836]
### 🐛 Bug report

When using `ts-loader` with Webpack 5, running `wrangler build` will result in `TypeError: Cannot read property 'tap' of undefined`.

This bug is not present when using Webpack 4, which leads me to suspect it has something to do `ts-loader` possibly using a different version of Webpack than Wrangler.

#### Reproduce the bug

1. Clone [this repo](https://github.com/TriangularCube/wrangler-test).
2. Run `wrangler build`

#### Environment and versions

Using Wrangler 1.15.0

**Comment by xortive** [comment]
if you're using the `webpack` project type, wrangler will always use webpack 4, regardless of the version you have set as a dependency.

However, you can use [custom builds](https://github.com/cloudflare/wrangler/releases/tag/v1.15.0-custom-builds-rc.2) to use a build step of your choice (including webpack 5).
