### ISSUE TITLE
wrangler tail can fail if cloudflared is setup using a shared config path

### ISSUE THREAD

**Issue by ZeroErrors** [cloudflare/wrangler#1844]
#### Describe the bug

It's possible for `wrangler tail` to fail if `cloudflared` has config from `/etc/cloudflared` or `/usr/local/etc/cloudflared`.

I had `cloudflared` configured to proxy dns using a config file in `/usr/local/etc/cloudflared`, this meant that when executing `cloudflared` from an unprivileged user it would fail due to port bind restrictions.

You can see the output below with the failure message.
```
$ wrangler tail --verbose
🦚  Setting up log streaming from Worker script "...". Using ports 8080 and 8081.
This may take a few seconds...
2021-04-12T04:53:02Z INF Version 2021.4.0
2021-04-12T04:53:02Z INF GOOS: darwin, GOVersion: go1.16.2, GoArch: amd64
2021-04-12T04:53:02Z INF Settings: map[metrics:localhost:8081 proxy-dns:true proxy-dns-port:53 proxy-dns-upstream:[https://1.1.1.1/dns-query https://1.0.0.1/dns-query] url:localhost:8080]
2021-04-12T04:53:02Z INF Adding DNS upstream url=https://1.1.1.1/dns-query
2021-04-12T04:53:02Z INF Adding DNS upstream url=https://1.0.0.1/dns-query
2021-04-12T04:53:02Z INF Starting DNS over HTTPS proxy server address=dns://localhost:53
2021-04-12T04:53:02Z INF cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/argo-tunnel/reference/service/
2021-04-12T04:53:02Z ERR Initiating shutdown error="Cannot start the DNS over HTTPS proxy server: failed to create a UDP listener: listen udp 127.0.0.1:53: bind: permission denied"
Cannot start the DNS over HTTPS proxy server: failed to create a UDP listener: listen udp 127.0.0.1:53: bind: permission denied
```

My solution to work around this issue was to move the privileged user config to `~/.cloudflared` so it wouldn't get loaded by the unprivileged user.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Install `cloudflared` with proxy-dns on port 53 using one of the shared config paths, such as the following:
`/usr/local/etc/cloudflared/config.yml`
```yaml
proxy-dns: true
proxy-dns-port: 53
proxy-dns-upstream:
 - https://1.1.1.1/dns-query
 - https://1.0.0.1/dns-query
```
2. Run `wrangler tail` as an unprivileged user
3. `wranger tail` should timeout and fail

#### Expected behavior

`wrangler tail` should work under any environment even when `cloudflared` is configured using a shared config path.

#### Environment and versions

* operating system: macOS
* output of `wrangler -V`: `👷 ✨  wrangler 1.15.0`
* output of `cloudflared -V`: `cloudflared version 2021.4.0 (built 2021-04-07-2111 UTC)`

**Comment by karnauskas** [comment]
I'm having similar issue, related to cloudflared config file `~/.cloudflared/config.yaml` with tunnel and ingress configuration – if it's present, `wrangler tail` not working.

```
wrangler tail --verbose
🦚  Setting up log streaming from Worker script "ou". Using ports 8080 and 8081.
This may take a few seconds...
Use `cloudflared tunnel run` to start tunnel E65D05A6-FE79-45A7-A61D-D728807F88B4
^CClosing tail session...
```

**Comment by kcantrel** [comment]
I have also run into this problem. If you don't use the --verbose option you will have no clue as to what is wrong. Therefore, since apparently there is no way to tell cloudflared to ignore configuration files, it would be nice if wrangler would check the exit code of the cloudflared command and immediate display error message and exit if cloudflared returns with a non-zero status. If would be super nice if it would look for a cloudflared configuration file ahead of time and display a warning message if it finds one warning that the "tail" might fail because of an existing cloudflared configuration.
