### ISSUE TITLE
Error while using "wrangler init --site" with version 1.15.x

### ISSUE THREAD

**Issue by ecerroni** [cloudflare/wrangler#1850]
#### Describe the bug

Error while trying to use init command

#### Reproduce the bug

A list of steps to reproduce the bug.

2. `npx @cloudflare/wrangler@1.15.1 init --site`
2. Error:
`Error: values must be emitted before tables`

#### Expected behavior

Site initiated without errors as with version 1.14.1

#### Environment and versions

Fill out the following information about your environment.

* operating system: Ubuntu 20.04
* output of `wrangler -V`:
* output of `node -v`: v14.15.1
* content of `wrangler.toml`:

**Comment by Electroid** [comment]
Thanks for quickly reporting this. It appears this may have to do with TOML serialization: https://github.com/cloudflare/wrangler/blob/c72f2b704cec9514863231bb5230a5b2a4b99259/src/settings/toml/manifest.rs#L140

We'll investigate a fix.

**Comment by xortive** [comment]
Bug is above, would be a quick fix.

**Comment by mabounassif** [comment]
I confirm the bug happening `wrangler@1.51.1` both 32 and 64 bit architectures.

**Comment by lnikell** [comment]
Same issue
