### ISSUE TITLE
Ambiguous error when uploading ES modules without the entitlement

### ISSUE THREAD

**Issue by frandiox** [cloudflare/wrangler#1859]
#### Describe the bug

When running `wrangler dev` or `wrangler publish`, it throws 403 Forbidden error.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Clone https://github.com/cloudflare/modules-rollup-esm (official example)
2. Install dependencies, modify package.json `name`, add `account_id` to `wrangler.toml`.
3. Run `wrangler dev`
4. See error:

```bash
$> wrangler dev
...
src/index.mjs → dist/index.mjs...
created dist/index.mjs in 223ms
Error: HTTP status client error (403 Forbidden) for url (https://api.cloudflare.com/client/v4/accounts/<account-id>/workers/scripts/custom-build-test/edge-preview)
```

```bash
$> wrangler publish
...
src/index.mjs → dist/index.mjs...
created dist/index.mjs in 214ms
✨  Build completed successfully!
Error: Something went wrong! Status: 403 Forbidden, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10015,
      "message": "workers.api.error.not_entitled"
    }
  ],
  "messages": []
}
```

#### Expected behavior

Should build and deploy, but it fails in the deploy.

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS Catalina 10.15.7
* output of `wrangler -V`: `wrangler 1.16.0`
* output of `node -v`: `v14.16.1`
* content of `wrangler.toml`:

It's literally like the example (hiding account id here):

```
name = "custom-build-test"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = "<account_id>"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build"
upload.format = "modules"
upload.main = "./index.mjs"

```

**Comment by Electroid** [comment]
Thanks for reporting this. To get around this, you should signup your account for the Durable Objects open beta. Go to the Workers section of the dashboard, and you'll see a tab for "Durable Objects"

Soon, we will remove this restriction, but before then we should clarify the error message. So I'll keep this open

**Comment by frandiox** [comment]
@Electroid related question, it says `Durable Objects is only available while you are on the Workers Bundled plan.` and, even though I'm on paid plan, I'm basically making open source and I assume most people don't have a paid account.
Will the custom builds (without DO) be available with free plans after the restriction you mention is removed?

**Comment by Electroid** [comment]
> @Electroid related question, it says `Durable Objects is only available while you are on the Workers Bundled plan.` and, even though I'm on paid plan, I'm basically making open source and I assume most people don't have a paid account.
> Will the custom builds (without DO) be available with free plans after the restriction you mention is removed?

@frandiox If I understand correctly: you enabled Unbound, but when you try to sign up for Durable Objects it won't let you with that error?

**Comment by frandiox** [comment]
@Electroid Ah no, I haven't enabled Unbound. I'm in a `workers bundled plan` (the one that is $5/mo) and that seems to be working well after enabling Durable Objects.

The message I wrote in my previous post is not an error, but a warning when enabling DO in the dashboard. Basically my question is, will the "custom builds" feature be available only for paid plans, or also for free plans? Thanks!

**Comment by Electroid** [comment]
Custom builds are available for all plans, free and paid. :) It's only ES modules, that for now, you'll need to be in the Durable Objects beta. Soon, that will no longer be a requirement.
