### ISSUE TITLE
console.log() not working

### ISSUE THREAD

**Issue by barti04** [cloudflare/wrangler#1860]
🐛 Bug report
When trying to debug my worker I can only use console.log in my entry script defined in webpack.config.js. In any other script console.log() does not print to the console. 

I'm using wrangler 1.16.0, node v14.16.1 on Windows 10 with webpack.

**Comment by Electroid** [comment]
Thanks for reporting! What command are you using?

**Comment by Electroid** [comment]
We don't have enough information here to action. Please feel free to reopen an issue if you run into this again.
