### ISSUE TITLE
Custom build fails if dist folder contains extra files

### ISSUE THREAD

**Issue by frandiox** [cloudflare/wrangler#1867]
#### Describe the bug

Wrangler checks every file in `dist` folder after a custom build before publishing the files. If these files have anything that wrangler doesn't understand (such as an `import` statement), it fails. It is common to have other files here that are used for the `bucket` property in `wrangler.toml` with import statements.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Clone official Rollup custom build repo: https://github.com/cloudflare/modules-rollup-esm
2. Build the project and add manually a file `dist/something.js` with content `import path from 'path'` (see wrangler.toml content at the end of the issue)
3. Try to run `wrangler publish` or `wrangler dev`

#### Expected behavior

It should ignore `dist/something.js` since both `main` field in `wrangler.toml` and `module` in `package.json` point to `dist/index.mjs`.

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS Catalina
* output of `wrangler -V`: wrangler 1.16.0
* output of `node -v`: v14.16.1
* content of `wrangler.toml`:

```
name = "custom-build-test"
type = "javascript"
account_id = "<account_id>"
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build && echo \"import path from 'path'\" > dist/something.js"

[build.upload]
format = "modules"
main = "./index.mjs"
```

**Comment by xortive** [comment]
This is intended behavior -- if you want to exclude files from consideration for being uploaded as modules or change the module type they are detected as, you'll want to use the `rules` section, [documented here](https://developers.cloudflare.com/workers/cli-wrangler/configuration#es-modules).

Although in this case, it sounds like you'd be better off having separate directories for `bucket` (which is used for wrangler sites assets) and `build.upload.dir`

**Comment by frandiox** [comment]
@xortive Thanks! I guess `build.upload.dir` with `dist/worker/` is what I need, so it ignores the rest of the `dist` folder.
Now I'm having problems with accessing static files from the bucket but I guess that's another issue.

**Comment by frandiox** [comment]
For the record, the error I mentioned with the bucket is because `getAssetFromKV` is still not compatible with modules: https://github.com/cloudflare/kv-asset-handler/issues/174

@xortive I'm trying to find more docs on custom builds but failing hard. Is there anything else apart form the link you posted?
For example, where is now the `event.waitUntil` to make async requests?
