### ISSUE TITLE
Missing cargo-generate 0.5.0 binary build for Apple Silicon

### ISSUE THREAD

**Issue by dctanner** [cloudflare/wrangler#1869]
### 🐛 Bug report

I have been able to install and run wrangler (https://github.com/cloudflare/wrangler/releases/tag/v1.16.0-durable-objects-rc.0) on fresh Apple Silicon M1, without homebrew or NPM by doing:

```
curl https://sh.rustup.rs -sSf | sh
git clone https://github.com/cloudflare/wrangler.git
cd wrangler
git checkout custom-builds-rc
cargo install --path . --debug
```

However `wrangler generate` looks for the cargo-generate binary inside a wrangler cache folder. If it's not there, it tries to download https://workers.cloudflare.com/get-binary/ashleygwilliams/cargo-generate/v0.5.0/aarch64-apple-darwin.tar.gz which does not exist.

I found a workaround by installing cargo-generate locally: `cargo install cargo-generate  --version 0.5.0 --features vendored-openssl` (note `--features vendored-openssl` was required for installation to work on Apple Silicon without homebrew) and then overwriting the wrangler [run_generate() binary_path](https://github.com/cloudflare/wrangler/blob/3aa7bd9215efe91491b07b47a4414d81ee9b0fd5/src/commands/generate.rs#L50-L50) to use the full path of my local cargo-generate binary `/Users/USERNAME/.cargo/bin/cargo-generate`

It would be great if @ashleygwilliams could build and upload a cargo-generate 0.5.0 binary for Apple Silicon, and I think this would prevent the need for this workaround.

Then we could add clear instructions for installing wrangler on Apple Silicon.

**Comment by Electroid** [comment]
Hello! We do not support M1 yet, but we are actively working on it! #1685

**Comment by nilslice** [comment]
This should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:

`npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`
