### ISSUE TITLE
M1 Mac Serious Bug: Failed to get workers.cloudflare.com/get-binary

### ISSUE THREAD

**Issue by leeanson19** [cloudflare/wrangler#1873]
Once I run "wrangler generate my-worker"
The following error comes up

Failed to download from https://workers.cloudflare.com/get-binary/ashleygwilliams/cargo-generate/v0.5.0/aarch64-apple-darwin.tar.gz

**Comment by Electroid** [comment]
Hello! We do not support M1 yet, but we are actively working on it! #1685

**Comment by nilslice** [comment]
This should be fixed in the latest release. Please give it a try and let us know if you still are hitting any errors:

`npm i -g @cloudflare/wrangler@1.16.1` or `cargo install wrangler --version 1.16.1`
