### ISSUE TITLE
Generating multiple tokens with "wrangler login" causes problems

### ISSUE THREAD

**Issue by Yrlish** [cloudflare/wrangler#1883]
#### Describe the bug

When logging in to wrangler via the link provided with `wrangler login`, it creates a token in my CloudFlare account with the name "Wrangler Login". It works, all is good.

But when I go to a second device and use the `wrangler login`, after accepting the token in the browser. *Nothing happens.* What now has happened, is that the second device's wrangler has now overridden the existing "Wrangler Login" token, and doesn't receive it so it waits forever. The first device is also now broken, as the token is now invalid.

When I manually changed the name of the tokens in my account between the logins, to avoid name duplicates, it worked fine.

#### Reproduce the bug

1. Login with wrangler `wrangler login` and follow steps
2. Go to a new device
3. Login with wrangler `wrangler login` and follow steps
4. Wrangler login process is now stuck and previous device is invalidated

#### Expected behavior

I expect tokens to be created without conflicting with each other, to be able to login on multiple devices or environments simultaneously easily.

#### Environment and versions

* operating system: Two environments: Windows 10 and WSL Ubuntu 20.04
* output of `wrangler -V`: 1.16.1
* output of `node -v`: 14.16
* content of `wrangler.toml`: *doesn't have it available right now*

**Comment by nilslice** [comment]
Hi @Yrlish  - thanks for the bug report! I'm currently investigating this, and some additional detail would be great if you can share. 

There's another tracking issue for this, where I've left a comment with some extra info that would help debug: https://github.com/cloudflare/wrangler/issues/1703#issuecomment-828554818

If you have a chance to reply on that thread it would be much appreciated.
