### ISSUE TITLE
KV namespace not found

### ISSUE THREAD

**Issue by Graren** [cloudflare/wrangler#1902]
#### Describe the bug

A clear and concise description of the bug.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Clone any template
2. Fill wrangler.toml with account_id and sensitive data
3. Make a worker that stores data in a KV namespace
4. Create said KV namespace running `wrangler kv:create` command
5. Fill wrangler.toml with the bindings 
```
kv-namespaces = [ 
     { binding = "NAME", id = "id printed by kv:create" }
]
```
6. wrangler publish
7. Make a request to said endpoint
8. ReferenceError: NAME is not defined

#### Expected behavior

I should not be seeing a reference error and see my data correctly stored

#### Environment and versions

Fill out the following information about your environment.

* operating system: Ubuntu 16.0.4
* output of `wrangler -V`: Version 1.16.0-durable-objects-rc.0
* output of `node -v`: v12.13.0
* content of `wrangler.toml`:

```
name = "some name"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
workers_dev = true
account_id = "<my acc id>"
route = ""
zone_id = ""
kv-namespaces = [ 
	 { binding = "NAME", id = "clipped", preview_id = "clipped" }
]

[build.upload]
# Upload the code directly from the src directory.
dir = "src"
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "OTHER_NAME", class_name = "SomeClassName"}]


```

**Comment by koeninger** [comment]
It sounds like you are trying to do `NAME.get('foo')` rather than `env.NAME.get('foo')`

With modules syntax, bindings you associate with your worker, such as KV namespaces, are available on the env object, not a global variable.  See e.g. https://developers.cloudflare.com/workers/learning/using-durable-objects#writing-a-class-that-defines-a-durable-object

**Comment by osdiab** [comment]
@koeninger i'm having the same issue, and i tried accessing the namespace with `env.MY_KV_NAME` but that just led to `env is not defined`. It works as a global variable on production for me, but just not with `wrangler dev`. So not sure what to think about this.

**Comment by chasoft** [comment]
I'm struggling with binding a KV with a worker... Works with "wrangler dev" but does Not work with "wrangler publish"...

**Comment by chasoft** [comment]
My case (solved 😎).

I use CLI (wrangler) and ... i add binding infor to "wrangler.toml" but it does not binded... until

i do a manual step on web-interface:: 

go to Settings tabs in your Worker, go to "Variables", at the end of the page, you will see "KV Namespace Bindings"... add it manually here.

![image](https://user-images.githubusercontent.com/7332422/150632173-f71f75c7-5ecf-43bf-959f-365e2ddead34.png)


 the problem solved, but I am still confusing with the notice

![image](https://user-images.githubusercontent.com/7332422/150632206-9f2e2608-be69-45f4-92c5-ad9466761bd3.png)

**Comment by andyrichardson** [comment]
Looks like this is related to https://github.com/cloudflare/wrangler/issues/2142.

I'm also seeing this bug.

**Comment by koeninger** [comment]
@andyrichardson Can you clarify what you are seeing and why you think it's related?

If you're using multiple wrangler environments, it's documented that you need to define KV bindings for each of them, they are not inherited: https://developers.cloudflare.com/workers/cli-wrangler/configuration#keys

**Comment by georgephillips** [comment]
Just did a deploy using wrangler after updating from the old CLI. This option didn't work and I had to add the variable manually as well.

**Comment by understream** [comment]
For those who didn't solve this problem yet, I found the solution here:
https://community.cloudflare.com/t/kv-binding-is-not-defined/391499

**Comment by georgephillips** [comment]
Looks like a new error message has been added. The issue was `kv-namespaces` was renamed to `kv_namespaces`.

**Comment by swuecho** [comment]
can not even get a small example working, the document really could use some work.  hard to  believe it is a 'popular' product?

**Comment by ashishjullia** [comment]
> For those who didn't solve this problem yet, I found the solution here: https://community.cloudflare.com/t/kv-binding-is-not-defined/391499

I followed this^, still facing the error, if possible can you please take a look at the files? [here](https://community.cloudflare.com/t/kv-binding-is-not-defined/391499/4?u=ashishjullia19)
