### ISSUE TITLE
Cannot connect to websocket with wrangler dev

### ISSUE THREAD

**Issue by universse** [cloudflare/wrangler#1910]
#### Describe the bug

I keep getting this message when trying to connect to websocket using `wrangler dev`. Non-websocket routes work fine though.

```
[2021-05-04 22:54:59] GET dev-bug.ulrjch.workers.dev/ws HTTP/1.1 400 Bad Request
[2021-05-04 22:55:08] GET dev-bug.ulrjch.workers.dev/ HTTP/1.1 200 OK
```
![image](https://user-images.githubusercontent.com/15166715/117025215-4d7b6c80-ad2d-11eb-8530-ea325f5c5217.png)

#### Reproduce the bug

1. Clone https://github.com/universse/wrangler-bug
2. Enter `account_id` in `wrangler.toml`
3. Run `wrangler dev`
4. Open `index.html`
5. Above error messages would appear in terminal.

Optional: It works fine when published.
1. Run `wrangler publish`
2. Replace websocket link in `index.html`
3. Open `index.html`
4. Websocket connection is successful.

#### Expected behavior

Should be able to connect to websocket using `wrangler dev`.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Windows 10 Home
* output of `wrangler -V`:  wrangler 1.16.0-durable-objects-rc.0
* output of `node -v`: v15.10.0
* content of `wrangler.toml`: per repo

**Comment by universse** [comment]
I have tried `type: "webpack"` for `wrangler.toml` as well. It doesn't work still.

**Comment by Electroid** [comment]
We currently do not support WebSocket debugging in `wrangler dev`, but obviously we should. Will get back to you as we figure out the complexity for this addition.

**Comment by dan-online** [comment]
Hey it's September now, how's this doing? I've found the same issue with wrangler dev and can confirm it only works when published.

```bash
$ wrangler -V
wrangler 1.19.3
```

**Comment by threepointone** [comment]
We've scheduled to fix this in q4 (ie - before the end of this year) Until then, the recommendation is to use miniflare https://github.com/cloudflare/wrangler/issues/2079#issuecomment-924759723 Sorry for the delay on this, we'll fix it soon.

**Comment by seeekr** [comment]
Just a heads up to maybe update the note at https://developers.cloudflare.com/workers/learning/using-websockets#writing-a-websocket-server in case this should already be fixed in production!

**Comment by threepointone** [comment]
Good catch! sent a PR that removes the message https://github.com/cloudflare/cloudflare-docs/pull/3082. Thanks!
