### ISSUE TITLE
wrangler whoami Error

### ISSUE THREAD

**Issue by leyenda** [cloudflare/wrangler#1914]
#### Describe the bug

wrangler command whomi is responding this:
```
Error: ⚠️  Error: error decoding response body: missing field `betas` at line 1 column 490
```
#### Reproduce the bug

A list of steps to reproduce the bug.

1. install wrangler globally version 1.16.1
2. Run wrangler whoami
3. See error

#### Expected behavior

Expected info about account using wrangler

#### Environment and versions

Fill out the following information about your environment.

* operating system: Ubuntu 18.04 LTS
* output of `wrangler -V`: wrangler 1.16.1
* output of `node -v`: v14.15.5
* content of `wrangler.toml`: N/A

**Comment by eshanj19** [comment]
Same error for me as well. I also faced this [issue](https://github.com/cloudflare/wrangler/issues/1703). So I have logged in to wrangler via `wrangler config` and provided the `API Token`.

```
wrangler whoami
Error:  Error: error decoding response body: missing field `betas` at line 1 column 1978
```

- operating system: Ubuntu 20.04 LTS
- output of wrangler -V: wrangler 1.16.1
- output of node -v: v15.8.0
- content of wrangler.toml: N/A

**Comment by nilslice** [comment]
this should be fixed once https://github.com/cloudflare/cloudflare-rs/pull/144 is merged, and we update the dep within wrangler - it will be included in an upcoming release this week. thanks for reporting!
