### ISSUE TITLE
Wrangler whoami command erroring after wrangler installed/updated with npm

### ISSUE THREAD

**Issue by ckdrew670** [cloudflare/wrangler#1922]
#### Describe the bug

`wrangler whoami` command still responding with the following error after updating with npm:
```
Error: ⚠️  Error: error decoding response body: missing field `betas` at line 1 column 490
```

#### Reproduce the bug

A list of steps to reproduce the bug.

1. install wrangler globally with `npm i @cloudflare/wrangler -g`
2. Run `wrangler login` and follow steps to get success message
3. Run `wrangler whoami` and get above error

#### Expected behavior

After successful authentication, `wrangler whoami` should return user info

#### Environment and versions

Fill out the following information about your environment.

* operating system: Mojave 10.14.6 
* output of `wrangler -V`: wrangler 1.16.1
* output of `node -v`: 14.17.0
* content of `wrangler.toml`: n/a

**Comment by Electroid** [comment]
Hi, we've fixed this issue here: https://github.com/cloudflare/wrangler/issues/1914

We're going to get this in the next release ASAP, will keep this open until we do.

**Comment by ckdrew670** [comment]
Great, thanks @Electroid

**Comment by rynpc** [comment]
Is there a workaround for getting the account id while we wait for this to be released?

**Comment by Electroid** [comment]
This was released and fixed.
