### ISSUE TITLE
wrangler generate causes Error: Bad CPU type in executable (os error 86) on M1 Mac

### ISSUE THREAD

**Issue by kynrai** [cloudflare/wrangler#1924]
#### Describe the bug

Fresh install of latest rustup stable and latest cargo install of wrangler on fresh M1 Mac (no rosetta 2).
After wrangler installed successfully, running `wrangler login` works fine and most if not all other commands work except for the `wrangler generate` command which results in `os error 86`

#### Reproduce the bug

A list of steps to reproduce the bug.

1. rustup update (stable)
2. cargo install wrangler
3. wrangler login
4. wrangler generate
5. Error: Bad CPU type in executable (os error 86) on M1 Mac

#### Expected behavior

Should generate a project as per tutorial

#### Environment and versions

Fill out the following information about your environment.

* operating system: Mac OS BigSur 11.3.1
* output of `wrangler -V`: wrangler 1.16.1
* output of `node -v`: v16.1.0
* content of `wrangler.toml`: N/A

**Comment by nilslice** [comment]
Hi @kynrai, I just tested this on an M1 and could not reproduce. 

```zsh
$ cargo install wrangler --version 1.16.1
...
   Installed package `wrangler v1.16.1` (executable `wrangler`)
$ wrangler generate something
🔧   Creating project called `something`...
✨   Done! New project created /Users/stevemanuel/Projects/something
...
$ which wrangler
/Users/stevemanuel/.cargo/bin/wrangler
$ file $(which wrangler)
/Users/stevemanuel/.cargo/bin/wrangler: Mach-O 64-bit executable arm64
$ cd something 
$ wrangler build
✨  Basic JavaScript project found. Skipping unnecessary build!
```

Did you use a specific `--type` when you generated a project?

**Comment by kynrai** [comment]
Well, I can no longer reproduce now either, I guess it must have been an environment issue on my end.

**Comment by nilslice** [comment]
For those who run into this error, please try to force the install of Rosetta on your M1: 
```zsh
softwareupdate --install-rosetta --agree-to-license
```

then, re-run the `wrangler` commands
