### ISSUE TITLE
Not specifying Fetch Cache Ttl when no-cache for Enterprise Accounts causes frequent MISS

### ISSUE THREAD

**Issue by mattpatterson94** [cloudflare/wrangler#1943]
#### Describe the bug

_This isn't specifically a `wrangler` bug, but more of a potential worker bug_

This problem seems very specific, but it caused me a bit of headache.

Our worker uses `fetch` to retrieve an origin's body and headers to send back to the client. We are providing `cf: { cacheEverything: true }` in our fetch options to cache the response. Our origin responds with `Cache-Control: `public, no-cache`, indicating that we want to cache this response in the browser and Cloudflare, but revalidate every time. 

When testing this locally (via `wrangler dev`), it worked fine. It also worked fine using our `workers.dev` subdomain, as well as on a zone on a free Cloudflare account. 

We were getting `cf-cache-status: REVALIDATED` in the client in every response.  

However, we then deployed this to a zone in our Enterprise account and we started seeing:

`cf-cache-status: MISS` every time. 

After tinkering with various Cloudflare settings I decided to play around with the cacheKey / cacheTTL options on fetch and that's when I uncovered the nuance. 

When setting `cacheKey: 'something'`, I started receiving a `cf-cache-status: HIT` after every request. When I set a `cacheTtl: 2`, I started receiving a `cf-cache-status: REVALIDATED` or `HIT` (based on the timeframe).

I'm not sure why it's different between Enterprise and Free, but maybe having the option of a `cacheKey` changes the result. 

#### Reproduce the bug

1. Create worker that runs:

```javascript
addEventListener('fetch', async (event) => {
  event.respondWith(fetch('https://some.origin/some-page', { cf: { cacheEverything: true } }))
})
```

2. Ensure the origin responds with `Cache-Control: public, no-cache`
3. Deploy this worker to a Free account, or to workers.dev
4. Visit in browser or curl and make note of `cf-cache-status`
5. Attempt to deploy this to a zone in an Enterprise account

#### Expected behavior

Free account will have a `cf-cache-status` of `MISS` then `REVALIDATED`, whereas the Enterprise account will always have `MISS`.

#### Reproducible Fix

1. Update the worker code to:

```javascript
addEventListener('fetch', async (event) => {
  event.respondWith(fetch('https://some.origin/some-page', { cf: { cacheEverything: true, cacheTtl: 2 } }))
})
```

2. Deploy and test again in browser or curl.

Both should now act consistently.

#### Environment and versions

Via the Cloudflare Console

**Comment by nilslice** [comment]
@mattpatterson94 - hey, thanks for writing this up! I'm working on routing it to the right team to get some feedback. Will report back ASAP.
