### ISSUE TITLE
Issue when installing with NPM on Windows 10

### ISSUE THREAD

**Issue by snakysnake** [cloudflare/wrangler#1949]
#### Cant install on Windows

Is the issue my PC / Win version?
This is the error I get after trying to install multiple times using a fresh installation of NPM 
Error: Unsupported platform: Windows_NT ia32

**Comment by caass** [comment]
Hey! Can you verify the installation fails completely? Like the installation doesn't work, in addition to displaying the error? It could be a dependency on `fsevents` [like here](https://github.com/angular/angular/issues/13935#issue-200859878), which may not actually affect your ability to use wrangler. Either way though, I'd be happy to dig further into this. Can you provide some more info about your machine?

**Comment by NSpencer4** [comment]
Same issue 
Node v14.17.0
Npm 7.12.0
Windows 10

npm i @cloudflare/wrangler --save-dev

`npm ERR! Error: Unsupported platform: Windows_NT ia32`

**Comment by jgentes** [comment]
@NSpencer4 Would you mind going to Settings > System > About, then hit the `Copy` button and paste the info here?

![image](https://user-images.githubusercontent.com/1149470/125509543-26e41187-2e1e-4ea3-9497-c90c1cc40008.png)

**Comment by NSpencer4** [comment]
Did some more research and found that I accidentally installed the x86 version of Node 14 :man-facepalming: . Only posting this to hopefully help others that did the same.

**Comment by jgentes** [comment]
> Did some more research and found that I accidentally installed the x86 version of Node 14 :man-facepalming: . Only posting this to hopefully help others that did the same.

Ah, good catch! Thanks, we'll look out for that if we see this come up again.
