### ISSUE TITLE
wrangler publish --rename-class and --transfer-class arguments help is insufficient

### ISSUE THREAD

**Issue by codefrau** [cloudflare/wrangler#1950]
#### Describe the bug

This is the help being displayed:

        --rename-class <rename-class> <rename-class>                           Rename a durable object class
        --transfer-class <transfer-class> <transfer-class> <transfer-class>
            Transfer all durable objects associated with a class in another script to a class in this script

#### Reproduce the bug

```
wrangler publish -h
```

#### Expected behavior

Should display something like

        --rename-class <OldClassName> <NewClassName>                     Rename a durable object class
        --transfer-class <old-script> <ClassNameInOldScript> <ClassNameInThisScript>
            Transfer all durable objects associated with a class in old-script to a class in this script

#### Environment and versions

* output of `wrangler -V`:

        wrangler 1.17.0

**Comment by nataliescottdavidson** [comment]
@a-robinson @xortive might want to change the verbiage here?

**Comment by a-robinson** [comment]
Yeah, thanks for raising this.

**Comment by xortive** [comment]
Yeah, looks like this got lost in the transition to structopt.

Pretty sure all that's needed here is adding back in the [`value_names` method call](https://github.com/cloudflare/wrangler/pull/1824/files#diff-0fe902b7cd3f239d8f9accf1fe68898dde0dcc2b2789896ad82fa49aaf09853bR73) as a [raw method](https://docs.rs/structopt/0.3.21/structopt/#raw-methods).

I'll handle it when I implement tagged migrations in `wrangler.toml` which is next up on my plate.
