### ISSUE TITLE
Missing build.upload main file gives: Uncaught TypeError: Main module name is not present in bundle.

### ISSUE THREAD

**Issue by geelen** [cloudflare/wrangler#1952]
Following on from #1951, if a user misconfigures the `main` file for a modules project, no error is reported from the command line. Instead, the file appears to be uploaded but then the API actually reports the following error:

```
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10021,
      "message": "Uncaught TypeError: Main module name is not present in bundle.\n  at line 0\n"
    }
  ],
  "messages": []
}
```

Obviously, wrangler should be verifiying that whatever file it's trying to upload actually exists before this, and report an error message like `Error: main file './dist/dist/index.mjs' does not exist. Cannot upload Worker.`. This would indicate to the user that the error is the in the _config_ (i.e. the path `./dist/dist/index.mjs` is not what's specified in `wrangler.toml`), not in the _contents_ of the file ("main module name is not present").

Reporting this so the error message is googlable, if you hit this the bug is _probably_ the same one I hit in #1951

**Comment by nataliescottdavidson** [comment]
TODO add better error specifying which module is missing

**Comment by janat08** [comment]
Please do soon, linking weirdness around specifying upload file with this template: https://github.com/cloudflare/modules-rollup-esm/blob/master/wrangler.toml

Apparently you pass the bundle output to dist, and then point wrangler to top level directory when neither input nor output are in it.

**Comment by threepointone** [comment]
This is a lot better in wrangler2; we're explicit about the path to the worker (re: https://github.com/cloudflare/wrangler/issues/1951#issuecomment-1064831946) and we specifically call out that we couldn't resolve a file at the given path in the error message in the above scenario.

**Comment by threepointone** [comment]
Closing this since wrangler v2 is now in GA
