### ISSUE TITLE
Multiple headers not handled correctly in list [Regression?]

### ISSUE THREAD

**Issue by Sharkgamedev** [cloudflare/wrangler#1956]
#### Describe the bug

When using the list method (EG) 
```
headers = {
'Set-Cookie': 'cookie=value',
'Set-Cookie': 'cookie2=value2',
}
```
Everything but the last header is dropped and the client only gets cookie2
Whereas with the explicit append method:
```
resp.headers.append('Set-Cookie', 'cookie=value');
resp.headers.append('Set-Cookie', 'cookie2=value2');
```
It works flawlessly. Both explicit append and list were supposedly fixed in #1412 but it would appear to have regressed.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Make a brand new worker that responds to a fetch request and returns a response with set-cookie headers
2. Send a request to it from the client while it is running on wrangler
3. Observe behaviour

#### Expected behavior

All headers are preserved as in with resp.headers.append();

#### Environment and versions

Fill out the following information about your environment.

* operating system: Windows
* output of `wrangler -V`: 1.17.0
* output of `node -v`: 14.6.1
* content of `wrangler.toml`: 
```
name = "Name of worker"
type = "webpack"

account_id = "Account ID is specified"
workers_dev = true
route = "Route is specified"
zone_id = "zoneIdIsSpecified"
```

**Comment by nataliescottdavidson** [comment]
Defining multiple headers in the fetch(..., {headers: { ... }}) call just creates an object with two of the same keys, and the last one wins. So having to use explicit `append` for this is expected.

**Comment by Sharkgamedev** [comment]
> Defining multiple headers in the fetch(..., {headers: { ... }}) call just creates an object with two of the same keys, and the last one wins. So having to use explicit `append` for this is expected.

Huh, 4 years with JS and I never knew you had to have unique keys in an object! You learn something new every day, I suppose. Sorry about that!

**Comment by nataliescottdavidson** [comment]
> > Defining multiple headers in the fetch(..., {headers: { ... }}) call just creates an object with two of the same keys, and the last one wins. So having to use explicit `append` for this is expected.
> 
> Huh, 4 years with JS and I never knew you had to have unique keys in an object! You learn something new every day, I suppose. Sorry about that!

@Sharkgamedev No worries at all... I had to call an assist on this one cause I was stumped :)
