### ISSUE TITLE
wrangler init --type="javascript" doesn’t work as expected

### ISSUE THREAD

**Issue by tylerbrostrom** [cloudflare/wrangler#1960]
#### Describe the bug

`wrangler init` doesn’t work as expected when `--type="javascript"`.

Running `wrangler init --type="javascript"` outputs a `wrangler.toml` file where, unexpectedly, `type = 'webpack'` and `target_type = "js"`.

It is accompanied by a warning in the console:

```text
⚠️  The template recommends the "webpack" type. Using type "js" may cause errors, we recommend changing the type field in wrangler.toml to "webpack"
```

#### Reproduce the bug

Run `wrangler init --type="javascript"`

#### Expected behavior

Running `wrangler init --type="javascript"` should produce a `wrangler.toml` similar to the following:

```toml
# ... truncated
type = "javascript"
build.command = "npm install && npm run build"
```

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS 10.15.7 
* output of `wrangler -V`: wrangler 1.17.0
* output of `node -v`: v14.16.1
* content of `wrangler.toml`: N/A

**Comment by caass** [comment]
Thanks for your report! Looking into this :)
