### ISSUE TITLE
Duplicate wrangler build and using yarn instead of npm

### ISSUE THREAD

**Issue by hamzahsn** [cloudflare/wrangler#1967]
#### Describe the bug

Currently, I'm using wrangler to publish a site but I have an issue with the integration to webpack with wrangler, this is the old structure which I had where I used to have CRA for the react project:

```
    |-- build // where react project get built
    |-- dist // where worker project get build with the command yarn build:worker from package.json
    |-- .gitignore
    |-- package.json
    |-- tsconfig.json
    |-- worker.webpack.js
    |-- wrangler.toml
    |-- yarn.lock       
    |-- public
    |-- src
    |-- workers-site
        |-- .gitignore
        |-- package.json
        |-- tsconfig.json
        |-- yarn.lock
        |-- src
            |-- index.ts
```

Then I introduced webpack, where we set the `worker.webpack.js` to build on the root folder next to the react build, and removed the `package.json` from wrangler, while I wanted everything handled by a single `package.json` from the root as you can see in this structure:

```
    |-- package.json // this is where we are running now worker commands
    |-- package-lock.json // unwanted file when we run "wrangler build" or "wrangler dev" because we are using yarn
    |-- tsconfig.json
    |-- wrangler.toml
    |-- yarn.lock
    |-- build // react build by webpack
    |-- dist // wrangler build by webpack
    |   |-- worker.js
    |-- config
    |   |-- webpack.config.js
    |   |-- worker.webpack.js
    |-- public
    |-- src
    |   |-- app
    |-- workers-site
        |-- tsconfig.json
        |-- src
        |   |-- index.ts
        |-- worker // unwanted folder created when running "wrangler build" or "wrangler dev"
            |-- script.js
```

When we build wrangler from package.json command it successfully works as expected with our webpack config in the desired folder, but when we run `wrangler build` or `wrangler dev` it create an unnecessary `package-lock.json` on the root folder and create another build named `worker` for wrangler inside `workers-site` as you can see, which is not the desired behavior as we want, I have found similar issues on Github but didn't find a solution to avoid the creation of `worker` folder inside `worker-site` also to avoid creating a `package-lock.json` file because we're using yarn.

These are some similar here: https://github.com/cloudflare/wrangler/issues/778 and https://github.com/cloudflare/wrangler/issues/820 and https://github.com/cloudflare/wrangler/issues/1046 

#### Expected behavior

- We expect when we run `wrangler build` or `wrangler dev` it will use `yarn` instead of `npm`
- The ability to have a single build which is in our case webpack, or even if it's possible to specify it in `wrangler.toml` file and avoid webpack somehow.
- Avoid creating `package-lock.json` file whenever we run `wrangler dev` or `wrangler build` and having the ability maybe to check if there is a `node_modules` folder inside the project to avoid installing dependencies.

#### Environment and versions

* operating system: MacOs Big Sur 11.4
* output of `wrangler -V`:   1.17.0
* output of `node -v`: 14.15.4
* content of `wrangler.toml`: 

```
type = "webpack"
account_id = "1234567890"
webpack_config = "./config/worker.webpack.js"

[build]
command = "yarn install"
[build.upload]
format = "service-worker"


[site]
bucket = "./build"

[env.dev]
name = "mysite"
workers_dev = true
route = ""
zone_id = ""
```

**Comment by nilslice** [comment]
@hamzahsn - thank you for reporting this! would you please try using `type = "javascript"` instead of webpack? 

Wrangler may be making some assumptions when using `type = "webpack"`, and it will be helpful to know that your custom build command is not overriding that.

**Comment by hamzahsn** [comment]
@nilslice - Thank you for your quick answer and I have applied your changes but here what I got:

- Now I'm able to run `wrangler build` and it uses `yarn` instead of `npm` while I have changed the command inside `wrangler.toml` file `command = "yarn install"` into `command = "yarn install && webpack --config config/worker.webpack.js` so it successfully run the build without creating additional wrangler build files inside workers-site.

- I'm able to build the project **BUT** when I run the publish command to publish my site I get the error:
`Error: Your JavaScript project is missing a `package.json` file` which I believe it complains about missing a `package.json` inside the `workers-site` which I have removed.

- Following the last error, I have tried to create an empty `package.json` file inside workers-site without any dependencies but just some description and name, but I still get an error: 
 ```
{
      "code": 10021,
      "message": "Uncaught SyntaxError: Cannot use import statement outside a module\n  at line 1\n"
 }
```

So any idea how to avoid that maybe?

**Comment by caass** [comment]
Hey! So this sounds like two issues, right? One is that you should be able to run wrangler commands through yarn instead of npm, and the other one is that you don't like the folder in `workers-site/worker/script.js`? The `npm` / `yarn` issue should be fairly straightforward to land in the next release, I'm curious what the contents of `workers-site/worker/script.js` is? I think that's autogenerated by wrangler, so you should be able to just `.gitignore` it.

**Comment by koeninger** [comment]
Are you specifying a value for "main" in the empty package.json file you added?

**Comment by jgentes** [comment]
Hi @hamzahsn - the `Cannot use import statement outside a module` error is often caused by a Typescript compilation issue. This is generally due to a configuration setting in `tsconfig.json` or if you're using babel, then `babel.config.json` (or `.babelrc`).

Could you paste the content of these files, and for good measure, your `package.json` as well?

**Comment by hamzahsn** [comment]
@koeninger  thanks for the update, but the `main`  in package.json for the workers-site is set to `src/index.ts `

**Comment by hamzahsn** [comment]
@jgentes  Thanks for following up, but I'm actually using `ts-loader` for workers-site where I have set a separate webpack config for it.

The content of my `tsconfig` file inside workers-site is the following:

```
{
  "compilerOptions": {
    "outDir": "./dist",
    "module": "commonjs",
    "target": "es2020",
    "lib": ["es2020", "webworker"],
    "alwaysStrict": true,
    "strict": true,
    "preserveConstEnums": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "esModuleInterop": true
  },
  "include": [
    "./src/*.ts",
    "./src/**/*.ts",
    "./node_modules/@cloudflare/workers-types/index.d.ts"
  ]
}
```
And the content of package.json file in workers-site directory is:

```
{
    "private": true,
    "name": "worker-site",
    "version": "1.0.0",
    "main": "src/index.ts"
}
```

**Comment by koeninger** [comment]
> @koeninger thanks for the update, but the `main` in package.json for the workers-site is set to `src/index.ts `

I believe for custom builds with format = service worker, wrangler is going to look at main in package.json to determine what file to upload, which would explain why you're getting syntax errors about import (assuming your index.ts file has import statements).

I'd try setting main to the output of your bundler, e.g. dist/worker.js, and configuring your bundler to look at src/index.ts as its entry point.

**Comment by jgentes** [comment]
@hamzahsn were you able to try the previous suggestion?

**Comment by hamzahsn** [comment]
Hi @koeninger  and @jgentes , we have tried your suggestion and we have made some small other changes and finally it works for us, thanks a lot and much appreciated!

**Comment by jgentes** [comment]
Great, we're glad you were able to get it resolved :)

**Comment by jgentes** [comment]
As a follow up for future readers - the contents of `package.json`:

```
"main": "dist/worker.js",
"module": "src/index.ts"
```
