### ISSUE TITLE
Validate wrangler.toml before Fetching Deps

### ISSUE THREAD

**Issue by elithrar** [cloudflare/wrangler#197]
On a fresh project , invoking `wrangler publish` will fetch dependencies (first) and then error out if `account_id` (or other vals) in `wrangler.toml` are not set.

This could be frustrating on slower networks, or even if you just waited to see it fail.

Suggestion: validate the required fields in `wrangler.toml` first.

**Comment by ashleygwilliams** [comment]
this is an excellent feature request. are you interested in making this PR yourself? i'm happy to offer mentoring! if you don't have the time no worries!  let me know :)
