### ISSUE TITLE
Support "stages" or different route targets.

### ISSUE THREAD

**Issue by RichiCoder1** [cloudflare/wrangler#199]
Not sure how this would work specifically, but at least currently with Serverless we push to a different route/zone depending on what "stage" of the CI is running. Aka, `dev`, `qa` and `production`. Would be nice to able to do something like this either by baking the idea into wrangler or supporting specifying the `wrangler.toml`.

**Comment by xtuc** [comment]
I believe we already support multiple routes in the configuration. it would be great to be able to specify a `env` key and allow to pass an `--env` argument when publishing.

I'm not sure we want constraints on the string (dev, qa and production), users are free to define any env.

**Comment by EverlastingBugstopper** [comment]
I'd like to see this happen, lots of workers consumers push to a staging or development environment prior to releasing to production, and allowing multiple configurations within wrangler.toml with different aliases, or even a method to specify a .toml file would be really useful.

**Comment by EverlastingBugstopper** [comment]
Hey this is happening! Watch for the release on monday, you can read about the new API here: https://github.com/cloudflare/wrangler/blob/master/docs/content/environments.md
