### ISSUE TITLE
Unsupported platform Windows_NT arm64

### ISSUE THREAD

**Issue by StrawMonkey** [cloudflare/wrangler#1998]
#### Describe the bug
Trying to install wrangler on a Surface Pro X. Installation fails with unsupported platform. If I remove the platform check things work fine.

#### Reproduce the bug
Get an arm device with a recent version of Windows (that supports emulation) and run `npm i @cloudflare/wrangler -g`

#### Expected behavior
Wrangler gets installed.

#### Environment and versions

* operating system: Windows 10
* output of `wrangler -V`:
* output of `node -v`: 15.8 (arm)
* content of `wrangler.toml`:

**Comment by nilslice** [comment]
@StrawMonkey  - thanks for filing this. I may need to send you some code to help identify your system and add it to the architecture checks. Let me do some testing first and I'll get back to you asap!

**Comment by nilslice** [comment]
@StrawMonkey - sorry for the delay here.. a bit backed up with some other work at the moment. In lieu of official support via pre-built binary for your system, can you try to build it from source using `cargo`: https://github.com/cloudflare/wrangler#install-with-cargo

I think that should at least unblock you. Thanks -- let me know if you have any issues with this.

**Comment by imdavidmin** [comment]
I'm having the same error but for `Windows_NT ia32`

I tried this with both node v14.17.4 and v16.5.0.

**Comment by threepointone** [comment]
We have much wider platform support with wrangler v2. You can try it today with `npm install wrangler@beta`. More info at https://github.com/cloudflare/wrangler2 (which we'll eventually merge back into this repo)
