### ISSUE TITLE
Error Install Wrangler via Cargo in Windows 10

### ISSUE THREAD

**Issue by lynnellneri** [cloudflare/wrangler#201]
error: linking with `link.exe` failed: exit code: 1

**Comment by xtuc** [comment]
Could you please provide the full ouput?

**Comment by lynnellneri** [comment]
![image](https://user-images.githubusercontent.com/7625546/58820868-5e656400-8666-11e9-8b4b-a76b7090a840.png)
![image](https://user-images.githubusercontent.com/7625546/58820888-69b88f80-8666-11e9-91ce-9e39b0314da8.png)
![image](https://user-images.githubusercontent.com/7625546/58820904-7210ca80-8666-11e9-85d2-7f9f476647e6.png)

**Comment by steveklabnik** [comment]
Do you have the C++ build tools installed? That is, https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019

**Comment by lynnellneri** [comment]
I used the Windows installer of Cargo. If I'm not wrong, it's RUSTUP (
https://www.rust-lang.org/tools/install). The installer installed all the
dependencies including the C++ something.

Lynnell Neri
https://lynnellneri.com

**Comment by steveklabnik** [comment]
Rustup will not install the build tools for you, you have to install them yourself. It should have printed a message instructing you to do so.

To be sure, does this work for you?

```console
> cargo new foo
> cd foo
> cargo run
```

It should print "hello world".

**Comment by lynnellneri** [comment]
![image](https://user-images.githubusercontent.com/7625546/59111049-e0a99d00-8972-11e9-8677-2054daa50612.png)
![image](https://user-images.githubusercontent.com/7625546/59111083-ef904f80-8972-11e9-9b6f-1e866982c7c1.png)

Here's the output when I ran the commands.

**Comment by steveklabnik** [comment]
Yes; please go to the link I posted above, and install the tools, and try again!
