### ISSUE TITLE
wrangler publish: workers.api.error.script_not_found

### ISSUE THREAD

**Issue by holms** [cloudflare/wrangler#2039]
### 🐛 Bug report

I ain't do anything fancy just followed tutorial from here: https://egghead.io/lessons/cloudflare-set-up-a-new-cloudflare-workers-project-with-wrangler unable to continue a tutorial due to this error.

#### Describe the bug

wrangler publish fails

#### Reproduce the bug

A list of steps to reproduce the bug.

1. wrangler generate fbevents 
2. cd fbevents
3. wrangler config --api-key
4. add `account_id` to `wrangler.toml`  from `wrangler whoami` command
5. wrangler publish

```
holms@debian:~/Dev/gitlab/fbevents$ wrangler publish
✨  Basic JavaScript project found. Skipping unnecessary build!
Error: ⚠️  There was an error fetching your subdomain.
 Status Code: 404 Not Found
 Msg: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10007,
      "message": "workers.api.error.script_not_found"
    }
  ],
  "messages": []
}

```

#### Expected behavior

Command should work

#### Environment and versions

Fill out the following information about your environment.

* `Linux debian 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux`
* output of `wrangler -V`: `wrangler 1.19.0`
* output of `node -v`: `v14.17.5`
* content of `wrangler.toml`:

```
holms@debian:~/Dev/gitlab/fbevents$ cat wrangler.toml 
name = "fbevents"
type = "javascript"

account_id = "5a6f4ba42ccae8578392f47e0c54e6a4"
workers_dev = true
route = ""
zone_id = ""

```

**Comment by holms** [comment]
Ok solved, had to create a subdomain which this tutorial never covered.

**Comment by CoraHo** [comment]
hey, I had the same problem. How do you create a subdomian?

**Comment by CoraHo** [comment]
> hey, I had the same problem. How do you create a subdomian?

I got it!

**Comment by volkanger** [comment]
@CoraHo well, why don't you share how you got it? :D
