### ISSUE TITLE
Strange behavior generating to a existing directory

### ISSUE THREAD

**Issue by Menci** [cloudflare/wrangler#2051]
#### Describe the bug

When doing `wrangle generate` to a existing directory `test`, the behavior is strange. A TOML file is written to the existing directory but with the name field `test-1`. Everything other, plus another TOML file is written to a new directory `test-1` but with the name field `helloworld`. The newly created directory's TOML's type field is also wrong.

#### Reproduce the bug

```
$ wrangler -V
wrangler 1.19.1
$ mkdir wrangler
$ cd wrangler
$ mkdir test
$ wrangler generate --type=webpack test
 Creating project called `test-1`...
 Done! New project created /home/Menci/wrangler/test-1
$ find
.
./test
./test/wrangler.toml
./test-1
./test-1/.gitignore
./test-1/.prettierrc
./test-1/CODE_OF_CONDUCT.md
./test-1/LICENSE_APACHE
./test-1/LICENSE_MIT
./test-1/README.md
./test-1/index.js
./test-1/package.json
./test-1/wrangler.toml
./test-1/.cargo-ok
./test-1/.git
<.git sub-directories omitted>
./test-1/.git/HEAD
$ cat ./test/wrangler.toml
name = "test-1"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
$ cat ./test-1/wrangler.toml
name = "helloworld"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
```

#### Expected behavior

Wrangle should deny generating to a existing non-empty directory and success generating to a existing empty directory.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Manjaro Linux
* output of `wrangler -V`: `wrangler 1.19.1`
* output of `node -v`: `v16.7.0`

**Comment by nilslice** [comment]
Hi @Menci  - 

Thanks for reporting this. We'll do some further investigating.
