### ISSUE TITLE
Improve error message for invalid auth token

### ISSUE THREAD

**Issue by jkup** [cloudflare/wrangler#2054]
#### Describe the feature

I ran into a problem where I had an invalid auth_token in `~/.wrangler/config/default.toml`. I didn't know that file existed and whenever I would try to run a command like `wrangler dev` I would get:

`Error: ⚠️  Code 9109: Invalid access token`

Which wasn't super helpful. @threepointone helped me debug and showed me where the file was. Deleting it fixed my problem! Maybe we could update that message? Suggesting users delete that token? Or maybe even provide a `wrangler logout` command which will clean things up?

#### Describe the alternatives

Deleting the file and trying again worked great. I just didn't know the file existed.

**Comment by ocsfrank** [comment]
Looks like you read into my mind haha! I'm currently adding a logout feature for the OAuth support.

**Comment by ocsfrank** [comment]
Error message should be improved with #2060.

**Comment by threepointone** [comment]
Maybe this can be closed now?

**Comment by ocsfrank** [comment]
Yes, this should be solved.
