### ISSUE TITLE
change Wrangler build directory

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#206]
Currently the built worker end up in ./worker. However, that directory could be used by the user.

I would suggest to hide the directory, it's useful for debugging but not for the user.

**Comment by signalnerve** [comment]
Agreed. I wouldn't be surprised if people defaulted to using `worker/` as the workspace for their Workers in larger projects: can we just do `.build` or something similar? 

(Note that whatever change we do will involve some changes to the various templates: they all generally have `worker/` in `.gitignore`)

**Comment by xtuc** [comment]
Yes, if I remember correctly even a template uses `worker` for user code.

Using `.build` instead sounds good to me. Also using the os tempdir would make sense to me, I don't expect the user to commit them.

**Comment by granjef3** [comment]
People using [dollarshaveclub/cloudworker](https://github.com/dollarshaveclub/cloudworker) might want to use the output of the build to put into cloudworker, so maybe a public build directory is the best option here.

**Comment by johnelliott** [comment]
Using 1.8.1 I am noticing the same file created in `dist/` and `worker/` and haven't tracked down what is causing that behavior.

**Comment by xtuc** [comment]
@johnelliott it's expected. One is webpack's output the other is wrangler's output

**Comment by johnelliott** [comment]
Yeah I saw #640

**Comment by xortive** [comment]
closing since this is addressed by #1677, which will be going out as part of an RC in the near future
