### ISSUE TITLE
Wrangler npm global install fails when run as 'root'

### ISSUE THREAD

**Issue by whereisaaron** [cloudflare/wrangler#2063]
#### Describe the bug

If you try to install `wrangler` following the instructions here:

https://developers.cloudflare.com/workers/get-started/guide

with the command:

```
npm install -g @cloudflare/wrangler
```

The wrangler `npm` global install fails when run as 'root'. This includes the use case of building a docker image. This seems like a regression of the bug reported in #240. Based on that the problem appears to be that wrangler install tries to create `/root/.wrangler` as 'nobody' instead of 'root'.

The easiest workaround in to install using `yarn` which doesn't have this problem:
```
yarn global add @cloudflare/wrangler
```

another workaround is add extra options to the installer when installing as root https://github.com/cloudflare/wrangler/issues/240#issuecomment-559135179
```
npm install @cloudflare/wrangler --global --unsafe-perm --allow-root
```

#### Reproduce the bug

Create a minimal Dockerfile with just the `npm` install and try to build.

**Dockerfile**
```
FROM node:14-bullseye-slim
RUN npm install -g @cloudflare/wrangler
```

**Command:** `docker build .`

**Error:**
```
[+] Building 8.9s (6/6) FINISHED
 => [internal] load build definition from Dockerfile-foo                                                                                                  0.0s
 => => transferring dockerfile: 114B                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/node:14-bullseye-slim                                                                                  4.0s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                               0.0s
 => CACHED [1/2] FROM docker.io/library/node:14-bullseye-slim@sha256:1b2caf980f422bf707f9dc64879a0a4f9f748d6d3a4e504d8485aa71884c9ec8                     0.0s
 => ERROR [2/2] RUN npm install -g @cloudflare/wrangler                                                                                                   4.7s
------
 > [2/2] RUN npm install -g @cloudflare/wrangler:
#6 4.341 /usr/local/bin/wrangler -> /usr/local/lib/node_modules/@cloudflare/wrangler/run-wrangler.js
#6 4.353
#6 4.353 > @cloudflare/wrangler@1.19.2 postinstall /usr/local/lib/node_modules/@cloudflare/wrangler
#6 4.353 > node ./install-wrangler.js
#6 4.353
#6 4.515 internal/fs/utils.js:314
#6 4.515     throw err;
#6 4.515     ^
#6 4.515
#6 4.515 Error: EACCES: permission denied, mkdir '/root/.wrangler'
#6 4.515     at mkdirSync (fs.js:1009:3)
#6 4.515     at Binary._getInstallDirectory (/usr/local/lib/node_modules/@cloudflare/wrangler/binary-install.js:52:13)
#6 4.515     at Binary.install (/usr/local/lib/node_modules/@cloudflare/wrangler/binary-install.js:78:26)
#6 4.515     at install (/usr/local/lib/node_modules/@cloudflare/wrangler/binary.js:50:10)
#6 4.515     at Object.<anonymous> (/usr/local/lib/node_modules/@cloudflare/wrangler/install-wrangler.js:4:1)
#6 4.515     at Module._compile (internal/modules/cjs/loader.js:1072:14)
#6 4.515     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
#6 4.515     at Module.load (internal/modules/cjs/loader.js:937:32)
#6 4.515     at Function.Module._load (internal/modules/cjs/loader.js:778:12)
#6 4.515     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
#6 4.515   errno: -13,
#6 4.515   syscall: 'mkdir',
#6 4.515   code: 'EACCES',
#6 4.515   path: '/root/.wrangler'
#6 4.515 }
#6 4.585 npm ERR! code ELIFECYCLE
#6 4.585 npm ERR! errno 1
#6 4.589 npm ERR! @cloudflare/wrangler@1.19.2 postinstall: `node ./install-wrangler.js`
#6 4.589 npm ERR! Exit status 1
#6 4.589 npm ERR!
#6 4.589 npm ERR! Failed at the @cloudflare/wrangler@1.19.2 postinstall script.
#6 4.589 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#6 4.602
#6 4.602 npm ERR! A complete log of this run can be found in:
#6 4.602 npm ERR!     /root/.npm/_logs/2021-09-06T07_01_31_977Z-debug.log
------
executor failed running [/bin/sh -c npm install -g @cloudflare/wrangler]: exit code: 1
```

#### Expected behavior

Expected `npm` to successfully install `wrangler`.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Linux
* output of `wrangler -V`: 1.19.2
* output of `node -v`: 14.17.6
* content of `wrangler.toml`: N/A

**Comment by whereisaaron** [comment]
@magicfredo [suggests another workaround](https://github.com/cloudflare/wrangler/issues/240#issuecomment-559135179) that enables using npm. It's not pretty but it works 🎉  
```
npm install @cloudflare/wrangler --global --unsafe-perm=true --allow-root
```

e.g. Dockerfile:
```
FROM node:14-bullseye-slim
RUN npm install @cloudflare/wrangler --global --unsafe-perm=true --allow-root
```

Really the `npm` installer should at a minimum work with the official `node.js` container images! But this is a workaround that could be added to docs at: https://developers.cloudflare.com/workers/get-started/guide

https://github.com/cloudflare/wrangler/issues/240#issuecomment-559135179

**Comment by diracs-delta** [comment]
Same here on `node:14-alpine`. I understand the Wrangler dev team wants developers to install this package globally, but there really should be out-of-the-box functionality in Docker images. CI/CD is an extremely common software practice these days, and it'd be nice if this would "just work".

**Comment by nilslice** [comment]
Thanks for reporting - and I agree. Will bring this to the team to discuss.

/cc
@caass 
@Electroid

**Comment by threepointone** [comment]
Notes - 
- Even when installing with npm, we download the binary and manually save it to `~/.wrangler`, which we shouldn't. That yarn uses the 'right' user, while a workaround, shouldn't be the way forward (indeed, it means postinstall scripts executed with yarn will have root, which is kinda scary). We should probably take a leaf from esbuild's playbook and make packages for each distribution, that solves it neatly. (with the knock on effect that versioning/caching will work properly) 
- We also use `.wrangler` as a store for config, specifically api tokens. In a CI/CD scenario, I'm assuming that config won't even be populated, because the tokens would be passed in with environment variables. 

So there are 2 action items here to resolve this 
- We should fix how we 'install' the binary and not store it in `.wrangler`. 
- We shouldn't throw and error when we fail to make the folder; it should log a warning and carry on.

**Comment by threepointone** [comment]
Further - we shouldn't be encouraging global installs; it should be local to the app/package being developed. That'll take some more work.

**Comment by diracs-delta** [comment]
> we shouldn't be encouraging global installs; it should be local to the app/package being developed. That'll take some more work

Absolutely agree. Making `wrangler` behave more similarly to other NPM packages would make this way more dev-friendly and intuitive 😄

**Comment by threepointone** [comment]
This is how we're dealing with this in the next major version of wrangler: 

- We do not attempt to create `~/.wrangler` on install
- On first usage, we only attempt to create the configuration file if you haven't explicitly passed `CF_API_TOKEN`/`CLOUDFLARE_API_TOKEN`
- We encourage folks to use wrangler like any other npm package; NOT installed with `-g`, and as a regular dependency of their project. The executable code is then installed under `node_modules` as expected (You can still install it globally if preferred, but even then it uses node's global `node_modules` directory, not `~/.wrangler`)

You can try this today with `npm install wrangler@beta` (note that we don't require the `@cloudflare/` scope). We're actively developing this at https://github.com/cloudflare/wrangler2, and hope to go to GA soon.

**Comment by threepointone** [comment]
Closing this since wrangler v2 is now in GA.
