### ISSUE TITLE
Change bundler

### ISSUE THREAD

**Issue by janat08** [cloudflare/wrangler#2067]
#### Describe the feature
Change webpack to rollup so that you could use template literal templating, and get sensible error message. Potentially you also get customization with plugin system. I don't really remember what error messages webpack failed me with, but I imagine it's just reknown for it.

#### Describe the alternatives
You could use parceljs that simply tries to be 0 config bundler, and it's probably what you'd want for cli tool that does bundling and not webpack.

**Comment by nilslice** [comment]
Thanks for the suggestion, @janat08! We have some early ideas for improvement along these lines. Will definitely bring your idea to the broader team internally. 

cc/ @threepointone

**Comment by threepointone** [comment]
We're looking closely at this, but for now you're free to use `'javascript'` as the 'type' in `wrangler.toml` and then use rollup yourself as the tool to build your worker. 

I'll leave this issue open until we have anything to announce, and potentially gather feedback

**Comment by janat08** [comment]
Btw there's a duplicate issue for changing to esmbuild. Then there's the issue of sourcemap being missing. Anyway crappy error messages are not at all conducive to development with no sourcemaps to boot.

**Comment by threepointone** [comment]
Closing this since we've completely redone this with wrangler v2 (which is internally powered by esbuild)
