### ISSUE TITLE
"Cannot find name" Error when trying to publish worker with vars

### ISSUE THREAD

**Issue by MauriceArikoglu** [cloudflare/wrangler#2072]
#### Describe the bug

Following the docs here https://developers.cloudflare.com/workers/platform/environment-variables and adding vars as shown, these vars cannot be used. Whenever I try to run or publish the code, wrangler errors when building. I am using typescript.

Output:
```
ERROR in /Users/me/projects/proj/src/handler.ts
./src/handler.ts 3:27-38
[tsl] ERROR in /Users/me/projects/proj/src/handler.ts(3,28)
      TS2304: Cannot find name 'EXAMPLE_ENV_VAR'.
 @ ./src/index.ts 3:18-38
```
wrangler.toml:
```
name = "proj"
type = "javascript"
account_id = "123456"

[vars]
EXAMPLE_ENV_VAR = "foobar"
```

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Run 'wrangler generate ip-collector https://github.com/EverlastingBugstopper/worker-typescript-template'
2. Set a [vars] environment variable
3. Use it in handler.ts via console.log

#### Expected behavior

wrangler doing its magic and defining the global consts correctly

#### Environment and versions

Fill out the following information about your environment.

wrangler 1.19.2
node 14.16

**Comment by koeninger** [comment]
That's not a wrangler issue, it's a typescript compilation issue. You need to declare global variables.

https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html#global-variables

**Comment by MauriceArikoglu** [comment]
@koeninger maybe consider enhancing the documentation here? It's kinda hard if you follow the documentation and it unexpectedly doesn't work.

Does this mean I can put a `declare EXAMPLE_ENV_VAR: string;` at the top of my handler.ts and I am fine?! The way these cars work is just intransparent coming from the docs..

**Comment by koeninger** [comment]
No, you need 
declare **var** EXAMPLE_ENV_VAR: string
as the typescript docs say.

The workers docs you linked https://developers.cloudflare.com/workers/platform/environment-variables say several times that environment variables are global variables.  Understanding how typescript type definitions for global variables work is ultimately your responsibility as a developer choosing to use typescript, and is not Workers specific. It's possible the Workers docs might be extended in the future to offer all of the examples in typescript or other languages, but they currently are javascript centric.
