### ISSUE TITLE
wrangler 1.19.3 requires at least Rust 1.53.0 to build

### ISSUE THREAD

**Issue by mattlockyer** [cloudflare/wrangler#2076]
### 🐛 Bug report
Tried to update wrangler using cargo

#### Describe the bug

![image](https://user-images.githubusercontent.com/321340/133805904-858ad8a6-e22d-498d-b986-bbd4a33e85dc.png)

#### Reproduce the bug

A list of steps to reproduce the bug.

Try to update wrangler using cargo on ubuntu 20.04

#### Expected behavior

It updates

#### Environment and versions

Above

**Comment by jyn514** [comment]
@mattlockyer arrays implement IntoIterator starting in 1.53: https://github.com/rust-lang/rust/blob/master/RELEASES.md#libraries-2

cc @Electroid, I don't know what the policy about support Rust versions is for wrangler.

**Comment by mattlockyer** [comment]
My fault, must be time to upgrade 😏

**Comment by mattlockyer** [comment]
Confirmed, installed successfully. Sorry forgot to include my version number in the OP.

**Comment by mikekasprzak** [comment]
There really needs to be an error prompt saying you need a new version of Rust before it builds 400 packages.

**Comment by jyn514** [comment]
Cargo is about to stabilize rust-version in Cargo.toml for 1.56: https://github.com/rust-lang/cargo/pull/9732
But it won't help for any toolchains earlier than that; cargo doesn't give us a way to run code before dependencies are built.

**Comment by mikekasprzak** [comment]
That's good to hear. Better than nothing.
