### ISSUE TITLE
API URL as parameter

### ISSUE THREAD

**Issue by boemekeld** [cloudflare/wrangler#2084]
#### Describe the feature

Allow setting the API URL (https://api.cloudflare.com) via parameter or configuration file.

#### Why?

Cloudflare access tokens permissions are limited, it is not possible for example to create an access token with access only to a certain worker or subdomain.
To work around this, we created a middleware that handles authorization and adds the access token to the request.
However, to use the middleware, we need to set a different API URL to wrangler.

**Comment by nilslice** [comment]
@boemekeld you can now override the API base endpoint via environment variable, and you can limit a tokens capabilities via restricting scopes with the new `wrangler login` OAuth2 flow. Maybe @ocsfrank can provide some more insight on this?

**Comment by ocsfrank** [comment]
For sure! To see the list of available scopes you can use `wrangler login --scopes-list`. Then, you can limit the scopes by running `wrangler login --scopes scope1 scope2 scopeN`. For example `wrangler login --scopes account:read user:read` will give  `account:read` and `user:read` scopes only to your OAuth token.

To set the API URL, you can set the environment variable `CF_BASE_API_URL=$API_URL` -- e.g. `export CF_BASE_API_URL=https://api.cloudflare.com`.

**Comment by boemekeld** [comment]
@nilslice @ocsfrank thank you guys, it helped me a lot.
