### ISSUE TITLE
Default React/Wrangler Template uses "Feature-Policy", "none", which may be causing mixed content HTTPS warnings due to invalid values. 

### ISSUE THREAD

**Issue by LKNSI** [cloudflare/wrangler#2089]
#### Describe the bug

Default React/Wrangler Template uses "Feature-Policy", "none", causing mixed content HTTPS warnings due to invalid values. 

#### Reproduce the bug

Using the most latest version of wrangler, with the default config set out below.

```text
name = ""
type = "webpack"
account_id = ""
workers_dev = false
route = "/*"
zone_id = ""

[site]
bucket = "./dist"
entry-point = "workers-site"

```

Creates a default Workers JS file, with the following line(s) causing the issue.

![image](https://user-images.githubusercontent.com/3456318/135153788-33f2295c-08a3-4097-a209-889e0ef5ba2a.png)

Causes a mixed HTTPS content warning - 

![image](https://user-images.githubusercontent.com/3456318/135154194-4159967f-bb42-4294-a433-8315796f5f02.png)

And is currently not supported for the option "none" as described here (or rather, not in the format presented when omitting the directive of feature-policy):

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy#browser_compatibility

#### Expected behavior

My interpretation is that a directive is missing before the "none".

Equally, it is experimental, and maybe should not be included on production.

**Comment by nilslice** [comment]
@LKNSI - Hey, figuring you found a path forward - but if not, feel free to start another issue on the `site` template repo: https://github.com/cloudflare/worker-sites-template
