### ISSUE TITLE
CF_API_BASE_URL not implemented in file upload

### ISSUE THREAD

**Issue by boemekeld** [cloudflare/wrangler#2090]
#### Describe the bug

The environment variable CF_API_BASE_URL are not implemented in file upload requests.

#### Reproduce the bug

set CF_API_BASE_URL=https://{YOU_PROXY_MIDDLEWARE}/client/v4/
or
export CF_API_BASE_URL=https://{YOU_PROXY_MIDDLEWARE}/client/v4/

run wrangler publish

it will work and return success for the firsts requests like:
Using namespace for Workers Site "XXXX" - Success

but it will not work for "Uploading site files" step.

#### Expected behavior

CF_API_BASE_URL environment variable should impact all requests made by wrangler to Cloudflare API.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Windows and Linux
* output of `wrangler -V`: 1.19.3

**Comment by boemekeld** [comment]
@nilslice @ocsfrank hi guys, could you help me? I can't use the CF_API_BASE_URL.

**Comment by boemekeld** [comment]
I believe that is related to this: https://github.com/cloudflare/wrangler/blob/master/src/upload/mod.rs#L20

**Comment by threepointone** [comment]
This should be something we fix, I'll assign it to myself and have a look next week. 

Side note: I understand you'd used this to implement your own authorisation hooks for developers working on the project. While we may fix this one missing usage for now, I have to say that CF_BASE_API wasn't meant to be a public api, and there's no guarantee that it'll stay in the far future. You don't have to worry about it breaking soon, but please don't build anything business-critical on it. As an idea, we're discussing building programmable authentication layers which should help in your usecase, but no concrete plans just yet.

**Comment by boemekeld** [comment]
@threepointone thank you for your response, we appreciate that.

Unfortunately, building an identity proxy with a custom authentication and authorization layer was the best solution we found for our business at this time.

It would be great to have programmable authentication layers! I hope this evolves!

**Comment by threepointone** [comment]
I found about 10+ places where this will have to be changed. This feels a little brittle, I'll have to get back to this issue in a while.

**Comment by threepointone** [comment]
This is now properly fixed in wrangler v2, so we recommend using that. More details at https://github.com/cloudflare/wrangler2.
