### ISSUE TITLE
KV bulk delete override user confirm input

### ISSUE THREAD

**Issue by andersquist** [cloudflare/wrangler#2095]
#### Describe the feature

Adding a flag so that `wrangler kv:bulk delete` don't ask for user confirmation when deleting key value pairs. This would be really nice to have in an automation use case.

#### Describe the alternatives

Using the Cloudflare API and do the bulk delete that way. It works but it would be nice if one could get things done solely using the Wrangler CLI.

**Comment by threepointone** [comment]
Happy to accept a PR that adds a `--force` flag for this operation.

**Comment by threepointone** [comment]
We released this in 1.19.4, thanks for the PR!
