### ISSUE TITLE
Exit code zero when wranger fails due to permissions error.

### ISSUE THREAD

**Issue by Chekote** [cloudflare/wrangler#2097]
#### Describe the bug

When wrangler is run and exits due to a permission error, the exit code is zero.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Checkout any wrangler project with NPM dependencies (but do not install NPM packages)
2. CD into the project
3. Change to a user that does not have permission to write to the project
4. Run wrangler publish
5. Wrangler will fail with a permissions error when it tries to call `npm install` 

#### Expected behavior

I should get a non-zero exit code.

#### Environment and versions

* operating system: Docker, Alpine 3.11.12
* output of `wrangler -V`: 1.19.3
* output of `node -v`: 14.18.0
* content of `wrangler.toml`: REDACTED

#### Implications
This causes automated deployments to consider the command a success when it has actually failed.

**Comment by threepointone** [comment]
I believe we've fixed this wrangler v2, so I'm going to close this issue.
