### ISSUE TITLE
How to unpublish a Workers script

### ISSUE THREAD

**Issue by DrDaveD** [cloudflare/wrangler#210]
Now that there can be any number of Workers scripts, how can we delete one we no longer want (in my own domain)?  I don't find it in the documentation or in wrangler --help.

**Comment by DrDaveD** [comment]
Ah, I found it in the web api of dash.cloudflare.com, under "...".  It required me to create a workers.dev domain first, which I didn't think I was going to need, but it works.  Anyway it would probably be good to document it and/or add a CLI interface.

**Comment by xtuc** [comment]
There no subcommand in Wrangler to do it. I would suggest going to the UI and deleting what script/route you don't need anymore.

**Comment by ashleygwilliams** [comment]
we can implement this in the CLI relatively simply. i think this is an excellent feature request- let's plan on it for 1.1.0.

we can "unpublish" in 2 ways:
- we can delete the script (workers.dev or custom domain)
- we can make the script not public on a domain (workers.dev)

i propose:

`workers unpublish`
- workers.dev, removes being public on subdomain
- custom domain, deletes route script is associated with 

`workers delete`
- for both workers.dev and custom domain, deletes the script from the account

thoughts?

**Comment by xtuc** [comment]
I would personally be against unpublishing. Deleting a domain, route or a script is dangerous, if you do it on mistake it will take down your prod. 

Now that workers are free, I don't see a reason to urgently unpublish a worker. 

I'm happy with people doing that in UI tho.

**Comment by EverlastingBugstopper** [comment]
Perhaps you could have an "Are you sure" prompt that requires you to type in the name of the script again. I think this would be useful.

**Comment by leo-ar** [comment]
This would be a convenient feature. I was about to open a feature request for it.
Right now I'm accomplishing the same thing by scripting requests to the API. In addition to removing the scripts the KVs have to be removed too.
Although writing these scripts it's a one time cost, it'd be convenient not having to do it 😸

**Comment by alonsohki** [comment]
This is a key feature to have for deployment pipelines where feature branches are automatically deployed for preview. What's the current status?

**Comment by yafanasiev** [comment]
+1. We are thinking about moving some of our apps to worker sites, and not having a convenient way to remove the feature branches deployments is a little discouraging.

**Comment by halzy** [comment]
This would be a fantastic! I have an app that is completely on CF Workers and having to log into the UI to delete the CI environments that are spun up is an annoyance. If there is a confirmation step, please also have a `-y` flag to automatically approve it.

**Comment by nhoughto** [comment]
yeah very strange that you can create a worker but there is no way of deleting it, unpublishing isn't a risk its the minimum required to control the full lifecycle of a worker script programmatically.

**Comment by geoffreysamper** [comment]
This feature is really needed when you want to enable ci/cd. I hope it will be available soon.

**Comment by danielnaab** [comment]
I agree that there should be a way for Wrangler to clean up after itself, and a confirmation prompt is all that's required to avoid accidental deletions. This feels like a strange omission from a IOC tool.
