### ISSUE TITLE
Setup wrangler outside of global

### ISSUE THREAD

**Issue by lmcardle** [cloudflare/wrangler#2103]
#### Describe the feature

The current path for installing wrangler is to install it globally on your system, `npm install -g @cloudflare/wrangler`. Likewise, inside a project when you log into wrangler, wrangler puts this auth token in a global folder, `/Users/{account-name}/.wrangler/config/default.toml`. In Javascript projects, this is considered legacy and users should generally avoid installing packages and making configurations globally, preferring instead to install and configure them local to a project. 

The requested workflow would be something like:
Starting in a projects folder, i.e. `/Users/{account-name}/projects`

`npx @cloudflare/wrangler generate hello-world`

The above command would create a `hello-world` folder and init wrangler inside of there. 

From within the `hello-world` project folder, run `npx @cloudflare/wrangler login`. The result of running this command would create a `wrangler-auth.toml` file that contains the auth info for your project. Likewise this file would be added to `.gitignore`.

#### Describe the alternatives

The alternative is to keep the existing process and install and configure wrangler globally. The issue with this approach is A) it is not considered best practice in the industry and B) it does not scale for situations where as a developer I am doing work against multiple cloud flare accounts.

**Comment by Chekote** [comment]
@threepointone are there any updates on the status of this? Having to install Wrangler globally is causing quite a few headaches for our projects and it would be awesome to be able to just install and run it as a local NPM package. 🙏

**Comment by threepointone** [comment]
There are a couple of options here - 
- Install using cargo, or download the binary manually https://developers.cloudflare.com/workers/cli-wrangler/install-update. 
- With that, pass `CF_ACCOUNT_ID` and `CF_API_TOKEN` manually as environment vars when calling `wrangler`. 

This should let you do isolated development with wrangler, and with multiple accounts. That said, you'd have to set up this stuff by yourself. 

- We're spending all our time right now on the [wrangler 2 rewrite](https://github.com/cloudflare/wrangler2) which should be Generally Available in Q1; this already is built to be used as a local dependency in your `package.json`. You can use `CF_ACCOUNT_ID` and `CF_API_TOKEN` with that if you'd like to use multiple cloudflare accounts; and we may build a more natural feature for multiple cloudflare accounts later too.

**Comment by Chekote** [comment]
That’s awesome. That’s for the prompt reply. I’ll wait on Wrangler 2, as that sounds like a better fit for us than adding Cargo to our pipeline.

**Comment by neenhouse** [comment]
+1 to this feature.  This will make CI much simpler with being able to install and run wrangler local to repository where worker resides.

**Comment by threepointone** [comment]
This is how we're dealing with this in the next major version of wrangler: 

- We do not attempt to create `~/.wrangler` on install
- On first usage, we only attempt to create the configuration file if you haven't explicitly passed `CF_API_TOKEN`/`CLOUDFLARE_API_TOKEN`
- We encourage folks to use wrangler like any other npm package; NOT installed with `-g`, and as a regular dependency of their project. The executable code is then installed under `node_modules` as expected (You can still install it globally if preferred, but even then it uses node's global `node_modules` directory, not `~/.wrangler`)

You can try this today with `npm install wrangler@beta` (note that we don't require the `@cloudflare/` scope). We're actively developing this at https://github.com/cloudflare/wrangler2, and hope to go to GA soon.

**Comment by threepointone** [comment]
Closing this since wrangler v2 is now in GA.
