### ISSUE TITLE
Wrangler tail - overflow when adding duration to instant

### ISSUE THREAD

**Issue by marcotuna** [cloudflare/wrangler#2109]
#### Describe the bug

When attempting to get the logs of the running wrangler service it is throwing an error. (It worked previously)

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Run `wrangler tail`

```
⠓ Creating tail...

Oops! Wrangler encountered an error:

panicked at 'overflow when adding duration to instant', library/std/src/time.rs:374:33

Please help Cloudflare debug this issue by submitting the error report
(/home/unknown/.wrangler/errors/1634823595280.log)

To submit this error report to Cloudflare, run:

    $ wrangler report
```

#### Expected behavior

Show logs of incoming requests to the worker

#### Environment and versions

Fill out the following information about your environment.

* operating system:
* output of `wrangler -V`: wrangler 1.19.4
* output of `node -v`: v16.11.1
* content of `wrangler.toml`:

```
name = "REDACTED"
type = "webpack"
zone_id = "REDACTED"
account_id = "REDACTED"
route = ""
workers_dev = true
webpack_config = "webpack.config.js"
compatibility_date = "2021-10-20"
```

**Comment by raRaRa** [comment]
Same issue here.

**Comment by piotrcichosz** [comment]
+1, sent report

**Comment by threepointone** [comment]
This error does not occur with wrangler v2, which is now in GA. You can test it out today by running `npx wrangler tail <worker name>` in your terminal. In general we now recommend projects tart moving our to wrangler v2. Closing this issue.
