### ISSUE TITLE
wrangler.toml firing wrong error messages on publish

### ISSUE THREAD

**Issue by adaptive** [cloudflare/wrangler#211]
**wrangler.toml** has `zone_id` and `account_id` missing `routes`

`Error: ErrorMessage { msg: "You must provide a zone_id in your wrangler.toml before publishing!" }`

**wrangler.toml** has  `account_id` `routes` missing `zone_id`

`Error: ErrorMessage { msg: "⛔ There was an error featching your project\'s routes.\n Status Code: 400 Bad Request\n Msg: {\"success\":false,\"errors\":[{\"code\":7003,\"message\":\"Could not route to \\/zones\\/workers\\/routes, perhaps your object identifier is invalid?\"},{\"code\":7000,\"message\":\"No route for that URI\"}],\"messages\":[],\"result\":null}" }`

**Comment by ashleygwilliams** [comment]
thanks for filing and sorry you are running into this! i am pretty sure i know where the offending code is and will work to fix it- but if you were interested in submitting a patch i'd be happy to help mentor you! let me know!

**Comment by adaptive** [comment]
@ashleygwilliams I will adventure with your PR challenge. I accept you mentoring 🍕

**Comment by derit** [comment]
i have solution for this error, you need fill in the **wrangler.toml** settings
zone_id
account_id and **route** 

cc @ashleygwilliams

**Comment by longbkit** [comment]
I am experiencing the same too. Default template comes with empty zone_id and route but no clear instructions on the document.
