### ISSUE TITLE
wrangler generate aborts with Error: Bad CPU type in executable (darwin/aarm64)

### ISSUE THREAD

**Issue by vieira** [cloudflare/wrangler#2120]
### 🐛 Bug report
```
$ brew install cloudflare-wrangler
$ wrangler generate
⬇️   Installing cargo-generate v0.5.0...
Error: Bad CPU type in executable (os error 86)
```

#### Describe the bug

It seems that the executable `cargo-generate` on which `wrangler generate` depends does not support (darwin/aarm64) resulting in a Bad CPU type error when ``wrangler generate` is run in darwin/aarm64.

#### Reproduce the bug

```
$ brew install cloudflare-wrangler
$ wrangler --version
wrangler 1.19.4
$ wrangler generate
⬇️   Installing cargo-generate v0.5.0...
Error: Bad CPU type in executable (os error 86)
```

#### Expected behavior

Expected `wrangler generate` to complete without errors.

#### Environment and versions

* operating system: macOS 12.0.1
* output of `wrangler -V`: wrangler 1.19.4
* output of `uname -a`:  Darwin spot.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

**Comment by threepointone** [comment]
We have much wider platform support with wrangler v2, however we haven't yet made a build for it to be on homebrew/cargo. More info at https://github.com/cloudflare/wrangler2
