### ISSUE TITLE
Wrangler whoami - missing field organizations

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/wrangler#2131]
#### Describe the bug
It seems like the account API changed and now `wrangler whoami` is erroing with:
> 	Error: ⚠️  Error: error decoding response body: missing field `organizations` at line 1 column 492

#### Reproduce the bug
Run `wrangler whoami`

#### Expected behavior
It should show the authenticated user and not error

#### Environment and versions

Fill out the following information about your environment.

* output of `wrangler -V`: wrangler 1.19.4
* output of `node -v`: v16.13.0

**Comment by OneCent01** [comment]
Seeing the error on macOS Big Sur. I need my account ID to set up wrangler config files, but this is the command all resources I've seen use to get it. Is there another way? The account_id doesn't exist in the default.toml file on my system at all. It only has: `oauth_token`, `refresh_token`, and `expiration_time`.

**Comment by threepointone** [comment]
Sorry about this y'all, we'll investigate and see what's broken. 

To workaround this and get your account id, visit https://dash.cloudflare.com/ and choose your domain/zone, it should be in the right sidebar.

**Comment by Electroid** [comment]
Hello, our teams are working on a hot-fix! There was a bug with the API schema.

**Comment by Electroid** [comment]
Fixed! Let us know if you continue to have any issues.

**Comment by WalshyDev** [comment]
Can confirm, appreciate the quick fix :+1:
