### ISSUE TITLE
Win32 path escape bug and a fix proposal

### ISSUE THREAD

**Issue by fikisipi** [cloudflare/wrangler#2136]
Building a Page Function is impossible on Windows because paths during compilation aren't escaped properly:

    Compiling worker:
    import { onRequest as __gh_ts_onRequest } from "C:\Users\user\cf\functions\gh.ts"
    routes.mjs:1:47: error: Could not resolve      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I cannot find the repo containing `@cloudflare/pages-functions-compiler` but the fix is:

1. Navigate to `plinko.mjs` and the function generating the routes.mjs source:
```ts
function generateRoutesModule(importMap, routes) {
  return `${[...importMap.values()].map(({ filepath, name: name2, identifier }) => `import { ${name2} as ${identifier} } from "${filepath}"`).join("\n")
}
```

2. Remove the manual quotes around `filepath`, and use `JSON.stringify(filepath)` which always forms a valid JavaScript string literal.

**Comment by WalshyDev** [comment]
Hey,

This is the old Wrangler repo. This issue has already been reported on Wrangler v2's repo here: https://github.com/cloudflare/wrangler2/issues/32

**Comment by fikisipi** [comment]
@WalshyDev Thanks, closing in favor of it.
