### ISSUE TITLE
`wrangler dev` does not have any value within the `request.header` map 

### ISSUE THREAD

**Issue by awwong1** [cloudflare/wrangler#2137]
#### Describe the bug

When running `wrangler dev` and querying my worker async function, the `headers` object is empty despite having values set from my browser.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Clone https://github.com/awwong1/workers-chat-demo `git clone https://github.com/awwong1/workers-chat-demo`
2. Run `yarn`, `wrangler publish`, `wrangler dev`
3. Open up a browser and navigate to `localhost:8787`. Observed the logged console output.

All requests show an empty header object for the console logged request.

```json
{
  "cf": {
    "clientTcpRtt": 1,
    "longitude": "-113.52270",
    "latitude": "53.45900",
    "tlsCipher": "ECDHE-ECDSA-AES128-GCM-SHA256",
    "continent": "NA",
    "asn": 6327,
    "clientAcceptEncoding": "gzip",
    "country": "CA",
    "tlsClientAuth": {
      "certIssuerDNLegacy": "",
      "certIssuerSKI": "",
      "certSubjectDNRFC2253": "",
      "certSubjectDNLegacy": "",
      "certFingerprintSHA256": "",
      "certNotBefore": "",
      "certSKI": "",
      "certSerial": "",
      "certIssuerDN": "",
      "certVerified": "NONE",
      "certNotAfter": "",
      "certSubjectDN": "",
      "certPresented": "0",
      "certRevoked": "0",
      "certIssuerSerial": "",
      "certIssuerDNRFC2253": "",
      "certFingerprintSHA1": ""
    },
    "tlsExportedAuthenticator": {
      "clientFinished": "fd827293dfa572b8069cbcf303fb270717626ad3252a2db9ec36b829d6bf9d88",
      "clientHandshake": "a9ff780b5f9454bd6049b3cffe67ea65f6c0819140f7c305cecf7154d5e54726",
      "serverHandshake": "1af272ad73386bb7dbbe0d3d34ca70253b3e5a7263fe4079a3a331ada8082e0f",
      "serverFinished": "64e11d0a6859692f31f1d1d16048237cd1bfd0e7e1a790a88b1d84a2d7f9ac4a"
    },
    "tlsVersion": "TLSv1.2",
    "colo": "YYZ",
    "timezone": "America/Edmonton",
    "city": "Edmonton",
    "edgeRequestKeepAliveStatus": 1,
    "requestPriority": "",
    "httpProtocol": "HTTP/1.1",
    "region": "Alberta",
    "regionCode": "AB",
    "asOrganization": "Shaw Communications",
    "postalCode": "T6J"
  },
  "signal": {
    "aborted": false
  },
  "fetcher": {},
  "redirect": "manual",
  "headers": {},
  "url": "https://edge-chat-demo.udia.workers.dev/favicon.ico",
  "method": "GET",
  "bodyUsed": false,
  "body": null
}
 
```

#### Expected behavior

Request headers should match the browser sent request headers.

<img width="1440" alt="Screen Shot 2021-11-22 at 12 50 02 PM" src="https://user-images.githubusercontent.com/2760111/142925759-543f3f37-59d6-4797-9b19-b34e03e6ee92.png">

#### Environment and versions

Fill out the following information about your environment.

* operating system: `sw_vers`
  ```text
  ProductName:	macOS
  ProductVersion:	12.0.1
  BuildVersion:	21A559
  ```
* output of `wrangler -V`: `wrangler 1.19.5`
* output of `node -v`: `v16.13.0`
* content of `wrangler.toml`: https://github.com/awwong1/workers-chat-demo/blob/master/wrangler.toml

EDIT: This problem does not occur when using miniflare.

**Comment by mattbdc** [comment]
This also occurs with Cloudflare Pages Functions context.request.headers map for onRequest is empty. Very difficult to test things like Auth tokens etc.. (e.g. dev environment vs production behind access)

**Comment by awwong1** [comment]
Closing this as non-issue.
Expected behaviour of console.log on headers object should return the `'{}'` string. Need to use iterator to see the key/value pairs.

https://developer.mozilla.org/en-US/docs/Web/API/Headers
