### ISSUE TITLE
Wrangler not compatible with web3 library

### ISSUE THREAD

**Issue by rosman83** [cloudflare/wrangler#2141]
#### Describe the bug

I am encountering issues when trying to use Wrangler to compile a cloudflare worker script requiring web3 as a dependency when set to the webpack mode.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Create blank worker project
2. require `web3` as a dependency. ex `const web3 = new (require("web3"))()`
3. See error below when running `wrangler dev` :
```
Error: Something went wrong with the request to Cloudflare...
Uncaught ReferenceError: window is not defined
  at line 40
  at line 1 in a
  at line 31
  at line 1 in a
  at line 10
  at line 1 in a
  at line 31
  at line 1 in a
  at line 31
  at line 1 in a
 [API code: 10021]
```

#### Expected behavior

Web3 utilities should work for cryptographic API functions such as signing messages and hashing.

#### Environment and versions

* operating system: windows
* output of `wrangler -V`: wrangler 1.19.5
* output of `node -v`: v16.6.2
* content of `wrangler.toml`:
```
name = "XXX"
type = "webpack"

account_id = "XXX"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-24"

```

**Comment by koeninger** [comment]
The Workers runtime doesn't have a global variable `window` (there's no browser window in a worker)

Depending on what the library you're trying to use is trying to do with `window`, you may be able to work around this by adding

```
const window = this;
```

in global context at the very beginning of your script.

If the library is just trying to use things like e.g. `window.crypto` this should work fine.  Other properties of window may not make sense in the Workers context and thus may not exist.

**Comment by threepointone** [comment]
The `web3` package is specifically built to be used in a browser context, and to connect with browser based wallets. You should file an issue at https://github.com/ChainSafe/web3.js asking them to provide a Workers compatible build, complete with usage instructions. Closing this issue.

**Comment by walletprotect** [comment]
@threepointone , are you aware of any JSON-RPC libraries that are for V8 that I could test in a Worker?

**Comment by BevanG** [comment]
@threepointone , are you aware of any web3 / JSON-RPC V8 packages that I could test on a Worker?
