### ISSUE TITLE
durable objects bindings not applied for the environment

### ISSUE THREAD

**Issue by domenkozar** [cloudflare/wrangler#2142]
If I have 

```
[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

[env.staging]
zone_id = ...
route = ...
```

Then running `wrangler publish -e staging` doesn't create the bindings.

Once I add

```
[env.staging]
durable_objects.bindings = [{name = "COUNTER", class_name = "Counter"}]
```

It works, but that's absolutely not clear from documentation.

I would expect `[durable_objects]` to be applied to all environments, same as other sections.

**Comment by threepointone** [comment]
We should make it more obvious in the docs that stuff like durable objects and kv namespaces aren't inherited by environments. Even wrangler should warn you when you're missing matching bindings across envs. Thanks for this report!

**Comment by janat08** [comment]
Using syntax similar to kv for setting it on different environments doesn't work either. It gives you an error that you can't do that.
