### ISSUE TITLE
wrangler login stalls on an error

### ISSUE THREAD

**Issue by mikedubcurry** [cloudflare/wrangler#2143]
#### Describe the bug
After installing the latest version of wrangler via `npm i @cloudflare/wrangler -g` and creating an account for cloudflare, I ran `wrangler login` which opened a new tab in Chrome. When I click "Allow", I am returned a blank Error page with no message. The terminal hangs, still prompting me to open a browser window.  It seems i can use a global API key but the docs say it is not recommended. 

#### Reproduce the bug

A list of steps to reproduce the bug.

1. create a fresh cloudflare account and run `npm install -g @cloudflare/wrangler`. 
2. run `wrangler login` in a terminal and confirm you want to open a browser tab.
3. log in to cloudflare and click Allow

#### Expected behavior

After clicking "Allow", the browser tab should close or prompt me to return to the terminal with my credentials saved to my computer.

#### Environment and versions

Fill out the following information about your environment.

* operating system: Pop!_OS 21.04
* output of `wrangler -V`: wrangler 1.19.5
* output of `node -v`: v14.16.0
* content of `wrangler.toml`: N/A since Im not working in a project, just logging in.

**Comment by threepointone** [comment]
That's weird behaviour, sorry about that. I can't reproduce it here. It's possible this was an intermittent error. Could you try again and lemme know if it's still a problem?

**Comment by mikedubcurry** [comment]
i just created a fresh account, updated node to v.17, reinstalled and still get the same results. 
There is a CORS error in the console regarding the manifest.json but that doesnt seem related.

**Comment by WalshyDev** [comment]
Are you getting just a white page that says "Error"?

**Comment by mikedubcurry** [comment]
yes

**Comment by threepointone** [comment]
Can you go to your workers dashboard, click "Create a service", and deploy the default one?

**Comment by mikedubcurry** [comment]
it seems i can. I got the success message after accepting all the default options and the [link](https://aged-queen-9a5c.michaelcurry951730.workers.dev/) it gave doesnt load, saying it is using an unsupported protocol. im gonna give it another few minutes to wait for it to update

**Comment by threepointone** [comment]
In a couple of minutes, try `wrangler login` again too. I have a hunch...

**Comment by mikedubcurry** [comment]
hmm, im stilll getting the same blank, white error page, and the freshly created worker still gives the error `This site can’t provide a secure connection`. im going to try this on my windows machine to rule out any compatibility issues possibly due to my OS and or network conditions.

**Comment by threepointone** [comment]
I can confirm that the link you gave isn't loading for me too. This seems like a proper problem. Unfortunately I can't help you anymore till monday and I'm back at work laptop :/

**Comment by mikedubcurry** [comment]
wrangler login worked for me just now. yesterday I would have to solve a captcha every time i log into the browser, but not today. maybe with a fresh account and non-mainstream OS, I was being blocked somehow from immediately accessing api access. 
any way im closing this since im good to go. Thanks for the help!
