### ISSUE TITLE
Server randomly dies when running wrangler dev --inspect

### ISSUE THREAD

**Issue by jamsinclair** [cloudflare/wrangler#2163]
#### Describe the bug

I am debugging memory management in my Worker. I am currently running with the `unbound` usage type.

When running the worker with `wrangler dev --inspect`  and after sending two or three requests the server closes with:

```
panicked at 'failed to run websocket server: chrome -> edgeworker: Trying to work with closed connection', src/commands/dev/socket.rs:234:23
```

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Run worker with `wrangler dev --inspect`
2. Open Chrome DevTools inspector and open dev tools for instance
3. Send request to local worker URL more than once
4. Notice that dev server sporadically closes connection and dies.

#### Expected behavior

The server should not close and keep running when inspecting.

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS Monterey (Apple Silicon)
* output of `wrangler -V`: 1.19.6
* output of `node -v`: v16.13.1
* content of `wrangler.toml`: 
```
name = "upgrade-to-webp"
type = "javascript"
route = ''
zone_id = ''
usage_model = 'unbound'
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-11-06"

[wasm_modules]
JPEG_DEC_WASM = "node_modules/@jsquash/jpeg/codec/dec/mozjpeg_dec.wasm"
WEBP_ENC_WASM = "node_modules/@jsquash/webp/codec/enc/webp_enc_simd.wasm"
```

**Comment by threepointone** [comment]
@jyn514 ^

**Comment by jyn514** [comment]
It's unlikely this is caused by sending multiple requests to the *worker* - did you refresh the page in Chrome? That's not currently supported, you'll have to restart the wrangler process if you refresh chrome.

If this did happen just by sending requests to the worker, can you post the project you're working on? This doesn't happen for me on a toy hello-world project.

**Comment by jamsinclair** [comment]
> did you refresh the page in Chrome? That's not currently supported, you'll have to restart the wrangler process if you refresh chrome.

@jyn514 Ah I was doing this. By "sending request" I meant accessing from the browser. In my mind there's not much of a difference, other than headers the browsers sends? Odd that refreshing closes the server 😅 .

However, issue solved. Manually sending repeated requests with `curl` works and does not seem to kill the wrangler process 👍
