### ISSUE TITLE
Wrangler feature request to bind arbitrary workers

### ISSUE THREAD

**Issue by bever1337** [cloudflare/wrangler#2164]
#### Describe the feature

Developers can bind and validate the existence any arbitrary worker (not just durable object workers) using `wrangler.toml`

`wrangler.toml` examples:

Current:
```
kv_namespaces = [
  { binding = "FOO", id = "0f2ac74b498b48028cb68387c421e279", preview_id = "6a1ddb03f3ec250963f0a1e46820076f" },
  { binding = "BAR", id = "068c101e168d03c65bddf4ba75150fb0", preview_id = "fb69528dbc7336525313f2e8c3b17db0" }
]

[durable_objects]
bindings = [
  { name = "EXAMPLE_CLASS", class_name = "DurableObjectExample" } # Binding to our DurableObjectExample class
]
```

Proposed changes:
```
kv_namespaces = [
  { binding = "FOO", id = "0f2ac74b498b48028cb68387c421e279", preview_id = "6a1ddb03f3ec250963f0a1e46820076f" },
  { binding = "BAR", id = "068c101e168d03c65bddf4ba75150fb0", preview_id = "fb69528dbc7336525313f2e8c3b17db0" }
]

[durable_objects]
bindings = [
  { name = "EXAMPLE_CLASS", class_name = "DurableObjectExample" } # Binding to our DurableObjectExample class
]

[workers]
bindings = [
  { name = "my-worker" }
]
```

A really flexible implementation could let developers declare all their bindings at once, maybe that requires passing a specific type, maybe not, this is just a draft:
```
bindings = [
  { name = "EXAMPLE_KV", type = "KV", id = "abc123", preview_id = "xyz456" }, # Binding to KV
  { name = "EXAMPLE_CLASS", type="DO", class_name = "DurableObjectExample" }, # Binding to DurableObjectExample
  { name = "my-worker", type="SOME_RELATIVELY_GENERIC_TYPE_THAT_IS_NOT_TOO_OVERLOADED" } # Binding to generic worker to only communicate using fetch
]
```

I think `workers_dev` and environments of the bound workers still needs consideration. For example, those values could be inherited by default while allowing an override in the wrangler binding table. These example configs are just that, I'm not proposing any specific implementation details.

I find this helpful because:
1. In my opinion, wrangler encourages well-defined worker scope. Using `fetch` for inter-process communication feels natural and leverages the CF cache.
  a. exposing a single worker name in `wrangler.toml`
  b. allowing a single default export/event handler per worker module.
  c. disallowing WASM modules over 1MB 
2. I want to validate the existence, zone, and environment of all workers I bind
3. I do not want my application layer cluttered with logic to find a worker (that's too meta for my liking)

An example service might look like:
- Worker `schema` exposes an API to retrieve or validate data against JSON schema documents
- Worker `webhook` exposes a webhook API to receive events outside the system
- Worker `entity` is a durable object store

With this example service, the `webhook` service will want to validate its payload using the `schema`service before updating the `entity` store. Due to schema versioning and production security concerns, it is crucial that schemas are validated by the correct worker.

#### Describe the alternatives

Some of this is easily accomplished in user-land with wrangler config variables. Edit to add better documentation: This workaround does not support worker:worker in the same zone.

```
[env.my_environment]
vars = { bindings = [{ name = "my-worker", url = "https://service-subdomain.workers.example.com }] }

[env.my_other_environment]
vars = { bindings = [{ name = "my-worker", url = "https://service.mydomain.example.com }] }
```

The down-side of this approach is the lack of publish-time validation. Instead, the worker would need to apply the validation during the request.

Thanks for considering this feature request

**Comment by WalshyDev** [comment]
Service bindings are coming - https://blog.cloudflare.com/introducing-worker-services/

I heard they're starting to accept external testers too (though I haven't got my invite yet sadly 😢)

I imagine it will work something like this

**Comment by bever1337** [comment]
Awesome, thanks @WalshyDev! This matches my request and then some.
