### ISSUE TITLE
npm update -g @cloudflare/wrangler will uninstall npm

### ISSUE THREAD

**Issue by skywalkervenne** [cloudflare/wrangler#2167]
### 🐛 Bug report

npm update -g @cloudflare/wrangler will uninstall npm

#### Describe the bug

npm update -g @cloudflare/wrangler will uninstall npm

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Run 'npm update -g @cloudflare/wrangler will uninstall npm'
2. See error
![企业微信截图_16405888458530](https://user-images.githubusercontent.com/39072894/147445040-98cecdb1-8cc5-4c47-867c-88002d54adae.png)

**Comment by threepointone** [comment]
This seems bad. Will investigate soon.

**Comment by petebacondarwin** [comment]
Probably the same problem as here?  https://github.com/npm/cli/issues/2014

**Comment by petebacondarwin** [comment]
Actually I think this is a problem with the way npm update works in global mode. See https://github.com/npm/cli/issues/3175

The workaround (if you want to update wrangler globally) is to use:

```sh
npm -g install @cloudflare/wrangler@latest
```

**Comment by threepointone** [comment]
Thanks for the workaround @petebacondarwin! There's nothing much else we can do here, I'm afraid. The next version of wrangler encourages local installation in projects, so that should be a better situation than this. Closing.
