### ISSUE TITLE
Wrangler command to stop dev

### ISSUE THREAD

**Issue by vincenzon** [cloudflare/wrangler#2170]
### 💡 Feature request

Maybe this exists, however I couldn't find it. It would be nice to be able to run: 

`wrangler dev stop`

to stop the wrangler dev server. I have just been using grep + kill which seems a little kludgy.

**Comment by threepointone** [comment]
Sorry if I'm missing something here. `wrangler dev` doesn't run in the backgrouund, so you should be able to `ctrl+c` in the terminal you started the command to kill it. Is this not enough?

**Comment by vincenzon** [comment]
Hi Sunil,

The original terminal is not always easily accessible, that's why I find myself killing it manually. Perhaps my workflow is unusual, it just seemed a natural thing to be able to do so I was fishing for a "oh, you need to do ..." type response.

Matt

**Comment by threepointone** [comment]
In which case the workaround using grep + kill seems very capable to me, I suppose that's what we would've recommended for this.
