### ISSUE TITLE
Add flag to load Environment Variables from .env

### ISSUE THREAD

**Issue by connergdavis** [cloudflare/wrangler#2177]
#### Describe the feature

The best way to load environment variables (secrets) into `wrangler pages` _for the local development environment_ is currently:

```sh
wrangler pages ... -b MY_VAR=my-hardcoded-value
```

This is a security issue because scripts in `package.json` are an ubiquitous convention for launching a development environment (note Cloudflare Pages itself), and `package.json` must be published to your repository. It is clearly not suitable for secrets.

**I propose `wrangler` should either use or emulate the functionality of `miniflare` described here: [Variables and Secrets | Miniflare](https://miniflare.dev/variables-secrets.html#env-files)**

> Variables and secrets are automatically loaded from a .env file in the current directory. This is especially useful for secrets if your .env file is .gitignored. .env files look something like this:
> ```sh
> KEY1=value1
> KEY2=value2
> ```
> 
> You can also specify the path to a custom .env file:
> 
> ```
> miniflare --env .env.test # or -e
> ```
> 
> ```
> # wrangler.toml
> [miniflare]
> env_path = ".env.test"
> ```

#### Describe the alternatives

1. Intentionally omit secrets from your `package.json` scripts, and inform anyone working on your codebase they will need to manually add the `-b VAR=VAR` flag for each secret, and be sure to never commit those changes. Yuck!
2. Add commands _ahead_ of `wrangler` in your `package.json` script to force `wrangler` to detect your secrets. That works fine, but requires two additional outside dependencies, which anyone would rather avoid:
```sh
dotenv -- cross-var wrangler pages dev -b SOME_VAR=%SOME_VAR_IN_ENV_FILE%
```

There's been a lot of discussion on this on Cloudflare's and Remix's Discord servers.

Also, this is definitely not the first mention of the issue there, so I am not the first to find this.

**Comment by BasixKOR** [comment]
`wrangler pages` is feature of V2 and thus should be discussed there: https://github.com/cloudflare/wrangler2

**Comment by threepointone** [comment]
Closing this issue since we now support this properly in wrangler 2.
