### ISSUE TITLE
wrangler dev should not fail if it can't open the browser

### ISSUE THREAD

**Issue by stevenpack** [cloudflare/wrangler#2180]
#### Describe the bug

wrangler dev assumes it's running in an interactive environment, which is not always true. For example, running on Github codespaces, it's in a remote docker image. The way other frameworks work is they open the local port and codespaces detects that and magically port forwards and gives you a URL to use. E.g. I can run npm run serve on a Vue project, it opens https://localhost:8080 and then access that on my browser via a URL like https://my-project-xxv4q6php6vw-8080.githubpreview.dev over port 80.

It doesn't work with wrangler though, because it tries to pop up the browser with `xdg-open` and fails hard when that doesn't work the process dies.

```
$ npx wrangler pages dev ./dist
Compiling worker to "/tmp/functionsWorker.js"...
Compiled Worker successfully.
Serving at http://127.0.0.1:8788/
/workspaces/eth-registrar/app/web/node_modules/wrangler/wrangler-dist/cli.js:27072
            throw ex;
            ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://127.0.0.1:8788/' ]
}
```

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Open any repo with a Cloudflare worker using https://github.com/features/codespaces
2. Run `npx wrangler pages dev <your output dir>`
3. See error 'xdg-open' failed, and note that there is nothing running.

#### Expected behavior

1. Run `npx wrangler pages dev <your output dir>`
2. See the url in the console output e.g. http://127.0.0.1:8788 as per https://github.com/cloudflare/wrangler/issues/1544
3. Don't fail on the error. Keep the process running with so codespaces sees the open port and allows me to access it the browser on my local machine.

#### Environment and versions

Fill out the following information about your environment.

* operating system: `uname -a
Linux codespaces_7ecb11 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* output of `wrangler -V`: `$ npx wrangler -v
0.0.7`
* output of `node -v`: v16.9.1
* content of `wrangler.toml`: none.

NOTE: This is pretty specific to Github code spaces, but other frameworks 'just work'. It would be great if wrangler did too.

**Comment by threepointone** [comment]
This is a wrangler2 issue, and is being tracked here https://github.com/cloudflare/wrangler2/issues/23. Closing this issue.

**Comment by threepointone** [comment]
regarding opening the browser, that was fixed in https://github.com/cloudflare/wrangler2/pull/211. We'll do a publish next week that includes that fix, or you could try with `wrangler@alpha`.
