### ISSUE TITLE
wrangler dev keeps restarting despite no changes being made locally to any file

### ISSUE THREAD

**Issue by gregmsanderson** [cloudflare/wrangler#2189]
#### Describe the bug

I created a new project with a simple src/index.js, run `wrangler dev` to see if it worked, and it does but restarts over and over again, despite not making any change to any file.

I have the latest wrangler, updated today.

I have refreshed the OAuth token (so it has not expired). I used `whoami` and it confirms I am signed in using my email to my account.

This is the output. It says detected changes but shouldn't.

```
$ wrangler login
wrangler login
Allow Wrangler to open a page in your browser? [y/n]
y
💁  Opened a link in your default browser: https://dash.cloudflare.com/oauth2/auth?response_type=code&client_id=...
✨  Successfully configured. You can find your configuration file at: /Users/NAME/.wrangler/config/default.toml
$ wrangler dev --env dev
👂  Listening on http://127.0.0.1:8787
🌀  Detected changes...
💁  Starting a new session because the existing token has expired
💁  Ignoring stale first change
👂  Listening on http://127.0.0.1:8787
🌀  Detected changes...
💁  Starting a new session because the existing token has expired
💁  Ignoring stale first change
👂  Listening on http://127.0.0.1:8787
🌀  Detected changes...
💁  Starting a new session because the existing token has expired
💁  Ignoring stale first change
👂  Listening on http://127.0.0.1:8787
🌀  Detected changes...
💁  Starting a new session because the existing token has expired
... and so on
```

I'm not sure if I need to exclude any folders it may be looking at that may be being auto-updated by it or by the system? I have node_modules  in .gitignore, and tried adding dist and worker in case wrangler dev was updating those folders, but that hasn't helped. It kind of _seems_ like wrangler dev is changing some file itself e.g in dist/worker, and self-detecting the change, and so restarting ... and repeat. But it may not be that.

#### Reproduce the bug

A list of steps to reproduce the bug.

Run `wrangler dev`.

Note I used`wrangler dev --env dev` as I have a separate route in wrangler.toml for production and staging. But that makes no difference. It still restarts repeatedly.

#### Expected behavior

It _not_ to restart by itself _unless_ I have changed a file. Of course then, it should restart.

#### Environment and versions

Fill out the following information about your environment.

MacOS Catalina
wrangler 1.19.7
v16.13.2 (node)
```
compatibility_date = "2022-01-21"
account_id = "***"
name = "***"
type = "webpack"
workers_dev = false

[env.dev]
name = "***"
route = "***.dev/*"
zone_id = "***"
vars = { DEBUG = "no" } # to test env

[env.com]
name = "***"
route = "***.com/*"
zone_id = "***"
vars = { DEBUG = "no" } # to test env
```

**Comment by gregmsanderson** [comment]
For anyone else getting this same problem, I've bypassed it by using wrangler 2 (aka beta), which is miniflare. That seems to work correctly, only _restarting_ when I _do_ make a change to a file.

So replace `wrangler dev` with e.g `npx wrangler@beta dev src/index.js --local`

**Comment by threepointone** [comment]
This might be because you've set `workers_dev = false` but not defined a zone / route for the default. Can you try setting `workers_dev = true` and see  if that solves your problem?
