### ISSUE TITLE
$ wrangler dev --env local randomly returns 502 Bad Gateway

### ISSUE THREAD

**Issue by manuelbent** [cloudflare/wrangler#2198]
Hi, the title pretty much says it all.
I'm trying to build a worker but whenever I try to start it locally with `$ wrangler dev --env local` a 502 is _randomly_ returned.
Not every time, not never.
Just randomly.
Frustrating.

I'm passing  the --env option in order to bind a KV namespace I've set in the wrangler.toml file.
I'm also using the itty-router package to handle incoming requests.
When the 502 doesn't happen, everything works just fine.

Node version: 16.13.2
Wrangler version: 1.19.7

I've tried with wrangler@beta, too. 
Same issue.

Any help anyone?
Thanks!

**Comment by lengthmin** [comment]
I have the same problem, maybe it is the cloudflare tunnel's problem

**Comment by leonardofficial** [comment]
I am having the same issue

**Comment by threepointone** [comment]
This sounds frustrating, sorry about that. Could you share a some more details? I'd like to see what the logs say when this is happening. If you can make a sample project that reproduces that issues that would be extremely helpful.

**Comment by tunahanerkoyuncu** [comment]
I have the same problem too. I'm using router starter project. Just changed a little bit.   
After getting 502, I changed my internet connection to another network, and it worked just fine.

**Comment by Electroid** [comment]
Hey all, sorry about the issues! We've identified the issue and are rolling out a fix. Let us know if you continue to have any issues!
