### ISSUE TITLE
workers.api.error.too_many_crons: Crons have to be deleted manually before republishing

### ISSUE THREAD

**Issue by andreas-sqsh** [cloudflare/wrangler#2200]
#### Describe the bug

I have 2 cron jobs configured.
When using `wrangler publish` i get `workers.api.error.too_many_crons [API code: 10072]`

Limit is currently 3 per script.

It seems like they are added instead of overwritten. 

Therefore I have to manually remove them before publishing.

Also happens in wrangler-action (I am about to implement an automatic deletion before publishing in my action script)

#### Reproduce the bug

- Create 2 cron jobs.
- Publish
- Publish again
-> Error

#### Expected behavior

Jobs are overwritten instead of added, automatically deleted then added or not affected at all, if unchanged.

However, publishing seems to work
wrangler-action fails though, since it is marked as an error instead of a warning

**Comment by JamesCullum** [comment]
This breaks my workflows as well. Having a wrangler command to clear up the cronjobs would allow to have a workaround, where all cronjobs are emptied and then recreated via publish.

**Comment by threepointone** [comment]
wrangler 2 follows this behaviour, so I'm going to close this issue.
