### ISSUE TITLE
'fallback' not allowed in webpack config

### ISSUE THREAD

**Issue by atecey** [cloudflare/wrangler#2201]
#### Describe the bug

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'fallback'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, ignoreRootsErrors?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, preferAbsolute?, resolver?, roots?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }

`Fallback `is a valid option in webpack 5. Why does Wrangler not allow it?

#### Reproduce the bug

1. Add your own webpack.config.js
2.  Add to your config:
```
       resolve: {
        fallback: {
            crypto: require.resolve('crypto-browserify'),
        }
    },
```

#### Expected behavior

Should build successfully

#### Environment and versions

Fill out the following information about your environment.

* operating system: Ubuntu
* output of `wrangler -V`: 1.19.7
* output of `node -v`: v16.13.1
* content of `wrangler.toml`:
```
  name = "wrangler-test"
  type = "webpack"
  route = ''
  zone_id = ''
  usage_model = ''
  compatibility_flags = []
  workers_dev = true
  webpack_config = "webpack.config.js"
  compatibility_date = "2022-01-28"
```

**Comment by threepointone** [comment]
wrangler uses webpack 4, and will be deprecating it's usage in the next major ([details](https://github.com/cloudflare/wrangler/issues/2158)). If you'd like to use webpack 5, use `type = "javascript"` and setup a custom build as described in https://developers.cloudflare.com/workers/cli-wrangler/configuration#build

**Comment by Cryptolyfe** [comment]
I got the same error but im not using wrangler
