### ISSUE TITLE
Wrangler proxy issues

### ISSUE THREAD

**Issue by lilianmoraru** [cloudflare/wrangler#222]
It seems that Wrangler at the moment does not take Proxy configurations into consideration.
Here is how `rustup` picks up the proxy configurations: https://github.com/rust-lang/rustup.rs/blob/d35f94183601a81489bce025c2abc35cd395c909/download/src/lib.rs#L298

I am trying to setup a project behind a Corporate Proxy(Reverse Proxy) and running `wrangler generate` throws this error:
```
Error: Error(Io(Custom { kind: TimedOut, error: StringError("timed out") }), "https://crates.io/api/v1/crates/cargo-generate")
```

Running `cargo install cargo-generate` solves this issue but then I hit the next connection problem when running `wrangler build`, met with this error message:
```
Error: Error(Io(Custom { kind: TimedOut, error: StringError("timed out") }), "https://crates.io/api/v1/crates/wasm-pack")
```

Of course, again, `cargo install wasm-pack` solves this issue.

**Comment by xtuc** [comment]
Thanks for the report, this should be an easy fix. My reading of the rustup code is that the Proxy URL is passed in env, is that true?

**Comment by ashleygwilliams** [comment]
this may actually be a bug in binary-install... https://github.com/rustwasm/binary-install.

**Comment by gabbifish** [comment]
#1009 will fix this, thanks to the new reqwest release 0.10.1 which supports proxy env vars by default :)

**Comment by EverlastingBugstopper** [comment]
This is released 😄
