### ISSUE TITLE
Unable to publish site (500)

### ISSUE THREAD

**Issue by tillkruss** [cloudflare/wrangler#2234]
#### Describe the bug

I'm unable to publish a site using `wrangler publish --verbose`.

When I run the command I see:

```
...
✨  Built successfully, built project size is 351 KiB.
🌀  Using namespace for Workers Site "__objectcachepro-workers_sites_assets"
✨  Success
🌀  Uploading site files
Error: Something went wrong with the request to Cloudflare...

Internal Server Error
```

#### Environment and versions

Fill out the following information about your environment.

* operating system:
* output of `wrangler -V`: 1.19.11
* output of `node -v`: v17.8.0
<details><summary>content of `wrangler.toml`:</summary>
<pre>
<code>
name = "objectcachepro"
type = "webpack"
route = "objectcache.pro/*"
zone_id = "..."
account_id = "..."
usage_model = "unbound"
compatibility_date = "2021-09-29"
webpack_config = "workers-site/webpack.config.js"

kv-namespaces = [
  { binding = "APP", id = "...", preview_id = "..." },
  { binding = "METRICS", id = "...", preview_id = "..." },
  { binding = "LICENSES", id = "...", preview_id = "..." },
  { binding = "LEADS", id = "...", preview_id = "..." },
]

[site]
bucket = "./public"

[triggers]
crons = [
  "*/6 * * * *",
  "*/15 * * * *",
  "*/20 * * * *",
]

[vars]
ENVIRONMENT = "production"
SENTRY_DSN = "..."
</code>
</pre>
</details>

**Comment by tillkruss** [comment]
When I remove the `[triggers]` from my `wrangler.toml` the publish works. Something must have changed at CF end to no accept these anymore?!

**Comment by gofannoneth** [comment]
I'm encountering the same issue.

**Comment by oliverchank** [comment]
I have the same exact error, but my changes are is still published. 🤷

**Comment by rileymiller** [comment]
we are having issues with this as well

**Comment by ObsidianMinor** [comment]
A fix for this went out in the most recent API release, can someone confirm their uploads are working now?

**Comment by tillkruss** [comment]
@ObsidianMinor: Working! Please add a test case for this 🫠

**Comment by threepointone** [comment]
Closing since this has been fixed in the api. Thanks for reporting!
