### ISSUE TITLE
Compatibility flag `streams_enable_constructors` is not enabling ReadableStream constructors 

### ISSUE THREAD

**Issue by 0x15f** [cloudflare/wrangler#2235]
#### Describe the bug

When using Wrangler v1.19.11 and adding `streams_enable_constructors` to `compatibility_flags` in `wrangler.toml` with a compatibility date of `2022-01-28` ReadableStream Constructors are still unavailable.

`To use the new ReadableStream() constructor, enable the streams_enable_constructors feature flag.`

_When using wrangler2 this does function as expected_

#### Reproduce the bug

_This issue was discovered while attempting to deploy https://github.com/Shopify/hydrogen to Cloudflare Workers_

1. Run `yarn create hydrogen-app`
2. Add appropriate credentials to `wrangler.toml`
3. Run `wrangler publish`
4. Run `wrangler tail`
5. Visit published route, check wrangler console for error.

#### Expected behavior

When using the `streams_enable_constructors` compatibility flag I would expect `new ReadableStream()` to not throw an error.

#### Environment and versions

* operating system:
ProductName:	macOS
ProductVersion:	12.0
BuildVersion:	21A344
* output of `wrangler -V`:
1.19.11
* output of `node -v`:
v16.13.0
* content of `wrangler.toml`:
```
name = "*********"
type = "javascript"
account_id = "******************"
workers_dev = true
route = "***********.ptn.dev/*"
zone_id = "**********************"
compatibility_date = "2022-01-28"
compatibility_flags = ["streams_enable_constructors"]

[site]
bucket = "dist/client"
entry-point = "dist/worker"

[build]
upload.format = "service-worker"
command = "yarn && yarn build"
```

**Comment by threepointone** [comment]
I think the solution here is to use wrangler2. We would be open to feedback on your experience migrating!

**Comment by brillout** [comment]
I managed to make it work, see demo https://github.com/brillout/cloudflare-workers-react-18-streaming.

It successfully uses `streams_enable_constructors` (and uses `new ReadableStream()` under the hood).

**Comment by brillout** [comment]
FYI this is still needed for wrangler v2 with React 18 and [`react-streaming`](https://github.com/brillout/react-streaming). See https://github.com/brillout/vite-plugin-ssr/commits/8d29e1f3c197912ca33fc07c3c75accebe15770f.
