### ISSUE TITLE
Different workers created for different environments

### ISSUE THREAD

**Issue by gijo-varghese** [cloudflare/wrangler#2251]
#### Describe the bug

Wrangler is adding the environment name to the worker while publishing, which creates separate workers for each environment.

For example, I have a worker named "foo". `wrangler publish --env production` creates a new worker `foo-production` and `wrangler publish --env staging`  creates a new worker `foo-staging`.

#### Reproduce the bug

A list of steps to reproduce the bug.

1. Create a new project `wrangler generate foo`.
2. Add `production` and `staging` environments to `wrangler.toml` (as below).
3. Run `wrangler publish --env production`.
4. Run `wrangler publish --env staging`.
5. Notice the newly created workers "foo-production" and "foo-staging" both with the production environment.

#### Expected behavior

Only a single worker will be created named "foo" with two environments "production" and "staging". Instead, it's creating two workers with both of them having a production environment.

#### Environment and versions

Fill out the following information about your environment.

* operating system: MacOS 12.3.1
* output of `wrangler -V`: 1.19.12
* output of `node -v`: v16.14.2
* content of `wrangler.toml`:
```wrangler.toml
name = "foo"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-05-07"

[env.production]
route = "*/*"

[env.staging]
route = "*/*"
```

**Comment by threepointone** [comment]
Closing this since we discussed it on https://github.com/cloudflare/wrangler2/issues/921
