### ISSUE TITLE
Add a message to Wrangler 1 indicating that the user should try Wrangler 2 instead.

### ISSUE THREAD

**Issue by petebacondarwin** [cloudflare/wrangler#2261]

**Comment by JacobMGEvans** [comment]
Is the messaging when running/initializing when using Wrangler 1 or improving the messaging in the GitHub and NPM package?

**Comment by petebacondarwin** [comment]
The idea, in my mind, is that every time you run Wrangler 1 you get a "deprecation" warning that suggests you should try updating to the latest wrangler, giving instructions on how to do so.
