### ISSUE TITLE
Support for Emscripten?

### ISSUE THREAD

**Issue by robertaboukhalil** [cloudflare/wrangler#229]
Hi there, thanks so much for this library!

I've been able to create Cloudflare Workers with Rust compiled to Wasm, and I'm curious whether `wrangler` supports C/C++ code compiled with Emscripten?

The README mentions that we can use `type=webpack`:

```
webpack: This project contains any number of JavaScript files or Rust/C/C++ files that compile to WebAssembly. Rust files will be built with wasm-pack. C/C++ files will be build with emscripten. This project type uses webpack and webpack plugins in the background to build your worker.
```

That said, I'm not sure where I should specify where my C/C++ files live so that `wrangler build` can detect them.

Thanks!

**Comment by ashleygwilliams** [comment]
@xtuc can you share the example you have here? we should also make a template for it and make sure to link it in the docs :)

**Comment by robertaboukhalil** [comment]
Hey! Just wanted to follow up on this. I'll be speaking at OSCON in a few weeks and would love to briefly show a simple Emscripten example. I already have a nice example with a Cloudflare worker that uses Rust but it would be cool to show both if possible 😄

**Comment by xortive** [comment]
Once today's wrangler release (v1.1.0) drops, you'll be able to use (https://github.com/cloudflare/worker-emscripten-template) with wrangler!

**Comment by robertaboukhalil** [comment]
Thank you @xortive, I'll give it a try!
