### ISSUE TITLE
Publishing an invalid Wasm doesn't throw

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#230]
It should throw.

**Comment by gabbifish** [comment]
What do you mean by invalid WASM--an invalid WASM file, you mean? The Workers API has nothing like a validator for uploading WASM (only js scripts) so I think this feature may be blocked by the API performing WASM validation (unless we want to introduce validation logic in Wrangler, and therefore spread validation logic across code bases. I am strong against that).

**Comment by ashleymichal** [comment]
this should be implemented in the api.
