### ISSUE TITLE
Support for Yarn as a package manager?

### ISSUE THREAD

**Issue by okyanusoz** [cloudflare/wrangler#2312]
#### Describe the feature

I'm not sure if this is available in Wrangler, but I would like to use Yarn instead of npm.

Yarn is an npm alternative and is usually faster than npm.

See https://github.com/yarnpkg/berry or https://github.com/yarnpkg/yarn

**Comment by penalosa** [comment]
We're no longer actively developing `wrangler`, as it'll be sunset soon. Active development has shifted to [cloudflare/wrangler2](https://github.com/cloudflare/wrangler2), where using yarn is already supported. It should be fairly easy to migrate your project to [cloudflare/wrangler2](https://github.com/cloudflare/wrangler2), and we've got a migration guide at [developers.cloudflare.com/workers/wrangler/migration](https://developers.cloudflare.com/workers/wrangler/migration/) which should cover any issues you might encounter.
