### ISSUE TITLE
better error message for Krate HTTP error

### ISSUE THREAD

**Issue by tuananh** [cloudflare/wrangler#247]
just `wrangler generate myproject` and then `wrangler preview` but it fails with this error

```
⬇️ Installing wasm-pack...
⬇️ Installing wranglerjs...
✨   Built successfully.
Error: Error("expected value", line: 1, column: 1)
```

**Comment by xtuc** [comment]
Could you please run `export RUST_BACKTRACE=1` and try to run your command again? This should give us more information.

**Comment by tuananh** [comment]
I got this 

```
⬇️ Installing wasm-pack...
⬇️ Installing wranglerjs...
✨   Built successfully.
Error: Error("expected value", line: 1, column: 1)

stack backtrace:
   0: backtrace::backtrace::trace::h379958959b40dd56 (0x1092280ee)
   1: backtrace::capture::Backtrace::new_unresolved::h63674da28c1bba7f (0x109227118)
   2: failure::backtrace::internal::InternalBacktrace::new::h30a93456ed16e304 (0x109226969)
   3: <failure::backtrace::Backtrace as core::default::Default>::default::h09b3c6b58f5b002f (0x109226b65)
   4: wrangler::commands::publish::preview::preview::h44ba605b0f0f26d6 (0x108e99e32)
   5: wrangler::main::hfbc4c89f30aacff3 (0x108eb3db2)
   6: std::rt::lang_start::{{closure}}::hc293ed58579bef94 (0x108e9f7cb)
   7: std::panicking::try::do_call::h0b8150034252df34 (0x1092a78a8)
   8: ___rust_maybe_catch_panic (0x1092b12ff)
   9: std::rt::lang_start_internal::h72393d7cb5a1e5ac (0x1092a838e)
  10: _main (0x108eb4689)
```

**Comment by tuananh** [comment]
the issue has resolved by itself. i have no idea why though

**Comment by thochra** [comment]
👋 
It happened to me twice today and indeed the first time it disappeared by itself.

The second time I looked in processes and SIGTERM all remaining `wranglerjs` processes.
Then it worked again...

Note: I mostly used `wrangler dev` command

**Comment by tuananh** [comment]
Happened with me again today. Gone after half an hour or so

**Comment by EverlastingBugstopper** [comment]
this is very strange, going to re-open and tag with bug and needs reproduction. i'm not able to reproduce this on my machine - if anybody can give detailed steps to reproduce we can track this down.

**Comment by tuananh** [comment]
I don't know what cause it either. I got that but, goes away for half an hour and when i came back, tried again and it worked.

**Comment by msfjarvis** [comment]
with `RUST_BACKTRACE=1 wrangler publish` I was able to pinpoint this bug to `Krate`. When crates.io's API is down for any reason we get this error. It appears we all were unfortunate enough to use wrangler in separate transient downtime periods. I'd love to address the to-do there to use GitHub and fix this issue in the process.

<details>
<summary>Screenshot of crates.io API outage</summary>

![image](https://user-images.githubusercontent.com/13348378/84537598-b1f49e00-ad0d-11ea-8adf-7798c3ec2b92.png)


</details>

**Comment by EverlastingBugstopper** [comment]
aha! so it sounds like we just need to surface that error explicitly instead of masking it. thanks for the sleuthing @msfjarvis
