### ISSUE TITLE
Add configuration option for source location

### ISSUE THREAD

**Issue by granjef3** [cloudflare/wrangler#251]
This is a blocker for implementing live reloading that doesn't require user configuration. With wrangler supporting multi language builds, doing a webpack style traversal from the entry point is needlessly complex, when moving all source files into one directory and watching that recursively is a much easier problem. 

we could use `src` or `worker` as a default (probably combine this with #206). As long as all of your source files are in this <src-dir>, the rest of your directory tree is irrelevant as we will recursively check the source directory for changes.

**Comment by xtuc** [comment]
I don't like your proposal because I don't want to assume the user's source directory.

Related to https://github.com/cloudflare/wrangler/issues/235.

Also `worker` is not a source directory currently; https://github.com/cloudflare/wrangler/issues/206.

**Comment by granjef3** [comment]
Webpack traverses dependencies (using the resolve option) from the entry point, and also has an option to set things to ignore. I don't think reimplementing this is something we should do, but we could potentially change wranglerjs to not do `dist-to-clean` cleanup on livereloads and run webpack in watch mode and monitor the output of it. However, with projects that use webpack as well as rust/wasm this means they would have two places to configure hot reloading (webpack config, and wrangler.toml)

Cargo defaults putting everything in `<project-root>/src` but this can be configured.

Ideally the solution we adopt supports all current project types, as well as any custom things in the future. I'm thinking we allow a config option that lets you specify file paths as well as source directories which will be searched recursively, and an ignore option that functions just like .gitignore rules do (we could even add an option to look at gitignore, reusing the ignore crate that ripgrep created)
