### ISSUE TITLE
give option to not open browser when previewing

### ISSUE THREAD

**Issue by samuelcolvin** [cloudflare/wrangler#256]
Hi, great talk last Tuesday at cloudflare connect in London on workers and rust.

Wrangler looks awesome, building and testing workers looks like it's got a lot nicer in the last 6 months.

Would be great if I could preview workers without having to open a browser (or have one opened for me) for every preview.

A few things that would make this possible:
* option to not open a browser on `wrangler preview` (obviously)
* connect to the websocket for receiving console output and log it to the terminal - quite how this is displayed is an open question since one can't click to expand output in the terminal as one can in a browser console
* get more details about the request to the worker and response, eg. headers and body - something like the output from httpie.

There's a gist [here](https://gist.github.com/samuelcolvin/bc4783a69ac78e5a09ad7f82ff4b3a92) (old and ugly code, sorry) that demonstrates much of what I'm asking for.

Failing all this, one step would be to reuse the same browser tab for each preview so I don't end up with 50 old cloudflare worker tabs, although maybe that's a limitation of chrome?

**Comment by granjef3** [comment]
#252 is in progress and adds `wrangler preview --livereload` which will build your worker and update the preview tab (without making a new one) on file changes automatically.

**Comment by samuelcolvin** [comment]
Thanks, this fixes the work around mentioned at the end, but does not help with the original request.

Terminal only previews/development would be wonderful.

**Comment by ashleygwilliams** [comment]
@samuelcolvin i think adding a flag `--browser`/`--browserless` (i'm not sure what the default should be yet) that controls whether the browser responds is a great idea, and was something i simply ran out of time to build. 

would you be interested in submitting a PR? if not i think this is achievable for an upcoming release :)

**Comment by samuelcolvin** [comment]
How many of the features above should `--browserless` implement? 

I'm guessing that just not opening the browser would be a good start?

Showing request and response headers wouldn't be that hard (though you could go a lot further and highlight the body etc.), the real bulk of the work would be on printing the console log.

**Comment by ashleygwilliams** [comment]
i would imagine that this would be for preview and would encompass the http request commands we currently support, get (default), and post.

i think we should definitely add headers to the console output as well!  this could be a separate PR tho, if we wanted to keep them small (though i'd be happy with either).

**Comment by samuelcolvin** [comment]
Okay, I'll try and work on it when I get a chance, but feel free for anyone to take over if I don't get around to it.

**Comment by paulbhartzog-holo** [comment]
> @samuelcolvin i think adding a flag `--browser`/`--browserless` (i'm not sure what the default should be yet) that controls whether the browser responds is a great idea, and was something i simply ran out of time to build.
> 
> would you be interested in submitting a PR? if not i think this is achievable for an upcoming release :)

I like this approach, and I would argue that NOT opening the browser should be the default, but maybe that's just me.  I'd rather have `--browser` than `--browserless` :-)

Any movement on this?

**Comment by samuelcolvin** [comment]
been too busy to work on this, that's not going to change too soon.

I suspect that while many of us would prefer not to open a browser it will be hard to persuade cf to change the default.

**Comment by lucas-pelton** [comment]
In a similar (and potentially off-topic, sorry) experience, I'm running `wrangler preview --watch` on a machine that is terminal-only and therefore _can't_ launch a browser window. I must open a browser window on another machine.

I'm interested to know if the URL for the current instance of `wrangler preview --watch` is discoverable in any way so that I can launch my own browser window.

**Comment by ashleygwilliams** [comment]
hey! we actually are prioritizing this work this quarter, and hope to implement a terminal only preview, a la "wrangler cURL", and parameterize the option of opening the browser cc @samuelcolvin

**Comment by samuelcolvin** [comment]
Thanks for the cc, afraid I haven't been working on cf workers recently so unlikely I'll be able to help implement this.

**Comment by ashleygwilliams** [comment]
it's all good! @EverlastingBugstopper is going to be focusing on it :) if you have any suggestions or thoughts, feel free to share!

**Comment by samuelcolvin** [comment]
My main point would be that a websocket connection and worker console log in the terminal as demonstrated by my gist above would make a massive different for those of us fond of using the terminal.

`--browerless`, or perhaps better respecting the [`BROWSER` env. variable](https://create-react-app.dev/docs/advanced-configuration/) like create react app, would obviously be the simplest win.

**Comment by ashleygwilliams** [comment]
thank you for sharing @samuelcolvin !

**Comment by lucas-pelton** [comment]
@ashleygwilliams Do you know if the URL for the current instance of `wrangler preview --watch` is discoverable in any way? I'm running the command on a terminal-only machine and I want to launch the preview URL in a browser window on a separate machine.
