### ISSUE TITLE
Document --debug flag for local builds

### ISSUE THREAD

**Issue by xortive** [cloudflare/wrangler#264]
https://github.com/cloudflare/wrangler/blob/305c650bba1de8e888f7b460b4f91cdf680ab832/src/commands/build/wranglerjs/mod.rs#L151

In order to try out a build of wrangler locally, you should use `cargo install --debug --path .` so the local version of wranglerjs is used rather than a release.

**Comment by ashleygwilliams** [comment]
this should likely go in a `CONTRIBUTING.md` document

**Comment by xtuc** [comment]
This is intended for local dev, I'm not sure someone wants to install the development version from cargo and I'm pretty sure it won't work because it relies on the js source.

**Comment by granjef3** [comment]
@xtuc `--path .` tells cargo to install from the current directory, but if you use it without `--debug` it will install wranglerjs from github releases instead of the source directory

**Comment by ashleymichal** [comment]
closed in favor of #270
