### ISSUE TITLE
errors propagated to main using Result / failure::bail! don't print unicode correctly

### ISSUE THREAD

**Issue by granjef3** [cloudflare/wrangler#274]
To replicate:

- comment out name or account_id (probably works for more fields) in `wrangler.toml` with a `#` at beginning of the line.
- try `wrangler publish`
- prints ``Error: ErrorMessage { msg: "⚠\u{fe0f} Your project config has an error, check your `wrangler.toml`: missing field `name`" }"``

**Comment by EverlastingBugstopper** [comment]
while my PR technically addresses this issue, it’s more of just a workaround. underlying issue isn’t fixed. might be worth looking into further but not a huge priority. @granjef3 expressed some interest in looking into it
