### ISSUE TITLE
Cannot generate new Rust project

### ISSUE THREAD

**Issue by Joe8Bit** [cloudflare/wrangler#277]
From a clean install via `cargo install wrangler` I cannot have wrangler generate a rust based project.

Have tried:

* `wrangler generate` => webpack project (as expected)
* `wrangler generate foo` => webpack project (in `/foo`, as expected)
* `wrangler generate foo --type=rust` => webpack project
* `wrangler generate foo --type="rust"` => webpack project
* `wrangler generate --type="rust"` => webpack project

None of these seems to result in a rust project being generated. Started out from the [Cloudflare tutorial](https://developers.cloudflare.com/workers/webassembly/tutorial/), but it made no mention of `--type` but found that in this repos docs.

Is this expected behaviour? Am I being an idiot?

```
~/src/tmp $ wrangler -V
👷  ✨   wrangler 1.0.0

~/src/tmp $ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.35.0-nightly (3750348da 2019-04-08)

~/src/tmp $ cargo --version
cargo 1.35.0-nightly (6f3e9c367 2019-04-04)

~/src/tmp $ node --version
v11.4.0
```

On OSX via HyperTerm

**Comment by ashleymichal** [comment]
hey @Joe8Bit , thanks for reporting! We haven't been able to reproduce this yet, but while we troubleshoot it, if you pass this template repo as your second argument, you should get a proper rust wasm worker!

`$ wrangler generate my-worker https://github.com/cloudflare/rustwasm-worker-template`

**Comment by Joe8Bit** [comment]
Not sure if this will help, but recorded the issue happening!

https://streamable.com/wxlb8

**Comment by Joe8Bit** [comment]
I also tried `--type=javascript` but honestly not sure if the outcome is the right level of difference of this issue exists for this type too

```
~/src/tmp/wrangler $ wrangler generate --type=javascript
🐑  Generating a new js worker project with name 'worker'...
🔧   Creating project called `worker`...
✨   Done! New project created /Users/joep/src/tmp/wrangler/worker
~/src/tmp/wrangler $ wrangler generate foo              
🐑  Generating a new webpack worker project with name 'foo'...
🔧   Creating project called `foo`...
✨   Done! New project created /Users/joep/src/tmp/wrangler/foo
~/src/tmp/wrangler $ diff -r worker foo
diff -r worker/package.json foo/package.json
2c2
<     "name": "worker",
---
>     "name": "foo",
diff -r worker/wrangler.toml foo/wrangler.toml
1,2c1,2
< name = "worker"
< type = "javascript"
---
> name = "foo"
> type = "webpack"
```

**Comment by jupiter** [comment]
For what it's worth, I'm having the same issue.

```
$ rustup show
Default host: x86_64-apple-darwin

stable-x86_64-apple-darwin (default)
rustc 1.35.0 (3c235d560 2019-05-20)
```

**Comment by jupiter** [comment]
The default template was changed to the JS one (see https://github.com/cloudflare/wrangler/commit/e30da22b9c82e9d6abc3a6cc64fa7b10ee27714b). This means you now need to specify the `template` parameter in order to generate the demo Rust template. E.g.

```
$ wrangler generate demo https://github.com/cloudflare/rustwasm-worker-template
```

**Comment by EverlastingBugstopper** [comment]
@Joe8Bit I believe that this is actually intended behavior, but it is quite misleading. When you pass `—type` to wrangler, it changes the way the project is built, and doesn’t provide you with any different directory contents. If you check your `wrangler.toml` after running `wrangler generate —type rust` you should see the `type` field is, in fact `rust` (please confirm! want to make sure we’re on the same page)

That being said — your issue is really helpful in identifying that we really should be providing you some rust files when you ask for a rust project! If you could confirm that your wrangler.toml has `type=rust` after generating a rust project, I’ll go ahead and rename the issue and we’ll update the default behavior for project generation.
