### ISSUE TITLE
Cannot install wrangler

### ISSUE THREAD

**Issue by davidkayce** [cloudflare/wrangler#281]
Hey, 
I am trying to get started on workers and running 'sudo npm install -g @cloudflare/wrangler' on my Mac 2014 2.6 GHz Intel Core i5 keeps returning this error: 
![image](https://user-images.githubusercontent.com/22254534/60307091-fc351180-993a-11e9-8267-db666eba4344.png)

**Comment by davidkayce** [comment]
Please any help on what to do about this

**Comment by xtuc** [comment]
Thanks for the report. This is a known issue, see https://github.com/cloudflare/wrangler/issues/240.
