### ISSUE TITLE
Preview be able to pass in which path

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/wrangler#284]
Preview defaults to root, but it'd be nice to be able to pass in a specific path when testing
e.g.

```
wrangler preview --watch --url https://status.io/blah
```
The preview window pops up at `https://status.io/blah`

**Comment by sheerun** [comment]
This is such important thing, weird it wasn't implemented from the beginning

**Comment by EverlastingBugstopper** [comment]
This is fixed by #1001
