### ISSUE TITLE
RFC: Safe publishing

### ISSUE THREAD

**Issue by Electroid** [cloudflare/wrangler#290]
By default, wrangler should pull the deployed version of your script + bindings and compare it with your local changes before publishing. A diff would appear showing what's changed in your Worker script and any added or removed bindings. You can optionally provide `--force` to ignore this safety check.

**Comment by xtuc** [comment]
Could you please elaborate on why the worker should change after publish? Your sugestion would trigger many false-positive, every local update will show a diff with the remote...

I see the worker as a compilation target, the proper way to modify it is locally and via the tool. However, similar to a `node_modules`, you are allowed to change it in your project (in the UI) and I would disable the JavaScript optimizations, to make it easier. But then I don't expect the modifications to be somehow persistent.

**Comment by Electroid** [comment]
The idea is that we should remind users about the differences between their currently deployed Worker and their about-to-deploy Worker so there are no surprises. 

This is more useful for bindings, if I remove a KV namespace from my Worker, and the deployed Worker has that KV namespace, we should say: "hey, are you sure you want to do that?"

**Comment by EverlastingBugstopper** [comment]
+1 for diff on bindings, makes a lot of sense. I don’t think it makes as much sense for the contents of the script itself. 

cc @ashleymichal

**Comment by ashleymichal** [comment]
i would be interested to see what other serverless platforms do about this; it doesn't seem like a safe operation for a client tool, especially when you start looking at any sort of assumptions around collaboration. the safest place to implement such features would be in the configuration API, not in wrangler, as a single client can _never_ make a true guarantee that the last state it received from the server is in fact up to date when there are multiple clients in play.

I've looked at the idea of a courtesy feature in wrangler, but the more i think about it, the more i feel we would be making a false guarantee. this should be a core feature, not client feature.

**Comment by EverlastingBugstopper** [comment]
That makes a lot of sense. The pain point that Ashcon identified is definitely a real one, but @ashleymichal is right in that Wrangler can’t make any guarantees about that without making a call to the api.

**Comment by ashleymichal** [comment]
the real point is that even _with_ a call to the api, wrangler cannot guarantee that nothing changed between the query for existing bindings, and the command to publish a new version. yes that window is small, but again, as soon as you introduce multiple clients, plus automation, it can actually become a real problem.

**Comment by EverlastingBugstopper** [comment]
Shall we close this?

**Comment by ashleymichal** [comment]
yes, i think we should close this. thanks @Electroid for pointing out this problem, and while I think we could superficially paper over the issue in Wrangler, it would likely result in more subtle unexpected behavior. I'm for sure available to discuss how this could be addressed in the api.

**Comment by jRiest** [comment]
The API already implements a way to do that. If you store the `Etag` response header when you fetch the script/generate the diff, and then send that etag along in the `If-Match` header when you try to save the script, the API will reject the call if the script has been updated in the meantime.

**Comment by EverlastingBugstopper** [comment]
@jRiest is this documented anywhere?

**Comment by ashleymichal** [comment]
i don't believe it is; looking into this.
