### ISSUE TITLE
RFC: expand usage of the Bundle

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#293]
## Problem

In #215 #292 we want to generate the bindings for every backend, regardless of their implementations. For wranglerjs I introduced the notion of the bundle; representing the backend's output and a worker.

## Suggestion

We should move the bundle struct and base impl out of  the `webpack` backend. It contains the following information: path to the build dir, path to the script, path to the wasm, has a wasm module?. 

The backend should call write before handing the struct to wrangler, so that it just has to upload the bundle.

Conceptually the result of the backend computation is a bundle.

### Creating the metadata file

The metadatas (including bindings) are not included into the bundle, that said the bundle gives information about it. Wrangler should write the metadata and the bindings.

### Creating the multipart form

This is not part of the bundle, but rather Wrangler's logic once it gets the bundle from a backend.

**Comment by granjef3** [comment]
I would like to see this result in the bundle being passed as an output from the build command, such that the publish and preview commands would take it as an argument

**Comment by cwndrws** [comment]
I believe bundle is a webpack-specific term, so we probably shouldn't overload it if we're going to use it as a top-level type that contains everything that makes up a worker.

**Comment by xtuc** [comment]
I believe other teams already uses WorkerBundle, does it make sense to use it? or Worker?

**Comment by granjef3** [comment]
> I believe bundle is a webpack-specific term, so we probably shouldn't overload it if we're going to use it as a top-level type that contains everything that makes up a worker.

This is a good point too -- maybe we can do a s/bundle/worker or other similar name? Would be nice to distinguish between your worker as in the code before compile, and a worker as in the thing we upload

**Comment by cwndrws** [comment]
I had started working in this direction and have a struct called `Worker`. It contains a script path and a list of bindings. My goal was to have some sort of API client that took a `Worker` no matter what type and uploaded it.

**Comment by cwndrws** [comment]
Here's the `Worker` type I was talking about: 

```rust
use reqwest::multipart;
use serde::Serialize;

pub struct Worker {
    script_path: String,
    bindings: Vec<Binding>,
}

impl Worker {
    pub fn multipart(&self) -> Result<multipart::Form, failure::Error> {
        let mut form = multipart::Form::new().file("script", &self.script_path)?;
        let binding_parts = binding_parts(&self.bindings)?;
        for (name, part) in binding_parts {
            form = form.part(name, part);
        }
        Ok(form)
    }
}

fn binding_parts<'a>(
    bindings: &'a Vec<Binding>,
) -> Result<Vec<(String, multipart::Part)>, failure::Error> {
    let mut parts: Vec<(String, multipart::Part)> = Vec::new();
    let meta_part = binding_meta_part(bindings)?;
    parts.push(("metadata".to_string(), meta_part));
    for binding in bindings {
        match binding {
            Binding::wasm_module(ref wasm) => {
                let mut part = multipart::Part::file(wasm.path.to_string())?;
                part = part.file_name(wasm.symbol.to_string());
                parts.push((wasm.symbol.to_string(), part));
            }
            Binding::kv_namespace(_) => {
                // kv bindings don't add their own part to the multipart form
            }
        }
    }
    Ok(parts)
}

fn binding_meta_part(bindings: &[Binding]) -> Result<multipart::Part, failure::Error> {
    let metadata = MetaData {
        body_part: "script".to_string(),
        bindings,
    };
    Ok(multipart::Part::bytes(serde_json::to_vec(&metadata)?).mime_str("application/json")?)
}

#[derive(Serialize, Debug)]
pub struct MetaData<'a> {
    body_part: String,
    bindings: &'a [Binding],
}

#[derive(Serialize, Debug)]
#[serde(tag = "type")]
pub enum Binding {
    #[allow(non_camel_case_types)]
    wasm_module(WasmBinding),
    #[allow(non_camel_case_types)]
    kv_namespace(KVBinding),
}

#[derive(Serialize, Debug)]
pub struct WasmBinding {
    #[serde(skip_serializing)]
    path: String,
    #[serde(rename = "name")]
    symbol: String,
    part: String,
}

#[derive(Serialize, Debug)]
pub struct KVBinding {
    namespace_id: String,
    #[serde(rename = "name")]
    symbol: String,
}
```

My intention is to have some function that can init a `Worker` from a `Project` after it's been built. And then to have anything that needs access to this to use it like `publish_worker` here which will be a replacement for `publish_script`:

```rust
fn publish_worker(user: &GlobalUser,
                  project: &Project,
                  worker: &Worker,
                  release: bool) -> Result<(), failure::Error> {
    
    let worker_addr = format!(
        "https://api.cloudflare.com/client/v4/accounts/{}/workers/scripts/{}",
        project.account_id, project.name,
    );

    let client = http::auth_client(user);
    let mut res = client.put(&worker_addr).multipart(worker.multipart()?).send()?;

    if res.status().is_success() {
        message::success("Successfully published your script.");
    } else {
        failure::bail!(
            "Something went wrong! Status: {}, Details {}",
            res.status(),
            res.text()?
        )
    }

    if !release {
        let private = project.private.unwrap_or(false);
        if !private {
            info!("--release not passed, publishing to subdomain");
            make_public_on_subdomain(project, user)?;
        }
    }

    Ok(())
}
```
Sorry this stuff is all in a comment. Since adding the pre-push stuff, I can't really push a WIP PR.

**Comment by xtuc** [comment]
The bindings struct already exists https://github.com/cloudflare/wrangler/blob/master/src/settings/binding.rs.

**Comment by ashleymichal** [comment]
i believe an abstraction now exists that's pretty similar to this, called ProjectAssets (https://github.com/cloudflare/wrangler/blob/master/src/upload/form/project_assets.rs). closing, please re-open if i am mistaken.
