### ISSUE TITLE
Require webpack_config field in wrangler.toml to use custom webpack configuration

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#296]
It is not abundantly clear that wrangler will use your custom `webpack.config.js` to package everything. Some users may want to start using wrangler with a project that already has a `webpack.config.js`, but they may not understand that wrangler will use that configuration over its own default. We should require users who want to use their own configuration to specify it in their `wrangler.toml` `webpack_config` field so that there is no confusion that their webpack configuration is impacting their build output.

We need to decide if this is something we want to do, or if we want to leave things like they are and automatically override wrangler’s default webpack behavior when a user has their own `webpack.config.js`

**Edit**

Implementing this would be a breaking change for users that currently use `webpack.config.js` to build their workers, they would need to add a `webpack_config` field to their `wrangler.toml` in order for it to continue working. We would want to add an error message if they have a file `webpack.config.js` to say that if they want it to be used, they should add it to their configuration to override the default.

We're looking at implementing this for the upcoming release because some users will use `webpack.config.js` to build other types of apps alongside their worker. In these cases, the user will want to keep `webpack.config.js` around, but not to build their worker

**Comment by granjef3** [comment]
If we remove the automatically using the present webpack.config.js behavior, we should prompt the user if we detect one that they must put it inside wrangler.toml for it to be used in the build

**Comment by ashleygwilliams** [comment]
let's start with a PR that includes logic to look at the wrangler.toml for a webpack config, and if the file system has a webpack file at the root and errors. we'll go from there!
