### ISSUE TITLE
Allow specifying .toml file in wrangler build

### ISSUE THREAD

**Issue by davidgagnegarmin** [cloudflare/wrangler#302]
Currently, wrangler build uses the wrangler.toml file, but there are situations where it would be ideal to have multiple deploys of the same code, either for staging environments or for situations where you want to deploy to multiple zones or routes. 

This would work well with the addition of the kv namespace bindings (https://github.com/cloudflare/wrangler/pull/299), so that you could have a test namespace, with a test script, by specifying a "wrangler-test.toml" file. 

I suggest `wrangler build -c <file>`.

This of course can be solved via a build script as well, but I'd prefer to have something baked in.

**Comment by EverlastingBugstopper** [comment]
This seems like an alternative solution to what is proposed here: https://github.com/cloudflare/wrangler/issues/220

cc: @xtuc

**Comment by davidgagnegarmin** [comment]
Yes, that could work. 

There may be advantages to allow specifying a file instead of an env, so that you can deploy one script to multiple different zones?

**Comment by EverlastingBugstopper** [comment]
Thanks!
