### ISSUE TITLE
External webpack config can throw if target is changed from the default.

### ISSUE THREAD

**Issue by divyenduz** [cloudflare/wrangler#312]
I might be missing something, please correct me if I am wrong. The default webpack config doesn't target node. I overrode (or merged) that with this config by keeping a `webpack.config.js` directory on my project root. 

```
const nodeExternals = require("webpack-node-externals");
const path = require("path");
module.exports = {
  target: "node",
  externals: [nodeExternals()],
  entry: "./index.js",
  output: {
    filename: "script.js",
    path: path.resolve(__dirname, "worker"),
    libraryTarget: "commonjs2"
  }
};
```

Now, `wrangler preview` fails with this error: 

```
divyendusingh [cloudflare]$ wrangler preview
⬇️ Installing wasm-pack...
⬇️ Installing wranglerjs...

/Users/divyendusingh/Library/Caches/.wrangler/wranglerjs-2cfae6543744f4a7/index.js:38
fetchCompileWasmTemplatePlugin.fn = function(compilation) {
                                  ^

TypeError: Cannot set property 'fn' of undefined
    at Object.<anonymous> (/Users/divyendusingh/Library/Caches/.wrangler/wranglerjs-2cfae6543744f4a7/index.js:38:35)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
thread 'main' panicked at 'could not run wranglerjs: ErrorMessage { msg: "failed to execute `\"/Users/divyendusingh/.nvm/versions/node/v10.4.0/bin/node\" \"/Users/divyendusingh/Library/Caches/.wrangler/wranglerjs-2cfae6543744f4a7\" \"--output-file=/var/folders/8z/_p2h9_rs6js1_hs5ff32dh2m0000gn/T/.wranglerjs_outputvcJrw\" \"--wasm-binding=wasmprogram\"`: exited with exit code: 1" }', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I think, It fails to get the existing WASM template plugin here: https://github.com/cloudflare/wrangler/blob/master/wranglerjs/index.js#L51

Maybe we need to merge webpack config in place of replacing it?

**Comment by granjef3** [comment]
Hey @divyenduz! Sorry to see you're running into issues.

My best guess is this is a docs problem, while workers is a V8 based environment it is not the same as node.js and doesn't implement the node.js api, or have built-in module support (there is no node_modules for workers, there is only a single file per script).

The reason we use webpack is so we can bundle your project's dependencies and source code together into a single file for the runtime -- using `webpack-node-externals` would actually do the opposite of this and explicitly not include any dependencies.

Just use the default config (none at all) and you should be able to use `wrangler preview` successfully, however what you are trying to do has exposed an underlying issue.

The plugin `fetchCompileWasmTemplatePlugin` is actually a part of webpack's default `web` [compilation target](https://github.com/webpack/webpack/blob/d45bec3518f53153287ff2cad3cfae9d2b248d9a/lib/WebpackOptionsApply.js#L72) and is not brought in by the `node` [compilation target](https://github.com/webpack/webpack/blob/d45bec3518f53153287ff2cad3cfae9d2b248d9a/lib/WebpackOptionsApply.js#L97). Wranglerjs assuming that this plugin is present (so it can override the behavior to use the binding name instead of a fetch) without setting target itself is what caused the error message you observed. I changed the title of this issue to reflect this.

**Comment by divyenduz** [comment]
@granjef3 Thanks for the detailed answer, my use case is the following: 

`The reason we use webpack is so we can bundle your project's dependencies and source code together into a single file for the runtime`.

I am bundling together a package that relies on external assets (like a `binary`) to execute queries (against a database). I will need to override the `webpack.config.js` to move around those assets. 

I would need some sort of merge `webpack` configs functionality to make it work. Is this even a valid use case for cloudflare workers?

**Comment by EverlastingBugstopper** [comment]
Workers can’t read from the file system or interact with any service that doesn’t communicate over HTTP. I’m not entirely ruling out your use case, but my gut is telling me that what you want to do won’t work with the workers runtime. The general paradigm is handling HTTP requests. Available tools are Workers KV (an eventually consistent key value datastore), subrequests to other domains with the fetch api, our cache api, and JavaScript/Wasm compute. Any data that you want to interact with must be in KV or available over HTTP, so querying from a database (unless it’s one of the few HTTP databases) is likely not possible today.

**Comment by divyenduz** [comment]
Thanks for the detailed response. I am trying to see if [Photon JS](https://photonjs.prisma.io/) works with Cloudflare workers. 

It is a `npm` package that ships with a binary (overridable based on the underlying platform). 

It is a type-safe database client that `spawns` a binary capable of establishing a connection to the DB and executing queries. 

Based on your comment, it looks like right now Cloudflare workers do not support this use case (yet). I am aware of [this discussion](https://community.cloudflare.com/t/what-if-workers-could-access-your-sql-nosql-database/88805/6) and I am aware of Cloudflare KV store which is different from our use case. 

Please feel free to close this issue, unless we want to use this to track mergeable webpack config issue.

**Comment by EverlastingBugstopper** [comment]
@divyenduz We don’t support communication with databases from workers and it’s not on any announced roadmap so I wouldn’t hold your breath. Re: mergeable webpack config, there shouldn’t be an issue there as far as I know, your webpack configuration will work just fine if it’s called `webpack.config.js` and is in the project’s root directory, and our next release will allow you to configure the path of your custom configuration. 

Thanks for your interest in wrangler and for filing this issue!

**Comment by katopz** [comment]
> ...your webpack configuration will work just fine if it’s called `webpack.config.js` and is in the project’s root directory, and our next release will allow you to configure the path of your custom configuration.

Is this still true? I try, but got this error.
```js
module.exports = {
  target: 'node'
}
```
```
Error: Building a Cloudflare Worker with target "node" is not supported. Wrangler will set webworker by default, please remove the `target` key in your webpack configuration.
```
