### ISSUE TITLE
Provide a readable error message for API code 10034 - Please verify your email

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#320]
```
$ wrangler subdomain jazz
🐌  Registering your subdomain, jazz.workers.dev, this could take up to a minute.
Error: ErrorMessage { msg: "⛔ There was an error creating your requested subdomain.\n Status Code: 400 Bad Request\n Msg: {\"success\":false,\"errors\":[{\"code\":7003,\"message\":\"Could not route to \\/accounts\\/workers\\/subdomain, perhaps your object identifier is invalid?\"},{\"code\":7000,\"message\":\"No route for that URI\"}],\"messages\":[],\"result\":null}" }
```

This should be updated to inform the user that they need to validate their email before they can register the subdomain (maybe give them a link to re-send the email?)

**Comment by ashleygwilliams** [comment]
error 7003 is not specific enough for us to give a good error message. @rita3ko let's chat about this!

**Comment by ashleymichal** [comment]
i believe this _particular_ error had to do with a missing account id in the wrangler.toml. we check for that now on publish, so it should mitigate this particular error.

wrt the reported error with subdomain registration, this is actually about to become a thing, so we'll need to handle a 10034 error (email not yet verified).
