### ISSUE TITLE
cargo-generate not being installed correctly

### ISSUE THREAD

**Issue by adamchalmers** [cloudflare/wrangler#324]
**Problem:**
I was following the Quickstart and installed Wrangler via Cargo. Then I got an error when running `wrangler generate`. Unfortunately I didn't copy the error. However, I fixed it by running `cargo install cargo-generate`. I could then successfully run `wrangler generate`.

**Proposed solution:**
The quickstart guide should prompt users to `cargo install cargo-generate` if they're install Wrangler via Cargo.

**Comment by ashleymichal** [comment]
should we prompt, or install on behalf of the user?

**Comment by EverlastingBugstopper** [comment]
I’d say we should just install it. When I’m installing new tools I don’t really care what the dependencies are I Just Want It To Work.

**Comment by granjef3** [comment]
This sounds like a `binary-install` problem as we already install on behalf of the user

**Comment by adamchalmers** [comment]
@granjef3 If it's a bug in the install toolset, I probably shouldn't add an "install cargo-generate" step in the quickstart, right?

**Comment by granjef3** [comment]
@adamchalmers exactly. Could you see if you get that error again if you uninstall `cargo-generate` and `wrangler` and give some more info on your platform/rust version?

**Comment by granjef3** [comment]
Duplicate of https://github.com/cloudflare/wrangler/issues/35 after testing with Adam.
