### ISSUE TITLE
Overwrite Protection for Project Uploads

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#330]
# Problem
One of the biggest problems we are trying to solve with KV support in Wrangler is that users unknowingly overwrite existing bindings (especially namespace bindings) when publishing their Worker with Wrangler. One part of fixing this is adding support for KV Namespace binding configuration ( https://github.com/cloudflare/wrangler/milestone/6 ) , but that still requires users to duplicate their config exactly in order to avoid screwing anything up. Ideally, Wrangler could alert a user to differences between their local project, and the project that already exists by the same name in the Workers ecosystem.

# History
Previously I have pushed back against implementing publish-time checks in Wrangler because Wrangler cannot guarantee anything about the state of the script on the server. (see #290 ) However, as of last quarter, the Script upload endpoint provides support for `if-match` and `if-none-match` headers in request, which provides the appropriate API for implementing the kinds of checks that will prevent users from unintentionally overwriting data. (This is indicated in a later comment from @jRiest on that same issue).

# Solution
The likely flow is as follows:

## Scenario 1: A New Wrangler Project
On the first attempt to publish a Worker, Wrangler should include an if-none-match  header in the upload request. The API will return success or failure based on whether a script by the same name already exists for the given user.

## Scenario 2: An existing Wrangler project
Once Wrangler has successfully uploaded a script for the first time, it should maintain an append-only list of etags locally, and use the most recently added one in upload requests as the if-match  header (unless the --force flag is invoked). The API will return success if the etag it currently has on file for the given name matches the etag sent in the header. 

### On success :
A successful upload response includes an etag key, which corresponds with the bundle hash of the newly created Worker. Wrangler should add this hash to a list locally and use it in subsequent upload requests.

### On error :
If the API finds an existing script by the same name, it will return a precondition failed error. When this happens, Wrangler can present the user with the error, and helpful follow up instructions.

## Empowering the user
The user can now:

### resolve conflicts:
- "pull" or "fetch" (strawman commands) the old script and bindings and compare them. This is the trickiest part of this and requires some careful design to avoid scope creep for an MVP; it is sort of a feature on its own, but would unlock not only overwrite protection but script import into wrangler project as well. This functionality would also probably tie in heavily with a Wrangler versioning feature implementation.
- the "pull/fetch" GET the script by name. should add the local etag (included in the headers for the GET /script/:name response) to its internal state (see below).
this command should also indicate what the differences are in the script and bindings through some "diff" operation. _TODO: what would this look like for a script? what would it look like for bindings?_
- resolve conflicts _TODO: what does this look like?_
- rerun the publish command as usual.
- be guided through differences to look for in the dashboard (look for bindings, compare script)
rerun the publish  command with an --inherit  flag to send the inherit bindings header
rerun the publish command with a --force  flag to run a "dangerous" upload (i.e. sans precondition header). This should be an explicit flag

# Related features
There are some segments of this feature that are features in and of themselves, and likely deserve their own RFCs separate from this one:

## "Sync"-ing projects
The "fetch"/"diff" functionality suggested above is A Big Deal, and could be broken into two steps:

1. "pull"ing an existing script from the Workers config service as part of "init"
2. "fetching" the current state of the existing project to then "diff" against the local version.

A good deal of hidden local filesystem operations would be required to make these possible; "pull" and "fetch" would require two requests to the Workers API: one to pull a script by name, and another to pull the script's bindings (second unnecessary if first comes back empty).

The diff part of this would likely need to be an interactive command, not something you would integrate with CI.

### Don't do:
This sync feature could be skipped for an MVP by telling the user to go to the dashboard and look for the differences (is it missing binding? is the script content different?). An "inherit bindings" feature option would also be a lower-effort interim solution. (i.e. "this binding is different on the server, do you want to overwrite or use the existing binding?")

# Other considerations, related notes
- needs to support all  types of bindings to be effective.

**Comment by EverlastingBugstopper** [comment]
@Electroid :)
