### ISSUE TITLE
Build failure returns code 0

### ISSUE THREAD

**Issue by ateixeira-pt** [cloudflare/wrangler#335]
wrangler build always returns 0 even when it fails to build

**Comment by xtuc** [comment]
Thanks for the report and the quick PR!

I'm wondering why we need the rust compiler, could you please post the stack trace with `RUST_BACKTRACE=1`?

**Comment by ateixeira-pt** [comment]
Sorry forgot to say , I'm testing this on JS

**Comment by ateixeira-pt** [comment]
@xtuc this also applies to the publish function and this messes up the CI/CD Pipeline and/or make

**Comment by granjef3** [comment]
Thanks for filing an issue! Could you provide some more information:
- what project type is in your wrangler.toml 
- output from `wrangler build` when it fails

**Comment by xortive** [comment]
Did some unsuccessful debugging on this issue on latest master branch for `wrangler build`
- JS
    - Possible error points
        - Tested - incorrect entry point - returns 0 on build, 1 on publish
            - This doesn’t feel like the issue
- Webpack
    - Possible error points
        - Tested - Project config - errors are correctly propagated and return 1
        - Tested - webpack imports - errors are correctly propagated and return 1
        - Tested - webpack stats errors - propagates correctly, returns 1
        - Tested - incorrect entry point - returns 1
        - Tested - broken webpack config - returns 1
        - Tested - wranglerjs exits with error 1 - propagates, wrangler returns 1
- Rust
    - Possible error points
        - Tested - rust compiler error - returns 1
