### ISSUE TITLE
Add KV Command: List Namespaces

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#342]
As a Workers KV user, I should be able to list all of the namespaces in my KV store from Wrangler by typing

``` sh
$ wrangler kv ls
```

**Comment by victoriabernard92** [comment]
Will it include KV tag? that'd be real niice

**Comment by ashleymichal** [comment]
> Will it include KV tag? that'd be real niice

yes, see #404 . The output will include Title and ID for each namespace returned.

Closed by #404
