### ISSUE TITLE
KV store for wrangler is totally broken

### ISSUE THREAD

**Issue by posix4e** [cloudflare/wrangler#352]
So it seems as though, i can specify kv stores to create but it does nothing to attach my worker to the namespace:

I specified
kv-namespaces = ["NAMESPACE2", "FOO", "BAR"]
and it created those namespaces , but it did nothing to attach those resources

**Comment by signalnerve** [comment]
Hey @posix4e - this is a known bug and we're working on implementing support for it in Wrangler. You can track the milestone here: https://github.com/cloudflare/wrangler/milestone/6
