### ISSUE TITLE
Standardize default wasm binding names / filenames

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#358]
Re: https://github.com/cloudflare/wrangler/pull/329#discussion_r307363159 it would be good to standardize what we call the default wasm binding and filename across rustwasm and webpack project types. this will require that we update rust worker templates, or perhaps make changes to the wranglerjs bundle code if we standardize on rust wasm.

**Comment by ashleymichal** [comment]
notes: in https://github.com/cloudflare/rustwasm-worker-template/blob/master/worker/worker.js, the wasm binding name is `wasm`. Webpack projects, however, use injection to map the binding to whatever the user names their import, so the binding name change can happen purely in Wrangler; therefore we will change the values for webpack projects rather than rust to match.

**Comment by ashleygwilliams** [comment]
closed by #822
