### ISSUE TITLE
Build fails on Linux due to OpenSSL dependencies

### ISSUE THREAD

**Issue by xortive** [cloudflare/wrangler#361]
I tried to build Wrangler on Ubuntu and had to install `pkg-config` and `libssl-dev`, I believe this means that vendored openSSL isn't working correctly? do we need openssl as a direct dependency if we don't use it directly?

**Comment by steveklabnik** [comment]
It's a non-default feature: https://github.com/cloudflare/wrangler/blob/master/Cargo.toml#L42

I don't know if it was intended to be the default or not, so i can't say if this is a bug or not.

**Comment by granjef3** [comment]
it's not documented that you need extra stuff to build in our docs, so I'm assuming it's a bug of some sort either docs or configuration

**Comment by xortive** [comment]
There are 3 options here to resolve this:

- Document that `--features vendored-openssl` will fix your build on linux if you don't install the necessary dependencies to build against linked openssl.
- Make `openssl/vendored` a default feature so it just works
- Use `rustls`. We would have to migrate the `binary-install` crate to use `reqwest` instead of `curl`
