### ISSUE TITLE
Wrangler is unable to publish w/ authentication failure, using env vars

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/wrangler#371]
```
$ CF_EMAIL="kristian@abc123.com" CF_API_KEY="xxxxx" ~/.cargo/bin/wrangler publish
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
✨   Built successfully, built project size is 517 bytes. ✨
Error: Something went wrong! Status: 400 Bad Request, Details {"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
```

Trying to publish a project (w/ no changes, directly from `wrangler generate`) using env vars, Wrangler is unable to authenticate. Similar error to #367, but w/ env vars

**Comment by ashleygwilliams** [comment]
could not repro with current master. closing. please reopen if you still have trouble... your problem *might* be the quotes

**Comment by alexmcroberts** [comment]
I'm having a similar issue.

My wrangler.toml file looks like:

```
account_id = "my-account-id-went-here-with-quotes"
name = "my-project"
type = "webpack"
# route = ""
workers_dev = true
# zone_id = ""
```

The `account_id` has been substituted.

The project I was building was from:

```
wrangler generate my-project https://github.com/cloudflare/worker-template
```

I've verified the API key in `~/.wrangler/config/default.toml` is correct using:

```
curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
     -H "Authorization: Bearer api-key-went-here" \
     -H "Content-Type:application/json"
```

and the response appears to be successful:

```
{"result":{"id":"id-was-here","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}
```

I also tried using the command below, without having `account_id` in the `wrangler.toml`:

```
wrangler preview
```

This was the result:

```
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
✨  Built successfully, built project size is 517 bytes.
⚠️  Your wrangler.toml is missing the following fields: ["account_id"]
⚠️  Falling back to unauthenticated preview.
👷  GET https://00000000000000000000000000000000.cloudflareworkers.com
👷  Your worker responded with: Hello worker!
```

**Comment by alexmcroberts** [comment]
I'm having a similar issue. I installed wrangler using `cargo install wrangler` on a MacBook Pro running macOS Mojave 10.14.6

For reference, here are the toml files I used:

`~/.wrangler/config/default.toml`:

```
email = "emailaddress@domain-went-here.com"
api_key = "api-key-went-here-with-quotes"
```

`my-project/wrangler.toml`:

```
account_id = "account-id-went-here-with-quotes"
name = "my-project"
type = "webpack"
# route = ""
workers_dev = true
# zone_id = ""
```
---
I tested the API key from the cloudflare workers dashboard:

```
curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \        
     -H "Authorization: Bearer api-key-went-here" \
     -H "Content-Type:application/json"
```
Result:
```
{"result":{"id":"id-went-here","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}
```
---
I used an example template:

```
wrangler generate my-project https://github.com/cloudflare/worker-template
```
I ran preview, before I modified the `account_id` from `account_id = ''`
```
wrangler preview
```

```
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
✨  Built successfully, built project size is 517 bytes.
⚠️  Your wrangler.toml is missing the following fields: ["account_id"]
⚠️  Falling back to unauthenticated preview.
👷  GET https://00000000000000000000000000000000.cloudflareworkers.com
👷  Your worker responded with: Hello worker!
```
Then I modified `account_id` and set it to the account id on the cloudflare worker dashboard. I expected this might have resulted in an error:
```
wrangler preview
```

```
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
✨  Built successfully, built project size is 517 bytes.
Error: https://api.cloudflare.com/client/v4/accounts/8ebb8d81a9b45eb8b6d4a42008072281/workers/scripts/my-project/preview: Client Error: 400 Bad Request
```
Then I tried publish and it resulted in a 400 Bad Request. The account_id was populated was still set to the account id on the cloudflare worker dashboard:
```
wrangler publish
```

```
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
✨  Built successfully, built project size is 517 bytes.
Error: Something went wrong! Status: 400 Bad Request, Details {"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
```

Happy to help with further debugging

**Comment by ashleymichal** [comment]
hey @alexmcroberts, thanks for the thorough repro!

so this is an interesting thing! Cloudflare's API actually supports two types of authentication: an email/global api key, and an api token. based on the curl command you ran to check yours, you are actually trying to use an api _token_ in place of the global api key. support for api tokens is on our radar (you can follow #471 for progress), but not yet implemented. In the meantime, I found my global API key on this page https://dash.cloudflare.com/profile/api-tokens UNDER the API tokens section.

Hope this helps!

**Comment by phayes** [comment]
Thanks @ashleymichal ! 

If wranger ony works with a global API key right now, can we have `wrangler config` throw an error when you try to use it with a non-global key?

**Comment by oleksandrborniak** [comment]
CLI Quick Start [https://github.com/cloudflare/wrangler/issues/cli](url)  has a button called "Get your API token" , not "Global API Key" . So this is confusing.
<img width="678" alt="Screenshot 2019-10-09 at 15 28 28" src="https://user-images.githubusercontent.com/49722408/66481849-6b79e000-eaaa-11e9-9a73-e9e3e4d6aea0.png">

**Comment by ashleygwilliams** [comment]
@oleksandrborniak you are 100% right! sorry about that and we'll get it fixed right away

**Comment by swisster4** [comment]
PayPal me directing at agirlgogo4@gmail.com last years start of contract

**Comment by gonzaloserrano** [comment]
Just run into this.

Also you could change `Enter api key:` for `Enter Global API Key` and even print the https://dash.cloudflare.com/profile/api-tokens link

**Comment by spsaucier-bakkt** [comment]
I'm still getting this error, despite using my global API key. Unable to `preview`, `dev`, or `publish`.

**Comment by crotel** [comment]
"Unable to preview, dev, or publish" till now in China internet. and while I got an VPN which Legal and compliant in China, they told me that, should add some while list, so, how do I know the while list hostname or ip that wrangler use. Thank you very much!
