### ISSUE TITLE
Getting error on Wrangler config

### ISSUE THREAD

**Issue by juancampuzano** [cloudflare/wrangler#377]
By updating my wrangler version of 1.1.0 I am having problems with the configuration of my credentials.

When giving `wrangler config <email> <api_key>`  I always get the following error:

![image](https://user-images.githubusercontent.com/52759609/62314457-aa5f3a00-b458-11e9-9008-33ebd69938bd.png)

*Note: When trying with real data it also throws the same error*

**Comment by steveklabnik** [comment]
I *think* from reading the code, you are supposed to do just `wrangler config` and it interactively asks you for this info.

**Comment by juancampuzano** [comment]
> I _think_ from reading the code, you are supposed to do just `wrangler config` and it interactively asks you for this info.

In version 1.0.0 I did it as I showed in the previous example. What is the way to configure wrangler that is not interactively for continuous integration environments?

**Comment by ashleymichal** [comment]
hey @juancampuzano , along with the interactive command for config, you can now use environment variables for email and auth key!

Previously, Wrangler required a global configuration file to be able to run. As many users may use Wrangler in situations where they don't have an interactive terminal, meaning they can't instantiate a config file using wrangler config, this PR allows Wrangler to run even if the config file doesn't exist. This change means that users can also configure Wrangler exclusively with environment variables, using $CF_API_KEY for your Cloudflare API key, and $CF_EMAIL for your Cloudflare account email.

However your comment has alerted me to the fact that we need to update this information in our README, so thank you for bringing that to our attention!

**Comment by EverlastingBugstopper** [comment]
closing in favor of #378 Thanks for the report @juancampuzano!
