### ISSUE TITLE
RFC: CI to publish npm installer pointed to lastest binary release + README update

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#380]
## Problem

1. Many users complained that the npm installer and wrangler versions differes. The npm installer always takes the latest wrangler version but the mismatch can be confusing.
1. The README published on npm is not the file in the root, it's duplicated and lives in the `./npm` directory.
1. An old version of the installer will still install the latest wrangler version

## Proposal

1. - When we release wrangler, the CI should publish the npm package
    - The npm package should have the same version than wrangler (for simplicity I was thinking to set `"version": "$VERSION"` and use [envsubst(1)](https://linux.die.net/man/1/envsubst) to replace it).
1. - Before publishing to npm, run `cp ./README.md ./npm`
1. won't fix.

**Comment by ashleygwilliams** [comment]
i'm in strong favor of this. i think that (very reasonable) end user confusion will continue if we don't fix, and we need to remember to update the package when README changes are made at this point it seems prudent to simply always update the npm package.

the downsides, which are small but worth noting:  if we notice a bug in the installer code, we'll need to publish a new version of the installer... and a new version of the binary, if we wish to keep the version numbers in sync. i think this is a small inconvenience and not likely to happen often.

**Comment by signalnerve** [comment]
+1

> the downsides, which are small but worth noting: if we notice a bug in the installer code, we'll need to publish a new version of the installer... and a new version of the binary, if we wish to keep the version numbers in sync. i think this is a small inconvenience and not likely to happen often.

this is an unfortunate side-effect, good call-out! still think the potential to reduce confusion makes this worth doing

**Comment by EverlastingBugstopper** [comment]
SGTM

**Comment by xortive** [comment]
I think fixing #3 going forwards so npm can be used to install old wrangler versions could be very useful, and would eliminate a confusing experience where someone tries to install old wrangler to self-debug some issue and instead gets the latest one and is back where they started.

To do #3 we would have to make a commit to https://github.com/cloudflare/wrangler/blob/f3d492a11bc7561ba9da8a5140832a7ac2ca94a2/npm/install-wrangler.js#L14 to update the url to 
`https://api.github.com/repos/cloudflare/wrangler/releases/tags/<tag of latest release>` and add this step to the release checklist.

**Comment by ashleygwilliams** [comment]
👍 we will move forward with the original proposal + @xortive 's comment.
