### ISSUE TITLE
Rust projects are not minified

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#384]
![image](https://user-images.githubusercontent.com/9408157/62386044-4aca6280-b51c-11e9-8cf8-5188ffa11ded.png)

image description: screenshot of unminified JavaScript for the default Rust project generated by wrangler

**Comment by ashleygwilliams** [comment]
would be great to "fix" my "concat" function while solving this ;)

**Comment by gabbifish** [comment]
Follow-up as I work on this: Do we want to use unminified JS for the preview, and minified JS purely for publication? I think this would be the right choice--you never know if folks want to poke around the concatenated js code in preview mode.

**Comment by ashleymichal** [comment]
> Follow-up as I work on this: Do we want to use unminified JS for the preview, and minified JS purely for publication? I think this would be the right choice--you never know if folks want to poke around the concatenated js code in preview mode.

I'd agree, except that there are some scripts that will go well over the size limit when not minified, and the preview service enforces the same limits. It might be that we give folks an option? or use environments to allow for custom webpack configs that do or do not minify js.

**Comment by gabbifish** [comment]
^ I like ashley's suggestion of making this an option; perhaps we can make minification the default and allow people to specify unminified code for debugging (this logic could live in the config, for example).

If we were to make this something users can control, are we okay with widening the scope of this PR? Or is this veering into bike shedding territory?

**Comment by EverlastingBugstopper** [comment]
We already allow users to specify their own webpack configuration with `webpack_config` in `wrangler.toml` :)

**Comment by gabbifish** [comment]
^ I think webpack_config is only used for Webpack projects, not Rust ones. Let's shelve the option-setting functionality to another issue; I'll focus on just getting basic minification to work :)

**Comment by EverlastingBugstopper** [comment]
It looks like we aren't going to get to this for 1.2.0 which is fine. Removing the milestone but let's keep the issue open and return when we have a better game plan

**Comment by gabbifish** [comment]
We are going to close this ticket in favor of having users specify minification options via webpack configs. For Rust workers in particular, users can depend on wasm-pack-plugin to define their desired minification behaviror. See https://github.com/cloudflare/workers-docs/issues/568
