### ISSUE TITLE
Wrangler can panic if global user configuration contains non printable characters

### ISSUE THREAD

**Issue by xortive** [cloudflare/wrangler#389]
These lines will read until `\n`, which means on windows `email` and `api_key` will have `\r` at the end
https://github.com/cloudflare/wrangler/blob/1841a16b03435bf92a5766b4f36b8d748466265a/src/main.rs#L156
https://github.com/cloudflare/wrangler/blob/1841a16b03435bf92a5766b4f36b8d748466265a/src/main.rs#L158

which will cause a panic at these lines since `HeaderValue::from_str` requires its input to consist of solely printable ASCII characters.
https://github.com/cloudflare/wrangler/blob/1841a16b03435bf92a5766b4f36b8d748466265a/src/http.rs#L37
https://github.com/cloudflare/wrangler/blob/1841a16b03435bf92a5766b4f36b8d748466265a/src/http.rs#L38

**Comment by xortive** [comment]
we should use `trim_end()` on `email` and `api_key` to handle the windows EOL, and then validate the fields and return an error if they aren't valid.

**Comment by xtuc** [comment]
Good catch! Maybe we could match different characters for either MacOS/Linux and Windows, but sounds a bit over-complicated.

**Comment by mgrollins** [comment]
Hi, came her from #390 and was able to resolve issue by deleting `\r` from **within** email and api_key string in global default.toml file on a window machine.

Thanks for working this!
