### ISSUE TITLE
Wrangler Workers preview OOM error

### ISSUE THREAD

**Issue by AustinCorridor** [cloudflare/wrangler#39]
I attempted to follow the Wrangler tutorial and started by generating the demo project; I did not modify anything in the project.
I ran wrangler preview and hit a OOM: wasm memory issue.
It's very reproducible and others have confirmed they hit it as well.
<img width="632" alt="Screen Shot 2019-03-28 at 9 06 52 PM" src="https://user-images.githubusercontent.com/21045301/55243423-39d7b080-520d-11e9-96e0-ffc36b7ad560.png">

**Comment by ashleygwilliams** [comment]
i've confirmed that this a bug in V8 (https://bugs.chromium.org/p/chromium/issues/detail?id=935169) that may or may not be aggravated by how Workers handles devtools session. we're working on this upstream!!

**Comment by ashleygwilliams** [comment]
i can confirm that this bug is only related to the Workers preview and does not happen in the paid products.

**Comment by xtuc** [comment]
Oh interesting, I have seen this flyng-by. It seems to be a common usage but according to the issue tracker nobody is actively working on it.

@ashleygwilliams maybe I will be able to take a look at it?

I'm not sure how problematic this issue is when using the Cloudflare's worker testing site, which I believe use the console.

**Comment by ashleygwilliams** [comment]
@xtuc- if u want to look knto it that‘d be great. i‘m gonna work on a stop gap this morning but i‘d love to fix the underlying bug. maybe we can hop on a call to chat about it?

**Comment by xtuc** [comment]
I would be happy to, however, I think it's preferable to wait until my work starts officially.

**Comment by ashleygwilliams** [comment]
@xtuc extremely reasonable :)

**Comment by harrishancock** [comment]
This is now worked around in the Workers runtime: https://community.cloudflare.com/t/2019-4-12-workers-release-notes/75442

**Comment by ashleygwilliams** [comment]
🎉
