### ISSUE TITLE
Use published `cloudflare-rs` crate rather than git repo

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#401]
During development of #339 we will be working closely with the team on cloudflare-rs (https://github.com/cloudflare/cloudflare-rs) to improve the library as we develop the first client using it. Before merging to master, though, we need to point Wrangler's cargo.toml to the published crate, rather than the latest commit on master.

**Comment by gabbifish** [comment]
0.3.1 was released: https://crates.io/crates/cloudflare
Just need a PR to update wrangler to use the crate!
