### ISSUE TITLE
Make size limit warning more prominent, don't preview when over limit

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#417]
The user report #393 included some unclear error messaging. The root of the problem was that the user's script exceeded the script size limit imposed by the Workers platform, however Wrangler could do a couple of things to improve the experience around this limit:

1. Improve the error printed when build exceeds 1MB by printing the warning on a second line:

``` sh
# instead of this:
✨ Built successfully, built project size is 1 MiB. ⚠️ Your built project has grown past the 1MiB size limit and may fail to deploy. ⚠️ ✨
# print this:
✨ Built successfully, built project size is 1 MiB. 
⚠️ Your built project has grown past the 1MiB size limit and may fail to deploy.
```
2. Don't push to the preview service if the script size exceeds 1MB. The errors returned from the preview service are generally vague at this point, so it's best to simply not.
3. Add a `help` message with suggestions for reducing script size, such as disabling source maps, turning on minification, and enabling performance hints. (This may make the most sense for webpack projects only).

**Comment by xortive** [comment]
with regard to 2: The 1mb limit we calculate is not done in the same way that the runtime does it... Simulating this exactly is difficult. I think catching the error and returning our own error may be helpful when running up against the size limit, but halting on our calculated limit could break people who's workers are up against the limit and work today.

**Comment by bladerunner41** [comment]
Perhaps Cloudflare could increase the 1MB limit to 3MB to match StackPath.  
This could give you some breathing room to align the platform limit and CLI limit without breaking anyone.
I say this seriously.
