### ISSUE TITLE
install issues using npm installer on centOS

### ISSUE THREAD

**Issue by bipolarmorgan** [cloudflare/wrangler#421]
DOESN'T INSTALL

**Comment by xortive** [comment]
Hey, thanks for filing an issue. We'd love to help out, but we need some more information. Would you mind filling out some relevant sections of our bug report template?

#### Environment

* operating system:
* output of `rustc -V`:
* output of `node -v`:
* output of `wrangler -V`:

#### Steps to reproduce

What command are you using to install wrangler

**Comment by bipolarmorgan** [comment]
CentOS 7
rustc 1.36.0
node 10.16.2
wrangler 1.1.1 (*which I was only finally able to install after installing cargo and fixing some build issues)

Now I can only get two workers to produce any proper results...

**Comment by ashleygwilliams** [comment]
hi @bipolarmorgan ! thanks for responding with your info. can you explain how your attempt to npm install is failing? we'll need the specific error message to be able to debug.

sorry to hear that you are running into some issues with your worker projects. we'd like to track each issue separately, so please file an issue with the exact command you were running, your worker code, and the exact error message you are seeing.

**Comment by bipolarmorgan** [comment]
I would, but I'm well past that point, your install script through npm errored on every try. Then I finally thought what about cargo and it installed with an error, that I don't even remember, but I think it had to do with node-gyp ... If you tell me how to uninstall it, I'll reinstall and take notes for ya...

**Comment by ashleygwilliams** [comment]
you can uninstall wrangler by running `cargo uninstall wrangler`

**Comment by bipolarmorgan** [comment]
Ok, Uninstalled via cargo.
Then I will try to install via npm i @cloudflare/wrangler -g
it says it installed v1.1.1 successfully ... then I type wrangler at the cmd prompt and get
-bash: wrangler: command not found 

The last time I tried that method it gave other errors before it gave me the bash error....

**Comment by bipolarmorgan** [comment]
Then I run npm uninstall @cloudflare/wrangler and get this error:
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'

so I run it again... same thing. So then I'll try reinstalling via npm

and again the bash error. I'm assuming I'm not seeing the other errors because I fixed them and just don't remember what I did to fix them...sorry.

**Comment by bipolarmorgan** [comment]
Then I run cargo install wrangler (after I installed cargo) ... and this makes my CPU usage shoot to 100%, fans spinning loudly.... but after a few minutes of that, it succeeds with this - 
warning: be sure to add `/root/.cargo/bin` to your PATH to be able to run the installed binaries
then I run - export PATH=$PATH:/root/.cargo/bin

and voila I can run wrangler from bash...

**Comment by ashleygwilliams** [comment]
interesting. thanks for the details @bipolarmorgan - it sounds like you did eventually get up and running. is there anything else we can do to help?

**Comment by bipolarmorgan** [comment]
@ashleygwilliams I'm having issues getting certain example scripts to work, if you can help there, that'd be great.

**Comment by EverlastingBugstopper** [comment]
@bipolarmorgan if you could open a new issue with details about what exactly isn't working, we'd love to help! I'm going to close this issue and we can track other problems you're running into elsewhere. Thanks so much for documenting everything here :)
