### ISSUE TITLE
Suggest re-building node_modules on failed builds where appropriate

### ISSUE THREAD

**Issue by xortive** [cloudflare/wrangler#428]
We assume that the existence of `node_modules` in a `webpack` project means the dependencies are installed and we don't need to run npm install again. However, if the user does ctrl-c during `wrangler build`, `wrangler publish` or `wrangler preview` while the npm install stage is running, it is possible to have a `node_modules` folder with invalid contents.

**Comment by EverlastingBugstopper** [comment]
ooh good catch. do you think it's worth running `npm install` on every build or is there a better way to check for an unfinished install?

**Comment by gusvargas** [comment]
I've never developed/published a worker before so sorry if I'm misunderstanding something about the workflow... Wouldn't eagerly `npm installing`-ing make it possible for your dependencies to shift between build/publishes/previews (assuming a lock file isn't used or isn't capturing all transitive dependencies)? If so, I think it that would be a bit surprising – I wouldn't expect build/publish/preview to have side-effects outside of what the command describes.

Seems like the question that needs to be answered is "is something in node_modules wrong?" –  [`yarn check --verify-tree`](https://yarnpkg.com/lang/en/docs/cli/check/#toc-yarn-check-verify-tree) can help with that even if `yarn` wasn't used to install the dependencies originally. It should be easy enough to shell out to it and observe the exit code or process its stdout. If an issue was detected I'd probably want to be prompted for permission before wrangler ran the install process itself.

If I'm missing some context then I apologize for the distraction.

/cc @ashleymichal

**Comment by ashleymichal** [comment]
for the moment, we should try outputting a helpful message when these errors occur, such as "encountered error running `npm install`; try removing `DIR/node_modules` and running again" or "try running `yarn check --verify-tree`", etc.
