### ISSUE TITLE
NPM installer fails with opaque errors when run without -g

### ISSUE THREAD

**Issue by xortive** [cloudflare/wrangler#434]
We should return a better error to tell the user to run it with -g

**Comment by EverlastingBugstopper** [comment]
I'd argue this is more of a feature than a bug, it's not correct to run w/o `-g`. We can definitely give some better messaging when it's run w/o `-g` but I wouldn't say it's a bug 😄

**Comment by signalnerve** [comment]
-1, i think the error is consistent with trying to install other packages in a similar way. we should confirm that we do always refer to it as `npm i -g wrangler` though

**Comment by mxdpeep** [comment]
> npm i -g wrangler

+ wrangler@0.0.2

this is not good

**Comment by EverlastingBugstopper** [comment]
Hi @mxdpeep, unfortunately wrangler is not the correct install name for npm! You will need to run `npm install -g @cloudflare/wrangler` instead!
