### ISSUE TITLE
wrangler config should test for valid credentials

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#439]
#### Environment

* operating system:
* output of `rustc -V`: `rustc 1.35.0 (3c235d560 2019-05-20)`
* output of `node -v`: `v12.4.0`
* output of `wrangler -V`: `👷 ✨   wrangler 1.1.1`

#### Steps to reproduce

Leave email + api key fields blank when running `wrangler config`

```bash
❯ wrangler whoami
💁‍  👋  You are logged with the email 'me@cloudflare.com'.
❯ wrangler config
Enter email: 

Enter api key: 

✨   Successfully configured. You can find your configuration file at: /Users/me/.wrangler/config/default.toml
❯ wrangler whoami
💁‍  👋  You are logged with the email ''.
❯ rm /Users/me/.wrangler/config/default.toml 
❯ wrangler whoami
Error: ⚠️  Your global config has an error, run `wrangler config`: missing field `email`
```

#### What did you expect to see?

I either expect to see `wrangler config` return an error when I pass it invalid credentials, and for `wrangler whoami` to error when there are invalid credentials in their `.wrangler/config/default.toml`

#### What did you see instead?

No errors and `wrangler whoami` saying that I am successfully logged in as `email ''`.

#### Other cases

It's not just empty credentials that can be successfully configured, completely fake ones work just fine as well.

```bash
❯ wrangler config
Enter email: 
a@cloudflare.com
Enter api key: 
1234
✨   Successfully configured. You can find your configuration file at: /Users/me/.wrangler/config/default.toml
❯ wrangler whoami
💁‍  👋  You are logged with the email 'a@cloudflare.com'.
```

**Comment by ashleymichal** [comment]
one of the bigger issues here is that some of the error messages that wrangler gives for bad credentials are garbage. we should at least improve those. forcing valid credentials may be out of scope for this release (1.3.0).

**Comment by gabbifish** [comment]
If /user is not ready for use with API tokens, we can use the /user/tokens/verify endpoint as mentioned in https://blog.cloudflare.com/api-tokens-general-availability
