### ISSUE TITLE
Allow to deploy to a route from

### ISSUE THREAD

**Issue by rita3ko** [cloudflare/wrangler#44]
`wrangler publish` pushed up the script to the edge, but actually getting it running on the edge still required signing in and using the UI.

It would be great to be able to specify a route to deploy to, i.e:
`wrangler route example.com/hello`
or have a default route that the script gets deployed to. i.e. `wrangler publish` would just push to random-string.example.com. 

Alternatively, you could have a route configured as a part of `wrangler config`

**Comment by xtuc** [comment]
My experience is that a config file would be more UX-friendly; it's shareable, versionable etc.

**Comment by ashleygwilliams** [comment]
i intend to close this issue by creating a default route, and/or taking a parameter to `publish`. i have an issue i will be filing shortly about a per project config file.

**Comment by ashleygwilliams** [comment]
https://github.com/cloudflare/wrangler/issues/45

**Comment by ashleygwilliams** [comment]
@rita3ko thoughts on `/*` as the default route?

**Comment by rita3ko** [comment]
@ashleygwilliams that makes sense to me. question is - what would be the hostname?

**Comment by ashleygwilliams** [comment]
@rita3ko zone from the zone id (for now a required param, eventually a per project config file)
