### ISSUE TITLE
Support negation flags for publish, preview

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#450]
A refinement of #449 :
Sometimes you just want to publish your assets, but your Worker should stay the same.
Sometimes you just want to update your worker, but your assets should stay the same.

Wrangler should support `--no-assets` and `--no-worker` flags for these use cases.

**Comment by EverlastingBugstopper** [comment]
Would it also  possible to have this be inferred w/o passing a flag?

**Comment by ashleymichal** [comment]
i mean, if you don't have `assets` defined, we won't push things to KV.

**Comment by ashleymichal** [comment]
closed by #598 , but probably will be removed
