### ISSUE TITLE
Separate "bucket" use case from JSON uploads

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#459]
Currently we have two ways to handle KV bulk uploads: 

1. You can use the API raw and build your own JSON file with custom keys and values (we'll call this a standard `write`).

2. We also have a model where we walk a directory and generate keys on your behalf, effectively simulating a "bucket" that you access by path as if it was just a remote copy of your local assets directory.

Because the latter is really a specialized use case of the former, it seems more appropriate to make it its own class of commands; as a strawman, `wrangler bucket`, where you can either `wrangler bucket push` or `wrangler bucket pull` to sync the directory up or down as appropriate.

**Comment by gabbifish** [comment]
Ideally, bucket functionality could follow the `put`, `delete`, and `sync` functionality offered by popular bucket store CLIs like s3cmd: https://s3tools.org/s3cmd

**Comment by ashleymichal** [comment]
i'm also proposing lumping this into the KV Additions milestone, since it's a sort of higher level functionality built on normal api calls.

**Comment by gabbifish** [comment]
Closed by #485.
