### ISSUE TITLE
Add way to ignore certain assets

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#464]
#### Overview and problem statement

Ignore `.DS_Store` and maybe everything in `.gitignore`. Perhaps we need a `.wignore` or something for assets we don't want to upload

**Comment by ashleymichal** [comment]
hmm. piggybacking on gitignore would be great, however i think we would need to hook into git's logic since many users put `.DS_Store` in their root gitignore.

**Comment by ashleymichal** [comment]
on second thought, it is common to gitignore static site public folders since they are repeatedly regenerated from source; so gitignore is not a thing we should do. Perhaps we should just ignore "hidden" files? Should look and see what other solutions do.

**Comment by ashleymichal** [comment]
we should for sure ignore things like `node_modules`

**Comment by gabbifish** [comment]
This will be super useful for .wignore: https://git-scm.com/docs/gitignore

We should have feature parity with gitignore. :)

**Comment by EverlastingBugstopper** [comment]
https://crates.io/crates/ignore

**Comment by gabbifish** [comment]
Closing because this is now tracked in #716
