### ISSUE TITLE
Wrangler generate project name requirements

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/wrangler#470]
#### Environment

* operating system: OSX
* output of `rustc -V`: ` rustc 1.36.0 (a53f9df32 2019-07-03)`
* output of `wrangler -V`: `👷 ✨  wrangler 1.2.0`

#### Steps to reproduce

```
wrangler generate myApp https://github.com/cloudflare/worker-template 
cd myApp
# config wrangler.toml
wrangler publish
```

#### What did you expect to see?
Wrangler generate should either:
1. rename project names to Worker API accepted values 
OR 
2. reject the project name upon `generate`
Instead one can successfully generate a project with a name not accepted by the API

#### What did you see instead?
```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN myApp@1.0.0 No repository field.

added 1 package in 1.181s
⬇️ Installing wranglerjs...
✨  Built successfully, built project size is 517 bytes.
Error: Something went wrong! Status: 400 Bad Request, Details {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10016,
      "message": "workers.api.error.invalid_script_name"
    }
  ],
  "messages": []
}
```
Original discussion in https://github.com/cloudflare/cloudflare-docs/issues/261

**Comment by gabbifish** [comment]
We will check that a given worker name is valid by running it against the workers name regex, `"^[a-z0-9_][a-z0-9-_]*$"`. cc @ashleygwilliams @ashleymichal
