### ISSUE TITLE
use target: webworker

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#477]
We should force the `target: webworker` configuration in webpack, it will avoid webpack's runtime to use `window` or `document`.

**Comment by lolcoolkat** [comment]
@xtuc is there any way we can get a minor version push to npm to include this update? :cry:

**Comment by xtuc** [comment]
You can set `target: "webworker"` in your webpack configuration, if you have one as a workaround.

**Comment by EverlastingBugstopper** [comment]
You can also clone this repository and run `cargo install --force --debug --path .` to get the latest version. This does not come with many QA guarantees though, we try to only merge things into master that we are confident with, but we do more rigorous testing on releases.
