### ISSUE TITLE
Allow users to specify worker directory when running `wrangler publish`

### ISSUE THREAD

**Issue by gabbifish** [cloudflare/wrangler#482]
#### Overview and problem statement
There are Wrangler users that may use workers in a monorepo; that is, they will have multiple generated workers in one repository. This means that, for actions like CI, `wrangler publish` may be run on a specific worker within a monorepo. This is a case where providing an optional path argument for `wrangler publish` may be useful.

#### Basic example

Include a basic code example of this new feature if possible. Omit this section if not applicable.
Let's say we have a repo with multiple generated workers directories:
```
.
├── a
└── b
```
If we want to deploy the worker in directory `a` from the root of this repo, we would run
```
$ wrangler publish a
``` 
If we are just deploying from a worker directory, the preexisting `wrangler publish` invocation should still work.

**Comment by EverlastingBugstopper** [comment]
+1
