### ISSUE TITLE
Allow file bindings as text_blob 

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#483]
#### Overview and problem statement

We have a worker that does a HTML transformation that adds a new JavaScript script tag, called client code. We want to store the client code along the server-side transformation.

The server-side and client-side codes need to keep sync, even during deployements, so I think KV wouldn't be a good fit.

Alternatively, we can use webpack to inline the client-side code into the worker. But allowing files as text_blob seems useful (a customer requested to inline images, we can use the same technique). 

#### Basic example

worker.js:
```js
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

async function handleRequest(request) {
  return new Response(CLIENT_SIDE_CODE);
}
```

metadata.json:
```json
{
  "body_part": "foo",
  "bindings": [
    {
      "name": "CLIENT_SIDE_CODE",
      "type": "text_blob",
      "part": "CLIENT_SIDE_CODE"
    },
  ]
}
```

Then the multipart from needs to include the `CLIENT_SIDE_CODE` part. Note that the size limit needs to take metadata.json into account too.

**Comment by xtuc** [comment]
WIP branch https://github.com/cloudflare/wrangler/tree/sven/text-blobs

**Comment by EverlastingBugstopper** [comment]
This is _kinda_ supported with the introduction of sites but we would need to add some stuff to `wrangler.toml` to expose it to users

**Comment by xtuc** [comment]
We wanted to avoid using KV for that.

**Comment by EverlastingBugstopper** [comment]
I understand - with workers sites we upload an asset manifest that is a text blob. Text blobs can be uploaded, the back end is there in wrangler, we just haven't done the work to expose it to the users

**Comment by gabbifish** [comment]
@ashleymichal, what are you thinking in terms of an approach here? I am not opposed to putting full text bindings in wrangler.toml. The alternate approach is to upload text bindings exactly like secrets, but I think this is problematic from an API perspective; we're further straying away from the original intent of bundling workers with their bindings every upload. Secrets was supposed to be the only exception to that.

**Comment by ashleymichal** [comment]
these should only be specified in the toml under something like "globals". we will not be adding commands for these, as they would add little value for lots of state inconsistencies.

**Comment by EverlastingBugstopper** [comment]
we should make sure you can have per-env blobs as i'm sure they will be used to distinguish between staging and prod in the code

**Comment by ashleymichal** [comment]
i think blobs should follow a pretty standard inherit pattern; that is, i would not _force_ users to specify per-environment text vars

**Comment by xtuc** [comment]
Blob could host a sourcemap too, we need it to be per env.

**Comment by ashleymichal** [comment]
perhaps i was not clear: text blobs should be subject to the same inheritance pattern as some other fields; if one is specified top level but not at the env level, it should inherit, but an env level specification should overwrite. what i'm suggesting is that we not error or even necessarily warn if a text binding is not specified for every env.

**Comment by EverlastingBugstopper** [comment]
@xtuc do you think this is solved with secrets/config vars?

**Comment by ashleymichal** [comment]
this  should not (and likely  cannot) be handled by secrets/config  vars   due to size limitations.
