### ISSUE TITLE
Add command for syncing a "bucket"

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#484]
per https://github.com/cloudflare/wrangler/issues/459, we want to separate the use case where a user specifies a directory for upload with paths as keys into its own subclass of commands.

There should be one command (or at least the logic for publish to use) for syncing the contents of a directory up to the specified namespace; this includes clearing keys that no longer exist in the local directory.

**Comment by gabbifish** [comment]
Closed by #614
