### ISSUE TITLE
Ensure that rustc and other dependencies are installed before building a rust project

### ISSUE THREAD

**Issue by aqueenan** [cloudflare/wrangler#487]
### 🐛 Bug Report

`wrangler build` produces an unhelpful error message when rustc isn't in the path.

#### Environment

* operating system:
```
Microsoft Windows [Version 10.0.18362.295]
Command Prompt and Bash has the same problem though.
```
* output of `rustc -V`:
```
'rustc' is not recognized as an internal or external command,
operable program or batch file.
```
* output of `node -v`:
```
v8.11.3
```
* output of `wrangler -V`:
```
 wrangler 1.1.1
```

#### Steps to reproduce

I installed wrangler using npm, and created a rust project, then called `wrangler build`.

#### What did you expect to see?

Either a successful build, or a helpful error message prompting me to use rustup to install rustc and the dependencies.

#### What did you see instead?

When I called `wrangler build` I got the error:
```
>wrangler build
⬇️ Installing wasm-pack...
 Compiling your project to WebAssembly...
Error: The system cannot find the file specified. (os error 2)
Error: failed to execute `"cmd" "/C" "...\\AppData\\Local\\.wrangler\\wasm-pack-7824e3bac6af138a\\wasm-pack.exe" "build" "--target" "no-modules"`: exited with exit code: 1
```
The underlying issue is that wasm-pack doesn't return a helpful error either, just an exit code.

**Comment by ashleymichal** [comment]
for someone looking to pick up an  issue, this should be  easy enough  to check in the  build module using `which`
