### ISSUE TITLE
Split to make multiple requests when total payload exceeds 100MB

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#499]
The Cloudflare API puts a hard limit of 100MB on total payload size. For bucket uploads, Wrangler should intelligently split up payloads to fit this requirement. 

We should also check the size of each key and value to prevent partial uploads.

**Comment by gabbifish** [comment]
Should this only apply for bucket uploads? Not bulk ones? I would argue that it's okay to restrict this to bucket uploads.

**Comment by ashleymichal** [comment]
i think for the moment that is fine.

**Comment by gabbifish** [comment]
Closed by #601
