### ISSUE TITLE
Customize help

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#506]
We have namespaced the KV commands; however it would be nice if a user could type

```sh
$ wrangler kv --help
```

and get help on _all_ kv subcommands organized by namespace. This should be in addition to the help commands generated by clap automatically for each subcommand (i.e. `kv:key`).

**Comment by gabbifish** [comment]
I've tried to make this work today, and with Clap, it looks like I'm stuck having to add another `kv` subcommand to the list of options:
```
USAGE:
    wrangler [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    kv                            ??????
    kv:namespace     Interact with your Workers KV namespaces
    kv:key           Interact with individual Workers KV key-value pairs
    kv:bulk          Interact with bulk sets of Workers KV key-value pairs
    ...
```
I wish we could simply make `kv` a subcommand and have the other `kv:namespace`, `kv:key`, `kv:bulk` commands fall underneath it (like Heroku's CLI does) but this is seemingly not possible with Clap. If we were to approximate something like this in Clap, we'd end up with a situation where invoking kv commands would look like
```
$ wrangler kv kv:namespace...
```
This honestly makes me kinda wish we went with 
```
$ wrangler kv namespace <action>
```
invocations instead. But for the meantime, I'm going to mark this issue as blocked--I don't think there is a good way for us to implement this as is.

**Comment by ashleymichal** [comment]
thanks for trying @gabbifish . This was a nice to have for sure, perhaps if there is need we can request a feature in clap, but it's non-blocking on our work for kv subcommands. i'll remove the issue from the milestone and we can decide at next triage whether to close it entirely.

**Comment by gabbifish** [comment]
Sounds great @ashleymichal! We could definitely open up a feature request in Clap :D it would be lovely to see this functionality supported in the future...

**Comment by ashleymichal** [comment]
closing as won't do. `wrangler --help` gives plenty of context on kv  commands.
