### ISSUE TITLE
`wrangler preview --watch` only detects the first change (on Linux)

### ISSUE THREAD

**Issue by kentonv** [cloudflare/wrangler#517]
#### Environment

* operating system: Linux (Debian Buster; kernel 4.19.37)
* output of `rustc -V`: N/A
* output of `node -v`: N/A
* output of `wrangler -V`: 1.2.0

#### Steps to reproduce

1. Run `wrangler preview --watch`.
2. See preview.
3. Make a change to the code.
4. See preview update. Cool!
5. Make another change to the code.

#### What did you expect to see?

Preview updates again.

#### What did you see instead?

Preview did not update.

The full output of Wrangler at this point is:

```
 JavaScript project found. Skipping unnecessary build!
 watching "worker.js"
 Detected changes...
 Detected change during cooldown...
 Cooldown over, propogating changes...
 Updated preview with changes
```

No matter how many times I make changes to `worker.js`, no more output is shown and the preview is not updated.

It appears that Wrangler is failing to notice the file changing after the first time. Since file change notification APIs vary wildly across platforms, it's very possible this bug is Linux-specific.

**Comment by gabbifish** [comment]
Hi there! 

Thanks for reporting this. I was able to reproduce this with a Javascript worker. It looks like live reload works for multiple iterations to Webpack (default) workers, so I suspect this may not be a problem with the file change notification API. I'll investigate. :)
