### ISSUE TITLE
Binding multiple KV namespaces is unclear

### ISSUE THREAD

**Issue by kentonv** [cloudflare/wrangler#518]
The documentation says you can bind a KV namespace like:

```
[[kv-namespaces]]
binding = "FOO"
id = "0f2ac74b498b48028cb68387c421e279"
```

It says "Each namespace you include should have an entry in your wrangler.toml that includes:" and then describes the `binding` and `id` properties.

So to bind multiple namespaces, I tried:

```
[[kv-namespaces]]
binding = "FOO"
id = "0f2ac74b498b48028cb68387c421e279"
binding = "BAR"
id = "068c101e168d03c65bddf4ba75150fb0"
```

This resulted in an error:

```
Error: duplicate key: `binding` for key `kv-namespaces` in wrangler.toml
```

It turns out the correct thing to do is to create TWO `[[kv-namespaces]]` sections:

```
[[kv-namespaces]]
binding = "FOO"
id = "0f2ac74b498b48028cb68387c421e279"

[[kv-namespaces]]
binding = "BAR"
id = "068c101e168d03c65bddf4ba75150fb0"
```

The docs should clarify this. Also, maybe the section header should be called `[[kv-namespace]]` (singular) rather than `[[kv-namespaces]]` (plural)?

**Comment by ashleymichal** [comment]
this has been bothering me too. TOML reads funny this way.

with environments on the way this gets even more confusing; i'm inclined to change the examples to the equivalent:

``` toml
kv-namespaces = [{ binding = "STATIC_CONTENT", id = "c417513a199c4289a1a0c8385c58a0e7" }]
```

as it nests better under other tables.

**Comment by EverlastingBugstopper** [comment]
Ooh I like this much better
