### ISSUE TITLE
Handle duplicate route API error

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#519]
#### Overview and problem statement

When pushing a worker with a different name to a route that already exists, the Cloudflare Workers API returns an error. Wrangler should handle this error gracefully, and not print the raw API response.

#### Basic example

To reproduce, create a worker named `worker`, change your route to `myzone.com/test` run `wrangler publish`. Then change the name in your toml to `worker-test` and run `wrangler publish` again. You should see this: 

```sh
Error: ⚠️  There was an error creating your route.
 Status Code: 409 Conflict
 Msg: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10020,
      "message": "workers.api.error.duplicate_route"
    }
  ],
  "messages": []
}
```

It'd be nicer if we had a map of status codes/API messages to more user friendly messages.

**Comment by pradovic** [comment]
Hi,

Is the issue to map all status codes/API messages to more user friendly message, or just to handle `workers.api.error.duplicate_route` for now? I am asking because I see similar messages on lots of different API errors, something like this for example: 
``` Error: ⚠️  There was an error fetching your subdomain.
 Status Code: 404 Not Found
 Msg: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10007,
      "message": "workers.api.error.not_found"
    }
  ],
  "messages": []
}
 ```

**Comment by saran19** [comment]
Route pattern must include zone name:

**Comment by ashleymichal** [comment]
hey @saran19 thanks for the update! This issue is closed, and while it looks related, the error you are reporting is actually separate. can you please file a new bug issue with your case?
