### ISSUE TITLE
Firefox not supported with hot reload

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/wrangler#532]
#### Environment

* operating system: macOS
* output of `rustc -V`: 1.37.0
* output of `node -v`: 8.11.4
* output of `wrangler -V`: 1.2
* browser: Firefox 69

#### Steps to reproduce
wrangler preview 
make change in VScode 
get log output
```
🌀  Detected change during cooldown...
🌀  Cooldown over, propogating changes...
💁‍  Ignoring stale first change
🌀  Detected changes...
🌀  Detected change during cooldown...
🌀  Cooldown over, propogating changes...
✨  Built successfully, built project size is 4 KiB.
👷  Updated preview with changes
```
change not in previewer

#### What did you expect to see?
Change in preview 

#### What did you see instead?
Stale code in previewer

**Comment by tmikaeld** [comment]
I'm seeing the same, Firefox 69.0.2

Seems it cannot establish Websocket, there's some errors in the console.

![Image 2019-10-11 at 1 57 43 PM](https://user-images.githubusercontent.com/907195/66649781-54182f80-ec2f-11e9-9159-11e21e30873a.png)

**Comment by EverlastingBugstopper** [comment]
@victoriabernard92 could you add labels to this issue?

**Comment by ashleymichal** [comment]
just tested this with wrangler 1.9.0 and firefox 76 and i do in fact get a reload with a hello world. closing for now, please reopen if it recurs.
