### ISSUE TITLE
MongoDB driver NPM issues

### ISSUE THREAD

**Issue by limnove** [cloudflare/wrangler#543]
#### Environment

* OS: MacOS 10.12.6
* output of `node -v`: 8.16.0
* output of `wrangler -V`: 1.2.0

#### Steps to reproduce

Install mongoose or the native mongodb node driver via npm and then try to do "wrangler preview"

#### What did you expect to see?

I expected it to pack one mongoDB node driver at least to be able to access mongoDB drivers inside a Worker.

#### What did you see instead?

Error: Webpack returned an error regarding files that either don't exist or don't have a valid configuration.

Anyone knows of some kind of node mongoDB driver we can use on a Cloudflare Worker to access remote MongoDB databases? The db-connect cloudflare project explicitely says that it still doesn't work with MongoDb so that's not a viable solution for me. Didn't want to have a server just to serve mongoDB through http request as that kind of defeats the purpose of a serverless approach.

Thanks in advance

**Comment by xtuc** [comment]
Could you please share the error you are seeing? My guess is that the MongoDB node driver isn't compatile with a Web/ServiceWorker environment.

**Comment by limnove** [comment]
> Could you please share the error you are seeing? My guess is that the MongoDB node driver isn't compatile with a Web/ServiceWorker environment.

yes it is not compatible with a web environment although it works perfectly fine with amazon lambda or google functions. That's exactly why I'm asking you if there's any workaround since you were able to get one for MySQL and whatnot.

**Comment by EverlastingBugstopper** [comment]
Unfortunately you will not be able to use any module that requires the node runtime. The Cloudflare workers platform is based on the Service Workers API and uses V8 isolates. This is why we can promise practically non-existent cold starts, but also prevents you from using libraries that rely on the Node runtime.

**Comment by limnove** [comment]
> Unfortunately you will not be able to use any module that requires the node runtime. The Cloudflare Workers platform is based on the Service Workers API and uses V8 isolates. This is why we can promise practically non-existent cold starts, but also prevents you from using libraries that rely on the Node runtime.

okay I get that perfectly. Still, mongoDB is currently one of the Top 3 databases in use worldwide. Surely you've given some thought into how your users may access a mongDB remotely no?

**Comment by limnove** [comment]
It's really strange because you can currently use MySQL, MariaDB, PostgreSQL and even GraphQL but not mongoDB?

**Comment by zackbloom** [comment]
We have some experiments around connecting to databases (which you may be referencing), but we don't have a released and supported way of connecting to MySQL, MariaDB, or PostgreSQL at this time. Our GraphQL support is based around it's HTTP API, and you can connect to any other HTTP supporting database.

Thank you for opening this ticket and for commenting, it's an amazing thing for us that you want to use Workers and we're moving as fast as we can to get you the database support you need.

**Comment by nicovigil1** [comment]
anyone happen to have any luck with a workaround for this?

**Comment by greg-mckeon** [comment]
Hi @nicovigil1,

Support for the native MongoDB driver is something we're still working towards.  One approach we've considered in the short term is providing a GraphQL layer in front of MongoDB - would this approach help with your use-case?

**Comment by matteolobello** [comment]
Hi everyone, are there any updates about MongoDB support?

**Comment by ricky11** [comment]
not sure if you can use mongodb realm sdk ?
or with the new mongodb 5 does atlas allow http connections?
