### ISSUE TITLE
Cleanup 1.3.0 work

### ISSUE THREAD

**Issue by gabbifish** [cloudflare/wrangler#547]
In an effort to get environments merged so we could complete KV work dependent on it in time for 1.3.0, it would be great to revisit comments like https://github.com/cloudflare/wrangler/pull/534#discussion_r322081165 and continue refactoring/cleanup that we couldn't get done in time for 1.3.0! :dancer:

**Comment by ashleygwilliams** [comment]
closing in favor of . #538
