### ISSUE TITLE
Add messaging for where to find account id when it's missing from wrangler.toml

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#566]
if account id is not specified - we should run the logic in `wrangler whoami` to print out list of account ids

**Comment by garrettgalow** [comment]
+1 - after getting wrangler setup and trying to create a subdomain you get blocked by the missing account id. 

Fixing #331 will fix this for most folks since it would be inferred.

**Comment by neynah** [comment]
Yeah it can be found in 3 places: right sidebar on overview of any zone, right sidebar on Workers overview, and in the URL bar. Maybe there are ways we can make this info more accessible in the dashboard. It would be nice if users could find it easily without having to onboard a zone or onboard to the Workers dashboard.
