### ISSUE TITLE
Documentation doesn't represent current published version

### ISSUE THREAD

**Issue by wilsonpage** [cloudflare/wrangler#582]
I've been attempting to use `wrangler publish --env …` but found was hitting errors. Then I discovered that the feature hadn't been released yet and I was reading future API docs.

This is quite confusing I caused be to lose quite some time. All Wrangler documentation links I've stumbled across. point to `master/README.md`. I should have been reading `v1.2/README.md` as that is the current `@latest`.

Not sure what the best way of solving this is … ? Maybe keeping `master` as current and working on new versions in a separate `branch`. [`zeit/next.js`](https://github.com/zeit/next.js) have a similar "docs in README.md` approach and however they manage that seems to be working OK. I think cus they dev on a `canary` branch and periodically merge that into `master`.

I dunno! Just thought you'd like the feedback to help other users in future :D

**Comment by ashleygwilliams** [comment]
hi @wilsonpage ! thanks so much for filing and sorry you are running into this issue. we're super excited to release the environments feature and we're amped that you want to use it!

it's true that much of our documentation currently exists in our readme and, in some cases, confusingly reflects unreleased features. this is a relatively classic issue on github that many projects that i've worked on suffer from.

while we could put in efforts to change our development process such that our README reflects what is currently released and not what is on master, we're opting instead to move the entirety of our documentation to our primary docs page (developers.cloudflare.com/workers) and not have it tracked on the README. we'll publish those docs alongside a release to ensure that the docs accurately reflect the currently released build. we're aiming to have this docs challenge solved by early Q4!

in the meantime- if you build from master (cargo install --git https://github.com/cloudflare/wrangler) you can use those new features today! we'd love feedback :)

**Comment by wilsonpage** [comment]
Great thanks for the clarification! I'm very excited about this project and CF Workers in the general!

While you're here can you point me to any known limitation of CF-Workers. For example is it possible to connect to a database other than KV? Would be interesting to know what applications CF-Workers aren't good for :D

**Comment by pasierb** [comment]
> I dunno! Just thought you'd like the feedback to help other users in future :D

Thanks @wilsonpage, that saved me some time!

@ashleygwilliams having up-to-date would be very helpful. Maybe some info that GitHub docs can be out-of-date and we should use the docs on the website?

**Comment by EverlastingBugstopper** [comment]
> while we could put in efforts to change our development process such that our README reflects what is currently released and not what is on master, we're opting instead to move the entirety of our documentation to our primary docs page (developers.cloudflare.com/workers) and not have it tracked on the README. we'll publish those docs alongside a release to ensure that the docs accurately reflect the currently released build. we're aiming to have this docs challenge solved by early Q4!

@pasierb we're working on it! Thanks so much for the interest in the project :) The release today will sync the README with the behavior of the software. Appreciate the patience!
