### ISSUE TITLE
Change `kv:bucket delete` to clear the namespace

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#589]
right now we have designed this command to walk the user's local `bucket` directory and make the list of keys to delete from the kv namespace. these seems unexpected. what it should actually do, is list the keys in the namespace, and delete all of those. maybe the former would be desirable later, so maybe we rename this to `clear`?

Either way, this should also ask the user to confirm before it does its thing.

**Comment by EverlastingBugstopper** [comment]
mentioning from our prior convo before we forget - if someone tries to do a `kv:key put` to a namespace that's configured as a bucket we should probably warn them to put that content in a file in the bucket directory lest future them runs `kv:bucket delete`

**Comment by gabbifish** [comment]
I think that `kv:bucket delete` should be consistent with other `deletes` in that a user only deletes what they have provided. If we were to introduce this functionality suggested here, the `delete` operations in wrangler would begin to diverge in their scope / meaning.

This is where the `kv:sync` command comes in handy: it ensures total consistency between a local and remote storage bucket, and performs the functionality described above. I'm in favor of closing this issue AND making sure that this `kv:delete` command is clearly documented as ONLY deleting the keys/filenames you provide to it.

**Comment by ashleymichal** [comment]
> mentioning from our prior convo before we forget - if someone tries to do a `kv:key put` to a namespace that's configured as a bucket we should probably warn them to put that content in a file in the bucket directory lest future them runs `kv:bucket delete`

@EverlastingBugstopper can you file this as an issue?

**Comment by ashleymichal** [comment]
we are deferring bucket commands for a later release (#634 ); will revisit then.

**Comment by gabbifish** [comment]
Closing this issue; we have decided that keeping the current `delete` functionality (only delete kv pairs with keys provided to `delete`) will ensure consistency between `delete` usage between `kv:key`, `kv:namespace`, `kv:bulk`, and `kv:bucket` (only delete specified values)
