### ISSUE TITLE
Are environments supported in 1.2.0?

### ISSUE THREAD

**Issue by gregmsanderson** [cloudflare/wrangler#596]
#### Environment

* operating system:
Mac OS
* output of `rustc -V`:
* output of `node -v`:
v10.16.2
* output of `wrangler -V`:
 wrangler 1.2.0

#### Steps to reproduce

Run:
wrangler build --env dev
... with an [env.dev] defined in the wrangler.toml

#### What did you expect to see?
It to work :) Success etc

#### What did you see instead?
error: Found argument '--env' which wasn't expected, or isn't valid in this context

I have been trying the commands in the linked to docs from the main readme, like the first paragraph of https://github.com/cloudflare/wrangler/blob/master/docs/content/environments.md and https://github.com/cloudflare/wrangler/blob/master/docs/content/kv_commands.md but each time seem to get an error with anything environment-related. The command without the env flag works.

I ran the command to update wrangler and have the latest version, 1.2.0. So is it simply those documented features are coming in 1._3_.0? Any idea of a release date, if so?

Or am I doing it wrong?

Thanks

**Comment by EverlastingBugstopper** [comment]
This is coming out tomorrow with 1.3.0! Hang tight + thanks for being excited about new features :) (There was some discussion about the README and the released version not being in sync on this issue if you're interested in reading up #582)

**Comment by gregmsanderson** [comment]
@EverlastingBugstopper Ah ... that explains it. Awesome, no problem.

I didn't see that previous issue but now realise it lists open issues, and that was closed.
