### ISSUE TITLE
wangler preview not working dure to account_id missing

### ISSUE THREAD

**Issue by geekodour** [cloudflare/wrangler#600]
### 🐛 Bug Report

I tried running wangler preview, did not work as expected.

cat ~/.wrangler/config/default.toml 
```
account_id = "fb3ce26xxxxxxb20"
email = "hxxxxxn@gmail.com"
api_key = "2d3xxxxxf50ss"
```

#### Environment

```
rustc -V   
zsh: command not found: rustc
node -v    
v10.16.3
wrangler -V    
 wrangler 1.2.0
```

#### What did you expect to see?
wangler preview to  be successful

#### What did you see instead?
```
wrangler preview                   
⬇️ Installing wranglerjs...
⬇️ Installing wasm-pack...
 Built successfully, built project size is 517 bytes.
 Your wrangler.toml is missing the following fields: ["account_id"]
 Falling back to unauthenticated preview.
 GET https://00000000000000000000000000000000.cloudflareworkers.com
 Your worker responded with: Hello worker!
```

**Comment by geekodour** [comment]
i was looking at the wrong file. stupid me.

**Comment by EverlastingBugstopper** [comment]
You're not stupid! @ashleymichal we may need to revisit the messaging here. It might not be necessary to warn about "falling back to unauthenticated preview." If they act the same it seems like an implementation detail

**Comment by EverlastingBugstopper** [comment]
@geekodour thanks for checking out wrangler and filing an issue 😄

**Comment by ashleymichal** [comment]
@EverlastingBugstopper the reason we call out the difference is that kv namespaces are not supported in unauthenticated preview, and so giving folks a hint can be helpful before they chase down issues that are unrelated, as the preview will simply throw a Reference Error.

**Comment by EverlastingBugstopper** [comment]
I guess we can't assume that since there are no KV namespaces declared in their wrangler.toml that they do not access KV in their worker at all. My initial thought was that we should bail if there are KV namespaces declared in wrangler.toml and just use unauth'd preview w/o warning if there are none but that might be naive.
