### ISSUE TITLE
Provide better messaging when account_id is missing

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#607]
When the api gateway receives an invalid account tag, it returns a rather cryptic error:

``` terminal
Error 7003: Could not route to /accounts/storage/kv/namespaces/63ab5438e79d4678bb16262d4b7f5f79/keys,
```
we should catch code 7003 and return a helpful message suggesting the user check their account id.

**Comment by gabbifish** [comment]
Upgrading this to high priority because testers point to this problem frequently.
