### ISSUE TITLE
add instructions to readme about how to update wrangler

### ISSUE THREAD

**Issue by ashleygwilliams** [cloudflare/wrangler#61]

**Comment by signalnerve** [comment]
via [this cargo thread](https://github.com/rust-lang/cargo/issues/2392#issuecomment-185767864), is this just `cargo uninstall wrangler && cargo install wrangler`, or are we thinking we need to add more copy around this?

**Comment by ashleygwilliams** [comment]
@signalnerve yeah for now it is, but once i write an installer for the binaries we don't have to tell people to use cargo, and they can use npm or just the installer (npm will use the installer under the hood)

**Comment by ashleygwilliams** [comment]
closing in favor of #157
