### ISSUE TITLE
Enable "rollback" in bulk upload to make batched uploads one atomic action

### ISSUE THREAD

**Issue by gabbifish** [cloudflare/wrangler#627]
Because a series of batched uploads to Workers KV cannot be atomic (they are distinct calls to the API), it may be worth storing state about uploads and rolling uploads back if an upload in a batch of uploads fails. Here, "rolling back" means deleting newly uploaded values with new key hashes and keeping the old values with the old key hashes.

This rollback behavior should only be done if hashes are used; this is the only way we guarantee not deleting a remote value that was meant to be updated, but the batched uploads failed.

Specifically, the rollback behavior should behave like the following:
Imagine files with keys `a.hash1.txt` and `b.hash2.txt` live in Workers KV.

Now, imagine a user has changed file `a` so its hash is now `hash3`, and `b` so its hash is now `hash4`.

In a scenario where `a.hash3.txt` and `b.hash4.txt` are uploaded via different upload calls (because they are put into different batches due to Workers KV API bulk upload limits), say `a.hash3.txt` is successfully uploaded, but `b.hash4.txt`'s upload call fails.

The remote KV now has files
`a.hash1.txt`
`b.hash2.txt`
`a.hash3.txt`

Wrangler should maintain a list of successfully uploaded files and delete them. So, in this case, `a.hash3.txt` is deleted, and the remaining files are the exact ones that existed before `upload` or `sync` was called.

The scenario above would never work without hashes; without hashes, this logic would have deleted `a.txt`, even though it should still exist in the remote if the previous state of the remote were to be preserved!

**Comment by EverlastingBugstopper** [comment]
I feel like this is a good idea, but seems like something we need the API to implement. The reason I say that is because I'm worried about syncing this state across multiple machines. If more than one person works on a project, there could be a lot of unexpected behavior with rollbacks.

**Comment by ashleygwilliams** [comment]
cc @steveklabnik we should chat about how the API could help with this
