### ISSUE TITLE
refactor all cloudflare API calls to use cloudflare-rs

### ISSUE THREAD

**Issue by ashleygwilliams** [cloudflare/wrangler#63]
as we implemented KV support in Wrangler, we adopted the cloudflare-rs crate (https://github.com/cloudflare/cloudflare-rs) as our official cloudflare api client for use with those endpoints. We should make an effort to move _all_ of our cloudflare api calls into that crate, which would give us uniformity in api request and response handling, as well as a more robust pattern for writing unit tests (the crate comes with an example mock api client).

should likely convert this into a project to track work both in wrangler and in cloudflare-rs.

as per https://github.com/cloudflare/wrangler/pull/57#discussion_r273559460

**Comment by petebacondarwin** [comment]
Closing as the latest Wrangler version is not implemented in Rust and will not use `cloudflare-rs`.
