### ISSUE TITLE
whoami should display `account_id`

### ISSUE THREAD

**Issue by phayes** [cloudflare/wrangler#630]
#### Overview and problem statement

The `account_id` is rather hard to find. It requires you look at the URL on `dash.cloudflare.org`.   At the same time, `account_id` is required to publish anything. 

It would be nice if the `whoami` command displayed the account id in addition to the email.

#### Basic example

```bash
wrangler whoami
💁  👋  You are logged with the email 'ocudigitaltech@gmail.com'. Your account_id is 'b268fbd36acb17898f484b34d0d7'.

**Comment by phayes** [comment]
Additional related feature request:  If logged in via `wrangler config`, then `account_id` should be autofilled in `wrangler.toml`

**Comment by gabbifish** [comment]
@ashleygwilliams I'm thinking it would be ideal for `wrangler config` to request `account_id` as well so we can autopopulate `wrangler.toml` with this value and make https://github.com/cloudflare/wrangler/issues/607 less frequent.

**Comment by ashleygwilliams** [comment]
@gabbifish, i *believe* that a single User (Global API key) can have more than one Account- so there's some logic to work out there, and we can only do this for users with a single account.

**Comment by EverlastingBugstopper** [comment]
I think https://github.com/cloudflare/wrangler/issues/331 might be able to help with this, don't think it's an exact duplicate though. I think a good solution here is to have some sort of selector with `wrangler init` (kind of like npm check) that lets you select your account id from a list, and then your zone id from a list. Labelling this as needs design

**Comment by gabbifish** [comment]
Revisiting this: you can get a user's accounts from https://api.cloudflare.com/#accounts-list-accounts. We can print out all a user's accounts (names and ids) when they run `wrangler whoami`. I definitely think this could help reduce the friction caused by going back and forth between the dashboard and wrangler.

**Comment by EverlastingBugstopper** [comment]
I like the approach of having this in `wrangler whoami` - it would make the command more useful for everybody, especially API token users
