### ISSUE TITLE
markup on npmjs page renders less than great

### ISSUE THREAD

**Issue by ashleygwilliams** [cloudflare/wrangler#636]
https://www.npmjs.com/package/@cloudflare/wrangler

<img width="407" alt="Screen Shot 2019-09-20 at 7 56 28 AM" src="https://user-images.githubusercontent.com/1163554/65328570-3c8fde80-db7c-11e9-8519-09b53d0e104b.png">

**Comment by EverlastingBugstopper** [comment]
I think this is due to the README being formatted a bit weirdly, we have a bullet list of headings. Should probably just remove the bulleted list and have headers

**Comment by ashleymichal** [comment]
this appears to have been solved.
