### ISSUE TITLE
wrangler build (site) dumps a `dist` directory in the root

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#640]
this is a webpack configuration concern (where should webpack output bundled resources). it's not great, but needs design around where in the stack to implement, and what levers we should provide to override.

**Comment by johnelliott** [comment]
Good to know this is known. I'm going to just ignore all the dirs for now :)

**Comment by xortive** [comment]
closed by https://github.com/cloudflare/wrangler/pull/1833
