### ISSUE TITLE
update template references to the real thing before launch

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#642]
depends on:

* making a "boilerplate" repo
* making both the above repo and the site template repo public.

**Comment by EverlastingBugstopper** [comment]
what's the difference between the boilerplate repo and the site template repo?

**Comment by ashleymichal** [comment]
my current gross implementation of generate vs init involves two repos:

generate uses template, init uses boilerplate, where boilerplate is just the contents of the `workers-site` directory in the template.
