### ISSUE TITLE
improve messaging on bucket sync for sites

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#646]
right now it looks like we keep creating the same bucket over and over. we should just say we're "uploading" the thing.

**Comment by EverlastingBugstopper** [comment]
`🌀  Creating namespace for Workers Site "__www-workers_sites_assets"`

this message should only happen on the first publish when a namespace is actually created

**Comment by gabbifish** [comment]
Relevant: #719. We should also reduce namespace create calls to the API, given its flakiness.
