### ISSUE TITLE
Improve init --site error for existing wrangler.toml

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/wrangler#648]
### 💡 Feature request

For `wrangler init --site` if wrangler.toml exists already instead of erroring, make the worker-site directory and ask the user to append to their `wrangler.toml` `bucket` and `entry-point`

#### Basic example
Instead of:
```
this-wrangler init --site
Error: A wrangler.toml file already exists! Please remove it before running this command again.
```
output 
```
this-wrangler init --site
⬇️ Installing cargo-generate...
⚠️ Append to the parent environment in your wrangler.toml:
[site]
bucket = "./static-folder"
entry-point = "workers-site"
🌀  🐑  Generating a new webpack worker project with name 'workers-site'...
🔧   Creating project called `workers-site`...
✨   Done! New project created /Users/victoriabernard/cf-github/workers-docs/workers-site
```

Nit: Succesfully should be spelled Successfully while we at it

**Comment by ashleygwilliams** [comment]
so the trick with this is that we don't know what the user's static file directory is called. i can make a PR to improve the message tho- let me see what i can come up with
