### ISSUE TITLE
preview --watch does not work for site

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#653]
We need to watch the specified `bucket` directory for changes and sync with the preview namespace on changes

edit from @EverlastingBugstopper

**Comment by EverlastingBugstopper** [comment]
watch `bucket` separately from worker, upload kv assets on bucket file change, no changes to worker watch logic

**Comment by EverlastingBugstopper** [comment]
also - probably blocked by https://github.com/cloudflare/wrangler/issues/351
