### ISSUE TITLE
designing the publish command

### ISSUE THREAD

**Issue by ashleygwilliams** [cloudflare/wrangler#66]
there are a few considerations in designing the publish command that largely center around overwriting preexisting scripts and routes:

- publishing a script is always a put and always overwrites
- publishing a route is a post, and will fail if a route already exists with the same pattern
- there is no guarantee that a route with an id has the same pattern as it previously had

i have stopped work on route in #65 by allowing a single publish. if the route is changed in the wrangler.toml, multiple publishes will work, but attempts to publish to a route that has a pattern that has already been published will currently throw an error.

what is the behavior we want to see here? what API do we need to do to improve this situation?

**Comment by signalnerve** [comment]
can we codify these considerations into the CLI? for instance, can we look at what the script/route config is pre-publish, and try to determine how successful the publish command will be?

i'm not at all an expert on CLI design/best practices, but intuitively, what feels right to me is having all of the `publish`-related commands default to bailing if there's any chance that an error will come back – if a user publishes and the API errors out, the routes are going to be left in an unknown state, which kinda sucks! if they want to continue ahead, maybe the best way is to indicate _how_ things are going to change, and then having them confirm – if that happens, can we just delete the already-published route and create the new one as per local config?

**Comment by ashleygwilliams** [comment]
@signalnerve thanks for weighing in here!

one previously unspoken constraint i have here is that i anticipate that some folks will want to use this tool in an automated way- CI, etc. as a result, i prefer to avoid interactive commands, aiming that a command should either succeed or error out with a suggestion of the command to call to proceed.

given your feedback, i'd see the design being that we would not want to overwrite unless a force flag is present. here's how i would see that working:

- user writes a script, user defines a route pattern in their wrangler.toml
- user publishes, they have no previous scripts or routes so this publish succeeds
- a user updates their script, leaves route pattern defined
- user attempts to publish, this fails because it attempts to create a new route with the same pattern and to overwrite a previous script**
- user publishes with force to overwrite the script and the route

** creating a new route feels like overkill on every publish. it's hard tho for several reasons:
  - users should be able define routes in their wrangler.toml based on pattern, NOT id
  - id does not guarantee the same pattern

as a result the checking we'll have to do is as follow:
- script name => does it already exist (api call), does the user want to overwrite (force flag)
- route pattern =>
     - does a route with this pattern already exist? (api call)
     - if yes? is it the route that is associated with the script we are currently trying to push? (api call)
     - if yes, leave route, override script

the tricky thing is... what to do if the answers are no. we can just bail, but what the user should do to fix it is unclear to me.

**Comment by ashleygwilliams** [comment]
i solved this in #65
