### ISSUE TITLE
Forbidden error on preview

### ISSUE THREAD

**Issue by scaria** [cloudflare/wrangler#674]
QA bug test event
-----------------
wrangler 1.4.0-rc.1

on wrangler preview
```
Installing wasm-pack...
✨  Built successfully, built project size is 4 KiB.
Error: https://api.cloudflare.com/client/v4/accounts/53fca4dfa7dd414760ab7e84ff167297/workers/scripts/testSite/preview: Client Error: 403 Forbidden
```

**Comment by EverlastingBugstopper** [comment]
I think we talked about this one being due to an invalid `wrangler config` - I'm going to close this, but if I mischaracterized the issue, please re-open it and we can further discuss!
