### ISSUE TITLE
Validate route before publishing

### ISSUE THREAD

**Issue by ipostelnik** [cloudflare/wrangler#675]
Wrangler should validate route pattern before publishing. It's not clear that route has to include zone name. Publishing fails with:

```
Error: ⚠️  There was an error creating your route.
 Status Code: 400 Bad Request
 Msg: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10022,
      "message": "Route pattern must include zone name: /w1"
    }
  ],
  "messages": []
}
```

**Comment by ashleymichal** [comment]
this has been done: https://github.com/cloudflare/wrangler/blob/master/src/commands/publish.rs#L105
