### ISSUE TITLE
wrangler --init site doesn't warn about changing entrypoint, leaves it at /

### ISSUE THREAD

**Issue by gaahrdner** [cloudflare/wrangler#679]
### 🐛 Bug Report

Wrangler init site doesn't warn about changing entrypoint

```
○ → wrangler init --site
✨  Succesfully created a `wrangler.toml`
⬇️ Installing cargo-generate...
🌀  🐑  Generating a new webpack worker project with name 'workers-site'...
🔧   Creating project called `workers-site`...
Removed: "/Users/gaahrdner/Code/wrangler/test-b/quickstart/workers-site/.genignore"
Removed: "/Users/gaahrdner/Code/wrangler/test-b/quickstart/workers-site/LICENSE_APACHE"
Removed: "/Users/gaahrdner/Code/wrangler/test-b/quickstart/workers-site/LICENSE_MIT"
✨   Done! New project created /Users/gaahrdner/Code/wrangler/test-b/quickstart/workers-site
```

#### Environment

* operating system:
* output of `rustc -V`: rustc 1.37.0
* output of `node -v`: v10.15.3
* output of `wrangler -V`: wrangler 1.4.0-rc.1

**Comment by EverlastingBugstopper** [comment]
@gaahrdner thanks for the report! Could you explain a bit more about what you mean by "doesn't warn about changing entrypoint"?

**Comment by gabbifish** [comment]
@EverlastingBugstopper I think he means there should be an additional line in the `wrangler init/generate --site` output that asks a user to change what `bucket` points to in `wrangler.toml` :D

**Comment by ashleymichal** [comment]
bucket and entry point are different. fwiw, wrangler automatically assumes that you will be using `workers-site` as your entry point directory, and will generate it (or your configured entry point) for you on build if it doesn't already exist. so i think more info is still needed. however, we should indeed instruct the user on init to point their bucket somewhere.

**Comment by gaahrdner** [comment]
Yeah sorry, y'all! I forget who, but someone asked me to file this bug report during the debug session a few weeks back. I'm personally not aware what the issue is but they asked me to file this bug. :dancer:
