### ISSUE TITLE
Dist script should be named worker.js

### ISSUE THREAD

**Issue by sheerun** [cloudflare/wrangler#681]
#### Environment

I'm using newest wrangler 1.4.0-rc.1

#### Steps to reproduce

The dist file and sourcemap are named `main.js` and `main.js.map`, but when using error reporting like sentry it turns out that server-side .js file is names worker.js. Because of this there's filename mismatch and sentry cannot link uploaded sourcemaps to error stacktrace and we get "Source code was not found" error.

#### What did you expect to see?

If generated file and sourcemap were names worker.js Sentry would would out of the box.

Here's how proper configuration should look like:

```
  devtool: 'cheap-module-source-map',
  output: {
    path: path.join(__dirname, 'dist'),
    publicPath: 'dist',
    filename: 'worker.js',
    sourceMapFilename: 'worker.js.map'
  },

```

**Comment by xtuc** [comment]
that's interesting.

Currently, Cloudflare worker hardcodes the name of the script as `worker.js`, that's why your source map won't match.
We could easily rename `worker/script.js` to `worker.js`. Alternatively, we could use the name in the source map instead of hardcoding it to `worker.js`

**Comment by sheerun** [comment]
In any case Sentry won't work until worker.js is used in sourcemap. I hope you are able to confirm this issue and fix it (you don't need to use my solution).

**Comment by xtuc** [comment]
Implemented your fix in https://github.com/cloudflare/wrangler/pull/1063.
