### ISSUE TITLE
require `name` be configured and valid for kv commands

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#688]
we use `target.name` as part of the title we provision for users when they call `wrangler kv:namespace create <binding-name>`. we should require that the user's toml has a valid name specified before we make the call.

### Pros

the use of the worker name in the title along with the binding name is to provide uniqueness. requiring the name in your toml for kv commands prevents some confusion when users accidentally create a namespace with title `"-MY_BINDING"` (usually we'll have a worker name prefixing this, so `"worker-prod-MY_BINDING"`).

### Cons

requiring the worker name in the toml for kv commands is sort of unexpected from a user POV; i'm not doing anything with my project, why do i need to give you a project name to interact with my namespace? (in terms of other KV interactions).

Possible middle-ground: a bespoke requirement just for `kv:namespace create` that requires target.name, but not on other kv commands.

**Comment by ashleygwilliams** [comment]
> Possible middle-ground: a bespoke requirement just for kv:namespace create that requires target.name, but not on other kv commands.

^ i vote for this one

**Comment by EverlastingBugstopper** [comment]
i also vote for that one

**Comment by ashleymichal** [comment]
i would rather fix this by changing the requirement for kv namespaces from id -> title in the wrangler.toml. this would be a breaking change and would go in a 2.0 release.
