### ISSUE TITLE
Handle API errors in script_status

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#70]
When an API error is returned, https://github.com/cloudflare/wrangler/blob/921c626bb0a0a611ac7d6fb01fe0296d79f3bcca/src/user/account.rs#L27 doesn't handle it properly.

For example here's the API response: `{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}`, I would suggest adding into account the `success` field.

**Comment by ashleygwilliams** [comment]
because we are doing multiscript for all #72 has removed all checking of "script status" so this is resovled.
