### ISSUE TITLE
wrangler preview unauth'd preview won't work with sites

### ISSUE THREAD

**Issue by helloandre** [cloudflare/wrangler#706]
### 🐛 Bug Report

admittedly, this was a user error on my part. however, the way wrangler preview handled it could be improved. ideally it would not attempt to preview any site without be auth'd as it will not have access to KV.

#### Environment

* operating system: OSX 10.14.6
* output of `rustc -V`: rustc 1.37.0 (eae3437df 2019-08-13)
* output of `node -v`: v10.16.3
* output of `wrangler -V`: wrangler 1.4.0-rc.4

#### Steps to reproduce

 - `wrangler generate --site my-site`
 - DO NOT edit wrangler.toml to add an `account_id`
 - `wrangler preview`

#### What did you expect to see?

an error message telling me that preview will not work with a `--site` without being auth'd

#### What did you see instead?

it attempts to preview, opening a browser window with an unrelated error message output.

**Comment by EverlastingBugstopper** [comment]
We should probably not fall back to unauthenticated for any preview with a `site` table in `wrangler.toml`
