### ISSUE TITLE
1.4.0-rc.4 is not marked as a pre-relase?

### ISSUE THREAD

**Issue by bvanrijn** [cloudflare/wrangler#707]
I'm currently working on [making Wrangler installable using Homebrew](https://github.com/bvanrijn/homebrew-wrangler). I got an email about three hours ago that said [1.4.0-rc.4](https://github.com/cloudflare/wrangler/releases/tag/v1.4.0-rc.4) had been released—and, to my surprise, it wasn't marked as a pre-release, while all previous release candidates were.

Before updating my tap with the new release, I wanted to make sure this is not an oversight and this release candidate is indeed a new stable release.

**Comment by ashleymichal** [comment]
thanks for the heads up, this is for sure just a release candidate, NOT a stable release. cc @ashleygwilliams

**Comment by ashleygwilliams** [comment]
fixing now. thank you!
