### ISSUE TITLE
Generate command always prints rustwasm copy

### ISSUE THREAD

**Issue by signalnerve** [cloudflare/wrangler#71]
https://github.com/cloudflare/wrangler/blob/9d4f33137a787ac5eb8887d291d50cdc9705df92/src/commands/generate.rs#L23

The generate command will always print `Generating a new rustwasm worker project` even if the passed template is unrelated to rustwasm.

Maybe just `Generating a new Wrangler project` would be more appropriate here?

**Comment by ashleygwilliams** [comment]
this is fixed by #72 - you can test it by installing from master
