### ISSUE TITLE
Changelog is not readable

### ISSUE THREAD

**Issue by sheerun** [cloudflare/wrangler#715]
### 🐛 Bug Report

It seems you've automated releases and changelog but in the meantime it became unreadable: https://github.com/cloudflare/wrangler/releases

It would be far more useful if someone described major changes like before instead of just writing commit messages most of which are "merge with master"

**Comment by ashleymichal** [comment]
hey @sheerun ! you've caught us. The release you linked is actually a Release Candidate for 1.4.0, which will go out tomorrow with our usual carefully-curated changelog! Stay tuned...
