### ISSUE TITLE
RFC: .wranglerignore

### ISSUE THREAD

**Issue by gabbifish** [cloudflare/wrangler#716]
### The Problem
There are static assets directories that may contain lots of content that doesn't need to be uploaded to KV (and likely will trigger KV value size limits). This includes, but is not limited to, things like `node_modules/` and hidden files/directories. Users should be able to specify paths (in the vein of `.gitignore`) that do not get uploaded to KV.

### Option 1: .wranglerignore
We will introduce support for `.wranglerignore` files. These files will be automatically generated with `wrangler init` and `wrangler generate` and placed in the same directory (pwd) as `wrangler.toml`. By default Wrangler will ignore `node_modules` and hidden files (they don't need to be specified in `.wranglerignore`).

These files will be parsed and used exactly like `.gitignore` whenever bucket `upload_files()` is called. The https://docs.rs/ignore/0.4.10/ignore crate will help us a lot here.

### Option 2: include/exclude in wrangler.toml
A more rust-idomatic include/exclude approach is the one used by cargo: https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields-optional

This approach would become part of the `[site]` section of `wrangler.toml`, which would have two new fields, exclude and include. If both are present, wrangler will use include only (same as cargo). The exclude and include fields are used to filter file uploads from whatever directory is specified in the bucket field in wrangler.toml.

The benefits of this approach are that
- Wrangler users will have one fewer file to deal with (no .wranglerignore)
- We can constrain this ignore functionality to just Workers Sites, the only workers application that would use this ignore functionality
- The coupling between Workers sites and include/exclude would neatly be represented in wrangler.toml.

This implementation should be readily doable with https://docs.rs/ignore/0.4.10/ignore/overrides/struct.OverrideBuilder.html.

This approach makes it easier, code-wise, to always ignore node_modules (no messiness about expecting it in the .wranglerignore, we can just always put this logic in the OverrideBuilder).

I advocate for approach number 2. It's fairly easy for me to make implementations of both approaches above, so I can go ahead and the team can play around with the options and tell me which one they like best.

### Proofs of concept
Our two candidates:
1. `.wranglerignore` #720 
1. `include/exclude` in `wrangler.toml` #760

**Comment by ashleygwilliams** [comment]
where is it generated? in the root of the directory?

**Comment by gabbifish** [comment]
Yes! :D It is intended to coexist in the same directory as `wrangler.toml`.

**Comment by EverlastingBugstopper** [comment]
+1 on this implementation and the crate 

I do think that the `.wignore` should be cascaded like `.gitignore` is - that is to say, if I have a bucket `./public`, I would want wrangler to respect a `.wignore` inside `./public`

**Comment by xtuc** [comment]
Have you considered a configuration in `wrangler.toml`?

I'm concerned about the name, since Wrangler doesn't only upload files but it's a "building tool", some users might be confused by `.wranglerignore` ignoring files from building?

Often, with static site generator, the useful website end up in a `./dist` directory or similar. If we had a inclusion list instead of an exlusion list, I would just say upload everything in `./dist/**`.

I don't agree with the `node_modules` default. It has a meaning in JavaScript (even restricted to npm) but any other language is free to use it. Also, similar to how bower worked, some people might want to upload (dependend) node_modules. And not to mention people using `node_modules` as a module system hack for their source files.

**Comment by gabbifish** [comment]
Upon discussing this further with @ashleygwilliams, we've decided to get rid of the `.wranglerignore` file in favor of a more rust-idomatic `include/exclude` approach like the one used by `cargo`: https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields-optional

This approach would become part of the `[site]` section of `wrangler.toml`, which would have two new fields, `exclude` and `include`. If both are present, wrangler will use `include` only (same as `cargo`).

The benefits of this approach are that
1. Wrangler users will have one fewer file to deal with (no `.wranglerignore`)
1. We can constrain this ignore functionality to just Workers Sites, the only workers application that would use this ignore functionality
1. The coupling between Workers sites and include/exclude would neatly be represented in `wrangler.toml`.

This implementation should be readily doable with https://docs.rs/ignore/0.4.10/ignore/overrides/struct.OverrideBuilder.html. What do folks think?

**Comment by EverlastingBugstopper** [comment]
I like it. What does this mean for `bucket`?

**Comment by gabbifish** [comment]
@EverlastingBugstopper these rules will be used to include/exclude uploading files from the `bucket` directory :)

**Comment by EverlastingBugstopper** [comment]
yeah that makes sense. +1 on this :)

only reason i was asking was because i can see a world where people have assets scattered over a bunch of different directories with no clear bucket. but they could just set bucket to `./` and include exclude whatever they want

**Comment by gabbifish** [comment]
^ yep!!

**Comment by xtuc** [comment]
I prefer the new version of your RFC, thanks for the update!

**Comment by xtuc** [comment]
I have a feature request. I would be useful to have a debug mode (cli flag) when uploading the site. That way, the user could see the uploaded files and those that actually should be ignore instead.

**Comment by victoriabernard92** [comment]
TBH I prefer the `.wranglerignore` because it aligns more with what people are used to ( `.npmignore` `.gitingore` etc..) I think the less specialized config we put in the `.toml` file the better DX

**Comment by EverlastingBugstopper** [comment]
Hey @xtuc we've got an issue for that exact feature! https://github.com/cloudflare/wrangler/issues/657

**Comment by gabbifish** [comment]
@victoriabernard92 that is a good point-- though I feel like we mostly have consensus on the `include/exclude` approach, I still want to make sure we fold you into the consensus. What I'm going to do is keep a branch with the original wranglerignore functionality and build out another branch with the suggested `include/exclude` approach above, and we can try both out and decide which one feels best :)

**Comment by gabbifish** [comment]
Alright y'all! We have two candidates:
1. `.wranglerignore` #720 
1. `include/exclude` in `wrangler.toml` #760 

I lean towards #760 for the reasons stated above.

**Comment by EverlastingBugstopper** [comment]
Definitely a fan of option 2.

**Comment by ashleymichal** [comment]
my preference is include/exclude in the toml specifically because it makes it very clear what feature of wrangler it is relevant to.

**Comment by gabbifish** [comment]
We have decided to use option 2.

**Comment by xtuc** [comment]
Just for the record, I prefer option 2 as well :+1:
