### ISSUE TITLE
Figure out buckets and hashing

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#718]
While doing a small refactor for #717 I realized that for any and every bucket we will append the hash to the key. This is probably bad. Or maybe it's good.

**World 1** _where we want everything hashed_
We need to also upload an asset manifest text blob for all buckets

**World 2** _where we decide only site buckets are hashed_
There is some gnarly design work needed to untangle buckets from hashing logic

**World 3** _where we wanna give that lever to our users_
Also some gnarly design work that combines world 1 and world 2 where we hash some buckets and provide an asset manifest and don't hash/provide asset manifest for others

This issue is mostly just a note that there is some tech debt that we need to address.

**Comment by ashleymichal** [comment]
i actually ran a couple of cursory tests; the bucket field on the KvNamespaces struct is kind of cruft, and i don't believe we actually do anything with it. i have a PR to remove it from the code.
