### ISSUE TITLE
Only make requests to create namespace API if absolutely necessary, because it is flaky

### ISSUE THREAD

**Issue by gabbifish** [cloudflare/wrangler#719]
When testing sites live preview frequently, I ran into
```console
wrangler preview --watch
 Creating namespace for Workers Site "__blog-daniel-workers_sites_assets_preview"
Error: [ApiError { code: 10000, message: "{\"request_id\":\"51c032b3f1fa6da6-SJC\",\"message\":\"An error occurred processing your request. You may contact support with the given request_id to troubleshoot.\"}", other: {} }]
```
I think we need to find another way to persist namespace bucket knowledge in memory or in wrangler.toml to prevent making excessive calls to the KV namespace API.

**Comment by ashleygwilliams** [comment]
let's test and see if we still need this!

**Comment by steveklabnik** [comment]
I'm not aware of any flakiness here; can you file an internal ticket about this?

**Comment by ashleymichal** [comment]
my history is fuzzy, but I believe this ticket was created before we increased wrangler's request timeout.

**Comment by EverlastingBugstopper** [comment]
@ashleymichal do you think we can close this?

**Comment by ashleymichal** [comment]
nah the timeout increase should  have fixed this.
