### ISSUE TITLE
document Custom webpack configuration behavior

### ISSUE THREAD

**Issue by ashleygwilliams** [cloudflare/wrangler#721]
per https://github.com/cloudflare/wrangler/pull/709. let's have a webpack doc in the docs/content/ dir that explains this.

**Comment by marc-barry** [comment]
👍 I've been running into a few webpack issues and find myself Googling for how/what can be done to work around them. Any documentation on this would be super helpful.

**Comment by ashleygwilliams** [comment]
good call @shalzz ! this issue is closed - could you file a new one? thank you!

**Comment by shalzz** [comment]
@ashleygwilliams done at #771

**Comment by ashleygwilliams** [comment]
thanks so much!! @shalzz
