### ISSUE TITLE
Use wrangler user agent for cloudflare-rs requests

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#731]
Might need to make a request to cloudflare-rs to do this, or to modify the `reqwest` that we get back from cloudflare-rs before executing it.

**Comment by gabbifish** [comment]
We will need to ensure the reqwest client built in cloudflare-rs is passed this new user agent as well (and uses it for requests).

**Comment by EverlastingBugstopper** [comment]
Perhaps this could be implemented with the same trait that we're using for extending the timeout
