### ISSUE TITLE
Refactor kv::format_error to cf::format_error

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#740]
Any API call we make with cloudflare-rs should be formatted in a single function. Looking at you https://github.com/cloudflare/wrangler/blob/master/src/commands/kv/namespace/site.rs#L42

This is related to #360

**Comment by gabbifish** [comment]
The `kv::format_error` function calls upon the `help()` function to print out helpful details when the API returns an error. Currently, this function looks for KV-specific error codes to figure out which help message to print. So, if we generalize this help function to `cf::format_error`, we need to extract this `help()` function and ideally have it provide helpful messaging for other CF API error codes.

**Comment by ashleymichal** [comment]
we may need to define multiple help functions for different apis, as there will be collisions in codes between them, e.g. 
workers api error codes:
https://api.cloudflare.com/#worker-script-errors
workers kv api error codes:
https://api.cloudflare.com/#workers-kv-namespace-errors

**Comment by gabbifish** [comment]
#841 actually already fixed this: it introduces a `http::format_error` function that takes a callback as an argument. This callback function takes an error code and returns a string providing more information about it. This means we now have a general error formatting function for the CF API's error responses, which any subcommand that calls a particular API (e.g. the routes API) can use to format CF API errors.
