### ISSUE TITLE
ApiError on init

### ISSUE THREAD

**Issue by happysalada** [cloudflare/wrangler#742]
### 🐛 Bug Report

upon installation of the cli, when first trying to preview a project, the only feedback is
`Error: [ApiError { code: 10000, message: "Authentication error", other: {} }]`

#### Environment

* operating system: MacOs Mojave 10.14.6
* output of `rustc -V`:
* output of `node -v`: v12.9.0
* output of `wrangler -V`: 1.4.0

#### Steps to reproduce

```
yarn global add @cloudflare/wrangler
wrangler config
```
add the cloudflare email, and a token from the workers template with the following permissions
`Account.Workers KV Storage, Account.Workers Scripts, Zone.Workers Routes`

on an exisiting gatsby js site run
`wrangler init --site my_site`
output
```
❯ wrangler init --site sassy_technology
✨  Succesfully created a `wrangler.toml`
⬇️ Installing cargo-generate...
🌀  🐑  Generating a new webpack worker project with name 'workers-site'...
🔧   Creating project called `workers-site`...
Removed: "/Users/raphael/Documents/Projects/javascript/gatsby-starter-mate/workers-site/.genignore"
Removed: "/Users/raphael/Documents/Projects/javascript/gatsby-starter-mate/workers-site/LICENSE_MIT"
Removed: "/Users/raphael/Documents/Projects/javascript/gatsby-starter-mate/workers-site/LICENSE_APACHE"
✨   Done! New project created /Users/raphael/Documents/Projects/javascript/gatsby-starter-mate/workers-site
```

edit the wrangler.toml fille
- add your account_id
- add `bucket = "./public"`

when trying to preview with
`wrangler preview --watch`
the error appears.

#### additional information

not really sure how to debug

output of wrangler whoami
`💁  👋  You are logged in with the email 'raphael.megzari@gmail.com'.`

I'm not the only one experiencing the issue
https://community.cloudflare.com/t/apierror-code-10000-message-authentication-error-other/117711/4

#### What did you expect to see?

something a little more informative. I'm not sure what to do next

#### What did you see instead?

an information message with no clear steps to resolve

**Comment by ashleygwilliams** [comment]
hi @happysalada ! sorry you are running into this issue. i believe this error would mean that you have configured wrangler incorrectly- which means that either you Global API key, email address, or both were incorrect when you run wrangler config.

2 commons issues are using an API token instead of your Global API key, or having changed your email recently. can you run `wrangler config` again ensuring you use the correct values?

i definitely agree the error message could be made better! we'll look into fixing it!

**Comment by happysalada** [comment]
The api key was the problem! My bad.
Thanks for the thoughtful reply.

**Comment by spsaucier-bakkt** [comment]
I'm getting this error even with my global API key. Additionally, `wrangler dev` returns 
```
Error: Could not upload your script. Check your internet connection or https://www.cloudflarestatus.com/ for rare incidents impacting the Cloudflare Workers API.
```
