### ISSUE TITLE
Content corrupted error

### ISSUE THREAD

**Issue by happysalada** [cloudflare/wrangler#744]
### 🐛 Bug Report

upon deploying a static site, when refreshing the page, the website throws a content corrupted error. 
(firefox 69.0.1)

#### Environment

* operating system: MacOs 10.14.6
* output of `rustc -V`:
* output of `node -v`: 12.9
* output of `wrangler -V`: 1.4.0

#### Steps to reproduce

deployed a gatsby JS SPA with the default worker for static website
content of the  wrangler.toml
```
route = "sassy.technology/*"
```

the error can be observed at https://sassy.technology

accessing the url directly gives no problem, however refreshing the page triggers the error

#### What did you expect to see?

no error on page refresh

#### What did you see instead?

content corrupted error

**Comment by ashleygwilliams** [comment]
hey @happysalada -  sorry you are running into this issue! when i access https://sassy.technology i get this:

<img width="1169" alt="Screen Shot 2019-09-29 at 9 31 59 AM" src="https://user-images.githubusercontent.com/1163554/65833986-0baa5a80-e29c-11e9-95a2-7227a0275dbc.png">

it seems like this *may* be a DNS issue?  but just in case it is not.. would it be possible for you to share your `wrangler.toml` and the contents of your static asset directory? just a representative listing of the files should be fine (curious if there's some unusual filetypes!).

all that being said, this definitely smells like a potential DNS issue to me. @rita3ko do you have any thoughts?

**Comment by happysalada** [comment]
I just made the whole repo public
https://github.com/happysalada/sassy_technology

I'm not really sure If I was supposed to do something special in terms of DNS on the clouldflare console.
Let me know if I can provide more info.

**Comment by ashleygwilliams** [comment]
thank you for sharing . the . repo!  i'll try to reproduce now. in the meantime- do you have a `workers.dev` subdomain? we can eliminate the possibility of a DNS issue by seeing if you can deploy to `workers.dev` instead! let me know if you need any help trying that.

**Comment by happysalada** [comment]
just pushed to my workers.dev, you can check it [here](https://sassy_technology.sassy.workers.dev/)
(there seems to be no problem refreshing the page)

**Comment by happysalada** [comment]
I'm guessing the issue lies with the route.
I used sassy.technology/*
it seems to be what was in the doc, maybe I got that part wrong.

**Comment by happysalada** [comment]
let me know if there is anything else I can do to help
(I reverted my website to not using workers anymore, since I couldn't have it down)

**Comment by gabbifish** [comment]
If your domain is behind Cloudflare, does it have an A/AAAA record in your Cloudflare dashboard? If none of these are present, that may be the cause of this error.

**Comment by happysalada** [comment]
Where should the record point to though?
The cloudflare worker should be the one taking care of that?
If I point the record to a server, then the worker won't be used right?

**Comment by EverlastingBugstopper** [comment]
Admittedly, this is a bit confusing but Cloudflare requires that you configure a DNS record even if it is never hit. Your worker will run and the IP in the A record will never be accessed, but DNS requires that you set an A record regardless.

**Comment by happysalada** [comment]
Got it, all is good then.
I would suggest adding a line somewhere in the quickstart just to mention this.
Thanks for the quick response on this!
