### ISSUE TITLE
Default wildcard route for Apps

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#76]
it would be nice to have a "sane default" of `/*` for "app" type scripts. need to take into consideration:
* zones that already have routes configured: most naive would be check route list and refrain from setting the wildcard if any exist

it would also be valid to simply have a default line in the configuration file.

**Comment by gabbifish** [comment]
Do we want to continue this? It looks like "app" type scripts basically referred to workers sites, and we now have helpful warnings for when a sane default is not provided. I'd actually be in favor of closing this ticket.

**Comment by gabbifish** [comment]
@ashleymichal and I chatted and agreed this should be closed.
