### ISSUE TITLE
Can't install wrangler

### ISSUE THREAD

**Issue by Puled** [cloudflare/wrangler#761]
Help me please, thanks.

When I was installing wrangler on Debian9, after "Compiling tokio-current-thread v0.1.6", an error occurred:

```
error: failed to compile wrangler v1.4.0, intermediate artifacts can be found at /tmp/cargo-install5D3FAO

Caused by:
  failed to run custom build command for openssl-sys v0.9.50

Caused by:
  process didn't exit successfully: tmp/cargo-install5D3FAO/release/build/openssl-sys-deb38e6c3bd336d7/build-script-main (exit code: 101)
```
 
here is more info:

```
--- stdout
cargo:rustc-cfg=const_fn
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running "perl" "./Configure" "--prefix=/tmp/cargo-install5D3FAO/release/build/openssl-sys-6ca6090207fc7e13/out/openssl-build/install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-engine" "no-async" "no-shared" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"

--- stderr
Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./Configure line 15.
BEGIN failed--compilation aborted at ./Configure line 15.
thread main panicked at 


Error configuring OpenSSL build:
    Command: "perl" "./Configure" "--prefix=/tmp/cargo-install5D3FAO/release/build/openssl-sys-6ca6090207fc7e13/out/openssl-build/install" "no-dso" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-engine" "no-async" "no-shared" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
    Exit status: exit code: 2
 /home/commelinales/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.6.0+1.1.1d/src/lib.rs:363:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I've Googled these issues and installed "libssl-dev" etc. but none of these solutions worked.

**Comment by EverlastingBugstopper** [comment]
Hi @Puled - could you please give us some more information about your install?

Are you installing with npm or with cargo?

* operating system:
* output of `rustc -V`:
* output of `node -v`:

**Comment by Puled** [comment]
Hi, I was installing using command `cargo install wrangler --features vendored-openssl`
Operating system: Debian 9 stretch
What are " output of ..." and where can I find them?

**Comment by Puled** [comment]
Hello.. How can I edit labels on this page??

**Comment by EverlastingBugstopper** [comment]
Hi @Puled - two things

1) For "output of" I just mean - could you tell me what your terminal outputs when you run the command `rustc -V` (I don't need `node` if you aren't installing with npm)

2) Only contributors to this repository can update labels

**Comment by EverlastingBugstopper** [comment]
@gabbifish do you think you could try to reproduce this on your Linux machine?

**Comment by Puled** [comment]
I don't know why this time it worked, but finally, I installed wrangler.
Maybe because _I increased my machine's memory yesterday from 600 M to 1.7 GB_?? That's strange.
Anyway thanks @EverlastingBugstopper , problem solved.

**Comment by EverlastingBugstopper** [comment]
Easiest bug fix of my life. Thanks @Puled! It is a little strange that that happened, if this ever happens again (or if anybody else stumbles across this issue) please please open it up again and we will further investigate. :)

**Comment by Darrenmeehan** [comment]
Hi @EverlastingBugstopper 

I hit this issue this evening, and the fix that worked on my system is to install the following package.

`sudo dnf install perl`

Perl isn't something I use, so I didn't delve into why these weren't being installed.

My system is running Fedora 34, and is running the latest version of cargo & rust stable.

**Comment by tnngoan** [comment]
Hi,

I have ran into this error today, couldn't install wrangler on an empty folder even though I have npm and node installed.
Problem seemed to fix itself when I ran `nvm 16` ( my current version of nodejs was v17.0.1) which to switch to node v16.13.0

Hope this helps someone with the same issue :)

**Comment by apoudel20** [comment]
Hi,
I'm on Windows and I used vcpkg to install openssl and that fixed the issue. Hope this helps!

**Comment by codebam** [comment]
Installing Perl fixed it for me too on the Fedora 35 Docker Image unpacked into WSL. Thanks @Darrenmeehan!
