### ISSUE TITLE
Refactor and simplify truth table logic for wrangler publish

### ISSUE THREAD

**Issue by gabbifish** [cloudflare/wrangler#769]
#751 has some complicated truth table logic I'd like to simplify. This ticket is to remind me to do that.

**Comment by ashleymichal** [comment]
BEAT YOU TO IT

**Comment by EverlastingBugstopper** [comment]
@ashleymichal can this be closed now?

**Comment by ashleymichal** [comment]
technically it is not merged to master yet. i can link it to the PR that fixes it though.
