### ISSUE TITLE
Document wasmpack/webpack configuration behaviour for building Rust

### ISSUE THREAD

**Issue by shalzz** [cloudflare/wrangler#771]
#### Overview and problem statement
#724 only documented custom webpack behaviour, in lieu of that also document how a rust wasm module is built and packaged for cloudflare workers.
This will allow people to combine custom webpack configuration with wasm builds.

#### Basic example
For example having both typescript and rust in the same worker.

**Comment by samuelcolvin** [comment]
Any progress on this? It would be great.

If I want to use webpack and rust in the same worker, am I best to use the webpack loader for wasm or do something else?

**Comment by EverlastingBugstopper** [comment]
👋  - hi, we don't have plans on prioritizing documenting this functionality at the moment. that being said, I believe [this npm module](https://github.com/wasm-tool/wasm-pack-plugin) may help with what you're looking to do.

**Comment by EverlastingBugstopper** [comment]
[this tool](https://github.com/rustwasm/rust-webpack-template/blob/master/package.json) also demonstrates how to create a hybrid project

**Comment by shalzz** [comment]
@EverlastingBugstopper Yes using wasm-pack-plugin allows achieving the required functionality.

However setting `type = "webpack"` in `wrangler.toml` and a custom webpack with the above plugin does results in a wasm module being built but not being uploaded to cloudflare worker.

The wasm module gets uploaded only when `type= rust` or similar. This means we have to rely on hacks to make sure the final artifacts result in the correct directory and filename, etc that are prone to changes with newer wrangler version.

The only reasonable solution I see in the long term is allowing the use of `webpack_config` with `type=rust` as well.  (The user has to make sure to have the wasm pack plugin)

**Comment by EverlastingBugstopper** [comment]
cc @xtuc

**Comment by samuelcolvin** [comment]
@shalzz what hacks are you using to get this to work?

**Comment by samuelcolvin** [comment]
Cancel that, I have it working. I don't know what hacks @shalzz was referring to, I've played around with this a lot and didn't find any hacks I had to implement to get workers to work with `wasm-pack-plugin`. The only negative change I saw was that I now get the warning

    ✨  Built successfully, built project size is 1 MiB. ⚠️  Your built project has grown past the 1MiB size limit and may fail to deploy. ⚠️ 

But the size hasn't actually changed - I assume the warning was just muted for `type = "rust"` projects as the size always exceeds 1MB?

It's working [here](https://github.com/samuelcolvin/edgerender) in case it helps anyone.

This change also fixed [this](https://community.cloudflare.com/t/cloudflare-workers-and-webassembly-script-exceeded-time-limit-when-reusing-object/182524) bug which I asked about on the community forum but never got any help with.

**Comment by shalzz** [comment]
Hi, are there no plans to work on this?

**Comment by ashleymichal** [comment]
hey @shalzz !

sorry for the dead air. if i understand correctly, the ask is for a more flexible approach which would support both a rust wasm module _and_ typescript in the worker. I think that's a great goal; we don't have cycles in the near term for this, however I do want to keep it on the roadmap.

**Comment by shalzz** [comment]
Wow! Thank you. I'm honored.
