### ISSUE TITLE
Template without a wrangler.toml warning

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/wrangler#777]
When using wrangler generate on any git repo, if the `wrangler.toml` DNE on the repo we should automatically create one for the generated project and probably warn them that we did so 

related: https://github.com/cloudflare/wrangler/issues/87

**Comment by EverlastingBugstopper** [comment]
@victoriabernard92 could you add labels to this issue?

**Comment by EverlastingBugstopper** [comment]
we did this a while ago
