### ISSUE TITLE
allow for `wrangler publish` without `npm install`

### ISSUE THREAD

**Issue by iameli** [cloudflare/wrangler#778]
#### Overview and problem statement

[Livepeer has a Yarn monorepo](https://github.com/livepeer/livepeerjs) and running `npm install` in it kind of mucks things up. I've already got a completely compiled `worker.js` suitable for uploading as a Cloudflare worker, as well as a static HTML Next.js site that I'd like uploaded to Workers Sites. I don't need any of the `npm` automation provided by `wranglerjs`, but it'd still be nice to be able to use `wrangler publish`.

[Here's the wrangler.toml I'm using.](https://github.com/livepeer/livepeerjs/blob/8de9589b96e80a49955809ff066c47984c05bc48/wrangler.toml)

#### Basic example

Seems like it'd be a configuration flag in `wrangler.toml`?
```
do_install = false
```

**Comment by gusvargas** [comment]
I think that this is sort of related to https://github.com/cloudflare/wrangler/issues/428#issuecomment-539222538

**Comment by iameli** [comment]
Yeah, I hear that — related to this would be supporting `yarn` in addition to `npm`. I understand how the automatic `npm install` is useful for folks that are new to JavaScript bundling and whatnot, but there's just no way you could possibly predict all the myriad of ways that complex projects handle dependency management and building. Running `npm install` totally breaks Livepeer's JavaScript repo.

[FWIW I worked around this by committing an empty package.json adjacent to the worker.js file](https://github.com/livepeer/livepeerjs/blob/ddd37a2738b511ff980930c5c1b26646e8c28ab6/packages/api/dist-worker/package.json), resulting in a no-op `npm install` upon `wrangler publish`. Works fine now.

**Comment by gusvargas** [comment]
The more I've thought about this the less I think `wrangler` should be concerned with package management at all. `build` seems like it should just run webpack or whatever to produce an artifact that will later be consumed by `preview` or `publish`, i.e., running `build` would be a necessary precursor to running `preview` or `publish`. Similar to `cargo`, `wrangler build` could produce directories like `target/preview` and `target/release`. The `build` will fail if dependencies haven't been installed correctly.

Decoupling those steps and allowing the "target" directory to be configurable (like `wrangler preview --target ./foo/dist-worker`) seems like it would resolve your issue without requiring hacks.

**Comment by xtuc** [comment]
@gusvargas In my opinion, that's the ideal case. However, you are missing context and implementation details here.

**Comment by samkelleher** [comment]
I have the same issue where `wrangler publish` keeps breaking because of npm install issues which have nothing to do with my yarn projects build or deployment.

I don't believe wrangler should really have anything to do with builds, but I get it's there to give a good out the box experience.

I did in the end write a example custom script I'll share for anyone interested that uploads the built worker and a KV asset via the API, bypassing wrangler.

If your use case is just for publishing, this might be of use.
