### ISSUE TITLE
Provide info or hit API to register DNS A record for sites

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#780]
When workers sites are created, a DNS A record needs to be created or workers site will not resolve.

**Comment by jmadruga-cf** [comment]
Similar set of concerns here: https://github.com/cloudflare/wrangler/issues/93

**Comment by victoriabernard92** [comment]
Modifying DNS records in this way can be complicated and easily break things. We did this with apps. Loop me in when you start planning to tackle this.

**Comment by EverlastingBugstopper** [comment]
This is something I think we should probably handle down the line - perhaps when we revisit routes. Would probably be something to implement on the API side and not in Wrangler.

**Comment by EverlastingBugstopper** [comment]
@ashleymichal want to close this? i think we should solve this at the platform level

**Comment by ashleymichal** [comment]
@EverlastingBugstopper yes
