### ISSUE TITLE
Throw error on install if node not installed

### ISSUE THREAD

**Issue by victoriabernard92** [cloudflare/wrangler#786]
### 🐛 Bug Report
 There are users from the user testing as well as a [user's documentation PR](https://github.com/cloudflare/workers-docs/pull/460/files) that did not have node installed and misleading errors were thrown and not until the wrangler preview step.

We should:
*  throw an error earlier - when  installing wrangler - if node is not installed
* Make the error message actionable "Install node on your machine.. "

Sorry for not providing reproduce dets, I actually have node installed myself so it'd be several steps to replicate.

**Comment by xtuc** [comment]
Related https://github.com/cloudflare/wrangler/issues/208

**Comment by EverlastingBugstopper** [comment]
@victoriabernard92 could you add labels to this issue?
