### ISSUE TITLE
Bundle wranglerjs into the same tarball as Wrangler releases

### ISSUE THREAD

**Issue by charl-kruger** [cloudflare/wrangler#788]
### 💡 Feature request
Bundle entire package, dont fetch from `https://cloudflare.works/download-wrangler/..`

#### Overview and problem statement

We are behind a firewall which will not allow npm to fetch during the install, if the module was bundled together with wrangler executable, it wouldnt be an issue.

#### Basic example

e.g. we are allowed to pull via nexus, however any fetches a installer tried to run will be blocked.

**Comment by xtuc** [comment]
Hi, could you please point to the relevant package? or code?

**Comment by ashleygwilliams** [comment]
hi @CharlJKruger thanks so much for filing! i understand the struggle here! 

@xtuc i believe @CharlJKruger means that the fetch to grab wranglerjs is failing because it's made during the install and the ask is to bundle the entire package together to eliminate fetches during installation.

**Comment by CharlJKruger** [comment]
@ashleygwilliams Yes thats correct.
