### ISSUE TITLE
Webpack: stabilize wasm finalizer

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#81]
The transformation in Webpack to the Wasm binary has some edge cases, sometime triggered by emscripten binaries.

We should work on https://github.com/webpack/webpack/issues/7565.

**Comment by xtuc** [comment]
I just found that this isn't going to be possible soon, our v8 version is far behind.

**Comment by xtuc** [comment]
We should use webpack 5, which removes many transformation.  WIP https://github.com/cloudflare/wrangler/tree/feat-webpack-5.

**Comment by ashleymichal** [comment]
closing as out of our hands
