### ISSUE TITLE
Add an example/template for react SSR app.

### ISSUE THREAD

**Issue by resdevd** [cloudflare/wrangler#819]
#### Overview and problem statement

There is no documentation available regarding react SSR in Cloudflare workers. Is it possible? 
Hoping there is way to deploy serverless app via Cloudflare workers for server side rendering (Nextjs?). What would be the best way to implement react SSR  ?

**Comment by ashleymichal** [comment]
this is probably a more appropriate issue for our docs repo (https://github.com/cloudflare/workers-docs), however, our own @signalnerve tweeted his example some time ago: https://twitter.com/signalnerve/status/1136297551622283264?s=21
