### ISSUE TITLE
Webpack: introducing JS deps

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#82]
I realized that the PR might not the best way to track this discussion.

@steveklabnik you commented in https://github.com/cloudflare/wrangler/pull/75#issuecomment-487603482, could you please elaborate? Are you aware of any precedence?

I agree that our JavaScript dependecy should be transparent for our users, apart from requiring nodejs.

It would be simpler for the user to not handle a `node_modules`/`package.json` setup in their project, especially if they are not used to JS.

**Comment by xtuc** [comment]
While we can't get rid of the JavaScript deps, It make sense to use wrangler to control it; ensuring the version and the install.

**Comment by steveklabnik** [comment]
So, there's sorta two main use-cases here. Simple use-cases where you don't use any JavaScript dependencies or bundlers. And more complex cases where you do. With the latter, you can't get away with not including a JS environment, of course. But for cases where you're not using any JavaScript, requiring an install of a completely separate environment is an extra step that's not going to be used.

**Comment by ashleygwilliams** [comment]
we've decided that we are doing this. there are still branches that allow folks to use wrangler without the node env.

**Comment by xtuc** [comment]
If we want to make it fully independent of the user's env, we can still bundle node/npm in our releases. Which isn't that hard.
