### ISSUE TITLE
wrangler's configuration format

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#83]
We talked with @ashleygwilliams about a non-Rust nor JS centric configuration format.

I don't think we reached consensus on a format. I propose using `yaml` (and `toml` for backward compatiblity).

**Comment by xtuc** [comment]
We should consider what `wrangler generate` should do? what configuration? flags?

**Comment by ashleygwilliams** [comment]
for the moment i think we are settling on the toml file and we'll explore further options as people request them! i'm going to close, but please reopen if i'm mistaken and there are still outstanding questions

**Comment by koistya** [comment]
I'm also voting for `yaml` to make it more inlie with other DevOps tools. Check this out:
https://github.com/toml-lang/toml/issues/516#issuecomment-369243479
