### ISSUE TITLE
How should we support wasm-pack?

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#84]
Currently, `wrangler` directly depends on `wasm-pack` to ship Rust code.

However, with the introducion of Webpack, we can support `wasm-pack` using the existing `wasm-pack-plugin`. This allows the support of npm dependecies and more.

Removing `wasm-pack` also simplifies our internals; what do you think?

**Comment by xtuc** [comment]
Wrangler should still install `wasm-pack` and handle updates, refs https://github.com/wasm-tool/wasm-pack-plugin/issues/58.

**Comment by ashleygwilliams** [comment]
this is solved by #94
