### ISSUE TITLE
WSL preview doesn't open browser, maybe print URL to terminal window as workaround?

### ISSUE THREAD

**Issue by thisguychris** [cloudflare/wrangler#840]
#### Environment

* operating system: Windows 10 build 19013
* output of `rustc -V`: rustc 1.36.0
* output of `node -v`: v12.10.0
* output of `wrangler -V`: wrangler 1.5.0

#### Steps to reproduce
`$ wrangler preview --watch`
or
`$ wrangler preview`

#### What did you expect to see?
A browser opening

#### What did you see instead?
First, thank you very much for making this 🙏🏻, it's really a joy to have a tool like this. 🙌🏻 I use it both on my Mac and Windows, but I'm reporting this bug/feature request as a Windows user.

The browser doesn't open. While WSL2 doesn't have xdg-open like the Linux variants, you can open the default browser using cmd.exe because of interop with Windows.

![Alt text](https://monosnap.com/image/drUe6bqCi29P6AaEWRRjnUpnzxmESZ)

So a command of:
**$ cmd.exe /c start http://example.com?foo=bar** would work on WSL2 environment.

Also printing --verbose doesn't print the URL either.
![Alt text](https://monosnap.com/image/lgYHQMN28b8xvEFIrgDFfhHSl3MqMu)

I do hope you add this 🙏🏻. Also maybe an interim, have the preview URL printed, so I can copy and paste manually on the browser?

**Comment by ashleygwilliams** [comment]
hi @thisguychris ! thank you so much for the kind words and the thoughtful issue! i actually think this shouldn't *be too hard*- right now we don't treat windows and WSL differently and if we can reliably detect WSL, we can make this change!

the piece of code that this runs is: https://github.com/cloudflare/wrangler/blob/master/src/commands/preview/mod.rs#L100

i don't have access to a WSL machine at the moment because i am traveling! but if you want to give this a try in a PR i'd be happy to help mentor you through it!

**Comment by thisguychris** [comment]
Hey, @ashleygwilliams 👋  I honestly haven't touched any Rust code yet, I mostly code in JS. But just hearing you mentor me, makes me really excited, I really appreciate your kind gesture.

There's nodejs library for detecting WSL (a fairly popular one), and it seems to check for the os-release if it includes "microsoft" as well as checking /proc/version output:

[is-wsl https://github.com/sindresorhus/is-wsl/blob/master/index.js](https://github.com/sindresorhus/is-wsl/blob/master/index.js)

I would gladly test it if you lack a WSL machine. Let me know what you prefer, I'm down on just being a tester, or make a PR (under your guidance), but I really haven't touch any rust code yet, so I don't know where to start ✌🏻

**Comment by thisguychris** [comment]
Hello 🙋🏻‍♂️,

I want to give an update. If you set your $BROWSER variable correctly, `xdg-open` should work.

In my case, to open it in firefox, I just symbolic link firefox.exe via
`ln -s /mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe firefox` under my `~/bin` directory where I have in my $PATH variable.

And set my browser variable to that symbolic link
`export BROWSER=firefox`

It should open on that browser, in this case, firefox. So just setting this variable would suffice, no change needed in wrangler binary.

@ashleygwilliams If you could point me where to put this in the docs, I'll gladly submit a PR to resolve this. 🙂

**Comment by EverlastingBugstopper** [comment]
Hey @thisguychris - that's great news! Does this mean we can close #934? 

As for the docs question, I think it would probably go really well here: https://github.com/cloudflare/workers-docs/blob/master/content/tooling/wrangler/commands.md#-preview

cc @victoriabernard92

**Comment by thisguychris** [comment]
@EverlastingBugstopper yes please, I just posted this WIP so I can ping @ashleygwilliams about the error I’m getting. I do think leveraging `xdg-open` is the most straightforward way to support WSL/2.

I do wish we can somehow note for WSL users how to leverage `xdg-open`. Let me know if I can help with documentation. 🙂
