### ISSUE TITLE
Create a dev server

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#845]
This issue is meant to be a summary of everything associated with [this milestone](https://github.com/cloudflare/wrangler/milestone/18) - for more detailed information, please look at the issues and PRs listed there.

The overarching goal is to create a "local" development environment for Workers that only requires an Internet connection. Expose the server on a configurable IP and port, and take care of uploading the script to the preview service and sending the necessary authentication headers. 

This feature will proxy requests to rawhttp.cloudflareworkers.com and future work will be built on top of how this service is currently implemented.

The proxy will need to mimic what the UI does:

- Send the same path to execute the worker to the preview endpoint
- Send the same HTTP method to execute the worker to the preview endpoint
- Append `cf-ew-` to all request headers #873 
- Strip `cf-ew-` from response headers #872 
- Pipe console.log output via the chrome devtools protocol #875 

The proxy will depend on the following endpoints:

1) https://rawhttp.cloudflareworkers.com
1) https://api.cloudflare.com/client/v4/accounts/{}/workers/scripts/{}/preview
1) https://cloudflareworkers.com/script

**Comment by yet-another-dev** [comment]
A big +1 for this, especially now that https://github.com/dollarshaveclub/cloudworker is no longer actively maintained. 

Unfortunately, for now, the absence of a clean and workable local development story with Cloudflare Workers is preventing me from using it. Even though not actively maintained, I tried getting a workable story together with https://github.com/dollarshaveclub/cloudworker and it nearly got me there, but it not supporting cookie headers (https://github.com/dollarshaveclub/cloudworker/issues/121) is a show stopper. Does anyone have a workable approach for this (a clean and sensible local development story with Cloudflare Workers)?

Something like [Netlify Dev](https://www.netlify.com/products/dev/) for Cloudflare Workers would be sweet.
