### ISSUE TITLE
use our  Environment struct to whitelist environment variables in Manifest

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#852]
right now if you have environment variables set on your dev machine for auth or account variables, wrangler's tests will take them into account when running tests, which means our tests are inconsistent machine to machine. we should totally be testing how wrangler behaves with and without environment variables set, but we should be doing it in a controlled manner.

UPDATE:  the relevant  struct was introduced with #879

**Comment by ashleymichal** [comment]
This was partly completed with the #879 for global user. need to extend to using the same struct in manifest. For science. 🤓

**Comment by EverlastingBugstopper** [comment]
Fixing this should eliminate usage of the `config` crate

When constructing GlobalUser, we should loop over CF_API_TOKEN, CF_EMAIL, and CF_API_KEY.

When constructing Manifest, we should loop over CF_ZONE_ID, CF_ACCOUNT_ID, CF_NAME, CF_TYPE, CF_WORKERS_DEV, CF_ROUTE, and CF_WEBPACK_CONFIG. Note that this leaves out CF_ENV, CF_ROUTES, CF_KV_NAMESPACES, and CF_SITE which we currently try to parse. These are not strings and cannot be set in an environment variable, so we should not attempt to parse them. This will eliminate the parsing bug seen in #704 and will also (very slightly) improve performance on machines with a large number of environment variables.
