### ISSUE TITLE
`Wrangler.toml` not appearing on `wrangler generate`

### ISSUE THREAD

**Issue by nodebotanist** [cloudflare/wrangler#87]
When I run `wrangler generate` the folder it creates does not contain a `wrangler.toml` file anywhere. I don't know if this is a bug or the file was deprecated and the docs were not updated. Either way I'd be happy to help with this issue.

This is on a Mac running 10.14.2, in case that's relevant

**Comment by ashleygwilliams** [comment]
this is currently on master- simply not deployed. can you try running `cargo install --git https://github.com/cloudflare/wrangler` and trying again?
