### ISSUE TITLE
[dev] Continue implementing devtools protocol work

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#875]
The preview service exposes a websocket according to [this protocol](https://chromedevtools.github.io/devtools-protocol/)

A good start on this has been made in #923 and future work on implementing types for the protocol is tracked at https://github.com/everlastingbugstopper/chrome-devtools-rs

**Comment by xtuc** [comment]
Good idea! Be aware that we don't fully implement the Chrome Devtools protocol.

I always wanted to make it fully standard to allow developers to use any debugger (aka preview :)) against the online preview or your proxy.
