### ISSUE TITLE
Allow zoned users to deploy to multiple routes

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#885]
see phase 1 of #866 

Provided a list of route patterns, on publish wrangler should iterate through all of the routes and PUT each to the API.

Not included in this issue, but in subsequent issues:

* deleting/syncing routes that are not listed in wrangler.toml
* uploading "off" routes

Interface:

1. In the wrangler.toml, a user may specify EITHER `route` or `routes`. We will not deprecate the singular at this time, or perhaps ever, as we generally encourage users to deploy apps with wrangler.

2. The `routes` key will NOT be inheritable in terms of wrangler environments, as this would cause unexpected overwrites across environments.

3. For this issue, implement a simple list of route patterns that should point to this script. Will include null scripts in a subsequent issue.

**Comment by SokratisVidros** [comment]
What's the status for this one? Thank you in advance.

**Comment by EverlastingBugstopper** [comment]
@SokratisVidros this should be released with 1.8.0 - you can follow along with this PR: https://github.com/cloudflare/wrangler/pull/916

**Comment by SokratisVidros** [comment]
Thanks a lot @EverlastingBugstopper
