### ISSUE TITLE
Linting phase

### ISSUE THREAD

**Issue by xtuc** [cloudflare/wrangler#90]
We could:
- warn on filesize
- check for forbidden functions (eval, Function)

For kv-namespaces we could:
- ensure the name is a valid JavaScript identifier (in strict mode).
- unsused kv_namespace bindings

**Comment by ashleymichal** [comment]
we have implemented some of these;  others are already implemented in the api  and so are for sure nice to haves but in the interest of reducing WIP, i am closing  this.
