### ISSUE TITLE
[dev] when host set to localhost, spin up trycloudflared endpoint

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#901]
devs should be able to test workers on something that runs on their local machine, let's use trycloudflared

**Comment by GregBrimble** [comment]
If it's any help, [I have a complete example of using `cloudflared` with `wrangler dev` which automatically pulls in the tunnel host](https://github.com/GregBrimble/wrangler-cloudflared-template).

Specifically, [`index.js` is the most interesting bit](https://github.com/GregBrimble/wrangler-cloudflared-template/blob/master/index.js): it starts the cloudflared tunnel, inspects the Prometheus metrics endpoint and grabs the hostname, and then starts the `wrangler dev --host ${hostname}` process.
