### ISSUE TITLE
command to add a secret to a worker

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#907]
wrangler should support a command that allows the user to securely add a secret environment variable to the script of their choosing. should be interactive by default to prevent sensitive data from leaking into terminal history. ideally also allows for values to be piped to it.

### Syntax
```
$ wrangler secret set secret-name
=> Enter your secret value
# or
$ echo $SECRET_VALUE | wrangler secret secret-name
```
this command should support the environment flag; when not present, the command should create a secret in the context of the top level worker. when present, the command should create a secret in the context of the worker specified in the env.

#### outstanding questions:

1. what to do when the worker does not exist yet
2. does this require extra encryption before sending?

### Depends on
* add endpoint to workers configuration api to add a secret binding to an already existing worker
* add endpoint definition to cloudflare-rs for calling the above endpoint

**Comment by victoriabernard92** [comment]
Thinking about this, I actually think we should be consistent with how wrangler uses `:` to separate actions from subcommand. We should either change how `kv:` does this or omit the `:` here
See https://wiki.cfops.it/display/~victoria/Wrangler+Commands

**Comment by ashleymichal** [comment]
we shouldn't change how kv does things. the difference between kv and secrets is that in kv you are potentially manipulating one of many subresources: namespaces vs keys, for example, so the whole `foo:bar` segment is still a "noun" while the command that follows is the verb. likewise here the only noun is `secret` and the verbs are still `create`, `list`, and `delete`
