### ISSUE TITLE
command to list secrets for a worker

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#909]
wrangler should support a command that allows the user to view a list of secret bindings configured on their worker. 

### Syntax
```
$ wrangler secret:list
```

this command should support the environment flag; when not present, the command should list secrets bound to the top level worker. when present, the command should list secrets bound to the worker specified in the env.

### Depends on
add endpoint definition to cloudflare-rs for calling the GET script bindings endpoint

**Comment by victoriabernard92** [comment]
Maybe add a note on whether env scoping will be supported (I think it's overkill for list)

**Comment by ashleymichal** [comment]
> Maybe add a note on whether env scoping will be supported (I think it's overkill for list)

actually env scoping will be necessary, since every env is its own script
