### ISSUE TITLE
`wrangler deploy` un-does KV namespace bindings

### ISSUE THREAD

**Issue by steveklabnik** [cloudflare/wrangler#92]
In three screenshots:

![image](https://user-images.githubusercontent.com/27786/57802941-c6d2bc80-771c-11e9-9e5d-c42aa7e4a6c4.png)

![image](https://user-images.githubusercontent.com/27786/57802950-cfc38e00-771c-11e9-8ef7-95d0231bdee7.png)

![image](https://user-images.githubusercontent.com/27786/57802973-d94cf600-771c-11e9-8bf9-1dc6be6a18e3.png)

**Comment by xtuc** [comment]
Ideally we would use JavaScript Module syntax to detect what KV things needs to be declared:
```js
import posts from "cloudflare:kv/posts".
```

Alternatively, we could fetch the current bindings, merge it with the local version and publish.

**Comment by kreitlowbryan** [comment]
It looks like an update was merged but it doesn't seem to honor the addition of `kv_namespaces = ["NAMESPACE"]` in the wrangler.toml file. Am I missing something?

**Comment by xtuc** [comment]
The change will create a kv-namespace when it doesnt already exists during the publishing. However, the bug here is that they are not defined in the Worker bindings.

**Comment by kreitlowbryan** [comment]
There is currently no support to add Worker KV bindings to the wrangler.toml file to have those bindings generated when the metadata.json is built as part of the `wrangler publish` command? It is really painful to try and dev using worker KV with wranger when these bindings are removed upon every publish.

**Comment by xtuc** [comment]
We are aware, see https://github.com/cloudflare/wrangler/issues/215

**Comment by grempe** [comment]
For those who find this. The current process to workaround that seems to be working for me now is:

* Deploy script with `wrangler publish` (destroys any currently configured bindings)
* Load CF Worker Editor Web UI to edit your worker.
* Click the resources tab for the worker and RE-ADD the binding between variable and namespace.
* Click the code tab AGAIN and `DEPLOY` the script you previously published with wrangler AGAIN by clicking the button.

Next time you do `wrangler publish` or `wrangler publish --release` you'll need to do this again.

Hopefully this gets cleanly resolved soon. /smh

**Comment by ashleymichal** [comment]
closed by #334 . Being released as part of 1.1.0.
