### ISSUE TITLE
Publish error - Route pattern must include zone name

### ISSUE THREAD

**Issue by newtack** [cloudflare/wrangler#920]
When in a directory with index.js, package.json and wrangler.toml and running "wrangler publish" I get the following error message.

Route pattern must include zone name: pittaadmin.app/*"

I checked at least 3 times and the zone id does map to pittaadmin.app.

The wrangler toml file has (blanked out zone and account id)
name = "follow-up-machine-admin"
  type = "javascript"
  account_id = "***"
  workers_dev = false
  route = "pittaadmin.app/*"
  zone_id = "***"

Another directory that contains another route and zone id works without problems.

I am using Wrangler version 1.6.0 on Ubuntu 18.04. And again, it works with the other one. 

Below is the full stack trace:

 Status Code: 400 Bad Request
 Msg: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10022,
      "message": "Route pattern must include zone name: pittaadmin.app/*"
    }
  ],
  "messages": []
}

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new
   1: <failure::backtrace::Backtrace as core::default::Default>::default
   2: wrangler::commands::publish::route::Route::publish
   3: wrangler::commands::publish::publish
   4: wrangler::run
   5: wrangler::main
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
      std::panicking::try::do_call
             at src/libstd/panicking.rs:296
   8: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
   9: std::panicking::try
             at src/libstd/panicking.rs:275
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  10: main

**Comment by gabbifish** [comment]
Hello! Sorry for the inconvenience. Could you try making your route `pittaadmin.app/*`, not `pittaadmin.app/`? The workers API expects `pittaadmin.app/*` if you want a worker to apply to your entire zone. :)

**Comment by ashleygwilliams** [comment]
cc @newtack in case you missed this- can you try what @gabbifish suggested and let us know how it went? sorry you are running into this- we'd love to help!

**Comment by newtack** [comment]
I double checked and the wrangler file contains 
workers_dev = false
route = "pittaadmin.app/*"
So the * is in fact set (I failed to copy it above, but the actual file does have the /*).

Any other idea as to why this doesn't work? Also, if I can't get this to work, what's the alternative to wrangler?

**Comment by gabbifish** [comment]
So in your wrangler.toml, you see `route = pittaadmin.app/*`? The `*` character itself is necessary. If this doesn't fix things, we can point you to the API docs (but wrangler has been tried and tested with deployments like yours hundreds of times, so let's make sure we're doing everything accordingly here :)).

**Comment by newtack** [comment]
Yes, it does include that route (with the star).

Is there some verbose or trace option that would provide you with more info?

**Comment by gabbifish** [comment]
You can use `RUST_LOG=info wrangler publish` to see more logs about what's going on. It looks like this is an API problem where the CF API is unable to find the zone for your given account ID. Is there a possibility the new zone you're working with belongs to a different account than the one you used before, and now the API is performing that lookup for a zone that belongs to another account?

**Comment by newtack** [comment]
Here is the output with the above command. Any idea on what's going on?

RUST_LOG=info wrangler publish
[2019-12-10T01:53:11Z INFO  wrangler] Getting User settings
[2019-12-10T01:53:11Z INFO  wrangler::settings::global_user] No $WRANGLER_HOME detected, using $HOME
[2019-12-10T01:53:11Z INFO  wrangler::settings::global_user] Using global config file: /home/ralf/.wrangler/config/default.toml
[2019-12-10T01:53:11Z INFO  wrangler] Getting project settings
[2019-12-10T01:53:11Z INFO  wrangler::commands::publish] pittaadmin.app/*
 JavaScript project found. Skipping unnecessary build!
[2019-12-10T01:53:11Z INFO  wrangler::commands::publish::upload_form] JavaScript project detected. Publishing...
[2019-12-10T01:53:11Z INFO  wrangler::commands::publish::upload_form] building form
[2019-12-10T01:53:11Z INFO  wrangler::commands::publish::upload_form] Form { boundary: "e07f36d4fef24d0db86f4bb9296d7e9d", parts: [("metadata", Part { value: Body { kind: b"{\"bindings\":[],\"body_part\":\"index\"}" }, mime: Some("application/json"), file_name: Some("metadata.json"), headers: {} }), ("index", Part { value: Body { kind: Reader { length: 3498 } }, mime: Some("application/javascript"), file_name: Some("index.js"), headers: {} })] }
[2019-12-10T01:53:12Z INFO  wrangler::commands::publish::route] Creating your route "pittaadmin.app/*"
Error:  There was an error creating your route.
 Status Code: 400 Bad Request
 Msg: {
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10022,
      "message": "Route pattern must include zone name: pittaadmin.app/*"
    }
  ],
  "messages": []
}

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new
   1: <failure::backtrace::Backtrace as core::default::Default>::default
   2: wrangler::commands::publish::route::Route::publish
   3: wrangler::commands::publish::publish
   4: wrangler::run
   5: wrangler::main
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
      std::panicking::try::do_call
             at src/libstd/panicking.rs:296
   8: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
   9: std::panicking::try
             at src/libstd/panicking.rs:275
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  10: main

**Comment by EverlastingBugstopper** [comment]
Hey @newtack - is it possible that you have `$CF_ZONE_ID` set? If you have that set it will override what you have in your `wrangler.toml`. If not, could you run `RUST_LOG=debug wrangler publish`? The debug output should show which zone id wrangler is sending to the API. Thanks so much for your patience on this.

**Comment by newtack** [comment]
Thanks! That was the problem. I had it set in an environment variable and it took the environment variable instead of what was in the wrangler.toml file. 

To help resolve this issue sooner in the future, maybe you at least a a warning/info message that CF_ZONE_ID is set in both environment variable and wrangler.toml and that it uses the environment variable value. 

Again, thanks.

**Comment by EverlastingBugstopper** [comment]
Awesome! Glad you got this one figured out. @ashleymichal do you think it would be worthwhile to include this info in the `--dry-run` flag that you proposed for multi-route support? 

I'm a bit wary on warning every time there's an environment variable set in addition to a field in the manifest, but it might be worth warning if only one env variable is set. 

cc @gabbifish
