### ISSUE TITLE
[dev] pass --inspect flag to get websocket endpoint for chrome://inspect

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#946]
node provides an interesting way to attach a debugger to its REPL

```
$ node --inspect
Debugger listening on ws://127.0.0.1:9229/long-hash-hash-hash-hash
For help, see: https://nodejs.org/en/docs/inspector
```

You can then navigate to chrome://inspect and it will show a node instance. If you run console.log in the node process, it will show up in the console on the browser. 

I think it would be a good idea to add `--inspect` to `wrangler dev`. This would mean that when your dev server starts up, it acts the same way in the terminal, except it also takes all websocket messages it receives and passes it to a local websocket listening on your machine. This would work the same way that the node inspector does, and you'd be able to navigate to `chrome://inspect` and see wrangler dev there instead of node.

A pitfall with this is that the runtime's implementation of the devtools protocol is incomplete (you can't set breakpoints). But I still think it's worth having - especially for interacting with large nested objects and viewing network requests.

**Comment by PierBover** [comment]
@EverlastingBugstopper when `dev` crashes we'd need to manually reopen `chrome://inspect` right?

Since I imagine the node process would be killed.

**Comment by EverlastingBugstopper** [comment]
I'm not sure actually - would need to see how it all works. My guess is yes - but we'd attempt to achieve parity with whatever `node` does.
