### ISSUE TITLE
Workers Sites uploads do not include files that are in .gitignore

### ISSUE THREAD

**Issue by lighterpl** [cloudflare/wrangler#958]
#### Environment

* operating system: windows 10 pro v1909 (18363.535) 

#### Steps to reproduce
Generate workers site project, set account id, api access granted using workers site template permissions. 

Static file export of Wordpress site, placed in ./public folder

Run wrangler publish 

Some css and js and font files are not uploaded (as seen by http 500 error in chrome dev tools for those resources)

I suspect this is because the files are in a deep folder structure, because when these files are moved to root public folder or 1 folder deep, wrangler does not skip them and they are successfully deployed.

#### What did you expect to see?
I expect ALL files in ./public folder to be deployed
#### What did you see instead?
Some files are skipped during wrangler publish process

**Comment by EverlastingBugstopper** [comment]
Hey @lighterpl - my guess is that these assets are actually being uploaded and they're just linked incorrectly from within the application.

That being said this is just a hunch, and it's very possible that they are not being uploaded! The best way for us to help here is if you could point us to a repository that reproduces the problem and then we can investigate :)

**Comment by lighterpl** [comment]
Seems that it happens when there is a subfolder anywhere inside the ./public directory named “dist” all files inside are ignored.

**Comment by EverlastingBugstopper** [comment]
Aha! It seems that Wrangler is not uploading files in the `.gitignore` for some reason. I'm pretty sure this is a bug! While we work on a fix for this, you should be able edit your `.gitignore` file - it should have `dist` in it, you can change this to `/dist` so it only ignores the top level `dist` directory, and not the directory in your `public` folder. Hope this helps!
