### ISSUE TITLE
all wrangler commands should accept `--verbose` flag

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#975]
Even if it doesn't actually change the output, it is jarring to pass this flag and have wrangler complain. we should accept it everywhere and use it where applicable.

**Comment by ericdeansanchez** [comment]
Hi 👋, could I start on this?

**Comment by ashleymichal** [comment]
@ericdeansanchez i see no reason why not! it should be a pretty straight forward change in `main.rs`, and a good opportunity to learn clap.rs. feel free to ping here if you want any assistance or suggestions!

**Comment by ashleymichal** [comment]
@ericdeansanchez there are a couple of commands (i don't remember which off the top of my head) that already accept a verbose flag; we should follow the same pattern those use but just kind of... ignore it where it is not already used.

**Comment by ericdeansanchez** [comment]
Ok, great! And yeah I thought that we could add the `--verbose` flag as an `Arg` to all the `SubCommand`s. 

And just to clarify, you want `--verbose` to be ignored **silently** when passed and only applied where verbose output is supported?
