### ISSUE TITLE
[dev] cache api warning

### ISSUE THREAD

**Issue by ashleymichal** [cloudflare/wrangler#976]
as in the workers dashboard, the first console event we always get is a message (i assume this is like a console.warn event)

```
unknown console event: "The Service Workers Cache API is currently unimplemented in the Cloudflare Workers Preview. Cache API operations which would function normally in production will not throw any errors, but will have no effect. Notably, Cache.match() will always return undefined, and Cache.delete() will always return false. When you deploy your script to production, its caching behavior will function as expected."
```
this only happens on the first request. maybe this is okay, maybe it is an issue for the preview service, but as a user it is a mixed bag of unsolicited helpful information that i will likely ignore in the moment and forget where to find when i need it.

**Comment by EverlastingBugstopper** [comment]
Good catch - I think we'll want to keep the message, I just need to handle the type of console event. Needs to be an enum in `chrome-devtools-rs` and currently I've only handled console.log messages and console.error messages. this is probably a "warn" message or something like that.
