### ISSUE TITLE
`Error: missing field `betas` at line 1 column 476` with `wrangler config --api-key`

### ISSUE THREAD

**Issue by ndarilek** [cloudflare/wrangler#979]
Getting the above when attempting to use a global API key with Wrangler 1.6.0 in `wrangler config --api-key`.

I'd love to follow your recommendation against global API keys, but I'm a blind screen reader user, and the "Continue to Summary" button on the API template page either can't be activated via the keyboard, or is displaying some error I can't find. So this is my only option for now and it doesn't work. Not a huge deal since I'm the only user of my account and take care of my token, but I'd like at least one path forward here. :)

Thanks.

**Comment by ndarilek** [comment]
My temporary workaround is to use environment variables, which appears to let me preview and publish using an API key and avoiding this error.

**Comment by ashleymichal** [comment]
we're glad you found a work around! but this kind of accessibility problem is no bueno. we've escalated to the team in charge of Cloudflare's web UI dashboard.

**Comment by EverlastingBugstopper** [comment]
I believe this is resolved and you should be able to tab through everything on the API tokens page. Please reopen if not the case :)
