### ISSUE TITLE
Allow setting account and zone id in environment variable

### ISSUE THREAD

**Issue by abiro** [cloudflare/wrangler#985]
#### Overview and problem statement

Similar to `CF_API_TOKEN` it would be great if  account and zone id could be set as environment variable instead of putting them into the config file. My worker code is open source and I don't want to publish those ids.

#### Basic example

`CF_ACCOUNT_ID=X CF_ZONE_ID=Y CF_API_TOKEN=Z wrangler publish`

**Comment by EverlastingBugstopper** [comment]
This works! You can do this today :)

**Comment by abiro** [comment]
ah great it's just missing in the docs

**Comment by EverlastingBugstopper** [comment]
I've opened an issue for that here: https://github.com/cloudflare/workers-docs/issues/613 Thanks for letting us know :)
