### ISSUE TITLE
Allow wrangler to be run in subdirectories

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/wrangler#989]
We should walk up the directory structure looking for a `wrangler.toml` so that you can run wrangler commands in subdirectories. 

This issue brought to you by [a PR doing this in `wasm-pack`](https://github.com/rustwasm/wasm-pack/pull/624)

**Comment by ashleymichal** [comment]
related: #860

**Comment by victoriabernard92** [comment]
How would we consider multiple wrangler.toml's in different subdirectories(`sub/wrangler.toml` and `sub2/wrangler.toml` )? What if you want multiple wrangler.toml (`wrangler-api.toml` ) files in one directory? 

Both concerns would be addressed  if we follow what webpack does and allow a flag to be passed in. To make convenient I put my wrangler commands in my package.json. In this case it'd look like

```
"scripts": {
  "deploy": "wrangler --config sub/wrangler.toml publish"
}
```
