### ISSUE TITLE
Publish is timing out

### ISSUE THREAD

**Issue by shuat** [cloudflare/wrangler#997]
### 🐛 Bug Report

💁 Uploading...
Error: Failed to upload file batch. ⚠️ Error: https://api.cloudflare.com/client/v4/accounts/0b7ab10fa40087efd0c9f21d953d0956/storage/kv/namespaces/04939c355a074ce4a89c2a3b7c343f19/bulk: timed out

#### Environment

* operating system: Macos catalina
* output of `rustc -V`: zsh: command not found: rustc
* output of `node -v`: v10.17.0
* output of `wrangler -V`: 👷 ✨  wrangler 1.6.0

#### Steps to reproduce

`wrangler publish`

#### What did you expect to see?

Completed successfully 

#### What did you see instead?

Error: Failed to upload file batch. ⚠️ Error: https://api.cloudflare.com/client/v4/accounts/0b7ab10fa40087efd0c9f21d953d0956/storage/kv/namespaces/04939c355a074ce4a89c2a3b7c343f19/bulk: timed out

**Comment by gabbifish** [comment]
Hi there! Sorry to see you're running into issues with uploads. Our timeout period is 5 minutes, which is pretty generous; what does your upload bandwidth look like?

**Comment by shuat** [comment]
I just tried to publish and it worked. This is about the 10th time I tried not sure what is different. I just ran a speed test and I got 137 down 36 up. It is possible the other time my internet was slower, but nothing else was suffering besides CF. Did anything change on the CF end? This time it published in < 10 sec

**Comment by mohamedrajhi** [comment]
hello , i have the same problem 
do anyone have an idea to solve this issue ?
![image](https://user-images.githubusercontent.com/40335054/84786078-8ebb3e80-afec-11ea-9edb-b15fe859ea22.png)

**Comment by EverlastingBugstopper** [comment]
Hey @mohamedrajhi we just released 1.10.1 that should address this issue 😄  sorry for the inconvenience!!
